### ISSUE TITLE
Add Attack Type argument to COMBATDAMAGE

### ISSUE THREAD

**Issue by phobos2077** [phobos2077/sfall#100]
Need to add:
`int arg12 - hit_mode (one of ATKTYPE_*)`

Or check if it's available other place.

**Comment by FakelsHub** [comment]
from Crafty?

**Comment by FakelsHub** [comment]
Исправьте описание.
`int arg9  - DamageMultiplier (this is divided by 2, so a value of 3 does 1.5x damage, and 8 does 4x damage.); Обычно равно 2, но при взятом перке Silent Death|Тихая смерть и соответствующих условиях атаки равно 4, а при критических попаданиях значение берётся из таблицы критов`

**Comment by NovaRain** [comment]
Fixed.
