### ISSUE TITLE
Scripting: Override tile coordinates of enter when map is loaded.

### ISSUE THREAD

**Issue by FakelsHub** [phobos2077/sfall#101]
Тут Crafty достал некоторые полезные смещения, позволяющие во время загрузки карты в map_enter_p_proc получить координаты куда будет перемещен игрок после захода на карту,
полезность представляют первые два смещения.
**tile_num** - координата на которую будет перемещен игрок, можно как получать так и переопределять координаты, если установить в 0, то игрок будет перенесен на координаты указанные в карте, т.е. будет игнорироваться любые данные к примеру от сеток перехода.
```
read_int(0x631D30) = tile_num
read_int(0x631D2C) = elev
read_int(0x631D34) = rotation
```
Можно бы сделать это все двумя функциями, а эти три параметра получать/задавать через массив, как сделано с аргументами в hooks.

**Comment by Lexx2k** [comment]
Out of curiosity-- any examples where this would be useful?

**Comment by FakelsHub** [comment]
Полезность в том, что без этого смещения tile_num, в map_enter_proc мы не сможем узнать на какие координаты заходит игрок,  а dude_tile всегда возвращает координаты указанные в самой карте (start tile).
