### ISSUE TITLE
Scan area for critters

### ISSUE THREAD

**Issue by Lexx2k** [phobos2077/sfall#102]
Would it be possible to add something like "is_seen_by" or "can_see_someone" ?

Example:
I want to trigger NPC behavior if the player has a certain companion following him, but I don't want to edit *every* NPC script with a new macro just for that. Therefore I guess the best approach would be to check in the companion script if any other critter is around (in area range x?) and return either the closest target, or the one that has seen the critter first. 

I could likely do exactly that with cycling through hexes around the companion, checking for critters, but I feel like this is a little bit of an overkill.

**Comment by FakelsHub** [comment]
`HOOK_WITHINPERCEPTION` - Runs when checking if one critter sees another critter.
Does not solve your problem?

**Comment by Lexx2k** [comment]
I don't know. How exactly would I use it in this case? Did some tests right now but can't figure it out. The arguments are always 0.

**Comment by Lexx2k** [comment]
I don't know. How exactly would I use it? Did some tests right now but can't really get any good results.

**Comment by FakelsHub** [comment]
Просто рассуждения на эту тему.
Может можно использовать экспортную переменную  в типа массива, обьявленную скрипте в карты: export variable object[15];, а потом в скриптах нужных объектов проверять в цикле массив и если какой-то индекс массива пуст то присвоить туда указатель на self_obj.
 Далее в проверяемом скрипте обьекта сделать проверочный цикл для массива на предмет 
For n=0 to object.len
 If self_see(object[n]) then call is_seen_by(object[n]);
Next
Вобщем это было бы лучшее решение чем проверять каждый тайл вокруг объекта.
Только вот я не вкурсе можно ли делать экспортируемые массивы?
 Phobos что там насчет таких массивов?

**Comment by phobos2077** [comment]
You should use `obj_blocking_line` function for checking if one critter sees another - this is exactly how engine is doing that. No need for workarounds :)
To cycle over critters, there is `list_as_array(LIST_CRITTERS)`

@FakelsHub:
См. выше, в этом костыле нет необходимости. А вообще использовать массивы в качестве экспортных переменных вполне можно, только их надо проинициализировать правильно, например в функции `start` карты.

**Comment by FakelsHub** [comment]
То есть list_of_array будет иметь список всех криттеров на карте?
Почему в документации об этом ничего не написано.

**Comment by NovaRain** [comment]
> То есть list_as_array будет иметь список всех криттеров на карте?
Почему в документации об этом ничего не написано.

In sfall function notes.txt:
> the list_xxx functions can be used to loop over all items on a map. list_begin takes an argument telling sfall what you want to list. (Defined in sfall.h) It returns a list pointer, which you iterate through with list_next. Finally, when you've finished with the list use list_end on it. Not calling list_end will result in a memory leak. Alternatively, use list_as_array to get the whole list at once as a temp array variable, which can be looped over using len_array and which you don't need to remember to free afterwards.

**Comment by FakelsHub** [comment]
The subjects of arrays and their application is very poorly disclosed in descriptions file. :(

**Comment by phobos2077** [comment]
> The subjects of arrays and their application is very poorly disclosed in descriptions file. :(

Why do you say so? Sfall function notes has full description (see NovaRain comment above), also refer to arrays.txt.
