### ISSUE TITLE
Ternary operator

### ISSUE THREAD

**Issue by FakelsHub** [phobos2077/sfall#103]
```
> Conditional expressions (python-inspired), also known as ternary operator:
new:
    X := value1 if condition else value2
```
It might be worth adding another syntax for the ternary operator, in my opinion the c++ syntax is better than Python's.
`X := If (condition) value1 else value2`
Slightly change the location of TRUE, and add the required parentheses :)

IMHO: Python is not very convenient and incomprehensible.

**Comment by phobos2077** [comment]
Python is one of the most popular languages out there, many people know it and find it much more readable than others, C++ included :)
What you propose is not C++ syntax, C++ uses symbols like  `a ? b : c`. Because SSL uses words more often, I thought such syntax would be fitting. Also if you use short-circuit evaluation, you can use ternary like in lua::

**Comment by FakelsHub** [comment]
Синтаксис который я предложил более понятен для тех кто не знаком с програмированием.
Я же не предлагал убирать питоновский вариант, а добавить по типу цэшного, но более понятного врамках ssl.
В Lua вобще что-то странное изобрели and и or прилепили :)

**Comment by FakelsHub** [comment]
Кстати можешь расстолковать каким образом работает short-circuit evaluation (то что правые условия не будут проверяться это я знаю) меня интересует то как это обрабатывает двиг в скомпилированном скрипте.
Если допустим скомпилировать скрипт с этой опцией, и без, то int файлы будут разные, а если их декомпилировать то содержимое скрипта будет одинаковым, в чем фокус?)

**Comment by phobos2077** [comment]
Любой синтаксис дело привычки. Если уже добавлен один вариант, нет смысла добавлять еще один. Пару раз напишешь и будет понятно. Кстати с точки зрения английского языка, питоновский синтаксис лучше читается. .

**Comment by FakelsHub** [comment]
Ну не знаю, не знаю... этот питоновский вариант так убого читается, что лучше классический if использовать.   
```
spec_item := item_type_weapon if filter_item_type == item_type_ammo else item_type_ammo;
      
if filter_item_type == item_type_ammo then 
   spec_item := item_type_weapon; 
else 
   spec_item := item_type_ammo;
```
