### ISSUE TITLE
Argument number in set_sfall_arg

### ISSUE THREAD

**Issue by FakelsHub** [phobos2077/sfall#104]
```
> void set_sfall_arg(int argnum, int value)
Changes argument value. This is usefull if you have several hook scripts attached to one hook point (see below).
```
argnum - in description does not specify which number is the first argument, 1 or 0 ???

**Comment by NovaRain** [comment]
It should be 0-indexed, just like most of other numbering stuff.

**Comment by FakelsHub** [comment]
Спасибо)
Just in the description everywhere written arg1, arg2 ... normal person will think that this will be 1, not 0. :-)

**Comment by NovaRain** [comment]
Well, more than half of programming languages use zero-based numbering, including high-profile ones like C++, Java, and Python. Plus, all other stuff in Fallout modding are also 0-indexed, not sure why someone would assume these two particular functions being 1-indexed.

**Comment by FakelsHub** [comment]
If the numbering started with zero-based (arg0, arg1, arg2...) the question would not have.

**Comment by NovaRain** [comment]
I've added a note for argnum in set_sfall_arg() in commit fc930ff7fbd6e0cb819b5b62b2c87ffe75229693 to make things clearer.
