### ISSUE TITLE
Compiler: Expected constant in Switch statements and export variable.

### ISSUE THREAD

**Issue by FakelsHub** [phobos2077/sfall#105]
![switch](https://user-images.githubusercontent.com/21695363/28736265-b918e586-73f1-11e7-846b-5f4d4c8496a1.jpg)
Error while compiling "Required constant" 
That is, this case only works with a constant directly written in statement `Switch <constant> ` ???

**Comment by NovaRain** [comment]
AFAIK Fallout scripts don't support 'switch' statement.

**Comment by FakelsHub** [comment]
See sslc_readme.txt fom modders pack.

> > switch statements: A shorthand way of writing big 'if then else if...' blocks
> new:
> switch get_attack_type begin
> case ATKTYPE_PUNCH: display_msg("punch");
> case ATKTYPE_KICK: display_msg("kick");

**Comment by NovaRain** [comment]
Oh, you're right. Looks like it does only take constant. I'll tag this as a bug.

**Comment by FakelsHub** [comment]
Case accepts the constants `case <constant>:`
But after the preprocessor PID_DOCTORS_BAG will be replaced by (91), in this case the compiler perceives the parentheses as not constant.

**Comment by FakelsHub** [comment]
The same problem to export variables
`export variable VarName := -1;`
Declaring an export variable with a negative value or parentheses causes an error when compiling - "Initialization of VarName  with non-constant".

This initialization method does not lead to an error.
`export variable VarName := 0xFFFFFFFF;`

**Comment by phobos2077** [comment]
Yeah I guess compiler could be improved in those places.

**Comment by phobos2077** [comment]
@FakelsHub , I can allow to use arbitrary expressions for SWITCH statement, this should be easy enough. However, I cannot say the same about exported variables. Currently compiler is built in a way that Parser, Optimizer and Codegen exist independently from each other, and while Optimizer knows about the concept of constant expressions (constant folding - when expression is calculated at compile time), the Parser does not. So for export variables in might be a bit tricky to do. I can use the same workaround as I did for default procedure argument values, but it only handles the minus sign, but no parens.

**Comment by FakelsHub** [comment]
Для экспортных переменных можно оставить как есть. В общем это на твое усмотрение.

**Comment by phobos2077** [comment]
@FakelsHub https://yadi.sk/d/4X1PXNij3NjLRB 
Пробуй. Включил поддержку любых выражений для `case`, а при определении любых переменных (а также дефолтных значений параметров процедур) можно указывать простейшие унарные выражения в скобках. Например: 
```
variable x := (-123);

**Comment by FakelsHub** [comment]
Ты парсер.длл сделал :) я в исходниках для него одну ошибку фиксил для процедур с агрументами, видимо она твоя :-)

**Comment by phobos2077** [comment]
@FakelsHub проверь может её уже и нет. Я переделал функцию которая парсит присваивание переменной, она используется в т.ч. для аргументов процедур.

**Comment by FakelsHub** [comment]
В файле parse.h убрать нерабочий вариант дефайна для DLL.
```
#ifdef BUILDING_DLL
// this can be ignored if you only want the syntax tree
#define parseSemanticError(format, ...) 1
#else
#define parseSemanticError(format, ...) parseError (format, __VA_ARGS__)
#endif
```

> Кстати есть идея как реализовать полноценные Constant expressions. Если есть желание заняться, могу подсказать.

не я не особо силен в коде с/с++, мне .net роднее :)

**Comment by phobos2077** [comment]
> В файле parse.h убрать нерабочий вариант дефайна для DLL.

Можно по подробней? Зачем убрать?

**Comment by FakelsHub** [comment]
> Можно по подробней? Зачем убрать?

Зачем) А что по твоему делает единица в #define parseSemanticError(format, ...) 1 <-- ???
Парсер зависает, когда количество аргументов в скрипте не равно объявленным аргументам.
Не знаю для чего тот дефайн был сделан.

**Comment by phobos2077** [comment]
@FakelsHub по поводу зачем нужен дефайн написал в личку. Приведи пример кода на котором зависает парсер? Словесное описание в таких случаях никуда не годится :)

**Comment by FakelsHub** [comment]
Кстати после правок новый парсер стал зависать по мере набора кода на других участках кода связанные так же с аргументами процедурами, тот старый не зависает них.
Также стал зависать на коде `display_msg(sprintf({char* format}, {any value}));` и еще каких-то других.
В общем тот старый с исправленной мной ошибкой - которая как бы и не ошибка стабильнее работает.

**Comment by FakelsHub** [comment]
Прошлось опять убрать это `#ifndef BUILDING_DLL` в SemanticParseError
