### ISSUE TITLE
Sfall 3.8.4: Crash on door object

### ISSUE THREAD

**Issue by FakelsHub** [phobos2077/sfall#106]
Критическая ошибка игры при метании гранаты в объект типа дверь (дверь без привязанного  к ней скрипта).

**Comment by NovaRain** [comment]
I thought all doors should have scripts attached to them? Does the game still crash without sfall?

**Comment by FakelsHub** [comment]
It seems I understood what the problem is) 
I'll check again tomorrow and write the result.

**Comment by FakelsHub** [comment]
Sorry, I used version 3.8.4 with an error instead of the original :)

**Comment by FakelsHub** [comment]
> I thought all doors should have scripts attached to them? Does the game still crash without sfall?

I use some old features from crafty that are not in the original sfall, and there is a small fix for the doors in the damage_p_proc handler.
https://github.com/FakelsHub/sfall/commit/8c2e25c4dd3c3d2569acf18d325cdfd01cfc9ebe

**Comment by NovaRain** [comment]
Any example for the incorrect message output or what will happen calling damage_p_proc for missing non-critters?

**Comment by FakelsHub** [comment]
>example for the incorrect message output 

**Crafty**:
Если у цели, получившей повреждения, есть скрипт, то сработает damage_p_proc, но функция, которая выводит в монитор сообщения игнорирует цели, если они не являются персонажами и вместо "правильного" промаха ("Ой! Стена получает удар вместо намеченной цели (Нарк)!") сообщает о фальшивом промахе ("Вы : промах").
Подправил, если цель — дверь и у неё есть скрипт, то в мониторе вместо фальшивого промаха будет "правильный" ("Ой! Деревянная дверь получает удар вместо намеченной цели (Нарк)!").

> what will happen calling damage_p_proc for missing non-critters?

**Fakeman**: Если игрок бьет по  дверям оружием(кувалдой допустим) то это сообщением/звуком вообще никак  не проявляется т.е. как удар в никуда, но обработчик на дверях всегда срабатывает, вне зависимости попал ли по двери Игрок.
**Crafty**: Ты прав — баг в движке: для не персонажа перед вызовом damage_p_proc нет проверки что попадание действительно было, а потому damage_p_proc срабатывает и при промахах.

**Comment by NovaRain** [comment]
apply_damage_hack is still only for "debugging" version of sfall in Crafty's last released source code (2017-02-15). Does he enable it for normal version in later releases?
