### ISSUE TITLE
Time passing on map loads differs

### ISSUE THREAD

**Issue by Sduibek** [phobos2077/sfall#11]
Can we fix this? The amount of time that passes when loading a map differs widely and as far as I know it's hard-coded.

In my opinion there should be no hard-coded time increase whatsoever; it should be based on worldmap speed of how far it is from the current map. Or if that's too difficult to automate, which is likely, just leave it up to the modder to put it in the script.

Fallout 1: For example loading a map can take days in-game, sometimes even weeks. This can be seen going to Irwin's Farm, and doing the caravans.

Not sure about Fallout 2 but I think it also exists in that engine. Just calling the load_map(Z) function seems to essentially do something like calling a "set_game_time(game_time + rand(X, Y))"

I was reminded of it by this bug report from Fixt:
"entering Irwin's farm takes 5-6 days, leaving it takes two weeks." <-- none of that is in the script, it's all being applied by the engine.

**Comment by phobos2077** [comment]
I will check it some time later.

**Comment by Sduibek** [comment]
What became of this? I do think it's hard-coded in Fo1 engine but maybe we'll get lucky with Fo2. :)

**Comment by FakelsHub** [comment]
No problem. The issue can be closed.
