### ISSUE TITLE
Getting script number by its name.

### ISSUE THREAD

**Issue by FakelsHub** [phobos2077/sfall#111]
Пишу на русском для phobos, чтоб было понятно.
Появилась небольшая идея для текстовых функции которая бы позволила отвязать скрипт от жестко прописанному номеру скрипта с его .msg файлом после компиляции.
Требуется функция которая бы по заданному имени скрипта возвращала его номер из scripts.lsl.
`message_str(get_script_number("name_script"), 100)`
Получится, что такой скрипт можно  будет свободно подключать к любому номеру в .lst без его перекомпиляции.

Конечно в таком случает скрипт намертво привязывается к имени прописному в скрипте, но если пойти дальше и сделать так, чтобы функция сама передавала текущее имя у скрипта.
`message_str(get_self_script_number, 100)`

**Comment by FakelsHub** [comment]
Это работает?
array sfall_func0("get_metarule_table")
- returns names of all currently available scripting functions (via sfall_funcX)

Если это возвращает имена всех скриптов в нумерационном порядке как в scripts.lsl, то можно сказать, что задача практически решена. Надо будет проверить.

**Comment by phobos2077** [comment]
Ты неправильно перевел. Она возвращает названия скриптовых функций, доступных через `sfall_func`.

**Comment by FakelsHub** [comment]
А точно)
