### ISSUE TITLE
Define_extra.h incorrect value.

### ISSUE THREAD

**Issue by FakelsHub** [phobos2077/sfall#112]
https://github.com/phobos2077/sfall/blob/08b92542f476d5bd281d920302cb545ed3085e58/artifacts/scripting/headers/define_extra.h#L167
need name swapping
```
#define PROTO_CR_FLAGS           (32) 
#define PROTO_CR_ACTION_FLAGS    (52)  
```

**Comment by FakelsHub** [comment]
Also correct opcodes list `get_proto_data(object, int offset)` > `get_proto_data(int pid, int offset)`

**Comment by NovaRain** [comment]
I'm not sure if swapping names in header file is a good idea, because it would effect existing scripts.

**Comment by FakelsHub** [comment]
> I'm not sure if swapping names in header file is a good idea, because it would effect existing scripts.

Make a comment about the incorrect value of the flags.
