### ISSUE TITLE
Refresh player stats in open inventory.

### ISSUE THREAD

**Issue by FakelsHub** [phobos2077/sfall#113]
`call_offset_v0(0x471D5C);           /* update display_stats_ */`

**Comment by phobos2077** [comment]
`intface_redraw` doesn't do this?

**Comment by FakelsHub** [comment]
`call_offset_v0(0x45EB98);  /* intface_redraw_  */` это который перерисовывает игровую панель? то нет.
Можно добавить в `intface_redraw` и обновление стат, только если интерфейс игрока закрыт то насколько я помню игра вроде как падает.

**Comment by NovaRain** [comment]
I made a quick 4.0 test build with display_stats script function implemented, but not sure if it really works so you might want to test it with your scripts: https://www.mediafire.com/file/9si1oady5k0eoso/ddraw_4.0test_20170828.rar

Remember to add `#define display_stats    sfall_func0("display_stats")` in scripts.

**Comment by FakelsHub** [comment]
`display_stats` - why is this name chosen?  display_stats_redraw the name fits better.

**Comment by FakelsHub** [comment]
Working!
The only thing you not did, is need check is whether the player's inventory is open.
The function can only be used in this context `if get_game_mode == INVENTORY then sfall_func0 ("display_stats");` otherwise the game will falls.

**Comment by NovaRain** [comment]
OK, here's my [second try with embedded game mode check](https://www.mediafire.com/file/bk8u4datt8tdcpm/sfall_4.0.2_testbin20171104.rar).
Adding `#define display_stats_redraw    sfall_func0("display_stats_redraw")` in scripts is enough. Now calling the function while not in opened inventory doesn't crash the game, just do nothing.
