### ISSUE TITLE
Compilator: code optimization

### ISSUE THREAD

**Issue by FakelsHub** [phobos2077/sfall#116]
Full optimization breaks the source code
`bwand not(FLAG_TRANSGLASS + FLAG_TRANSRED)`
after optimization
`bwand 0`

 `bwand not(FLAG_TRANSGLASS) bwor FLAG_TRANSRED)`
after optimization
`bwand 0 bwor 16384)`

`not()` - is optimized to zero 👍

**Comment by FakelsHub** [comment]
The question, which version of the code is right ?
`bwand not(FLAG_TRANSGLASS + FLAG_TRANSRED)`
Or so
`bwand not(FLAG_TRANSGLASS or FLAG_TRANSRED)`

**Comment by phobos2077** [comment]
@FakelsHub , not is a boolean operator. For bitwise negation, use bwnot
