### ISSUE TITLE
Note: Looping execution of global scripts.

### ISSUE THREAD

**Issue by FakelsHub** [phobos2077/sfall#118]
For the global script in mode 1 `set_global_script_type(1)`
In combat mode, any animation of the dude (running/walking/using) the execution of scripts is interrupted until the animation is finished playing.

Is it a bug or a technical feature? :)

**Comment by phobos2077** [comment]
It's related to how the game handles motion, etc. There is no single main loop as usual, but a lot of different loops all of the place (for every UI window, etc.). So during combat animations, those scripts doesn't work... You need to either use workarounds (like using MOVECOST hook, etc.) or make deep research into the engine to find proper solution.
