### ISSUE TITLE
Skipping the "use" animation when using scenery

### ISSUE THREAD

**Issue by Lexx2k** [phobos2077/sfall#119]
As the title says. If the player is using a scenery object, there will always be a "use" (ground / middle) animation playing before the actual object script is executed. 
Would it be possible to get new script command or object flag to prevent this from happening?

PS: The use animation is not played when using an item on a scenery.

**Comment by FakelsHub** [comment]
What is the need to skipping this animation?

**Comment by Lexx2k** [comment]
I have a situation where the dude_obj has a sledgehammer equipped. When using an object, the "hit" animation will be played. In this case now, though, dude_obj will first holster the hammer, then use the object, , then "hit" the object with the hammer animation. This takes much time and it looks ugly. Both things I'd like to prevent.

**Comment by FakelsHub** [comment]
I understand you want to replace the animation "use" on the other, at a "hit"?

**Comment by Lexx2k** [comment]
Not skipping, but replacing the animation would work as well, yeah.

**Comment by FakelsHub** [comment]
This only skiping animation :)
write_byte(0x4120B4, 0xEB); //skip use animation
write_byte(0x4120B4, 0x74); // restore

**Comment by FakelsHub** [comment]
> there will always be a "use" (ground / middle) animation playing before the actual object script is executed.

How will you check when you need to skip and when you do not need I have no idea)
If only spatial script

**Comment by FakelsHub** [comment]
`write_byte(0x4120AB, XX); // replace use middle animation`
XX - animation number from ANIMCOMD.h

**Comment by NovaRain** [comment]
Just casually tried testing the offsets in use_p_proc in DOORL100.ssl, to make the first locked door in the temple of trial unlock and open itself if player is wielding a spear (and playing the thrust anim). Didn't seem to work to remove the "magic hands" anims in this way. Unless I use a global script to skip use anims.

**Comment by FakelsHub** [comment]
> Didn't seem to work to remove the "magic hands" anims in this way. Unless I use a global script to skip use anims entirely

> How will you check when you need to skip and when you do not need, I have no idea)
> **If only spatial script**

:)

This idea with the skipping of the animation is not entirely understandable to me, and what is the need to skip it.
If could show a more illustrative example, wherever it really is needed.

**Comment by FakelsHub** [comment]
Were give functions to replace the animation, I think the question can be closed.
There is no need to add such narrowly specific functions.

Maybe new hook could be done. I'll think about it.

**Comment by NovaRain** [comment]
Now it can be done with HOOK_USEANIMOBJ in the coming sfall 4.1.
