### ISSUE TITLE
scrolling in barter

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#120]
An idea to improve barter experience.

Currently, scrolling works on dude's inventory and that's all. To scroll through other 3 barter areas, you still have to use clicks. It would be great to be able to scroll through others. The area to scroll would depend on current cursor location. So when the mouse is over merchant's inventory, it would scroll it, Same for things "prepared" for barter.

**Comment by NovaRain** [comment]
You can enable ALT_MOUSE_INPUT in HRP; it'll let you scroll through other lists.

**Comment by burner1024** [comment]
Oh, I didn't realize that. Thank you!

**Comment by FakelsHub** [comment]
```
; Set ALT_MOUSE_INPUT=0 to allow Sfalls mouse input functions to work.
; Set ALT_MOUSE_INPUT=1 to enable alternate mouse input control built into the hi-res patch.
```
Не рекомендуется это включать, так как некоторые скрипты типа set_global_script_type=1 не будут работать.

**Comment by burner1024** [comment]
```set_global_script_type=1```
where is it used, for example?

**Comment by FakelsHub** [comment]
Протестировать работу можно на фильтре. Если с версии 3.5 ничего не меняли то работать не будет.
По этой причине я просил крафти что бы он ввел аналогичную фишку со скролингом как у HRP в свой sfall.

**Comment by burner1024** [comment]
I'll try and report

**Comment by NovaRain** [comment]
Oh right, enabling ALT_MOUSE_INPUT will make all buttons from the inven filter unclickable. It's a known case [since JimTheDinosaur posted his inven sorting mod](http://www.nma-fallout.com/threads/inventory-sort-buttons-mod.203180/page-3#post-4091696) Heh, actually I was the one reported it, just forgot it because I don't use the inven filter.
