### ISSUE TITLE
Cant log off from EPA main computer

### ISSUE THREAD

**Issue by marvdomain** [phobos2077/sfall#122]
there is no option for such as "log off" from the computer besides 7 rows introducing the color.....
EPA主机电脑无法退出，没有退出的选项。

**Comment by NovaRain** [comment]
1. EPA有一堆電腦你指哪層的哪台？What is the "main computer" you're referring to?
2. 不要把FO2 RP的問題拿來sfall這邊說，除非你確定是sfall某一版造成的。Do not post issues/bugs of FO2 RP here, unless you're sure it's caused by sfall updates.

**Comment by FakelsHub** [comment]
You can send me the engine and Chinese localization, I will conduct experiments)
Chinese fonts are also probably needed?

**Comment by marvdomain** [comment]
thank you very much, but how?
