### ISSUE TITLE
Redraws interfaces slots for items.

### ISSUE THREAD

**Issue by FakelsHub** [phobos2077/sfall#125]
**Обновить предметы в слоте интерфейса для цели:**
```
_target_pud:=read_int(0x59E978);
target_inventory_offset:=0x59E7EC + (read_int(0x59E948) * 4);
write_int(target_inventory_offset, 0);
call_offset_v4(0x47036C, inventory_offset, visible_offset, _target_pud, mode); /* display_target_inventory_ */
// Redraw the open interface
call_offset_v1(0x4D6F5C, read_int(0x59E964)); /* win_draw_ */
```
Протестированная и рабочая реализация для слотов предметов NPC в интерфейсах INTFACELOOT и BARTER.
```
write_int(0x59E7EC + (read_int(0x59E948) * 4), 0);
call_offset_v4(0x47036C, 0, -1, read_int(0x59E978), mode); /* display_target_inventory_ */
call_offset_v1(0x4D6F5C, read_int(0x59E964));  /* win_draw_*/
```

**Обновить предметы в слоте интерфейса для игрока:**
```
inventory_offset:=0x59E844 + (read_int(0x59E96C) * 4);
write_int(inventory_offset, 0);
call_offset_v3(0x46FDF4, inventory_offset, visible_offset, mode); /* display_inventory_ */
```
Протестированная и рабочая реализация для слотов предметов игрока в интерфейсах INTFACELOOT и BARTER.
```
write_int(0x59E844 + (read_int(0x59E96C) * 4), 0);
call_offset_v3(0x46FDF4, 0, -1, mode); /* display_inventory_*/
```
Реализация для обновления слотов предметов игрока в интерфейсе INVENTORY без дополнительного кода, для интерфейса INTFACEUSE тестирование не проводилось.
```
call_offset_v3(0x46FDF4, 0, -1, 0); /* display_inventory_*/
```

Параметры:
**inventory_offset** - для рюкзака можно читать содержимое в памяти read_int(0x59E844) чтобы получить смещение вещи которая сейчас видна первой (если прокрутил инвентарь вниз) или же 0 для отрисовки инвентаря начиная с самой верхней вещи;
**visible_offset** - -1 должно хватить, если положительное значение, то вроде номер (1-6?) конкретной вещи видимой сейчас в инвентаре;
**mode** - режим интерфейсного окна: 0 (INVENTORY), 1 (INTFACEUSE), 2 (INTFACELOOT) и 3 (BARTER);

_*Информацию предоставил Crafty._

**Comment by phobos2077** [comment]
Возьмите за сделайте Pull request. Добавлять подобные функции не сложно теперь.

**Comment by FakelsHub** [comment]
Честно вообще не понимаю как их добавлять, там же надо какие-то еще ассемблерные коды писать, а с этим вообще туго.
И нет возможности поставить VS15, только для версии 3.8. а там я как понял добавить еще сложнее.

**Comment by phobos2077** [comment]
@FakelsHub там по аналогии вполне можно разобраться. Посмотри коммиты от NovaRain, он тоже добавлял какуюто функцию хотя толком не шарит)
Можешь попробовать поставит 2017 студию, она намного легче чем 2015, по идее должна смочь собрать.

**Comment by FakelsHub** [comment]
> Можешь попробовать поставит 2017 студию

да системные требования не подходят под них, надо другую ос ставить, я тут на олдскулл XP сижу. :) На ноут жены не хочу ставить студию.

**Comment by FakelsHub** [comment]
Реализовано 2a20209bb81a8824cd2d97209d89e5f2d9292093
