### ISSUE TITLE
Highlighting corpses

### ISSUE THREAD

**Issue by FakelsHub** [phobos2077/sfall#126]
https://github.com/phobos2077/sfall/blob/4d0c056e72693d6bf71c3ef173104dbb65e00909/artifacts/mods/gl_highlighting.ssl#L55
Добавьте здесь проверку на флаг криттера `CRITTER_FLAG_NODROP`, чтобы все трупы не подсвечивались.

**Comment by NovaRain** [comment]
If you mean to only highlight lootable corpses, it should check NOSTEAL flag instead of NODROP.

**Comment by burner1024** [comment]
In Crafty's, untouched corpses with loot are yellow, touched but still having loot are are purple, the rest are grey. Same for containers. Works fine, I think.
