### ISSUE TITLE
Additional game message files cannot be read

### ISSUE THREAD

**Issue by Vennor** [phobos2077/sfall#127]
I remember that when I implemented additional game message files support, it was important to call the reading function in adequate moment due to some weird filesystem behavior.

https://github.com/phobos2077/sfall/blob/4d0c056e72693d6bf71c3ef173104dbb65e00909/sfall/Modules/Message.cpp#L92

Currently, when ``ReadExtraGameMsgFiles`` is called through ``OnGameInit`` delegate, it doesn't seem to have the path root at ``data\text\english`` - where the code expects it to - and it won't read any files.

One way to fix it is calling it through ``OnBeforeGameStart`` delegate.

**Comment by NovaRain** [comment]
Fixed now, thanks.
