### ISSUE TITLE
Fix add_mult_objs_to_inven over 99999

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#129]
Can we have [this](https://github.com/FakelsHub/InventoryFilter/blob/master/gl_InvenFilter_SE.ssl#L176) (see [also](https://github.com/FakelsHub/InventoryFilter/blob/master/gl_InvenFilter_SE.ssl#L560)) fixed natively, please?

**Comment by NovaRain** [comment]
It makes me think if the upper limit should be increased to INT_MAX (2147483647) or just keep it as 99999.

**Comment by FakelsHub** [comment]
Write INT_MAX.

**Comment by NovaRain** [comment]
For now I'll play it safe here, so the upper limit is still 99999. BTW, using add_mult_objs_to_inven with the count over INT_MAX will result in only one item.
