### ISSUE TITLE
"Disable Pipboy alarm" option faulty

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#13]
After upgrading to 3.7 (from 3.3), there's no option to rest in pipboy (the screen is just empty). Disabling "Disable pipboy alarm button" allows to sleep as per original.

**Comment by phobos2077** [comment]
The only issue I'm observing right now is that with `DisablePipboyAlarm=1` when you open "sleep" screen using Z button, there is no "Pip Boy 2000" logo on the screen. 
AFAIK, the idea behind this option is to disallow resting at all. So what's the issue? What has changed in behavior since 3.3?

**Comment by NovaRain** [comment]
The option works the same in both 3.3 and 3.7. If you set DisablePipboyAlarm=1, you can't access the alarm by the button on Pip-Boy UI or pressing Z key.

**Comment by burner1024** [comment]
Indeed, I re-checked and it seems I got confused somewhere when trasferring settings. Apologies for the false alarm.
