### ISSUE TITLE
Fix_Array - Resets to 0 the temporary array?

### ISSUE THREAD

**Issue by FakelsHub** [phobos2077/sfall#133]
Потребовалось определить массив скрипте таким образом.
```
ar_skills := ["SKILL_SMALL_GUNS", "SKILL_BIG_GUNS", "SKILL_ENERGY_WEAPONS"];
fix_array(ar_skills);
```
Но при таком способе массив создается временным, я применил Fix_Array, и массив после этого почему-то стал иметь нулевые значения. 
Это ошибка кода или так и должно быть? - но в чем смысл тогда функции.

А как можно определить таким образом постоянный массив?

**Comment by NovaRain** [comment]
Judging from the two lines, it seems to me you only create a list with 3 elements but not assigning values to them yet. I made a test script:
```
#include ".\HEADERS\DEFINE.H"
#include ".\HEADERS\sfall.h"
#include ".\headers\dik.h"

procedure start;
procedure keypress_handler;

variable ar_list;

procedure start begin
   if (game_loaded) then begin
      register_hook_proc(HOOK_KEYPRESS, keypress_handler);
      ar_list := ["SKILL_SMALL_GUNS", "SKILL_BIG_GUNS", "SKILL_ENERGY_WEAPONS"];
      ar_list[SKILL_SMALL_GUNS] := has_skill(dude_obj, SKILL_SMALL_GUNS);
      ar_list[SKILL_BIG_GUNS] := has_skill(dude_obj, SKILL_BIG_GUNS);
      ar_list[SKILL_ENERGY_WEAPONS] := has_skill(dude_obj, SKILL_ENERGY_WEAPONS);
      fix_array(ar_list);
   end
end

procedure keypress_handler begin
   variable
      event := get_sfall_arg,
      keyDX := get_sfall_arg;

   if (event == 1) and (keyDX == DIK_V) then begin
      display_msg("Small guns: " + ar_list[SKILL_SMALL_GUNS]);
      display_msg("Big guns: " + ar_list[SKILL_BIG_GUNS]);
      display_msg("Energy: " + ar_list[SKILL_ENERGY_WEAPONS]);
   end
end
```
The values in ar_list are correct during the current gameplay session.

**Comment by FakelsHub** [comment]
> Sorry if I mistake the post, but judging from the two lines, it seems to me you only create a list with 3 elements but not assigning values to them yet?

This array of three elements must already contain the values ​​"SKILL_SMALL_GUNS", "SKILL_BIG_GUNS", "SKILL_ENERGY_WEAPONS".
But after the function fix_array it is reset.
from  sscl_readme
```
> *array expressions: sometimes you need to construct an array of elements and you will probably want to do it in just one expression. This is now possible:
new:
  list := ["A", "B", "C", "D"];
  
old:
  list := temp_array(4, 2);
  list[0] := "A";
  list[1] := "B";
  list[2] := "C";
  list[3] := "D";
```
Confirmation above written, this procedure will display the values ​​of the array.
```
procedure name begin
 ar_list := ["SKILL_SMALL_GUNS", "SKILL_BIG_GUNS", "SKILL_ENERGY_WEAPONS"];
    while (i < 3 ) do begin
        display_msg("Name: " +  ar_list[i]);  i ++;
    end
end
```
You above create a dictionary(KeyPair) array.

**Comment by FakelsHub** [comment]
Я думаю вопрос можно закрыть, я еще сделал тесты и видимо тут дело не в том что fix_array  обнуляет значения массива, а в том что временный массив не создается, по видимому это связанно как то с движком, и в зависимости от вызываемой процедуры, в данном случае, я пытался создать временный массив в экспортируемой процедуре, которая вызывается из другого глобального скрипта. Видимо это влияет на создаваемый временный массив.

**Comment by phobos2077** [comment]
Прикольно что кто-то наконец-то использует новые скриптовые фичи. Я в свое время потратил ОЧЕНЬ много времени на их реализацию...

**Comment by FakelsHub** [comment]
> Прикольно что кто-то наконец-то использует новые скриптовые фичи.

Я давно использую, как только узнал о них.
