### ISSUE TITLE
Двойной переход при загрузке карты.

### ISSUE THREAD

**Issue by FakelsHub** [phobos2077/sfall#134]
При переходе с карты на карту через сетки переходов или использования лестниц, когда гекс игрока при переходе совпадает с гексом зоны сетки перехода на загружаемой карте, то происходит переход на гекс указываемый в сетки перехода из загружаемой карты, а не на гекс с изначальной сетки. Происходит как бы двойной переход.
Подозреваю, что и spatial скрипты тоже при этом срабатывают.

**Comment by FakelsHub** [comment]
Исправление: Вызов вставки по адресу 0х48A704
```
    cmp     ds:_map_state, 0
    jz      short map_leave
    pop     eax
    push    offset 0x48A74E

map_leave:
    mov     ebx, 10h
    retn
```

**Comment by NovaRain** [comment]
I tested the so-called double jump "bug" with Arroyo Temple map (exit grid data: map 004, dest. hex 31111). The double jump seems occurring in a delayed manner. The only bugged situation I can think of is an infinite loop of map loading, but that's some serious bad mapping IMO. You want player character standing on the exit hex of the loaded map, only loading next map when he make a step? Is there any useful case of that?

**Comment by FakelsHub** [comment]
This is not a bad mapping, it's a mistake, because as the player enters the exit grid, his hex remains the same when the new map is loaded.

**Comment by NovaRain** [comment]
Looks like I mistook your first post. I'm not good at mapping, so it would be nice if there's a set of maps can demonstrate the issue you said, or at least a video.

**Comment by FakelsHub** [comment]
I did not make any changes to the exit grid on the ARCAVES map.
Just set another exit grid on hex 31310 on the ARTEMPLE map, and I get a wrong jump.
Demonstration of the algorithm.
![1](https://user-images.githubusercontent.com/21695363/38199769-9c84b794-369a-11e8-9bb7-1c33d25bd251.jpg)


> is the code from Crafty?

Yes.

**Comment by FakelsHub** [comment]
You could use another correct fix, change the HEX position of the player, to a different position (i.e. HEX=0) before/when the map is loaded, this will save the double jump if the modder wants to make such a strange way transition. :)

**Comment by NovaRain** [comment]
I think for now Crafty's simple fix should be enough. If a modder wants to make different hexes in the same exit grid area to different position in destination map, he could just set different exit data in hexes.
