### ISSUE TITLE
WorldMapTimeMod= low values cause slow down on world map

### ISSUE THREAD

**Issue by nirran** [phobos2077/sfall#142]
at 100 time and speed are normal,but I play with it at 5 and it drastically slows down travel speed

**Comment by NovaRain** [comment]
I don't have any particular slow down here with WorldMapTimeMod=5. Do you play in fullscreen or windowed mode?

**Comment by nirran** [comment]
full screen in vitual machine,but I fixed it,these settings do what I want `;World map travel time percentage modifier
;Modifies how fast in game time passes while you're moving around the map screen without affecting encounter rate
;100 is normal speed, 0 stops time from passing
WorldMapTimeMod=5

;Set to 1 to use the Fallout 1 code to control world map speed
WorldMapFPSPatch=1

;Controls the world map speed if WorldMapFPSPatch is 1. Higher values cause slower movement
WorldMapDelay2=5

;Set to 1 to enable Ray's patch to make world map encounter rate independent of your travel speed
;Higher values of WorldMapEncounterRate cause a slower encounter rate
WorldMapEncounterFix=1
WorldMapEncounterRate=25

sorry for troubling u
