### ISSUE TITLE
Help - BUG about Fallout 2 ITA

### ISSUE THREAD

**Issue by NarakuITA** [phobos2077/sfall#143]
Hello everyone, I need help, to solve a bug that affects the Italian version.
There has been an amateur translation of Fallout 2 for a long time. This translation has been adapted for the GOG version that contains default sfall.
The first tests seem to be good, but a bug has appeared, about the "binoculars" option, when you click with the right mouse button on your character, a menu appears, clicking on the binoculars, the stats of the character appear at the bottom left. If it is in good health, the game crashes. If he is injured, or has a broken leg or other, the game works correctly.
This happens, only when the game is translated into Italian. Everything works perfectly in the original language.

I enclose a video to make you understand better!
In the first part, the character is healthy (the game crashes).
In the second part it is wounded (the game does not crash).
www.youtube.com/watch?v=tqvAfMUnwTQ&feature=youtu.be

Thank you very much I await news!

**Comment by NarakuITA** [comment]
Update:
I discovered, as we can see from the video, that this bug appears only at the beginning of the game.
Loading an old rescue, the Bug does not show up .... Why? Solutions?

**Comment by Lexx2k** [comment]
Wouldn't say this is an sfall issue. What's the language string looking like? As the crash only appears in the fan translation, I'm guessing a typo somewhere in that file. Either duplicated string or something faulty with the {}{}{}.

**Comment by NovaRain** [comment]
>This happens, only when the game is translated into Italian. Everything works perfectly in the original language.

I don't think it has anything to do with sfall itself. I'll close this issue.

**Comment by NarakuITA** [comment]
I understand, thank you very much. However, the translation is based on the CD version and always worked, but I will try to control everything, as you suggested.
May I know if Sfall himself introduces new texts or changes some original texts?

**Comment by NovaRain** [comment]
All new texts (in English) are build-in, unless you set it up to load translated texts in an ini file.

**Comment by NarakuITA** [comment]
Now I understand, what did you mean. In the GOG version the translations folder where you keep the .ini files does not exist. This folder has been deleted by GOG.

**Comment by NarakuITA** [comment]
I asked this question, because I saw that here you have arrived at version 4.0.3 while the one on gog is firm to verisone 3.2a.
The "Translations" folder in the GOG version does not exist and consequently the "ini" file.
I do not know if in this version there are texts in the ddraw.dll and ddraw.ini files.

**Comment by FakelsHub** [comment]
translated .ini files are optional.

**Comment by NarakuITA** [comment]
No, no error message appeared.
It all seems in Italian.
What I was asking for was not optional files, but if Sfall 3.2a added or modified original Fallout 2 texts.
