### ISSUE TITLE
Allow highlighting more objects

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#15]
I think it would be great to have a hotkey to highlight critters and transition areas (such as stairs, manholes, etc). It would be really helpful in dungeons. and other low-light areas.

Critters can be highlighted by entering combat mode, then exiting it, of course. But it takes considerable time, and doing it repeatedly is impractical..

Could be the same or different key that is currently used to highlight items. Preferably different colors, though.

**Comment by phobos2077** [comment]
I believe there is already an option to highlight containers as well as ground items, but not critters. I think that should be not so hard to do, just need to find which engine function is responsible for outlining objects and "expose" it to scripts. If it will be possible to make such scripting function, I'm all up for it.

**Comment by burner1024** [comment]
I noticed that it was actually Timeslip's original objective, too: http://www.nma-fallout.com/showthread.php?178390-FO2-Engine-Tweaks&p=3736053&viewfull=1#post3736053

**Comment by phobos2077** [comment]
Basically done, see Highlighting script included in develop branch.

**Comment by burner1024** [comment]
Great news, thank you! I'll give it a try as soon as it's released.
