### ISSUE TITLE
Не компилируется проект в VS15

### ISSUE THREAD

**Issue by FakelsHub** [phobos2077/sfall#155]
Установил студию и при компиляции получаю такую ошибку.

Ошибка (активно)		отсутствуют экземпляры перегруженная функция
"std::unordered_map<_Kty, _Ty, _Hasher, _Keyeq, _Alloc>::insert [с _Kty=int, _Ty=std::unique_ptr<fo::MessageList, std::default_delete<fo::MessageList>>, _Hasher=std::hash<int>, _Keyeq=std::equal_to<int>, _Alloc=std::allocator<std::pair<const int, std::unique_ptr<fo::MessageList, std::default_delete<fo::MessageList>>>>]", соответствующие списку аргументов	ddraw	d:\VisualStudio2015\Sfall4.0_Fork.git\sfall\Modules\Message.cpp	73	

```
Modules\Message.cpp(73): error C2664: "void std::_Hash<std::_Umap_traits<_Kty,_Ty,std::_Uhash_compare<_Kty,_Hasher,_Keyeq>,_Alloc,false>>::insert(std::initializer_list<std::pair<const _Kty,_Ty>>)": невозможно преобразовать аргумент 1 из 
"std::pair<unsigned int,fo::MessageList *>" в "std::pair<const _Kty,_Ty> &&"
1>          with
1>          [
1>              _Kty=int,
1>              _Ty=std::unique_ptr<fo::MessageList,std::default_delete<fo::MessageList>>,
1>              _Hasher=std::hash<int>,
1>              _Keyeq=std::equal_to<int>,
1>              _Alloc=std::allocator<std::pair<const int,std::unique_ptr<fo::MessageList,std::default_delete<fo::MessageList>>>>
1>          ]
1>          and
1>          [
1>              _Kty=int,
1>              _Ty=std::unique_ptr<fo::MessageList,std::default_delete<fo::MessageList>>
1>          ]
1>  Modules\Message.cpp(73): note: Причина: невозможно преобразовать "std::pair<unsigned int,fo::MessageList *>" в "std::pair<const _Kty,_Ty>"
1>          with
1>          [
1>              _Kty=int,
1>              _Ty=std::unique_ptr<fo::MessageList,std::default_delete<fo::MessageList>>
1>          ]
1>  Modules\Message.cpp(73): note: Для выполнения данного преобразования нет доступного оператора преобразования, определенного пользователем, или вызов оператора невозможен
```
Что не так со студией?

**Comment by FakelsHub** [comment]
Еще необходимо в проекте к LibPath добавить расположение DirectX Sdk
$(DXSDK_DIR)lib\x86\

**Comment by NovaRain** [comment]
Not sure about the compile error, I installed my VS2015 with VC++ components only:
![Imgur](https://i.imgur.com/rteUMh0.png)

The only thing I changed for the project is Include/Lib paths of DXSDK (I use an extremely minimal set with about 13MB in size). Then I can simply build the project without C2664 error.

**Comment by FakelsHub** [comment]
If comment this line, then the project is compiled without problems.
may be incorrectly written code. :-)

**Comment by NovaRain** [comment]
>I used visual studio enterprise (update 1)
Maybe try to update VS2015 to the latest Update 3?

**Comment by FakelsHub** [comment]
> Maybe try to update VS2015 to the latest Update 3?

Are you using Update3?
For now, it's enough for me to use Update1 for the test with a commented line of code.

**Comment by FakelsHub** [comment]
> But yes we should change the project to use PATH variable by default, instead of a fixed path.

There is absolutely no path to lib, I had to write it myself.

**Comment by NovaRain** [comment]
>Are you using Update3?
For now, it's enough for me to use Update1 for the test with a commented line of code.

Yes.
The code change to Message.cpp was at 2016/11/10 by phobos, and Update 3 got released about five months earlier, so there's high chance he's already been using Update 3 by the time committing the code. Also from VS2015 release notes there are some changes/enhancements for C++ library in Update 2 & 3, so I'd say you should seriously consider to update your VS2015.
