### ISSUE TITLE
Add an option to auto reload

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#16]
It would be a considerable time saver an option for the dude to auto reload both weapons at the end of combat with the same ammo, if possible. (Like party orders addon does to NPC).

**Comment by phobos2077** [comment]
I think there is a key you can press to reload your weapon.
```
; R - reload
ReloadWeaponKey=19
```

Is it not enough?

**Comment by burner1024** [comment]
I'm using it, yes, and it's great. I do think it would be even greater to have autoreload. Of course, that's just my opinion.

**Comment by phobos2077** [comment]
It IS possible to script auto-reload. A little bit tricky though, as you need to understand how items stack together and how "top item quantity" works. Some guy already asked this in the past and I have pointed him to a solution in my version of Party Orders addon. Sadly he didn't finished the idea.

Basically you need to make a global script which will monitor if combat mode is one and trigger when combat ended (or just use *dude_obj's* `combat_p_proc`), then trigger the reload function.

This function will check if you need to load some ammo (`get_weapon_ammo_count`), check current ammo PID for a weapon (`get_weapon_ammo_pid`), search for ammo of this PID in dude inventory and then load as much ammo as you can/need, considering stacks and such.

**Comment by burner1024** [comment]
That guy is me.

On Fri, Nov 6, 2015 at 6:11 PM, Vlad <notifications@github.com> wrote:

> It IS possible to script auto-reload. A little bit tricky though, as you
> need to understand how items stack together and how "top item quantity"
> works. Some guy already asked this in the past and I have pointed him to a
> solution in my version of Party Orders addon. Sadly he didn't finished the
> idea.
>
> Basically you need to make a global script which will monitor if combat
> mode is one and trigger when combat ended (or just use *dude_obj's*
> combat_p_proc), then trigger the reload function.
>
> This function will check if you need to load some ammo (
> get_weapon_ammo_count), check current ammo PID for a weapon (
> get_weapon_ammo_pid), search for ammo of this PID in dude inventory and
> then load as much ammo as you can/need, considering stacks and such.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phobos2077/sfall/issues/16#issuecomment-154383177>.
>



-- 
Ilya Ivanov, DevOps eXtraordinaire. Contacts <http://devopsx.com/contacts>.

**Comment by phobos2077** [comment]
Hah, small world :)

I see there is some engine function that is used to reload weapon. Need to play with it and consider "exposing" it.

**Comment by burner1024** [comment]
I found the old thread. You stated that it's possible to script that, but the UI will not reflect the changes, that's why I dropped it.

**Comment by phobos2077** [comment]
No it's possible. See related issue.

**Comment by burner1024** [comment]
Got it. Will implement when 3.8 is out.
