### ISSUE TITLE
Game Hooks.

### ISSUE THREAD

**Issue by FakelsHub** [phobos2077/sfall#165]
Интересует мнение по поводу [такого](https://github.com/FakelsHub/sfall/commit/d896cb3a82516fb7c95e958fb1699fc2475c7d48) подхода к реализации встраивания игровых Hooks в код игры.
По сути сейчас если Hooks скрипты не используется, то в код движка они все равно встраиваются.

Я тут предлагаю вариант когда Hooks скрипты будут встраиваться в код движка когда они действительно используются.
Что скажете по поводу такого изменения? Нужно ли оно.

**Comment by phobos2077** [comment]
Я как-то давно хотел такое сделать, но видимо забил. Идея нравится но реализацию можно почистить, например `isInjectHook` перенести в другое место, этот флаг относится ко всему классу хук-скриптов, а не к конкретному скрипту (под "классом" имею ввиду HOOK_INVENTORYMOVE и тд, а "скрипт" это то что цепляется после вызова `register_hook_proc`). 
Еще я бы поработал над функцией где большой `switch`, может для каждого хук скрипта свой метод. 

Или вообще отдельный класс `HookScriptType` с виртуальным методом `Inject`. Для каждого скрипта свой подкласс, туда же можно и сам код хук скриптов свалить. Хранить эти объекты в массиве с индексами соответствующими id хука. Но это так вариант если хочется попрактиковаться в ООП )

**Comment by FakelsHub** [comment]
`isInjectHook` - типа сделать отдельный массив в количестве hook скриптов?
`std::vector<HookScript> hooks[numHooks]` << и здесь разве не список всех игровых хуков?

> switch, может для каждого хук скрипта свой метод.
А как потом эти методы вызывать, если будет регистрация хука из скрипта `register_hook/register_hook_proc` ?

**Comment by FakelsHub** [comment]
Переделал реализацию, без делегата куда лучше выходит.

**Comment by FakelsHub** [comment]
Если не кто не против я закрываю вопрос.
Я протестировал данное изменение и это работает без каких либо проблем.
