### ISSUE TITLE
Runtime party control toggle

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#17]
Probably a long shot, and not many people would use it, but I thought I'd ask, just in case. Reason is that controlling the party manually all the time is overly tedious, and not really worth it. But just once in a while, you really need the NPC to take cover, or shoot a specific enemy. And of course, it's exactly what he doesn't do.
Therefore, a key allowing to toggle between these 2 modes would be perfect.

**Comment by phobos2077** [comment]
That's actually should be easy to implement. A scripting command to change setting dynamically. And then a simple global script will listen for key presses and print appropriate message in console.

**Comment by phobos2077** [comment]
Added function `sfall_func1("set_dude_obj", obj)` - allows to take control of any critter at any time. Highly experimental. Will need to test various cases and also provide some combat-related hooks in order to replace current INI settings.

**Comment by phobos2077** [comment]
Though the original request is not yet fulfilled, it is now much easier to do. You can modify script *"gl_partycontrol.ssl"* and add whatever triggers/toggles you wish.
