### ISSUE TITLE
Perk Awareness

### ISSUE THREAD

**Issue by FakelsHub** [phobos2077/sfall#172]
> sFall 4.0.4(5) проблема с перком наблюдательность,
> при наведении не в прицельном режиме на NPC, может пропадать прицел
> и ты не видишь %, особо это проявляется на когтях смерти в пещере в Сэдите (Ressurection),
> в 3.8.9 такого нет, всё в порядке.

Нужно проверить этот баг.

**Comment by NovaRain** [comment]
I didn't have the issue with 4.0.4 when fighting deathclaws in Sedit cave, and actually I'm having a more serious bug with using party control with 4.0.5 in Resurrection: the game always crashes when trying to control party members (even if there's none):
```The instruction at 004589fc referenced memory at 00000065```

All binaries compiled between commit 76f88eae185ffd5783c665e2fb1b0ecf875609a0 and c2f7e38a43c18fd7443a30cea62180ef9f19091b seem to have this crashing issue.

**Comment by FakelsHub** [comment]
that is, there is no bug in this 30002664efe46eca6314195c0c1311edf160c428 commit?

**Comment by NovaRain** [comment]
Yes, it seems for some reason the new injection system prevents the crash that happened on my games (tested Resurrection and Mutants Rising demo). But I'm not sure why or how to reproduce your "target cursor missing ToHit number when controlling NPCs" issue.

**Comment by NovaRain** [comment]
>about the perk, the option 'watch in battle' should be turned on, as I understood.

Combat Looks? I always turn on the option in my game.

**Comment by FakelsHub** [comment]
The cause of the crash I found in HOOK_MOVECOST, but there is a deeper problem exists in the defect of hook HOOK_COMBATTURN, causing to crash in the script gl_partycontrol.
The temporary solution can be corrected in the script 'pid: = obj_pid (critter)' here critter==1 you can put a check on the type of object.

**Comment by NovaRain** [comment]
>The cause of the crash I found in HOOK_MOVECOST, but there is a deeper problem exists in the defect of hook HOOK_COMBATTURN, causing to crash in the script gl_partycontrol.

So it's more like the bug was made more obvious when extending the functionality of hooks during 4.0.5?

>The temporary solution can be corrected in the script pid := obj_pid(critter) here critter==1 you can put a check on the type of object.

I uncommented line 31 and changed it to ```display_msg("Combat Turn: " + status + ", by "  + critter + ", arg3: " + arg3);```. With 4.0.4 or the latest commit, "critter" is a normal pointer value when PC's turn ends:
```Combat Turn: 0, by 91896496, arg3: 0```
With 4.0.5, it's some unusually small value (e.g. 13) and arg3 is not a bool value, like:
```Combat Turn: 0, by 13, arg3: 13```
Weird. I tried to add a obj_type() check for the critter argument, but it's also resulted in a crash at obj_type function.

**Comment by FakelsHub** [comment]
These numbers (13) the number of moves from the  hook.
then you need to put a check 'critter> 100' (or more)

> So it's more like the bug was made more obvious when extending the functionality of hooks during 4.0.5?

These numbers (13) are the number from the previous hook (probably from HOOK_MOVECOST), in fact in the hook HOOK_COMBATTURN an wrong the implementation of the code.
then you need to put a check critter> 100 ' or more (1000 for example)

**Comment by FakelsHub** [comment]
I made a very serious mistake when implementing hooks, getting rid of the beginhook(3) and hookend() macros. Now I need to restore this as it was...

**Comment by NovaRain** [comment]
>we need to check this bug on win10, as the problem was on this system.

I tested in my Win10 x64 Pro and still couldn't reproduce the issue with 4.0.6 when fighting deathclaws in Sedit cave. Do you have the same issue or it's reported by some user on Russian forums?

**Comment by FakelsHub** [comment]
I have no problem, the person reported on the forum.

**Comment by NovaRain** [comment]
>I have no problem, the person reported on the forum.

It seems more like a random or system-specific glitch rather than a generic bug, unless there are more people having the same issue.

**Comment by FakelsHub** [comment]
here the problem is that with the version of 3.8+ such a problem is not observed.

**Comment by NovaRain** [comment]
>here the problem is that with the version of 3.8+/4.0.3 such a problem is not observed.

Well, majority of the changes in 4.0.4 binary were from you. I guess you could disable them (engine fixes/script functions) one by one with different binaries and test them with the guy having the issue.

**Comment by FakelsHub** [comment]
I'll try to ask him some clarifying questions. There guy 60 years) do not think that he wants to mess with the files.
At me still such question, you release v4.0.5 compilation did studio VS17?

**Comment by NovaRain** [comment]
>I have question, you did release v4.0.5 compiling with studio VS17?

The toolset I use is still VS2015 (v140_xp). All sfall 4.0.x builds are compiled with ReleaseXP config.

**Comment by NovaRain** [comment]
So it's solved, or just too random to find out the cause of glitch?

**Comment by FakelsHub** [comment]
It looks like a bug due to his system.
