### ISSUE TITLE
Display occupied/total space

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#18]
Display space usage in "occupied/total" format in containers. Trunk specifically, but other containers also would probably be great.

**Comment by phobos2077** [comment]
Where exactly on screen would you like this text to be displayed? 
If it's only Trunk you want, the simplest solution is to just edit it's script and on `description_p_proc` display current container size. It can be calculated using vanilla functions for inventory iteration and then checking item sizes via `get_proto_data`, for example.

I think it is possible to make pure scripted solution when text is drawn on screen as you open any container, using vanilla UI functions. Recent mod that allows to sort and filter inventory items - proved it.

**Comment by burner1024** [comment]
It doesn't matter where, or does it? Yes, for me trunk would be enough.
I've just learned about the sorting mod. I will check it out.

**Comment by burner1024** [comment]
I think those mods draw predetermined images after all, and not text. Please correct me if I'm wrong.

**Comment by phobos2077** [comment]
I think there should be a function for displaying a block of text. Will need to investigate it though.

**Comment by burner1024** [comment]
I believe this is obsolete now that inventory filter is out.
