### ISSUE TITLE
Alternate msg location for female characters (translation friendly)

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#183]
FO2 has multiple translations circling around (and we're [working](https://tra.bgforge.net/projects/fallout/) on some). Unfortunately, in most languages it's not quite possible to always have the same translation string for male and female characters. Which results in separate packages for male/female. And those are then used with ugly workarounds like creating separate startup icons, linking them to bat files, and having those bat files copy over the whole dialog dir each time you launch a game with another gender.
I imagine having mods installed makes this even more cumbersome.

If that is viable, I'd like to request an option such as "female_dialog_suffix", which, if set, would cause msg strings lookups to go to a directory suffixed with that value. So that if language in fallout2.cfg is set to "spanish", male characters would use default "data/text/spanish" and female ones - "data/text/spanish_female".

**Comment by FakelsHub** [comment]
Покажи мне вариант скрипта с использованием female_dialog_suffix.

> Unfortunately, in most languages it's not quite possible to always have the same translation string for male and female characters.

А что реализация как у 1C с женскими репликами, вас не устраивает?
просто добавляете макрос и вуаля.

**Comment by FakelsHub** [comment]
В общем я поглядел код движка, можно сделать чтобы все продублированные msg файлы диалогов лежали в папке `text\*lang*\dialog_female\`

**Comment by burner1024** [comment]
Да, дублирование. Можно с фоллбэком (если женский файл не существует, идти в мужской), но это не принципиально.
Опция бы включала эту фунциональность и говорила где искать, суффикс женской папки. _f или _female, это уже на выбор пользователю/моддеру.

**Comment by FakelsHub** [comment]
Имя для каталога файлов будет за хардкодено, для начало гляну если суффикс _female не вызовет проблем то так и оставлю, иначе будет урезано до 8 букв.

**Comment by burner1024** [comment]
No, phrasing probably doesn't change. I'm not sure what they did for F1, but a good chance it's just missing female alternatives.

**Comment by NovaRain** [comment]
>No, phrasing probably doesn't change.

I would like an example of why it needs a gender alternative for female player. And does it only happen on Spanish? What about other European languages?

**Comment by FakelsHub** [comment]
Je suis allée - female pc
Je suis allé   - male pc

**Comment by burner1024** [comment]
[Spanish](https://forum.bgforge.net/viewtopic.php?f=9&t=28&p=78) example. There are more differences in Russian (verbs). Can't vouch for all languages, but I know for a fact that Italian, Polish, Portuguese are also in this category.

**Comment by NovaRain** [comment]
Here's the test build with alternative female dialog files support from the commit above: http://www.mediafire.com/file/lplhnvl3ochc37r/sfall_20180723.rar/file

You need to add FemaleDialogMsgs=1 in ddraw.ini to enable the feature. The alternative dialog files should be in text\(language)\dialog_female. sfall will load the msg file from the default dialog folder if there's no alternative in dialog_female.

**Comment by burner1024** [comment]
Awesome, seems to work! Which section does the option go to? I added to both main and misc.

However, I'd like to ask to branch at "text/language" level, not "text/language/dialog". "Cuts" and "game" strings may also be gender dependent.

**Comment by burner1024** [comment]
One extra directory seems cleaner than three to me... Also if packaging a mod with translations, running diffs and comparing might be easier that way. But it's not principal, so

**Comment by FakelsHub** [comment]
Cuts и Game не могут содержать фраз зависивших от женского игрока.  В  game некоторые файлы уже имеют разделение для женского и мужкого рода.

**Comment by burner1024** [comment]
Я привел пример, он как раз из cuts.

**Comment by FakelsHub** [comment]
Ну там реально это одно слово "Избранный" :) я думаю ничего с игроком не произойдет если он увидит это слово в мужском роде.
Я понимаю в диалогах род может повсеместно использоваться, но в титрах можно и без рода переводить, ничего страшного не произойдет.

**Comment by burner1024** [comment]
ну... я могу много причин привести, но я не вижу, почему просто не сделать на все нормально.

**Comment by FakelsHub** [comment]
Для Game точно нет, в силу движковых причин. 
Cuts сделаю, но отдельной опцией так как там нет поддержки для фоллбэка.

**Comment by burner1024** [comment]
Понятно. Печальновасто...
```
killap-up$ diff -ur spanish/data/text/english/game spanish_female/data/text/english/game | grep "^+\|^-" | wc -l
268
```

**Comment by FakelsHub** [comment]
Мне просто интересно что можно переводить в игровых мсг под женский род? 
Там же интерфейс названия карт, прочая хрень не относящаяся к полу игрока.

**Comment by burner1024** [comment]
Перки, трейты, статусы боевые сообщения кое-какие (друг/подруга, неудачник/неудачница итд) , в pro_item кое-где сообщения от первого лица вроде.
[Тут](https://github.com/BGforgeNet/fallout2-up-translation) можно дифф поглядеть.
```
 diff -qr spanish/data/text/english/game spanish_female/data/text/english/game
Los archivos spanish/data/text/english/game/cmbatai2.msg y spanish_female/data/text/english/game/cmbatai2.msg son distintos
Los archivos spanish/data/text/english/game/combatai.msg y spanish_female/data/text/english/game/combatai.msg son distintos
Los archivos spanish/data/text/english/game/custom.msg y spanish_female/data/text/english/game/custom.msg son distintos
Los archivos spanish/data/text/english/game/editor.msg y spanish_female/data/text/english/game/editor.msg son distintos
Los archivos spanish/data/text/english/game/intrface.msg y spanish_female/data/text/english/game/intrface.msg son distintos
Los archivos spanish/data/text/english/game/misc.msg y spanish_female/data/text/english/game/misc.msg son distintos
Los archivos spanish/data/text/english/game/perk.msg y spanish_female/data/text/english/game/perk.msg son distintos
Los archivos spanish/data/text/english/game/pro_crit.msg y spanish_female/data/text/english/game/pro_crit.msg son distintos
Los archivos spanish/data/text/english/game/pro_item.msg y spanish_female/data/text/english/game/pro_item.msg son distintos
Los archivos spanish/data/text/english/game/proto.msg y spanish_female/data/text/english/game/proto.msg son distintos
Los archivos spanish/data/text/english/game/scrname.msg y spanish_female/data/text/english/game/scrname.msg son distintos
Los archivos spanish/data/text/english/game/skill.msg y spanish_female/data/text/english/game/skill.msg son distintos
Los archivos spanish/data/text/english/game/trait.msg y spanish_female/data/text/english/game/trait.msg son distintos
```

**Comment by FakelsHub** [comment]
Во всех этих файлах сообщений трейты/перки/предметы/криттеры и остальная интерфейсная составляющая все переводиться не привязываясь к полу игрока.

В боевых сообщения в COMBAT.MSG, где это необходимо уже есть разделение на female/male.
В COMBATAI/COMBATAI2 в случае где нпс обращаются к игроку, фразы должны быть построены/переведены от среднего рода.

```
Eres adicto al RadAway
Eres adicta al RadAway
```
Я так полагаю что переведено как - "вы зависим"
вторая строка  - "вы зависима"
А нельзя это перевести от множественного числа как в русском "зависимы/те"?

Даже в русском переводе 1С не занимались таким педантичным переводом как у вас.
```
{3003}{}{Defensor}
{3003}{}{Defensora}
```
имхо это уже излишество перевода.

Тогда я могу попробовать сделать дополнительную опцию для \lang_female\ но тогда уже все без поддержки фоллбэка (нет файла вылет игры).
Интересно мнение Novarain?

**Comment by NovaRain** [comment]
I'm fine with burn's idea of 'text\lang_female\" setup if possible to replace the current one, since I don't really have much opinion on translation or experience on European languages.

**Comment by burner1024** [comment]
Ну как переводится без привязки... вот перевод, переведено с ней. Чтобы говорить, что это неверно, надо по крайней мере язык знать не хуже того, кто переводил. Плюс если разделять файлы на категории, придется объяснять переводчикам, что тут так переводить, тут по-другому. Кто-то не поймет, кто-то забьет, кто-то везде начнет изворачиваться к среднему роду. Качество и так любительское, еще больше пострадает.

Дело в том, что неправильно механически переносить впечатления от одного перевода на другой.  Это как объяснять англичанину, скажем, рода и склонения. Берем простое предложение типа "he/she walked the road, hungry and angry". В английском меняется 1 слово, в русском почти каждое. Ну и гипотетический англичанин будет возмущаться, что местоимение уже есть, кто шел по дороге - понятно. А прилагательные и глаголы менять - уже "излишество". В принципе, он будет как бы и прав со своей точки зрения, ну просто вот такой русский язык.

И такие фишки везде. Разные правила, склонения, артикли, числительные, устойчивые языковые конструкции итд. Поэтому тяжело предусмотреть все случаи в коде - программист не переводчик, всех языков не знает, ему просто неизвестно, где подляночка выскочит. Как правильно перевести, решает переводчик в момент перевода.
Опцию я же не конкретно для себя и не конкретно под этот проект запрашиваю. Если бы так, то я бы и не заморачивался, наверное. Но сейчас только на BGforge и только на Fallout-проектах используются 4 языка. Вероятно, будет больше.

Конкретно по замечаниям:
* adicto/adicta: Верно полагаешь. Но в русском единственная и множественные формы местоимений совпадают, и то и другое "вы". В испанском они разные, "usted/ustedes" (это еще не трогая латиноамериканский вариант с vos/vosotros). В единственном числе половое различие сохраняется.
* adictivo означает в общем-то то же самое, что и в русском/английском - аддиктивный/ая. Это прилагательное, и тоже с родом изменяется. Конкретно на этой строке, как и в русском, в принципе можно извернуться, что-нибудь типа "tienes una dependencia al Rad-Away", но, как я выше объяснил, такие приемы в конечном итоге повышают корявость.
* Носители испанского какие-то есть, но пока они весьма неактивно его несут, поэтому сейчас в основном по испанскому делаю что-то я. Машинный перевод там идет в помощь, если тупо через него прогонять, то и смысла никакого не в онлайн переводе, за полчаса можно пробить оба фоллаута через гугл транслейт.
* Однако испанский перевод UP/RP не с нуля делается, он основан на переводе 1.02d, который сделали [ClanDLAN](http://academia.clandlan.net/?page=academia/view&id=371&title=Traduccion_Fallout_2). Они там вполне себе носители. А сейчас идет обновление/правка.

Вот... Так много написал не потому, что так сильно настаиваю, просто тема достаточно обширная. Если движок не может, ну, не может, ясно. Даже только диалоги это уже большое улучшение.

**Comment by FakelsHub** [comment]
> Уточнение небольшое, это будет работать с PatchFile директорией как phobos описал?

Думаю да. Я проверял с диалогами упаковал в path000.dat папку dialog_female и от туда тоже читает.

**Comment by FakelsHub** [comment]
В общем ничего не получится с game папкой, как оказалось большинство файлов загружаются в память при запуске игры, и там остаются до конца игры.
Так что интерфейс тебе делать только внешней опцией. через батник.

**Comment by burner1024** [comment]
Так а нельзя их перезагружать при загрузке игры/карты?
Я смотрю еще опция есть AlwaysReloadMsgs, но до конца не понятно, что именно она делает.

**Comment by FakelsHub** [comment]
Я незнаю как их перегрузить.
AlwaysReloadMsgs, влияет только на файлы из папки диалога.

**Comment by burner1024** [comment]
Ясно, ладно. А в какие моменты эта опция вообще применяется? Не пойму ее цель.

**Comment by FakelsHub** [comment]
Да толку от нее нет, для тестирования она нужна, файлы диалогов тоже один раз загружаются при начале диалога, и второй раз уже из памяти файл читается.
Так вот она убирает проверку, и файлы диалогов каждый раз заново загружаются.

**Comment by burner1024** [comment]
Понятно.

**Comment by FakelsHub** [comment]
Сделать то можно но нужно сидеть ковыряться и разбираться как перегрузить файлы.
При том что во время создания персонажа интерфейс будет по дефолту переведен по male.

**Comment by NovaRain** [comment]
Here's the new test build that can read video/slide subtitle files from text\(language)\cut_female:
http://www.mediafire.com/file/g22uxqx62or9s7b/sfall_4.1pre_20180903.rar/file

You need to set FemaleDialogMsgs=2 in ddraw.ini. You must have all subtitle files in cuts_female, not just the edited ones. The game does not load missing files from non-female folder like how dialog msgs works.

**Comment by burner1024** [comment]
Cuts working, confirmed.

**Comment by NovaRain** [comment]
Thanks for testing, and thanks to Mr.Stalin for the implementation. I guess this issue can be closed?

**Comment by burner1024** [comment]
So we have dialog_female and cuts_female, correct? If game not coming, then I guess it can.

**Comment by NovaRain** [comment]
Yes.
Since game msgs are loaded at the launch of the game before player can choose the gender, I guess alt game msgs would require some overhaul to make the engine load msgs from a different path after the game started.

**Comment by burner1024** [comment]
Very well. Many thanks @NovaRain and @FakelsHub.
