### ISSUE TITLE
quick save options

### ISSUE THREAD

**Issue by nirran** [phobos2077/sfall#186]
is it possible to add crafty's quicksave code to current? ie.

``;To use more than one save slot for quick saving (F6) and without picking a slot beforehand. The number assigned is a number of save slots (1..10) to use for quick saving, cycling from the top one down and over to the earliest one.
AutoQuickSave=5``

**Comment by FakelsHub** [comment]
we will add, but this is not in the priority.

**Comment by NovaRain** [comment]
>we will add, but this is not in the priority.

I didn't plan to add it in the past even if the code is already available in Crafty's build.

**Comment by nirran** [comment]
ok thxn for ur great work

**Comment by FakelsHub** [comment]
> I didn't plan to add it in the past even though the code is already available in Crafty's build.

A very useful thing, but it needs to be modified to work a little differently than Crafty.
