### ISSUE TITLE
Automatically open/walk through unlocked doors

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#19]
I think an option to have the doors open automatically for the dude when they're not locked would be a huge timesaver.

I'm not sure, maybe this is better done with scripting, if so, let me know and I'll try to look into that myself.

**Comment by NovaRain** [comment]
I'm pretty sure It can be scripted. The only downside is you have to recompile lots of scripts, but it's not hard to batch compile all scripts.

**Comment by phobos2077** [comment]
Not necessarily need to recompile scripts. If I'm not mistaken, when NPCs move, they automatically open doors on their way, if they not have "locked" flag. Need to investigate further, maybe it is possible without more hacks with some trick, maybe not. 
The key issue is that you can't order dude to move inside a room, until you open the door (the room will be highlighted as unaccessible).

**Comment by FakelsHub** [comment]
To do this, the door has a flag WalkThru.

**Comment by FakelsHub** [comment]
Можно глобальный скрипт написать чтобы он всем дверям  на карте поставил флаг WalkThru.
И будет то, что хочет автор данного вопроса.
И закройте уже этот Issue.

**Comment by phobos2077** [comment]
@FakelsHub хорошее предложение. Проверять я его конечно не буду... Пусть это сделает автор ;)

**Comment by Lexx2k** [comment]
I guess this is how I would approach this: Add a script to every door. Check if it is locked / unlocked. If unlocked, set proto flag to walk through. Check if the player is on the door hex, if yes, open the door. 
This isn't really perfect, though. It requires a script for every door, and existing door scripts need to be edited. Also it requires a spatial script on the door position. Oh, and you need to check this in combat, because opening / closing doors uses action points.

**Comment by FakelsHub** [comment]
> I guess this is how I would approach this: Add a script to every door. Check if it is locked / unlocked. If unlocked, set proto flag to walk through.

It is not required to set any scripts on every door, and do any checks - the flag is processed by the engine, and he will do everything necessary.

**Comment by FakelsHub** [comment]
> Oh, and you need to check this in combat, because opening / closing doors uses action points.

Yes, such a door with the flag set will not reduce of action points when running through it, but this is solved by a global script by resetting the flag for all doors on the map when entering combat mode.

**Comment by Lexx2k** [comment]
Well, I wouldn't know how to do this then. It sounds easy on paper, though.

**Comment by burner1024** [comment]
You refer to set_proto_data function, right?

**Comment by FakelsHub** [comment]
Mod ready.
```
/* Include Files */
#include "..\headers\define.h"
#include "..\headers\command.h"
#include "..\m_headers\sfall\sfall.h"
#include "..\m_headers\sfall\define_extra.h"

/* Standard Script Procedures */
procedure start;
procedure set_door_flag(variable state);

/* Defines */
#define PORTAL       (0)
#define DOOR_FLAGS   (0x24)

/*******************************************************************
   Imported variables from the Map scripts. These should only be
   pointers and variables that need not be saved. If a variable
   Needs to be saved, make it a map variable (MVAR_)
*******************************************************************/

/*******************************************************************
   Local variables which do not need to be saved between map changes.
*******************************************************************/
variable only_once := 0;

/*******************************************************************
*******                         PROCEDURES                   *******
*******************************************************************/
procedure start begin
   
   if game_loaded then begin      
      set_global_script_repeat(25);
      set_global_script_type(0);
      
      only_once := 1;
      call set_door_flag(true);
   end
   else begin      
      if (only_once == 1 and combat_is_initialized) then begin
         only_once := 2;
         call set_door_flag(false);
      end 
      else if only_once == 2 and not(combat_is_initialized) then begin
         only_once := 1;
         call set_door_flag(true);
      end   
   end

end

procedure set_door_flag(variable state) begin
   
   variable objectMap, obj, objPid;
   
   objectMap := list_as_array(LIST_SCENERY);
   foreach (obj in objectMap) begin   
      objPid := obj_pid(obj);
      if (proto_data(objPid, sc_type) != PORTAL) then
         continue;
      
      // set flag only if walkThru flag is initially set in prototype
      //if (get_proto_data(objPid, DOOR_FLAGS) == 4) then begin
         display_msg("objPid: " + objPid + " : " + state);
         if state then 
            set_proto_data(objPid, DOOR_FLAGS, FLAG_WALKTHRU);
         else
            set_proto_data(objPid, DOOR_FLAGS, 0);
      //end   
   end

end
```

**Comment by Lexx2k** [comment]
Alright, I'm impressed. :>
Only one issue: Script doesn't work anymore on map change. You have to save & load to get it recognize doors again.

**Comment by FakelsHub** [comment]
> on map change
when you enter on other a map?
Add the procedure map_enter_p_proc from which will be called set_door_flag (true)

**Comment by Lexx2k** [comment]
Yeah, works now. Awesome.

**Comment by FakelsHub** [comment]
Updated and optimized script.

@phobos2077
Знаешь чего не хватает в хуке HOOK_COMBATTURN?
Чтобы хук тоже срабатывал когда игрок заканчивал бой израсходовав свои очки, со значением -1 для аргумента (ну или -2 смотри сам).

**Comment by burner1024** [comment]
oh yes baby, I tested it - awesome! Stolen to fo2tweaks.
