### ISSUE TITLE
set_swiftlearner_mod

### ISSUE THREAD

**Issue by nirran** [phobos2077/sfall#194]
please alter this functon to be exact for the amnt of xp increased

**Comment by NovaRain** [comment]
set_swiftlearner_mod sets the "divisor" in the calculation. set_swiftlearner_mod(5) will double the xp the player received with lv1 of Swift Learner (bonus = xp * 5 / **5**). And there's already a DisplaySwiftLearnerExp in 4.1 to display xp with the bonus when gained from non-scripted situations
 (xp from skill usages, noticing random encounters, etc.).

**Comment by nirran** [comment]
using it as percentage,thxn ill mess with it,related note,the floor function errors in my swiftlearner script,it changes 5.000000 to 4

**Comment by nirran** [comment]
can close this,thxn for info

**Comment by nirran** [comment]
actualy was hoping the percentage could be exact such as : set_swiftlearner_mod(5) would be a dirrect 5% bonus

**Comment by NovaRain** [comment]
And potentially break the behavior of any old script using it? Unless you're sure you are the only one ever using the function.

**Comment by nirran** [comment]
good point,it works as is anyway

**Comment by nirran** [comment]
tho i prolly am the only one that has used this finction
