### ISSUE TITLE
Some docs on fs_* functions?

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#196]
Read/write/copy are clear enough, but I can't quite make out what the following do (and what do they return in case of an error):
* fs_find
* fs_pos
* fs_seek
* fs_resize

Also, the docs mentioned virtual filesystem, and that files are saved to savegames. Where do they reside until save? In memory?

My use case is that I want to do some in-memory patching, but the files are large enough (a few MB total), so I don't want to save them. I'm thinking about doing fs_copy/write on game load and fs_delete on game save. Will that work at all?
And if it will, is that a viable approach, performance and... common sense wise?

**Comment by FakelsHub** [comment]
хрень полная)

**Comment by FakelsHub** [comment]
QUOTE (Fakeman)
чего такого прикольного в UseFileSystemOverride
Crafty
Виртуальная файловая система, позволяет создавать копию файла и изменять её под свои требования. Движок при обращении к файлу будет получать данные этой копии, но изменять её не сможет — все изменения возможны только скриптово.
Из-за недоделанности некоторые вещи невозможны — нельзя использовать файлы, которые сохраняются в сейвах, к примеру, сделать копию pro'шника сопартийца, заморозив рост его уровней и прокачивая его самому.
По идее можно менять графику (добавив свой штрих в виде подписи) и тому подобное. Практического применения (если сравнивать с усилиями для создания физ.копии и виртуальной) придумать не могу, а потому странно-прикольная штука.
[Здесь ](http://www.nma-fallout.com/threads/fo2-engine-tweaks-sfall.178390/page-67#post-3736926) есть кривоватый пример практического использования.

**Comment by FakelsHub** [comment]
_Crafty_
Неудачный, кстати, пример. В данном случае нельзя будет сделать виртуальную копию базового pro'шника, но прокачивать с помощью виртуальных копий уровней можно. Вот для примера использование виртуальной копии pro'шника для Сулика — при получении первого уровня он получит +1 к оригинальному для первого уровня значению силы , gl_Sulik.ssl:
```
procedure start;

procedure start
begin
 variable file,str;
 if game_loaded and fs_find("proto\\CRITTERS\\00000310.pro")==-1 then begin
  file:=fs_copy("proto\\CRITTERS\\00000310.pro","proto\\CRITTERS\\00000310.pro");
  fs_seek(file,0x30);
  str:=fs_read_int(file);
  fs_seek(file,0x30);
  fs_write_int(file,str+1);
 end
end
```

**Comment by FakelsHub** [comment]
Изучай)

**Comment by FakelsHub** [comment]
на Crafty пробовал? в оригинальном старом коде как всегда может быть что-то сломано.

**Comment by NovaRain** [comment]
Yep, the script works in Crafty's.

**Comment by burner1024** [comment]
Isn't it supposed to always print 18? Seems that no version gets it right?

**Comment by NovaRain** [comment]
Honestly I don't know, but at least your script work in Crafty's (his newer all-ASM builds, not open-source ones). I tried to refactor all op_fs_* functions to sf_fs_*, now my test script always prints 18, but your script still doesn't work (NPCs stopped).

**Comment by burner1024** [comment]
Well, anyway, this counts as a bug report then, yes?

**Comment by NovaRain** [comment]
I tried various sfall versions as old as 2.13 (the last one mentioned about fixing virtual file system) with Timeslip's color palette script and your test script (reduced version without array, only change nmfatt) on unofficial patch. Both of them didn't work properly (no color switch and Vic stops when trying to run), and at least the fs_write_* or saving to sfallfs.sav part is broken, as the fps offset in the fs file remains unchanged. So it looks like the whole thing never works as intended. For some reason the color palette works but in an unwanted way in 3.2~3.4: it only takes effect after entering the game then exiting to the main menu, only the background of main menu changed.

Because I don't have the skill for fixing this, I'll put it in a "known issue" note in the readme in next release if no one else plans to look into it.

**Comment by FakelsHub** [comment]
> I only seem to manage to fix part of fs_* functions by refactoring them

Has anything changed after refactoring?
when I test: 0, 18, 18, 18 ... (w/o your refactoring)

**Comment by FakelsHub** [comment]
This garbage does not work even on the latest version of Crafty.
I tend to the version that it should be removed from sfall))

**Comment by NovaRain** [comment]
> 
> 
> This garbage does not work even on the latest version of Crafty.
> I tend to the version that it should be removed from sfall))

It's also broken in his latest build? So much for the 'virtual file system'.
Personally I'm perfectly fine seeing it gets removed from sfall, since the whole thing was never working well from the beginning.

**Comment by FakelsHub** [comment]
Only this does not affect the running speed if you change the FPS. (also on Crafty)

**Comment by NovaRain** [comment]
> 
> 
> > Honestly I don't really know. I was just trying to refactor them to see if result would be different.
> 
> It seems that after refactoring it began to work, checked on 8.3.13 / 4.1.3
> always prints 18, like Crafty
> Did you make corrections in 8.3?

Other than refactoring the script functions, no I didn't do anything else in 3.8.

**Comment by NovaRain** [comment]
The fs_* functions themselves seem OK. I think the main cause should be somewhere in loading and applying data from sfallfs.sav.

**Comment by FakelsHub** [comment]
Everything is good there with loading and applying, it's just a useless toy that is not completely realized.
In fact, now it performs its functions, ie creation of virtual files, but the redefinition of game files (the UseFileSystemOverride option) is not implemented.

**Comment by FakelsHub** [comment]
> with Timeslip's color palette script

Where to get this script?

**Comment by NovaRain** [comment]
> 
> 
> > with Timeslip's color palette script
> 
> Where to get this script?

From her old post in the sfall thread:
http://www.nma-fallout.com/threads/fo2-engine-tweaks-sfall.178390/page-67#post-3736926

**Comment by FakelsHub** [comment]
> Maybe it doesn't get pruned. Need to try on another file type, like pro, for which we know when it's reloaded.

C прототипами работает, но в том случае если физический файл не был загружен в память до создания виртуальной его копии.
