### ISSUE TITLE
Global scripts really require start procedure?

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#197]
Docs state "To use a global script, the script must have a name which begins with 'gl' and contains a procedure called 'start'."
But [this small script](https://github.com/BGforgeNet/fo2tweaks/blob/master/fo2tweaks/components/level5_temple/gl_g_level5.ssl) seems to be working fine without it. Or am I missing something?

**Comment by FakelsHub** [comment]
map_enter_p_proc тоже работают в глобалке, и вроде только в скриптах которые на локальных картах работают.

**Comment by NovaRain** [comment]
No it's not really required. I'll update the document to mention map_enter_p_proc/map_exit_p_proc.

**Comment by phobos2077** [comment]
Initially only start function worked with global scripts. I've added other functions later.

**Comment by FakelsHub** [comment]
None: gl* scripts of types 0 and 3 and all hs* scripts
