### ISSUE TITLE
get/set_proto_data work on which protos?

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#198]
(removed some nonsense about overlapping)

Trying to set weapon perk/range, log reports correct values, but no change in-game (4.1.0):
```
#include "..\headers\sfall\define_extra.h"
#include "..\headers\fo2tweaks\fo2tweaks.h"
procedure start;


procedure start begin
  if game_loaded then begin
    variable key, pid, pids, range, perk, ap;
    debug_msg("gl_g_no_scope_penalty: initialized");

    //vanilla scoped rifle
//    pids := sfall_func2("get_ini_section", ini_file, sec_remove_scope);
//    foreach key: pid in pids begin
      pid := PID_SCOPED_HUNTING_RIFLE;
      set_proto_data(pid, PROTO_WP_RANGE_1, 5);
      set_proto_data(pid, PROTO_WP_RANGE_2, 5);
      set_proto_data(pid, PROTO_WP_PERK, 0); //remove scope range
      set_proto_data(pid, PROTO_WP_APCOST_1, 2);
      range := get_proto_data(pid, PROTO_WP_RANGE_1);
      ap := get_proto_data(pid, PROTO_WP_APCOST_1);
      debug_msg("gl_g_no_scope_penalty: pid is " + pid + " range is " + range + "apcost is " + ap);
      debug_msg("gl_g_no_scope_penalty: removed scope range from pid " + pid);
    debug_msg("gl_g_no_scope_penalty: completed");
  end
end

```

**Comment by FakelsHub** [comment]
Для начало нужно убедиться что значения смещений PROTO_WP_RANGE_1 и д.р. правильны, для этого перед изменением проверяем(считываем) оригинальное значение если значение совпадает то смещение верно. Не первый раз у меня было, что смещения были некорректные.
И вроде как нужно каждый раз это дело применять к прошкам при заходе на карту, иначе после выхода измененные значения стираются

**Comment by NovaRain** [comment]
Or setting the script run repeatedly. I added set_global_script_repeat(60) and your script works as it should.

**Comment by burner1024** [comment]
oh... ok, are the events on which proto get reloaded documented anywhere? Setting it to repeat seems excessive, but just map_enter_p_proc doesn't seem to cut it.

**Comment by NovaRain** [comment]
>Setting it to repeat seems excessive, but just map_enter_p_proc doesn't seem to cut it.

You can put the code in a custom procedure and call it in start and map_enter_p_proc.
```
procedure set_rifle begin
   variable key, pid, pids, range, perk, ap;
   debug_msg("gl_g_no_scope_penalty: initialized");
   ...
end

procedure start begin
   if game_loaded then call set_rifle;
end

procedure map_enter_p_proc begin
   call set_rifle;
end
```

>Also, it seems that ```set_proto_data(pid, PROTO_WP_APCOST_1, X);`` actually sets it to (X-1)?

Nope. Your script works fine for me, as the scoped hunting rifle costs 2 AP to fire. Are you sure you don't have Fast Shot trait or Bonus Rate of Fire perk?

**Comment by burner1024** [comment]
> You can put the code in a custom procedure and call it in start and map_enter_p_proc.
Sure, but the question is - will that be enough? Or protos may get reloaded elsewhere?
> Are you sure you don't have Fast Shot trait or Bonus Rate of Fire perk?
Right, it's the perk. My bad.

**Comment by NovaRain** [comment]
I think that should be enough. I tried starting a new game, loading a save, moving to different maps/towns, and using load_map script function to move myself to another map. The proto setting script is called in all cases.

**Comment by burner1024** [comment]
I see. I was hoping it's documented somewhere.
The behaviour seems be not straightforward:
- if I load game, enter combat right away, and shoot, it still takes takes original AP to shoot (although interface shows modified AP, apparently it needs to be redrawn)
- but if I load, travel, then enter combat and shoot, it uses proper modified AP

I can hook into gamemodechange in this use case, of course. But it would be useful to know when the game actually re-reads the files, otherwise get/set functions are kind of gamble.

**Comment by NovaRain** [comment]
>if I load game, enter combat right away, and shoot, it still takes takes original AP to shoot (although interface shows modified AP, apparently it needs to be redrawn)

I've tried what you did. The interface shows 5 AP, but the rifle takes 2 AP to shoot. Adding a intface_redraw() at the end of set_rifle procedure helps. And if you really care about the reaction time, using the traditional method of an modified proto would be better.

**Comment by burner1024** [comment]
damn... 3 hours loading various savegames, one weapon working, another wouldn't, then in reverse... to find out in the end that it's caused by EcCo's [barterprice](https://github.com/phobos2077/ecco_ssl/blob/master/_pbs_main/hs_barterprice.ssl)?
Last time I was this close to insanity is when inventory filter would make dude resistances go negative.

**Comment by NovaRain** [comment]
Your rifle script works if you use set_global_script_repeat. That's why I usually set my proto altering scripts running repeatedly.

**Comment by burner1024** [comment]
I understand that setting it to repeat will make it work _somewhat_.
And that static proto files will work faster anyway. But scripts are (supposed to be) more compatible, and can actually be version controlled, so I'm willing to sacrifice a bit of performance, as long as it's reasonable.

Something fishy is going on here. Could it be a race condition with set_proto_data?

**Comment by NovaRain** [comment]
He did say he needs to remove proto altering from the script.

**Comment by FakelsHub** [comment]
> I remember reading somewhere that global scripts are executed alphabetically,

Да.

**Comment by phobos2077** [comment]
Там берутся все скрипты по маске gl*.int в папке Scripts при помощи функции: db_get_file_list. По идее в алфавитном порядке. Насчет конфликта с hs_barterprice посмотрел - странно, по идее никакого конфликта быть не должно. Если я правильно помню как работает set_proto_data, у меня меняется только цена предметов, причем происходит это только в момент перехода на экран бартера. Не знаю откуда может быть конфликт при загрузке.

**Comment by FakelsHub** [comment]
> Здесь происходит что-то рыбное. Это может быть состояние гонки с set_proto_data?

Что?))
Напишите на русском какой конфликт а то я ваш английский не понимаю.

**Comment by FakelsHub** [comment]
> Если я правильно помню как работает set_proto_data, у меня меняется только цена предметов, причем происходит это только в момент перехода на экран бартера. Не знаю откуда может быть конфликт при загрузке.

В последней переработки barterprice появилась возможность устанавливать/рассчитывать цену продажи не посредственно через хук, не используя прото.

**Comment by burner1024** [comment]
Ну состояние гонки это [оно и есть](https://ru.wikipedia.org/wiki/%D0%A1%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D0%B5_%D0%B3%D0%BE%D0%BD%D0%BA%D0%B8).
Хотя я в коде не вижу, откуда оно может взяться, но других вариантов почему поведение такое странное у меня тоже нет.

**Comment by FakelsHub** [comment]
Какое такое поведение, описать можешь что за ошибка?
Ну здесь не многопоточное выполнение термин гонки тут не уместен.

**Comment by NovaRain** [comment]
The barter price for the scoped hunting rifle is also changed, so I'm not sure if I broke anything.

**Comment by FakelsHub** [comment]
Я кажется понимаю в чем проблема, при выполнении remember_item_prices в ессо, возможно что при чтении всех прототипов get_proto_data ранее изменненные твоим скриптом про из памяти выгружаются и заменяются, аля типа нехватки памяти. 
Нужно закомментировать эту процедуру и проверить мою теорию.

**Comment by burner1024** [comment]
Вроде работает если закомментировать.
Ошибка тогда в get_proto_data, получается?

**Comment by FakelsHub** [comment]
Нет, так работает движковая функция, она не предназначена для изменения данных про в памяти, она только эти данные загружает в память, а изменение proto_data в пaмяти это уже костыль sfall.

**Comment by FakelsHub** [comment]
Алгоритм такой: в память может быть загружено не больше 512 прошек, если загружается больше то из памяти выгружается 16 прошек (какие именно не выяснял), и вместо них загружаются следующие 16. При выгрузке в дебаг логе печатается символ '^'

**Comment by NovaRain** [comment]
Increasing the 512 limit in proto\_ptr\_ seems to work. I tried using both EcCo's barterprice and the non-repeating version of rifle proto setting script with a new 2048 limit, and the rifle got changed correctly after loading a save. Just don't know if it's a good enough solution.

**Comment by NovaRain** [comment]
>The new limit?

I just increased the value at 0x4A21B3 to 1024/2048.

**Comment by FakelsHub** [comment]
I think this is not the right decision, you can erase something extra in memory, since there should be a place in the memory for the new 512/1536 protos.
We still need to allocate memory. :)

**Comment by burner1024** [comment]
Seems to work correct.

**Comment by NovaRain** [comment]
Thanks for testing. Currently the option is a variable setting with valid range 512 (def/min) ~ 10240. I was thinking if it should be a simple toggle with a reasonably higher preset value (2048/4096/10k/etc.) like BoostScriptDialogLimit or MoreTiles, or keep it variable.

**Comment by NovaRain** [comment]
>Is there any downside to having it maxed?

Other than possible increase of memory usage, there shouldn't be any problem if what Mr.Stalin said about auto memory allocation is correct.

>Maybe drop a line into debug log when protos start to unload, so that wouldn't be so mysterious?

So you want to replace the "^" symbol with some "Unloading protos" line?

**Comment by burner1024** [comment]
I checked RP, Nevada - both have about 8-10k protos, so probably 20k should be safe enough.

**Comment by NovaRain** [comment]
>I checked RP, Nevada - both have about 8-10k protos, so probably 20k should be safe enough.

Is there any need to batch process that many protos in one go?

**Comment by FakelsHub** [comment]
512 это не общий лимит, а ограничения для каждого типа прототипов, соответсвенно 512 умножается На количество типов, это и будет общее количество.

**Comment by burner1024** [comment]
> Is there any need to batch process that many protos in one go?

Don't know, just making observations.
But, as far as I understand, the limit isn't per one go, it's just total per type for all mods?

**Comment by NovaRain** [comment]
Mr.Stalin wrote a new implementation that will automatically increase the limit by 256 each time the limit is reached, until 4096. It works quite well without the need to change the option (it will be still in the INI in case someone really needs a higher limit at start).

**Comment by burner1024** [comment]
Cool.
