### ISSUE TITLE
Serious freezes when companions are lagging behind

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#199]
If I get a companion to lag by approximately half screen, especially in city environment, a building, game starts freezing.
Log:
```
Gsound: playing ambient map sfx: brdchir1^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^Loading sound file SODOORSA.ACM...succeeded.
^Loading sound file monitor.ACM...succeeded.
^Loading sound file SODOORSC.ACM...succeeded.
Loading sound file monitor.ACM...succeeded.
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^Loading sound file blank.ACM...succeeded.

Gsound: playing ambient map sfx: blank^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^Loading sound file brdchirp.ACM...succeeded.

Gsound: playing ambient map sfx: brdchirp^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^Loading sound file ib1p1xx1.ACM...succeeded.
```
"^"s seem to correspond to freezes.
I tried min/maxing NumPathNodes in f2_res.ini, made no difference.
Tested on 4.1.0 and 3.3.1 (last RP's default).

**Comment by NovaRain** [comment]
I tried it in the Virgin Street in New Reno, but the game still run normally, and there's no "^" in my debug.log. I played the game in the windowed mode (size 1024x768) with Direct Draw 7 + 16bit color + NumPathNodes=2 settings. What OS do you test the game with?

**Comment by burner1024** [comment]
Ubuntu/wine, emulating win 7, dx9 mode fullscreen. Heres 'a [video](https://www.useloom.com/share/1fddbcf4db5040e6963aeba915042004). You can see first freeze at 0:10 when Vic decides to run inside the building. Then at 0:18 he decides to run outside, freeze again. Freeze fest at 0:40-0:60, more later. Finally, a test run around the building without companions, to compare.

Это все тестировалось без глобальных скриптов и хуков.

**Comment by FakelsHub** [comment]
_что-то ссылка на видео не работает._

**Comment by NovaRain** [comment]
Have you tried disabling sfall DX9 mode or using HRP's DX9? I don't use Linux/wine, so I can't say much about running the game with sfall in emulated environments.

**Comment by NovaRain** [comment]
Maybe it's wine version related? I remember you and some other people discussed about running RP in wine on NMA.

**Comment by FakelsHub** [comment]
> Сайт открывается?
нет конечно.

**Comment by burner1024** [comment]
_Ты в России? Пробей по [blockcheck](https://github.com/ValdikSS/blockcheck)_.

**Comment by burner1024** [comment]
Appears to be related to #198 somehow then? Can't really reproduce it by now with 4.1.1. I guess it can be closed.
