### ISSUE TITLE
Instant weapon equip/switch

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#20]
Instant weapon equip/switch - to disable the annoying animation delay when searching containers and doing other stuff. This is nagging me since ever. And I'm quite sure it's not only me.

In fact, some time ago I tried to circumvent this by deleting the corresponding animation frames, but it didn't work out for some reason.

**Comment by phobos2077** [comment]
This might be possible by changing action frame number (it's in a fixed position inside FRMs) to 0 or 1 in all related FRMs. Should be pretty straightforward resource patching, once you understand which FRM names you need to change.

**Comment by burner1024** [comment]
I might be doing something wrong, but seems to have zero effect:
![tribal_spear zip](https://cloud.githubusercontent.com/assets/1279852/11020757/627e12b6-865c-11e5-8806-92f86fb4766e.png)
(Attached is a zip archive, but github won't allow to post that file extension, so I'm posting it as zip.png)

**Comment by NovaRain** [comment]
I've implemented the InstantWeaponEquip setting from Crafty's code. It will be available in the next version.

**Comment by burner1024** [comment]
Awesome!
