### ISSUE TITLE
get/set_sfall_global variable name length

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#201]
I've been bitten by this a couple of times. Since they must be exactly 8 characters long, maybe it's worth to make the compiler spit an error when it's not so?

**Comment by phobos2077** [comment]
I think this should be a run-time error. You can't know the length of a string at compile time unless it is a constant. So you'll need a run-time error either way. Changing compiler is not strictly necessary.

**Comment by burner1024** [comment]
But variable name is constant?

**Comment by FakelsHub** [comment]
Переменая может сожержать имя для глобальной переменной.
Можно использовать номера вместо имени, хотя это не так уникально будет.

**Comment by burner1024** [comment]
Но я говорю не про значение, а про имя. Какая разница, что она содержит?

**Comment by FakelsHub** [comment]
Ну в принципе ты 100% прав, компилятор должен выдать ошибку в случае константного имени.

**Comment by phobos2077** [comment]
@FakelsHub как я уже сказал, проверка в рантайме точно нужна. А проверка констант компилятором лишь дополнительная фича. Полезна но совершенно не обязательна.

**Comment by NovaRain** [comment]
Now sfall 4.1.5/3.8.15 print errors to debug output for get/set_sfall_global during runtime if the name of sfall global variable is not 8 characters long. I'd consider this issue solved.

**Comment by burner1024** [comment]
I agree.
