### ISSUE TITLE
set_critter_skill_points 

### ISSUE THREAD

**Issue by nirran** [phobos2077/sfall#202]
please alter this function to allow for negative values,as is it cannot subtract from dudes skills

**Comment by NovaRain** [comment]
get/set_critter_skill_point manipulate this field:
![Imgur](https://i.imgur.com/eNKx5Vi.png)
Values in this field only work normally if they are zero or positive integers. If you edit your own character with F12se and set one of the values to negative number like -10, the skill level will be exactly the same as the negative number (i.e. -10%). So it's not that the functions can't handle negative values, as you can use ```set_critter_skill_points(dude_obj, 0, -10);``` then
```display_msg("Skill points: " + get_critter_skill_points(dude_obj, 0));``` to get the output of "Skill points: -10". It's the engine requires to be changed on how it calculates skills with values from this field.

**Comment by nirran** [comment]
yea im able to add to dudes current small guns etc,but cannot subtract,im trying to make a 'Gifted' perk with the same penalties,and it wont allow for subtraction,assuming these are the 2 functions 'critter_mod_skill' and 'set_critter_skill_points'

can it be done with get/set proto?i did a 500 entry loop and nothing seemed to be the skills

**Comment by burner1024** [comment]
I think there's set_skill_max for that.

**Comment by nirran** [comment]
as it only has one arg,if it was setting skill total,it would have alt least 2 arg,one for value and one for what skill

**Comment by FakelsHub** [comment]
Не пойму, что вы тут за проблему решить не можете?

**Comment by nirran** [comment]
> 
> 
> Не пойму, что вы тут за проблему решить не можете?

im sorry i dont speak russian

**Comment by burner1024** [comment]
да он хочет переделать gifted с нуля и не может пенальти скиллам назначить.

**Comment by nirran** [comment]
to be thorough,i checked setting set_base_skill_mod and started a game,it set all skills negative,instead of subtracting from one skill

**Comment by burner1024** [comment]
how about something like this?
```
penalty := 20;
if critter_skill_level(who, skill) - penalty >= 0 then mod := 0-penalty;
else mod := critter_skill_level(who, skill) - penalty;
set_critter_skill_points(who, skill, mod);
```

**Comment by nirran** [comment]
this code set it to -20,and w/o altering it was 27(small guns)

`	  penalty := 20;
	  if critter_skill_level(dude_obj, 0) - penalty >= 0 then mod := 0-penalty;
      else mod := critter_skill_level(dude_obj, 0) - penalty;
      set_critter_skill_points(dude_obj, 0, mod);`

**Comment by FakelsHub** [comment]
вы че тут оба прикалываетесь?
clevel := get_critter_skill_points(dude_obj, 0);
clevel -= penalty;
if clevel < 0 then clevel  := 0;
set_critter_skill_points(dude_obj, 0, clevel);

**Comment by nirran** [comment]
`   if (game_loaded) then begin
      set_global_script_repeat(0);
	  //display_msg(critter_skill_level(dude_obj, 0));
	  penalty := 20;
	  if critter_skill_level(dude_obj, 0) - penalty >= 0 then mod := 0-penalty;
      else mod := critter_skill_level(dude_obj, 0) - penalty;
      set_critter_skill_points(dude_obj, 0, mod);
	  //display_msg(critter_skill_level(dude_obj, 0));`

**Comment by FakelsHub** [comment]
Indeed, `set_critter_skill_points` works strangely
for negative values sets the skill to negative values
for positive values it increases skill (work as the vanilla function `critter_mod_skill`)

`get_critter_skill_points` - broken function?!

**Comment by NovaRain** [comment]
The bug is how the engine handles negative skill points, as using F12se to change the skill resulted in the same situation.

**Comment by FakelsHub** [comment]
there are no problems with negative values.
27 - 20 = 7 the function was to set the skill value to 7, not to do the operation of adding +7 to the skill

**Comment by NovaRain** [comment]
>there are no problems with negative values.

I mean the negative values in the "raw value" field for skills (picture above), setting -1 for a skill and that skill will be "-1%" in the game.

**Comment by FakelsHub** [comment]
After fix the function `critter_mod_skill` it can subtract.

**Comment by FakelsHub** [comment]
> instead of the supposed (base skill - 1)%

I understand it requires that the engine display negative values?

**Comment by NovaRain** [comment]
> 
> 
> > instead of the supposed (base skill - 1)%
> 
> I understand, need to fix what would the engine display negative values?

I think the engine can already display negative skill values in the character screen. The case in this issue is like this:
1. An all-10 character has Sneak 35% (not tagged) at the start, with 0 point in the skill (raw value) field displayed in F12se above.
2. Assigning skill points to Sneak will increase the value of this "raw value" field, and get/set_critter_skill_points functions also manipulate this field.
3. If I lower player's Sneak skill with vanilla critter_mod_skill function (now fixed for negative values), the lowest I can get is 35% with 0 point in the raw value field.
4. If I use ```set_critter_skill_points(dude_obj, SKILL_SNEAK, -5)``` to try to lower player's Sneak to 30% at the start (setting the raw value field of the skill to -5), the result won't be "Sneak 30%" but "Sneak -5%" in the character screen.

**Comment by FakelsHub** [comment]
I think I understand what needs to be done/fix  :)

**Comment by FakelsHub** [comment]
I think I understand what needs to be done/fix  :)

**Comment by FakelsHub** [comment]
skill_level_ func.
```
result = skill_points_(source, skill);
skillPoints = result;
if ( result >= 0 )
```
Thus, negative values are simply output without calculation, since there is a problem when multiplying negative values.
I have only one idea, it is just to do the subtraction after the engine does the calculation for the zero value.

**Comment by NovaRain** [comment]
> I have only one idea, it is just to do the subtraction after the engine does the calculation for the zero skill value.

like adding ```if (skillPoints < 0) skill += skillPoints;``` (do it twice if skill is tagged?)
near the end of skill_level_ func before ```if (skill > 300) skill = 300; result = skill;```?

**Comment by FakelsHub** [comment]
Vanilla `critter_mod_skill` function can't reduce the base skill points less than zero.
In such cases, you need to use a bunch
```
baseLevel := get_critter_skill_points(dude_obj, 0);
baseLevel -= penalty;
set_critter_skill_points(dude_obj, 0, baseLevel);
```

**Comment by NovaRain** [comment]
>Vanilla `critter_mod_skill` function can't reduce the **base** skill points less than zero. ( Maybe this, too need to be fix? )

I don't think so. There are sfall functions can already do pretty much the same.

**Comment by FakelsHub** [comment]
They work differently and do not take into account the skill tag.

**Comment by FakelsHub** [comment]
for vanilla func, if the base value is 5 and we decrease the skill by 15, it will decrease only by 5, and the value 10 will be lost.

**Comment by NovaRain** [comment]
There's some kind of range clamping for it, like some other vanilla script functions.

**Comment by FakelsHub** [comment]
in such things, clamping is not appropriate, because then you have to take care of restoring 5 instead of 15

**Comment by nirran** [comment]
this request dead?

**Comment by NovaRain** [comment]
> 
> 
> this request dead?

It's completed so I closed it.

**Comment by nirran** [comment]
awesome !~ ty
