### ISSUE TITLE
StartGDialogFix causes game crash at some NPC dialog.

### ISSUE THREAD

**Issue by NovaRain** [phobos2077/sfall#203]
Enabling the option will crash the game when some NPCs try to start dialog, like the first encounter with Kaga, and Petey the drug addict and Little Bobby in the Den, with error message:
```
The instruction at 0261bef7 referenced memory at 00000064
The memory could not be read from
```
But Chris in Navarro doesn't cause the crash, it seems it's because he uses dialogue_system_enter instead of normal start_gdialog.

**Comment by FakelsHub** [comment]
Do you have a save game in DEN?
My tests with the start_gdialog function don't cause any failures.

**Comment by FakelsHub** [comment]
0261bef7  this pointer to npc
00000064 this pointer to pid

**Comment by NovaRain** [comment]
I tested with a save before leaving Arroyo (for the first encounter with Kaga) and a save before leaving Klamath (for the two NPCs in the Den):
http://www.mediafire.com/file/tw549p5h4n5rpow/rp233_testsaves.rar/file

**Comment by FakelsHub** [comment]
RP script make a 'start_gdialog' call not in the talk_p_proc procedure, which is an error.

**Comment by NovaRain** [comment]
but Little Bobby (DCLILBBY) does call start_gdialog in the talk_p_proc, or calling talk_p_proc in other procedures doesn't count?
