### ISSUE TITLE
What are "special effect flags" in hs_combatdamage?

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#204]
Can't find any info on this.

Reason is, I'm looking to alternate damage formula - script from scratch, that is, rather than apply tweaks. And it seems there's not enough information. Specifically, critical hits. There's damage multiplier available, but that still doesn't allow to determine whether the crit is armor bypassing or not, because there are entries in critical hit tables which share the multiplier, but not bypass flag.

**Comment by NovaRain** [comment]
They're DAM_* in defines.h of official script.

**Comment by burner1024** [comment]
Oh, that's where it is. Great, thank you. Probably worth mentioning in docs?
