### ISSUE TITLE
PatchFile can only take numbered multiple patches?

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#206]
Following [this post](http://nma-fallout.com/threads/fo2-engine-tweaks-sfall.178390/page-114#post-4041149), I presumed that it's possible to load multiple mods from multiple PatchFiles (directories, actually), but apparently it's not? Only the first mod gets loaded.
```
;To use a patch file other than patch000.dat, uncomment the next line and add your new file name
;If you want to check for multiple patch files, you can include a %d in the file name (sprintf syntax)
;By default, only the first patch file found will be used.
;If you want to load multiple patch files (up to 1000) at once, uncomment the MultiPatches line and set it to 1
PatchFile=mods/fo2tweaks
PatchFile=mods/original_ammo
PatchFile=DoNotUseAPatchFile.dat
MultiPatches=1

;Set to 1 to enable the modified data load order for the engine to find game data
;Original: patchXXX.dat > critter_patches > critter_dat > f2_res_patches > f2_res_dat > master_patches > master_dat
;Modified: master_patches > critter_patches > patchXXX.dat > critter_dat > f2_res_patches > f2_res_dat > master_dat
DataLoadOrderPatch=1
```

**Comment by NovaRain** [comment]
It can only take one PatchFile setting. If you want to load multiple patches, you need to pack them in numbered .dat files.

**Comment by burner1024** [comment]
I see. Any plans for improvement in this direction?
Lately I'm kind of trying to work out a guideline for mod compatibility, so that mods can be pluggable and each mod would keep its stuff separate. But having just numbers to distinguish between them makes that not very manageable.

**Comment by FakelsHub** [comment]
Нужно будет подумать.

**Comment by burner1024** [comment]
Это бы позволило моды включать/выключать на лету, и не устраивать помойку в файлах игры, а держать каждый мод отдельно. Обновление легче и все такое.
Еще я попробовал подгрузить ini файл из поддиректории, что-то не хочет.

**Comment by FakelsHub** [comment]
Can probably add additional options such as `PatchFile#=folder_path` or `PatchFolder#`
```
PatchFile0=
...
PatchFile#=
```

**Comment by burner1024** [comment]
Is there a poing in numbering them manually rather than just allowing to use PatchFile multiple times?

**Comment by FakelsHub** [comment]
Так нельзя.

**Comment by burner1024** [comment]
Непонятно почему, но раз уж ты так говоришь...

**Comment by FakelsHub** [comment]
Что непонятного,  это строки вида ключ=значение

**Comment by burner1024** [comment]
А какая разница? Четкой спецификации у ини формата нет, в некоторых имплементациях одинаковые ключи вполне себе позволены.

Хотя, возможно, явный порядок подгрузки по номерам вместо неявного по порядку позволит избежать лишней путаницы.

**Comment by FakelsHub** [comment]
В стандартном winapi такого нет.

**Comment by FakelsHub** [comment]
I will also put this in a separate section. 
```
[ExtraPatches]
PatchFile0=folder or name.dat
...
PatchFile99=
```

**Comment by NovaRain** [comment]
@burner1024 
Here's the build from the latest commit with ExtraPatches support if you want to try if the option suits your need: https://www.mediafire.com/file/as5dmlna5lt14oa/sfall416pre_20190306.rar/file

You need to add a new [ExtraPatches] section in the ddraw.ini, with PatchFile# (0~99) line like this:
```
[ExtraPatches]
PatchFile0=mods\super_zipgun
PatchFile1=newak_frms.dat
...
```
Their priority is higher than patchXXX.dat (or the numbered patch files specified with PatchFile= in [Misc]), and higher number line also has higher priority.

**Comment by burner1024** [comment]
Great, will try.
0-99 seems like a narrow range, but I guess it'd be easy to change should the need arise.

**Comment by FakelsHub** [comment]
Может нужно изменить приоритет? Сделать 99 самым низким.

**Comment by NovaRain** [comment]
> 
> 
> Может нужно изменить приоритет? Сделать 99 самым низким.

I think it's better to keep it the same as ordinary patch files.

**Comment by burner1024** [comment]
Я думаю система должна быть такой же, как и в оригинальных patchXXX.dat, чтобы лишней путаницы не было. А там вроде чем выше номер, тем выше приоритет, так?

**Comment by NovaRain** [comment]
Yes, PatchFiles99 has the highest priority among the PatchFiles# lines.

**Comment by burner1024** [comment]
Works, accroding to my testing.

**Comment by FakelsHub** [comment]
I think that need to be use without numbered options.
There is a ready-made small parser for ini https://github.com/mcmtroffaes/inipp
Can modify it for our needs and use it for this.

**Comment by burner1024** [comment]
you mean like I initially suggested?

**Comment by FakelsHub** [comment]
Да. Незнаю стоит ли это делать.
Либо просто подключать используя промежутки в диапазоне, допустим через каждые 5,  чтобы можно было втиснуть другой мод между двумя не передвигая уже существующие.
Как-то так.

**Comment by burner1024** [comment]
Это да, в этом смысле без номеров все-таки удобней.

**Comment by FakelsHub** [comment]
Наблюдается проблемы в игре (исчезает багажник, невозможно записать игру) когда отключена опция `DataLoadOrderPatch` и использутся папки вместо .dat файлов, игра начинает записывать информацию в первую папку. 
Подозреваю, что такое происходит когда вместо patch.dat используется папка. (проверить).
Предлагаю опцию `DataLoadOrderPatch` включить по дефолту.

**Comment by NovaRain** [comment]
Just setting DataLoadOrderPatch=1 by default or removing it from ini?
Do you mean when someone using `patchXXX.dat` file name as a folder name the issue would happen?

**Comment by FakelsHub** [comment]
1. set default
2. Yes

**Comment by NovaRain** [comment]
I'm OK with enabling it by default, since the vanilla load order is rather awkward.

**Comment by burner1024** [comment]
I think it'd be good too, allowing to drop shenanigans with re-packing .dat files.

**Comment by FakelsHub** [comment]
Added functionality that allows you to automatically loading any your .dat without having to specify it in the ddraw file.
For some reason, earlier, I did not think so to make such a decision.

**Comment by NovaRain** [comment]
> 
> 
> Added functionality that allows you to automatically loading any your .dat without having to specify it in the ddraw file.
> For some reason, earlier, I did not think so to make such a decision.

I still think there should be a list of some sort instead of blindly loading all .dat files under the game directory.

**Comment by FakelsHub** [comment]
dat files must be located in a specific folder.

**Comment by NovaRain** [comment]
> 
> 
> dat files must be located in a specific folder.

So people still need to specify a folder name in ddraw.ini like ExtraDatFolder=datmods?
And what's their load order? Alphabetical? Do .dat files in the special folder have higher load order than the list in [ExtraPatches] or between [ExtraPatches] and PatchFile?

**Comment by FakelsHub** [comment]
> so now the load order is

 yes

**Comment by NovaRain** [comment]
> 
> 
> > so now the load order is
> 
> yes
> `AutoSearchPath\aaa.dat > AutoSearchPath\zzz.dat`

I think the reverse alphabetical order is better, since other (PatchFile# and patchXXX.dat) are in reverse numerical order.

**Comment by FakelsHub** [comment]
it seems to me that it’s not convenient in reverse order, unlike numbering.
need to think.

**Comment by NovaRain** [comment]
> 
> 
> it seems to me that it’s not convenient in reverse order, unlike numbering.
> need to think.

I thought if a.dat is listed before b.dat, it would also be loaded first, and its content will be overrided by the content in b.dat (if the same file name). That makes b.dat have higher order than a.dat.

**Comment by burner1024** [comment]
On one hand, a pre-defined directory could be nice, on the other that could lead to cases of
```
zz_my_mod_is_the_bestest.dat
zzz_and_my_is_even_betterer.dat
```

**Comment by FakelsHub** [comment]
No need to addiing here numbering of PatchXXX 
If you rely on household items, for example, take such a thing as a quality class:
'A' is always higher than 'C', accordingly 'Z' is the lowest quality.
It is easier to operate than in the reverse order.

> On one hand, a pre-defined directory could be nice, on the other that could lead to cases of

What's wrong?

**Comment by FakelsHub** [comment]
Now
```
(lowest)
look > sfall.dat
look > mods\z.dat
look > mods\data10.dat
look > mods\data1.dat
look > mods\data0.dat
look > mods\a.dat
```
to
```
look > sfall.dat
look > mods\a.dat
look > mods\data0.dat
look > mods\data1.dat
look > mods\data10.dat
look > mods\z.dat
(highest)
```

It seems that with numbers it turns out a mess
OK, I will remove the reverse.

**Comment by FakelsHub** [comment]
Any other comments? change the folder. option name?

**Comment by NovaRain** [comment]
> ```
> look > sfall.dat
> look > mods\a.dat
> look > mods\data0.dat
> look > mods\data1.dat
> look > mods\data10.dat
> look > mods\z.dat
> (highest)
> ```
> 
> It seems that with numbers it turns out a mess
> OK, I will remove the reverse.

I think AutoSearchPath is good. What's wrong with the lower order?

**Comment by FakelsHub** [comment]
> What's wrong with the order in reverse?

In that the digital priority order is violated (highest) 0 > 1 > 10, and this is more important than A > Z. I did not immediately notice.
```
(lowest)
look > mods\z.dat
look > mods\data10.dat
look > mods\data1.dat
look > mods\data0.dat
look > mods\a.dat
(highest)
```

**Comment by NovaRain** [comment]
> 
> 
> > What's wrong with the order in reverse?
> 
> In that the numbering priority order is violated (highest) 0 > 1 > 10, and this is more important than A > Z.
> 
> ```
> (lowest)
> look > mods\z.dat
> look > mods\data10.dat
> look > mods\data1.dat
> look > mods\data0.dat
> look > mods\a.dat
> (highest)
> ```

But isn't the same for patchXXX.dat and PatchFileXX?
```
(lowest)
look > patch000.dat
look > patch001.dat
...
look > patch010.dat
(highest)
```
```
(lowest)
look > PatchFile0=mymod1.dat
look > PatchFile1=yourmod1.dat
...
look > PatchFile10=hismod1.dat
(highest)
```

**Comment by FakelsHub** [comment]
this w/o reverse
```
Found custom patches:
 > mods\adata11.dat
 > mods\data00.dat
 > mods\data01.dat
 > mods\data04.dat
 > mods\data10.dat
 > mods\z.dat
(highest)
```

**Comment by FakelsHub** [comment]
above log, w/o code `std::reverse(patchFiles.begin() + 1, patchFiles.end());`

**Comment by burner1024** [comment]
> What's wrong?

If instead of properly discussing and agreeing on mod load order, modders just start to compete in "my mod has the highest priority", what is your solution to that?
And if they do agree, it can be implemented with current PatchFile system, anyway.

Other questions:
1. So is the directory called `mods` or `datmods`?
2. Is it configurable or hardcoded?
3. Most importantly, does it it work with .dat files only, or does it support mod-in-directory, like PatchFile?

**Comment by NovaRain** [comment]
1. The default folder is `mods`.
2. Configurable with the new `AutoSearchPath=` option in [ExtraPatches] section.
3. .dat files only.

**Comment by FakelsHub** [comment]
3 .dat files only, and folder with .dat ext.

**Comment by burner1024** [comment]
Ok, so what about the first question?

**Comment by NovaRain** [comment]
TBH I'm not sure if it's really a question. It's not like there are tons of .dat mini mods floating around like .esp plugins for Bethesda games, or enough modders to compete "mod priority". People can always edit the load order by changing filenames or editing the PatchFileXX list if needed. The new AutoSearchPath just provides a simpler way to load several .dat files at the same time without the need of editing INI.

**Comment by burner1024** [comment]
Right. But it doesn't seem to be directed... is there an endgame? By that, I mean a _definitive mod packaging format_ for sfall. (Which is what I had in mind when opening this issue, actually).

**Comment by NovaRain** [comment]
> 
> 
> By that, I mean a _definitive mod packaging format_ for sfall. (Which is what I had in mind when opening this issue, actually).

For some reason it sounds like you're asking for a .esp plugin-like stuff from Bethesda games, I don't think there will be any other new packaging format other than the current "individual files in a folder" or .dat file.

**Comment by burner1024** [comment]
No, not at all. I think the current .dat / data dir is quite enough.
What I'm talking is
1. official spec "this is how you package a mod correctly".
2. (if necessary) additions to sfall to support the spec.

Right now, once you install 2-3 mods, game directory is polluted with various files, ini's, readme's, changelogs, etc. Coming back to a game after 2-3 months, it's hard to even know which mods are installed.

Ideally (I think)
1. There'd a single directory dedicated to mods ("mods"). Nothing gets written into root.
2. Inside it, each mod gets exactly one directory to store its stuff.
3. And what you do inside your own mod's directory is your business.

An example tree would look like

```
mods/
mods/fo2tweaks/
mods/fo2tweaks/fo2tweaks.ini
mods/fo2tweaks/readme.txt
mods/fo2tweaks/data/...

(or)
mods/fo2tweaks.dat # (no settings, can simply package it)
```

That way
- Mod installation is as simple as unzipped the archive into `mods` directory. No messing with ini's, like you said.
- It's clear where you need to go to edit mod settings (if any).
- You can clearly see which mods are installed.
- Most importanly, uninstallation is as simple as deleting mod directory (or .dat file). No leftovers, no garbage.

**Comment by NovaRain** [comment]
Sorry, I don't have an "official spec" or plan to define what the "correct" way is. If a modder think using folder for individual files or a .dat package is suitable for his mod and it indeed works, that's good enough in my book. I think the problem you're describing requires a brand new utility like those "mod organizers" of Bethesda games.

**Comment by burner1024** [comment]
> If a modder think using folder for individual files or a .dat package is suitable for his mod and it indeed works, that's good enough in my book.

I don't think I said anything contrary to that. These two format are enough.

> I think the problem you're describing requires a brand new utility like those "mod organizers" of Bethesda games.

No, it doesn't require anything like that. However, it would _allow_ for such,

> Sorry, I don't have an "official spec" or plan to define what the "correct" way is.

I see, OK.

**Comment by FakelsHub** [comment]
> mods/fo2tweaks.dat/fo2tweaks.ini

fo2tweaks.dat - это папка.
Так можно. Но Чтобы читать ini, ты должен ввести поддержку, получения текущего пути к модам из опции в ddraw

**Comment by FakelsHub** [comment]
> mods/fo2tweaks/data/...

fo2tweaks уже является data папкой.

**Comment by burner1024** [comment]
> fo2tweaks.dat - это папка.
> Так можно. Но Чтобы читать ini, ты должен ввести поддержку, получения текущего пути к модам из опции в ddraw

Ничего не понятно.
1. Так можно с AutoSearchPath или PatchFile? (про второе и так понятно, но зачем тогда так странно папку называть)
2. Ввести поддержку чего куда? Ты имеешь ввиду то, что AutoSearchPath делает или что-то другое?

**Comment by FakelsHub** [comment]
AutoSearchPath - ищет по маске *.dat
Если у тебя путь к твоему ini прописан жестко, то при изменении пути в AutoSearchPath, доступ к ini будет невозможен.

**Comment by burner1024** [comment]
А, теперь понял.
А обязательно эта маска? Может, для директорий убрать ее?

**Comment by FakelsHub** [comment]
Маска для защиты от мусора.

**Comment by burner1024** [comment]
Подумал, и в общем мне непонятно, от чего это защищает. Мусора и так можно накидать в любую директорию, хоть в корень, хоть куда.

**Comment by FakelsHub** [comment]
По маске происходит поиск. Если сделать маску *.* то будет какой-нибудь случайный файлик типа readme.txt добавляться, это и есть мусор.

**Comment by FakelsHub** [comment]
По маске происходит поиск. Если сделать маску *.* то будет какой-нибудь случайный файлик типа readme.txt добавляться, это и есть мусор.

**Comment by burner1024** [comment]
Ну там же и так весь корень в ридмиках, они же никак не влияют?

**Comment by FakelsHub** [comment]
Ты тему внимательно читал? Поиск в только в подпапке игры, какой корень.

**Comment by burner1024** [comment]
Ну и в подпапку можно накидать мусора. И назвать *.dat тоже. Если это будет проблемой, то защита так себе. А если нет, то смысла особого в фильтре я не вижу.

**Comment by FakelsHub** [comment]
Попробуй переименовать, посмотри что скажет движок на такой бэдовый файл.

**Comment by burner1024** [comment]
Вроде ничего не говорит.

**Comment by burner1024** [comment]
Что-то папка .dat [ломает сохранение](http://nma-fallout.com/threads/up-and-rp-updates.217877/).

**Comment by NovaRain** [comment]
It seems related to those ".sav/.pro/.db" temporary run-time files. For UPU/RPU the game saving works for new games if ".dat folder has no `maps` and `proto`.

**Comment by FakelsHub** [comment]
Предподчтительнее использовать не папки а полноценые Dat

**Comment by burner1024** [comment]
Непонятно, такое предпочтительней. Это же не вопрос вкуса. Либо папки должны нормально работать, либо не работать вообще.
Если использование папок требует обязательно DataLoadOrder - пусть, но надо это прописать в документации, а то откуда людям знать.

**Comment by FakelsHub** [comment]
Тут обэтом и написано, что при выключенной опции и использовании папок вместо дат будут глюки при сохранениях.

**Comment by FakelsHub** [comment]
Предпочтетельно это значит движок делает меньше усилий в поиске/сохранении временных файлов.

**Comment by burner1024** [comment]
> Тут обэтом и написано, что при выключенной опции и использовании папок вместо дат будут глюки при сохранениях.

Где тут?

**Comment by FakelsHub** [comment]
https://github.com/phobos2077/sfall/issues/206#issuecomment-504703091

**Comment by burner1024** [comment]
Ну вот оно должно быть в ddraw.ini написано, а тут это найдет только тот, кто уже на грабли наступил.

**Comment by FakelsHub** [comment]
Ну у меня опция всегда была включена, с того момента как она появилась.

**Comment by FakelsHub** [comment]
> ;Path to the folder in which the game will automatically search and load custom files (by mask *.dat, include folders)
> ;The data load order of the files in the folder will be in reverse alphabetical order of the filenames
> ;The files specified in the PatchFileXX options will have higher priority than others
> ;Uncomment the option to specify a different folder path. The default path is <GameRoot>\mods\
> ;AutoSearchPath=mods

Perhaps it would be better if it will take precedence over PatchFiles=###
Yes?

**Comment by Lexx2k** [comment]
I don't really understand. Files in folder have precedence over .ini setting?

**Comment by FakelsHub** [comment]
The files specified in the PatchFileXX options will have higher priority than in mods folders
To:
The files in mods folders will have higher priority than specified in the PatchFileXX options

**Comment by Lexx2k** [comment]
I don't think that's a good idea. You are forcing players to rename / remove folder from /mods/ then if something isn't right.

**Comment by burner1024** [comment]
> Perhaps it would be better if it will take precedence over PatchFiles=###

what's the purpose?

**Comment by FakelsHub** [comment]
> > Perhaps it would be better if it will take precedence over PatchFiles=###
> 
> what's the purpose?

Смотри какая ситуация, к примеру имеем некий апдейт записанный в опции PatchFiles0#= все хорошо.
Теперь я хочу без всяких заморочек с конфигами просто установить мод для этого создаю папку кримеру crazymod.dat и кидаю ее в папку /mods/ но хренос там мод не будет корректно работать потому, что имеет низкий приоритиет файлов.

**Comment by NovaRain** [comment]
So your plan is to make the chain like this?
`Data >> mods >> PatchFile99 >> ... >> PatchFile0 >> patch###.dat`

**Comment by burner1024** [comment]
> Те такой вариант сейчас имется в f1inf2, но правильнее им нужно было базу паковать в patch###.dat, чтобы не было такой херни как сейчас у них.

Мне кажется, изменение приоритетов ни к чему толком не приведет. Кто хочет, может сделать нормально и сейчас. А кто не хочет, и с другими приоритетами найдет как обосрать малину.

I think changing priorities won't be fruitful. Current system is good enough to make mods compatible, but changing order will still allow modders to fuck things up for other modders, there's no real advantage here.

If the underlying issue is F1in2 priorities, I'd first open a bug there and see if the developers would consider packing it properly. (I don't know why PatchFileX is used there at all, but then again, I find many of their development practices... unorthodox).

**Comment by Lexx2k** [comment]
What exactly is the issue? Nobody talked to me about anything.

**Comment by wipe2238** [comment]
> Maybe proper communication would be a good first step

I'd be happy if half of tickets comments in this repo wouldn't be in russian, for starters :D

**Comment by FakelsHub** [comment]
> > Те такой вариант сейчас имется в f1inf2, но правильнее им нужно было базу паковать в patch###.dat, чтобы не было такой херни как сейчас у них.
> 
> Мне кажется, изменение приоритетов ни к чему толком не приведет. Кто хочет, может сделать нормально и сейчас. А кто не хочет, и с другими приоритетами найдет как обосрать малину.

Ты как всегда пытаешь убежать от рельности файловых приоритетов.

**Comment by FakelsHub** [comment]
> We are using unpacked folders, because it makes handling the files simply easier. Besides, what's the point of moving everything into a shitty .dat with shitty dat tools if technically it changes nothing.

You should have placed the base files in a patchxxx. dat file or folder.

**Comment by Lexx2k** [comment]
Why? Then nobody knows what the file content is. Makes way more sense to me to give it an explicit name.

**Comment by burner1024** [comment]
@Lexx2k 
> What exactly is the issue? Nobody talked to me about anything. Maybe proper communication would be a good first step to prevent "such garbage" ... but who am I kidding, communication is for the noobz, am I right, folks?

I'm not sure. That's what I suggested, to open an issue with concrete details and discuss it.

> Please also enlighten me about other unorthodox development practices - I can change and adapt if necessary. Of course I can't if nobody talks about them ...

I don't mean it as "bad" practices, just some things are strange to me. However, I have no wish to go around and tell people how to do what they are doing, especially if they seem just fine without that :).
Offtopic here, but if you want some examples, well:
- Building scripts on schedule.
- Committing compiled scripts into repo.
- Compiling own sfall.
- Maintaining own copies of various mods (party armor, hero appearance, etc).
- Not having a clear scope, even looking at changelog - half of changes are tweaks, it's unclear what is supposed to be in the mod, and where it ends.
- Yes, and not sure why PatchFile directives are used, as far as I understand, dropping stuff into /mods/ would work just as well.

That's just off the top of my head.
To re-iterate, I think that you're doing great work, and FO1in2 is the best thing that happened to Fallout in the last few years. I do also think that everyone would benefit by putting more focus on compatibility and reusing stuff (which is what I'm trying with UPU/RPU, FO2tweaks), but that's just my opinion, which I'm only stating since you asked.

@FakelsHub 
> Ты как всегда пытаешь убежать от рельности файловых приоритетов.

Мне непонятно, о чем ты. Лучше объясни, что у тебя за мод и что за конфликт с 1in2, конкретно.
I don't know what you mean. It'd be easier if you explained what brings this up in the first place: what's the mod and what's the conflict with 1in2.

---

Back on topic, I still don't see how this change of load order would improve anything, but I'm pretty ambvivalent to the decision, since I don't use the directive and don't plan to.

**Comment by FakelsHub** [comment]
> Мне непонятно, о чем ты. Лучше объясни, что у тебя за мод и что за конфликт с 1in2, конкретно.

Нет у меня никакого мода. Речь идет об общей ситуации с модами.
А f1in2 взял как наглядный пример с ситуацией, когда у них базовые файлы висят в PatchFile опции, и не один мини-мод который будет перезаписывать их файлы не будет работать, без явного внесения мода в PatchFile конфиге.
На эти же грабли наступил и я, когда фиксы для Sonora поместил в PatchFile и решил быстренько закинуть и поиграть с небольшой модом безо всякой модификации конфигов.
Вот и оказалась полная лажа, т.к. mods папка имеет низкий приоритет.

>  I'd be happy if half of tickets comments in this repo wouldn't be in russian, for starters :D

I don't have any mod. We are talking about the General situation with mods.
And f1in2 took as a clear example of a situation where they have basic files hanging in the PatchFile option, and more than one mini-mod that will overwrite their files will not work, without explicitly making the mod in the PatchFile config.
I stepped on the same rake when I put the fixes for Sonora in PatchFile and decided to quickly throw and play with a small mod without any modification of configs.
So it turned out to be a complete mess, because the mods folder has a low priority.

**Comment by NovaRain** [comment]
If we change the priority of AutoSearchPath (seems nobody really against it), how should we treat "specifying a small mod in `mods` in PatchFile## config"? Lower its priority?
```
PatchFile0=FO3.5_main
PatchFile1=patch3.1416
PatchFile2=mods\ubertweaks.dat

AutoSearchPath=mods
;In mods\ there are: awezompak42.dat, ubertweaks.dat
```
Currently the chain is: ubertweaks.dat >> patch3.1416 >> FO3.5_main >> awezompak42.dat

Should it be: awezompak42.dat >> ubertweaks.dat >> patch3.1416 >> FO3.5_main
(lower the priority if specified in PatchFile##)

**Comment by Lexx2k** [comment]
I've stumbled over this again right now, and honestly, this whole "let's automatically load mods" is complete bullshit. Of the top of my head I can't think of any game that automatically loads mods if you put them into the games folder ... What do you want? Players shuffeling files from folder to folder? This is so stupid.

I'm guessing what you want is to auto-load *patch* files ... but even here: Why???? Is there any mod that releases multiple patches and deploys them like that? I know of none. Everyone releases a new big pack that will override the existing files instead ... because why bother. I might be ~okay~ with it if Fo2 would allow easy plug&play modding, but it simply doesn't and you can't trust players making sound decisions on what mods to load.

IMO you have 2 choices:
1. Rename the "mods" folder to "patches" because it makes way more sense, or
2. Remove this dumb auto-load shit, because nothing good comes from it.

Now I finally understood what Stalin said on NMA months ago when v1.0 of ettu was released... because I saw the \mods\ folder as "mods" and not "put auto-load patches in here" ....

**Comment by burner1024** [comment]
Hmm, I really don't understand what are you talking about, and fail to see how it's even relevant.
What's the issue?

**Comment by Lexx2k** [comment]
Automatically loading files in a folder called "mods" is bullshit. This is rather a "patches"-mechanic and even then it is questionable, because nobody in 2020 releases numbered patches for Fo2 mods.

But yes, ettu is using it "wrong" because "mods" wasn't made for.. uh.. mods. I'm not going to move my shit into a patch000.dat file because that unnecessarily complicates everything.

**Comment by FakelsHub** [comment]
Now everything works perfectly as planned. Mods are easily connected without digging into config file, and each one is located in its own folder (not in a common `data` folder aka the trash bin).
If you don't want to use `<somename>.dat`, this is your personal problem.

**Comment by burner1024** [comment]
@Lexx2k you're can dump everything into data, or package it however you want, or even rename the directory from mods to patches, it's configurable. You don't have to use it at all. So I don't understand the hate.

> Automatically loading files in a folder called "mods" is bullshit. This is rather a "patches"-mechanic

Where does this come from? Is there any specification, or RFC, or whatever, detailing mechanics of patches and mods?

> Is there any mod that releases multiple patches and deploys them like that? I know of none. 

Why yes, just look at RPU. But it's more about multiple mods, rather than a single mod with multiple components.

> I might be ~okay~ with it if Fo2 would allow easy plug&play modding

It certainly won't allow that if the attitude is `because why bother`. However, sfall capabilities have grealy expanded over the years, allowing to do much more - not everything, but much more in plug and play style.

**Comment by Lexx2k** [comment]
If mods in a folder load automatically, you will have to name them correctly, or else the load-order is fucked. Also you can't have optional mods in the same folder - you're forcing players to shuffle files around.

**Comment by burner1024** [comment]
> If mods in a folder load automatically, you will have to name them correctly, or else the load-order can be fucked up.

There are mutliple options to deal with this, the most obvious being writing mods in such a way that load order doesn't matter. Another is loading them explicitly with PatchFile from another dir. Yet another is actually naming them such that they load in "correct" order.
Is it perfect? Maybe no. But it's better than nothing (= dumping everything into data dir, making it a trash bin). We already have nothing, and anyone who wants can keep using it.

> Also you can't have optional mods in the same folder

I already have, therefore I can.

> you're forcing players to shuffle files around

Not a single player has ever come to me to complain about how they are forced to shuffle files around.

> As example, this is why the inventory filter mod made problems for me a while ago.

Do I understand correctly that there's an incompatibility between IF and F1in2? Then my first suggestion would be to open an issue in the corresponding repo and discuss how one or both mods could be altered to be compatible.

**Comment by NovaRain** [comment]
OK, there might be a (yet another) change on this stuff, especially for AutoSearchPath option:
1. Keep the current settable option. Maybe change the default path to something else (i.e. `patches\`) so people don't mix it with the paths in PatchFile## options too easily.
2. Remove the option from the INI, making sfall always load DATs from a fixed path (again, maybe change it from the current `mods\`), so there would be less problems in scripting if someone changes AutoSearchPath.
3. Kill the option entirely, leaving loading non-numbered DAT mods/patches to `PatchFile##` options only.

**Comment by burner1024** [comment]
I really don't understand what's it about. What is the issue that yet another change would solve? What people are confusing what with what and how is this a problem?

**Comment by NovaRain** [comment]
> 
> 
> I really don't understand what's it about. What is the issue that yet another change would solve? What people are confusing what with what and how is this a problem?

Well, because Mr.Stalin is taking option 2, I'd like to know if people have some other opinions.
It's not like I'm using or want this "autoload" stuff in the first place.

**Comment by wipe2238** [comment]
Hardcoding something into project which is all about fixing and exposing hardcoded stuff makes perfect sense to me.
