### ISSUE TITLE
A function to get object under cursor

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#207]
I tried to do automatic cursor mode switching, to reduce the number of incessant mouse right clicks using tile_under_cursor. The results are not satisfactory, even when detecting objects in south tiles. I wonder if there's a way to get the actual object? It seems that without it, set_cursor_mode is not very useful.

**Comment by NovaRain** [comment]
I found a sample script about auto cursor switching in my hard drive:
```
procedure start begin
   variable tile, obj_array, obj;

   if game_loaded then begin
      set_global_script_type(0);
      set_global_script_repeat(5);
   end else begin
      if combat_is_initialized then begin
         tile := tile_under_cursor;
         obj_array := tile_get_objs(tile, dude_elevation);
         if get_cursor_mode == CURSOR_MOVEMENT then begin
            foreach (obj in obj_array) begin
               if obj_type(obj) == OBJ_TYPE_CRITTER then begin
                  set_cursor_mode(CURSOR_TARGETING);
                  break;
               end
            end
         end

         if (len_array(obj_array) == 0) and (get_cursor_mode == CURSOR_TARGETING) then
            set_cursor_mode(CURSOR_MOVEMENT);
      end
   end
end
```

**Comment by FakelsHub** [comment]
This bad works.

**Comment by burner1024** [comment]
Here's a bit more advanced [version](https://github.com/BGforgeNet/fo2tweaks/blob/master/fo2tweaks/source/gl_g_auto_cursor.ssl) I came up with. Still too bad.
That's the reason for the request, tile is too imprecise. Would be great to have the object (what look_p_proc would show if in look mode).

**Comment by burner1024** [comment]
Тут пара моментов:
* Редко когда они закрывают гекс полностью, обычно остается какое-то видимое пространство.
* Возможность ручного переключения никуда не девается. Автоматическое переключение срабатывает только при смене объекта/тайла под курсором.

Проблема в том, что пока в игре не попробуешь, непонятно насколько удобно будет. По идее щелканий должно стать меньше, но с другой стороны, если нужно перемещаться в толпе, то может наоборот стать хуже.

Плюс еще хука на смену тайла нет, так что курсор будет меняться с задержкой... может и не очень хорошая идея это.

**Comment by burner1024** [comment]
Только собрался тестировать, а ты уже расписал аргументы.
Функция работает, добавил в скрипт, как погоняю с ним немного, станет понятней насколько полезно.

**Comment by burner1024** [comment]
Overall, the feature doesn't work as well as I hoped, but I'm still thinking if the script can be improved.

**Comment by burner1024** [comment]
Yes, definitely better than tile functions.
