### ISSUE TITLE
function to get current critter in dialog mode

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#209]
Use case: non-sucky version of unlimited party. When talking to a potential party member, a hook would temporarily dump other companions and minimally raise CHA (if necessary, just enough to allow joining).
Alternatively, it could be an arg in GAMEMODECHANGE?

Edit: a function to do that from a global script, I mean. So that no changes to critter scripts would be required.

**Comment by FakelsHub** [comment]
Непонял смысл.

**Comment by burner1024** [comment]
Ну это о чем я [тут](http://www.nma-fallout.com/threads/how-to-determine-which-critter-is-dude-talking-to.216604/) спрашивал.

**Comment by FakelsHub** [comment]
А причем тут харизма и напарники?

**Comment by burner1024** [comment]
Конкретно такая фича будет полезна, чтобы можно было снять лимит на количество напарников отдельным скриптом. Т.е. он будет временно чуть-чуть поднимать харизму если нужно.

**Comment by FakelsHub** [comment]
Все равно не понял) что надо то?

**Comment by burner1024** [comment]
Ну что то такое
```
if get_game_mode bwand DIALOG then begin
  if is_in_array(obj_pid(dude_in_dialog_with_critter), potential_party_members) then begin
    call boost_charisma;
  end
end
```
Вот _dude_in_dialog_with_critter_ возвращал бы указатель на криттера, с которым разговариваем сейчас.

**Comment by FakelsHub** [comment]
Так добавили уже в 4.1.2

**Comment by burner1024** [comment]
Аа а чего молчали. Так это отлично! Уродливую рекомпиляцию из FO2tweaks продолжаю выпиливать тогда.

**Comment by FakelsHub** [comment]
А какой у тебя метод получения? Вроде нельзя получить так, без захода в бартер.

**Comment by burner1024** [comment]
Пока никакой, просто скрипты напарников меняются.

**Comment by burner1024** [comment]
Запилил [скрипт](https://github.com/BGforgeNet/fo2tweaks/blob/master/fo2tweaks/source/gl_g_unlimited_party.ssl), вроде работает.
