### ISSUE TITLE
Alternative to drag-and-drop in barter/steal/loot interface

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#21]
Drag-and-dropping item in barter/steal/loot interfaces is tedious. I think it would be great to have a key combination that'd allow to do that faster.

For exampl use ctrl+right click to move items back and forth. (and something like shift-rclick could be used to move the whole stack, bypassing "quantity" window)

**Comment by FakelsHub** [comment]
> something like shift-rclick could be used to move the whole stack, bypassing "quantity" window

Что-то подобное было реализовано в #162.
Насчет остального, даже не знаю как такое сделать.

**Comment by NovaRain** [comment]
The ItemFastMoveKey modifier key in 4.0.5/3.8.10 should make moving lots of items easier, you still need to do the "drag-n-drop" part though.
