### ISSUE TITLE
get_weapon_ammo_pid returns -1 on empty weapon

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#210]
Like the title says. Probably intended behaviour, but the problem is that when you reload a weapon, you generally want to reload it with the same ammo type. And it seems there no way to discover the type if the weapon is empty?

**Comment by NovaRain** [comment]
I tried get_weapon_ammo_pid on the weapon in active slot and it returns valid ammo PID.

**Comment by burner1024** [comment]
that was empty weapon?

**Comment by NovaRain** [comment]
>that was empty weapon?

Of course. It only returns -1 for weapons with no ammo.

**Comment by FakelsHub** [comment]
Что-то не совсем понял проблему. 
оружие и так перезаряжается тем же типом патроном который в него был заряжен в ручную.

**Comment by FakelsHub** [comment]
См. Issue #121

**Comment by burner1024** [comment]
> Yes. It only returns -1 for weapons that don't require ammo.
I must be doing something wrong then. Alright.
