### ISSUE TITLE
Possible to expose old mode in GAMEMODECHANGE?

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#211]
When dealing with game modes, I often find that it's not the actual mode that is interesting, but change in modes. For example, firing certain actions at beginning and end of combat.
I guess old mode could be tracked in a global variable and updated every time it changes. But that probably would get messy with multiple scripts.

Edit: well, new mode can be gotten with get_game_mode, so this is really about the old one.

**Comment by FakelsHub** [comment]
Теперь по русски напиши, а то не понятно что за старый режим ты нашел.

**Comment by burner1024** [comment]
Ну режим был один, стал другой. В хуке мы не знаем какой был.

**Comment by FakelsHub** [comment]
Заводишь переменную и записываешь в нее режим. Потом когда изменится режим смотришь в переменную и узнаешь какой был режим до смены.

**Comment by burner1024** [comment]
ну да по идее можно и локальной переменной обойтись, что-то меня заклинило.

**Comment by FakelsHub** [comment]
Думаю можно добавить, меньше будет возьни с локальными переменными.

**Comment by burner1024** [comment]
Да, было бы неплохо.
