### ISSUE TITLE
Cannot load the original ddraw.dll library

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#212]
Sfall 4.1.2 simply doesn't work under Wine. Not sure about Windows, I don't have it.
Tried re-dowloading, running with vanilla ini - doesn't help.
4.1.1 loads fine.

![captura de pantalla de 2018-11-07 04-45-20](https://user-images.githubusercontent.com/1279852/48095899-74ce4d00-e248-11e8-8c0c-e4cf10465a55.png)

**Comment by FakelsHub** [comment]
Переходи на Windows) в wine видимо забыли добавить оригинальную библу.

**Comment by NovaRain** [comment]
>Sfall 4.1.2 simply doesn't work under Wine. Not sure about Windows, I don't have it.

It's due to the change in commit 3203152ca4352e496093660a73b028cbe8edcae3 for a [proper proxy-dll](http://developers-club.com/posts/133956/). Now sfall will check if the original ddraw.dll in system directory. I can't get the Ubuntu+Wine work in my VM so I didn't test it in non-Windows environment, only in all available Windows versions in my workplace (2000/2003/2008/7/10).

**Comment by burner1024** [comment]
> But I thought Wine should be able to set up stuff like that?

Sorry, stuff like what?

> У тебя сама оригинальная игра без модов sfall & HRP запускается под wine?
> Игра ведь для запуска требует такую библиотеку, иначе она без нее не должна запуститься.
> проверь там должна лежать ddraw `$ cd ~/.wine/driver_c/windows/system32/`

Где ж ее найдешь без модов теперь. Если просто ddraw.dll и f2_res.dll удалить, запускается.
```
ls ~/.wine/drive_c/windows/system32/ | grep ddraw
ddraw.dll
ddrawex.dll
```

**Comment by NovaRain** [comment]
>Sorry, stuff like what?

I mean the path to system directory or similar settings. But your game can start without sfall, which seems it did find the original ddraw.dll.

**Comment by FakelsHub** [comment]
А под вайном в v4.1.1 режим DX9 оконный работает?

**Comment by burner1024** [comment]
Работает.
Лог вайна с ошибкой приложен.
[wine.log.zip](https://github.com/phobos2077/sfall/files/2557299/wine.log.zip)

**Comment by burner1024** [comment]
Ошибка вылезает, но после нажатия ок все запускается.
![captura de pantalla de 2018-11-07 23-32-32](https://user-images.githubusercontent.com/1279852/48145592-b3661500-e2e5-11e8-8a6c-e18949c6fb1f.png)

**Comment by FakelsHub** [comment]
Ясно что-то с вайном, возможно это только у тебя такое.
Может для wine нужно что бы путь к длл был задан в Unicode?
И что такое builtin для библиотек, задается в конфиге wine вроде, ты не в курсе про это?

**Comment by FakelsHub** [comment]
Кстати вышли мне из wine эту библиотеку, можeт она какая-то не такая.

**Comment by burner1024** [comment]
I tried a new wine prefix, it's all the same.
Wine's ddraw.dll attached: [ddraw.dll.zip](https://github.com/phobos2077/sfall/files/2560387/ddraw.dll.zip).

**Comment by FakelsHub** [comment]
какая то пустая библиотка размером 3кб
вот отсюда скачай для wine там ее размер 309кб
https://www.reasoncoresecurity.com/ddraw.dll-579e1bee5e9df44e4db78c4b03fc68b8cccf59be.aspx

**Comment by burner1024** [comment]
Официальный [пакет](https://packages.ubuntu.com/bionic/i386/libwine/download) убунту, там то же самое.
Я не до конца понимаю в чем смысл этого коммита, но, наверное, можно автору статьи на хабре написать, возможно он что-нибудь подскажет. Хотя там у него все на виндоус.
Ну и надо проверить что не только у меня, разве виртуалки с линуксом нет ни у кого?

**Comment by FakelsHub** [comment]
Как я понимаю эта библиотека должна содержать фукции winapi но которые должны эмулировать эти функци под свою lunix систему. Но она у тебя просто напросто пустая.
 Как вариант использовать нативную микрософтовскую ddraw, вместо этой пустышки, но нужно будет еще выставить в конфиге что ddraw используется в нативном режиме.
Но я ничего не понимаю в wine, это я тебе написал из того что я начитал в интернете, по поводу  ddraw и diretX.
Cмысла для wine в этом комите нет, он есть только для виндовс систем.
Причем тут автор на хабре не понял)

**Comment by burner1024** [comment]
Все, разобрался. В общем было `WINEDLLOVERRIDES=ddraw.dll=n`, стало `WINEDLLOVERRIDES=ddraw.dll=n,b`

**Comment by FakelsHub** [comment]
И что это значит?

**Comment by burner1024** [comment]
Так работает. n - native, b - builtin.
Судя по всему пока была тупая инъекция, для вайна это было прозрачно, а как стало поумнее, через LoadLibrary, надо ему специально указать подгружать и то и другое. Иначе он ожидает полную имплементацию в файле от sfall и в system32 не идет.
Надо в документацию добавить где-нибудь.

**Comment by NovaRain** [comment]
>Надо в документацию добавить где-нибудь.

Since I still can't get FO2 running on Wine (I tried again yesterday), maybe you could give a suggestion on how to write it?

**Comment by burner1024** [comment]
well, is just basic command line usage. What I use is `XMODIFIERS="" WINEDLLOVERRIDES='ddraw.dll=n,b' WINEPREFIX="~/.wineprefixes/f2" wine fallout2.exe > wine.log 2>&1`, or some variation.
A simple text or md file called running_in_wine mentioning such a line should be enough.

What's the problem that you're having, anyway?

**Comment by NovaRain** [comment]
>What's the problem that you're having, anyway?

Just managed to get it work. I was being stupid and didn't create a proper wineprefix. Now I can check if sfall works under Wine (albeit laggy, but that's expected from my office desktop). I'm thinking about adding this to the readme:

>For Wine users:
You need to set DLL overrides for ddraw.dll to 'native, builtin' in winecfg, or use 'WINEDLLOVERRIDES="ddraw=n,b"' to run the game.

**Comment by burner1024** [comment]
Yes that should be enough.
