### ISSUE TITLE
Values in map array can't be 0?

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#213]
Apparently can't assign 0 to a value in a map array:
```
  variable k, v, ar, tmp;
  ar := {"1":"5", "2":"10", "3":"11", "4":"0", "7":"11", "8":"0"};
  tmp := temp_array_map;
  foreach k: v in ar begin
    k := atoi(k);
    v := atoi(v);
    debug_msg("k " + k + ", v " + v);
    tmp[k] := v;
  end
  debug_msg("tmp length is " + len_array(tmp));
  foreach k: v in tmp begin
    debug_msg("k2 " + k + ", v2 " + v);
  end
```

output:
```
k 1, v 5
k 2, v 10
k 3, v 11
k 4, v 0
k 7, v 11
k 8, v 0
tmp length is 4
k2 1, v2 5
k2 2, v2 10
k2 3, v2 11
k2 7, v2 11
```

**Comment by NovaRain** [comment]
0 means to unset the value from map, from arrays.txt:
```
> void set_array(int arrayID, mixed key, mixed value):
...
- to "unset" a value from map, just set it to zero (0)
- this works exactly like statement:
    arrayID[key] := value;
```

**Comment by NovaRain** [comment]
From arrays.txt it seems you just unset the value from map:
```
> void set_array(int arrayID, mixed key, mixed value):
...
- to "unset" a value from map, just set it to zero (0)
- this works exactly like statement:
    arrayID[key] := value;
```

**Comment by burner1024** [comment]
yeah... alright, thank you.

**Comment by FakelsHub** [comment]
какое значение возвращается из tmp[8] ?

**Comment by burner1024** [comment]
Ну читаешь массив интов из конфига, делаешь foreach, а значений 0 в нем нет, они пропускаются.
Возьми любой другой язык программирования, и попробуй разработчикам скажи, что в массиве нельзя хранить 0, думаешь в какое направление они тебя пошлют?
Не смертельно конечно, можно это все обработать, но решение необычное и неинтуитивное.

**Comment by FakelsHub** [comment]
Ну тут же не язык программирования, там есть проверка на существование ключа, тут нету такого, кто делал массивы тот пускай и доделывает)

**Comment by FakelsHub** [comment]
Лучше так попробуй. float не должен удалять ключ, да и преобразовывать не придется из string.
`tmp[k] := v if v else 0.0;`

**Comment by FakelsHub** [comment]
Made an associative array that can contains a key with a value of zero.
Only in such an array can not change the value of the existing key (made for other purposes).
