### ISSUE TITLE
use_obj_on_obj from global script crashes even with set_self

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#214]
The following will crash the game:
```
procedure skill_handler begin
  variable user := get_sfall_arg;
  variable target := get_sfall_arg;
  variable skill := get_sfall_arg;
  variable skill_bonus := get_sfall_arg;
  variable skill_level := critter_skill_level(user, skill);
  variable item;
  variable skill_points := get_critter_skill_points(user, skill);
  ndebug("user is " + obj_name(user) + ", target is " + obj_name(target)
    + ", skill is " + skill + ", skill level is " + skill_level + ", bonus is " + skill_bonus
    + ", skill points is " + skill_points);
  if skill == SKILL_REPAIR then begin
    set_sfall_return(0);
    item := create_object(PID_SUPER_TOOL_KIT, 0, 0);
    add_obj_to_inven(user, item);
    set_self(user);
    ndebug("self is " + obj_name(self_obj) + ", item is " + obj_name(item));
    set_self(user);
    use_obj_on_obj(item, target);
  end
end
```
Apparently this a [known issue](http://www.nma-fallout.com/threads/fo2-engine-tweaks-sfall.178390/page-56#post-3688162), any chance it will be fixed?

**Comment by FakelsHub** [comment]
В следующей версии (4.1.5) сделаю исправление, но нужно будет двойное применение функции set_self
```
    set_self(user);
    set_self(user);
    use_obj_on_obj(item, target);
```

**Comment by FakelsHub** [comment]
В следующей версии (4.1.5) сделаю исправление, но нужно будет двойное применение функции set_self
```
    set_self(user);
    set_self(user);
    use_obj_on_obj(item, target);
```

**Comment by burner1024** [comment]
отлично

**Comment by burner1024** [comment]
А какой смысл два раза кстати? Обратная совместимость? Так вроде ничего не должно сломаться.

**Comment by FakelsHub** [comment]
Потому, что под капотом в функции два раза вызывается функционал, при котором сбрасывается установка setsel. Придумал сделать счетчик для сброса.

**Comment by NovaRain** [comment]
Here's the build from the latest commit with fixes for issue 196 & 214. It also prints error when the given sfall global var name is not 8 character long:
http://www.mediafire.com/file/ypukznmi58az8rj/ddraw_20190121.rar/file

@burner1024 You can test the build to see if the fixes/changes work for your intended scripts.
One major improvement for fs_* function is now the altered virtual files (i.e. those FRMs in your demo script) don't get saved automatically in save games, unless you specifically set the flag for them using fs_resize(fileId, -1), so there won't be large sfallfs.sav files cluttered in player's save game folders.

**Comment by burner1024** [comment]
Will do

**Comment by burner1024** [comment]
@NovaRain awesome, everything seems to be working correctly, both this issue and #196.

Maybe also add a warning to fs_* if UseFileSystemOverride is disabled?

**Comment by FakelsHub** [comment]
> Maybe also add a warning to fs_* if UseFileSystemOverride is disabled?

В скрипте это делайте.
