### ISSUE TITLE
Hook light level change

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#215]
Apparently the original scripts are littered with set_light_level in map_update_p_proc, so set_light_level in a global script either gets reverted or results in flickering (if using set_global_script_repeat or map_update_p_proc).
A hook could help to avoid that, by returning consistent values.

**Comment by FakelsHub** [comment]
use get_light_level

**Comment by burner1024** [comment]
it doesn't matter, it gets reset by map scripts.

**Comment by FakelsHub** [comment]
А ну да. Тебе надо отменять установку так бы и сказал)

**Comment by burner1024** [comment]
Не совсем отменять, перезаписывать скорее. Вообще я искал способ выставить минимальный уровень - в RP очень темные карты есть.
В итоге выяснилось, что освещение очень коряво выставляется, там функция с разрывом в середине. Плюс скрипты карт постоянно сбрасывают освещение, так что даже если выставлять в цикле, постоянно мигает. Поэтому хук был бы лучшим решением.

**Comment by burner1024** [comment]
Great, thank you!
