### ISSUE TITLE
Possible to expose real damage type in combatdamage hook?

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#216]
Calculating damage in hs_combatdamage requires accounting for resists. Normally they can be gotten by weapon_dmg_type(weapon), but that can be overriden by set_attack_is_explosion_fire (and as far as I understand, other damage types can be set, too).
So once damage type is overriden, and there no way to know that in combatdamage currently, incorrect resist type will be used in calculation and thus the total damage will be incorrect.

**Comment by FakelsHub** [comment]
Нельзя. Сделайте переменную и учитываете это в скриптах.

**Comment by burner1024** [comment]
Свою-то переменную не проблема учесть, а вот кто что в других модах сделает неизвестно.
Сделаю пока настройку в ини файле.

**Comment by FakelsHub** [comment]
Зачем закрыл? забуду что нужно)

**Comment by burner1024** [comment]
Я думал ты не собираешься.
Ну и в общем случае еще не понятно, другой хук ведь может быть зарегистрирован позже и уже там поменять тип дамага.

**Comment by FakelsHub** [comment]
Я тут обдумал и решил что действительно нет  смысла в такой функции. 
По правильному использовать set_attack_is_ нужно так что бы и в прототипе оружия был установлен соответствующий тип повреждений, а не так - сегодня Normal завтра Explosion, а от взятого перка что-то другое, это неправильный подход.
Так что вопрос можно закрыть.

**Comment by burner1024** [comment]
Так не всегда получится, потому что из одного оружия можно разными типами зарядов стрелять.

**Comment by burner1024** [comment]
Так не всегда получится, потому что из одного оружия можно разными типами зарядов стрелять.

**Comment by FakelsHub** [comment]
> Ну и в общем случае еще не понятно, другой хук ведь может быть зарегистрирован позже и уже там поменять тип дамага.

если тот отработает после твоего, то твой скрипт уже и так ничего не сможет изменить.
