### ISSUE TITLE
ai_check_drugs is wrong?

### ISSUE THREAD

**Issue by FakelsHub** [phobos2077/sfall#219]
This is not a big snippet of code from the engine, I cannot understand this algorithm, it seems to me that there is an bug in these lines of code
`if ( _ipid == aiCap->chem_primary_desire )`
`while ( counter < 3 && itemObj->pid == aicap_offset->chem_primary_desire );`
Should be not equal ( != ), Instead of equal ( == ) ???

```
itemObj = inven_find_type_(scr, item_type_drug, &buf);
if ( !itemObj )
{
	noInvenItem = 1;
	break;
}
aicap_offset = aiCap;
_ipid = itemObj->pid;
counter = 0;
if ( _ipid == aiCap->chem_primary_desire )
{
	do
	{
		++counter;
		aicap_offset = (aicap_offset + 4);
	}
	while ( counter < 3 && itemObj->pid == aicap_offset->chem_primary_desire );
}
if ( counter < 3 )
```

**Comment by NovaRain** [comment]
>This is not a big snippet of code from the engine, I cannot understand this algorithm, it seems to me that there is an bug in these lines of code

I don't poke around AI functions as much as you do, but I think it's better to figure out the algorithm first before deciding if it's really bugged. Or maybe test the supposed fix in game to check how the AI behavior changes.

**Comment by FakelsHub** [comment]
After analyzing, I came to the conclusion that there is indeed an bug in the algorithm.
This list of pid `chem_primary_desire`- if the drugs is not included in this list, then the NPC will not use it. 
Conclusion: This list indicates allowed drugs for the NPC to use. if the this list is empty, any drugs will be used.

**Comment by NovaRain** [comment]
Funny thing is that many AI packets set it with only Iguana-on-a-stick. Not sure if "fixing" it will result them in only eating iguanas not using stims/other drugs.

**Comment by FakelsHub** [comment]
Yes, I know about it, but stimpack are used separately from this feature.

**Comment by burner1024** [comment]
what's the difference then?

**Comment by FakelsHub** [comment]
Разница?
Тут дело в том что этот кусок кода не работает.

**Comment by NovaRain** [comment]
Does ```chem_primary_desire``` list only work when AI's chem_use is set to sometimes/anytime? Is it a hard limit (AI won't use any other drugs) or pids in the list just have higher priority than other drugs (AI will use pids in the list first, if there's no than other drugs)?

**Comment by burner1024** [comment]
Код мне тоже не особо понятен, но я к тому что если они начнут жрать игуан в бою то это им не особо поможет.

**Comment by FakelsHub** [comment]
> AI will use pids in the list first, if there's no than other drugs

It is by this algorithm that I make the fix.

**Comment by FakelsHub** [comment]
> Does chem_primary_desire list only work when AI's chem_use is set to sometimes/anytime?
Yes, and "always"

**Comment by NovaRain** [comment]
I tested the chem_primary_desire and chem_use in AI.txt. I added:
```
chem_primary_desire=284,81,103
chem_use=anytime
```
to [Arroyo Warrior] section. I gave Klint five iguanas and one RadAway, provoked him and just ran around to trigger him using drugs. Without the fix, he would use two iguanas and take other actions in a turn, and also use RadAway when iguanas run out (the third time he tries to use drugs). I didn't notice any difference when enabling the fix.

**Comment by FakelsHub** [comment]
Strange, I will check your test config.

**Comment by FakelsHub** [comment]
> I didn't notice any difference when enabling the fix in new build.

did not quite understand, but what difference did you want to see with such a config?

**Comment by NovaRain** [comment]
>did not quite understand, but what difference did you want to see with such a config?

Because it seems your fixes didn't make any difference. chem_primary_desire wasn't bugged in the first place (Klint uses iguanas first then RadAway normally without your fix), and config_get_values returned the last value (pid 81) correctly even if the number of values is less than requested (again, without your fix).

**Comment by FakelsHub** [comment]
284 is not RadAway
you have the wrong config.

**Comment by FakelsHub** [comment]
The iguanas you added first, so they are located first in the list of items in the inventory, access to the item is not random but sequential.

**Comment by FakelsHub** [comment]
Возможно нужно было делать исправление альтернативным, что-бы указать какие наркотики можно употреблять для данного AI - но я не вижу смысла в этом способе.

**Comment by FakelsHub** [comment]
Maybe it was necessary make so the drugs used strictly in the order specified in the list?

**Comment by NovaRain** [comment]
>Maybe it was necessary make so the drugs used strictly in the order specified in the list?

Nah, I don't see a point in making this.
