### ISSUE TITLE
Automatically load full magazine

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#22]
When the user reloads a weapon from inventory screen, there's a dialog with quantity of magazines. There's 0 sense to it. I can't think of a time I didn't need to load the weapon fully. It would be great to bypass this dialog, as you pressed "all"

**Comment by phobos2077** [comment]
I think Crafty already added some hack like this. We will investigate.

**Comment by NovaRain** [comment]
Yes, there's already one in Crafty's mod, but I'm not interested on implementing it during 3.7 development.

**Comment by phobos2077** [comment]
Yeah but 3.7 is already released, isn't it? :)

**Comment by NovaRain** [comment]
I've implemented the ReloadReserve setting from Crafty's mod. It should be available in later 3.7a or 3.8, depends on the release plan/schedule.
