### ISSUE TITLE
Highlighting with caps lock

### ISSUE THREAD

**Issue by wipe2238** [phobos2077/sfall#221]
If highlighting key is set to caps lock (`0x3A`/`58`, aka `DIK_CAPITAL`) it turns itself off after opening container/changing map. Not a big deal, just turn caps off and on again, but maybe it could be fixed some day to support permanent highlighting.

sfall v4.1.2

**Comment by NovaRain** [comment]
The auto disable when opening containers was done to [avoid some display glitches](http://www.nma-fallout.com/threads/fo2-engine-tweaks-sfall.178390/page-142#post-4300255).

**Comment by wipe2238** [comment]
Aww, i'd be fine with that, but i'm sure i'm in minority here :)
Thanks for quick clarification.
