### ISSUE TITLE
has_trait only works on party members?

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#224]
```
procedure map_enter_p_proc begin
  variable who;
  if enabled then begin
    ndebug("living_anatomy_min_doctor="+living_anatomy_min_doctor);
    if living_anatomy_min_doctor < 300 then begin
      foreach who in list_as_array(LIST_CRITTERS) begin
        ndebug(obj_name(who) + " has Doctor of " + critter_skill_level(who, SKILL_DOCTOR));
        if critter_skill_level(who, SKILL_DOCTOR) >= living_anatomy_min_doctor
          and not has_trait(TRAIT_PERK, who, PERK_living_anatomy_perk)
        then begin
          ndebug(obj_name(who) + " gets living anatomy!");
          critter_add_trait(who, TRAIT_PERK, PERK_living_anatomy_perk, 1);
          if in_party(who) then begin
            display_msg(obj_name(who) + " " + living_anatomy_msg2);
            float_msg(who, living_anatomy_msg, FLOAT_MSG_WHITE);
          end
        end
      end
    end
  end
end
```
I'm getting some strange messages with this:
```
gl_g_healing_revision: living_anatomy_min_doctor=5

gl_g_healing_revision: Lesser Scorpion has Doctor of 8

Error: perkGetLevelData: Can't find party member match!
gl_g_healing_revision: Lesser Scorpion gets living anatomy!

intextra::critter_add_trait: Adding Perk Living Anatomy to Lesser Scorpion
Error: perkGetLevelData: Can't find party member match!
gl_g_healing_revision: Lesser Scorpion has Doctor of 8

Error: perkGetLevelData: Can't find party member match!
gl_g_healing_revision: Lesser Scorpion has Doctor of 8

Error: perkGetLevelData: Can't find party member match!
gl_g_healing_revision: Giant Ant has Doctor of 8
```

First, it seems that it only works on party members?
Second, after one invocation of perkGetLevelData failed, somehow next critters in the list just get skipped, it doesn't even try to apply the perk?

**Comment by FakelsHub** [comment]
перки только для игрока.

**Comment by FakelsHub** [comment]
Назревает вопрос, для какой цели вы добавляете это к другим существам?
У них даже не предусмотрено игрой место в памяти, чтобы хранить добавленный перк.
Поду поэкспериментирую с добавление перков, даже интересно куда он там добавиться).

**Comment by FakelsHub** [comment]
Если криттер является партиец то перк добавиться к самому партийцу (в его таблицу, неизвестно сохраняется ли его таблица в сохранении), но в движке большинство механик перков рассчитано на игрока, поэтому некоторые перки просто не будут работать.
Сработаю лишь те которые дают прибавку к special, и некоторые движковые, к примеру Healer будет работать c партийцем.
Было бы замечательно собрать инфу по перками которые могут работать с партийцами.

**Comment by burner1024** [comment]
Хмм понятно. Я думал, что все честно и любой криттер может иметь перки. Цель собственно такая и есть - "честная" игра.
Я уже испугался что у меня в damage mod расчитывается все неправильно и перки оружия не учитываются у врагов.
Надо будет добавить в вики эту инфу, да.

**Comment by FakelsHub** [comment]
не ванильные - это которые ты сам придумываешь и/или сам реализуешь их механику в своих скриптах.

**Comment by FakelsHub** [comment]
```
 //ranged_bonus - bonus ranged damage perk
ranged_bonus := 2 * has_trait(TRAIT_PERK, attacker, PERK_bonus_ranged_damage);
```

Ну твой damage mod конечно с косяками.
Ты уже понял что это косяк? если игрок будет иметь перк, то любой атакующий криттер(не партиец) тоже получит бонус от перка игрока.

**Comment by burner1024** [comment]
> не ванильные - это которые ты сам придумываешь и/или сам реализуешь их механику в своих скриптах.
Это понятно, я спрашиваю они на не-партийцах сохранятся будут?

> Ты уже понял что это косяк? если игрок будет иметь перк, то любой атакующий криттер(не партиец) тоже получит бонус от перка игрока.
А вот это непонятно. С чего получит-то, когда явно проверяется атакующий криттер? Так криво функция работает?

**Comment by burner1024** [comment]
> В оригинальной формуле для игрока и сокомандников сложность всегда равна 100. т.е. модификатор +/- должен действовать на других криттеров.

Точно? Мне [казалось](http://www.nma-fallout.com/threads/what-does-combat-difficult-setting-do.215187/) на всех.

**Comment by FakelsHub** [comment]
Код из движка
```
      team = *(_ctd->source + offsetof(pobj, team_num));
      teamPC = *(obj_dude + offsetof(pobj, team_num));
      difficulty = 100;
      if ( team != teamPC )
      {
         buf = 1;
         config_get_value_(game_config, "combat_difficulty", "preferences", &buf);
         if ( buf )
         {
            if ( buf == 2 )
            {
               difficulty = 125;
            }
         }
         else
         {
            difficulty = 75;
         }
      }
```

**Comment by FakelsHub** [comment]
Не может действовать на всех, если при 125 криттеры должны наносить больше урона, то и игрок/партийцы будет наносить тоже больше. ... Логика? не, не слышали))

**Comment by burner1024** [comment]
Почему, логика есть. Сложнее? Сложнее.
Наверное сделаю опцию чтобы и так и так можно было.

**Comment by FakelsHub** [comment]
Чем сложнее? Если противники тоже быстро умирают. И по сути это увеличивание дамага.

**Comment by burner1024** [comment]
[documented](https://falloutmods.fandom.com/wiki/Fallout_1_and_Fallout_2_scripting_-_commands,_reference,_tutorials)

**Comment by FakelsHub** [comment]
> Only player can have Perks

Партийцы тоже имеют, но многое не будет работать.
