### ISSUE TITLE
Better documentation format

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#225]
Txt docs aren't really convenient to work with. I was thinking maybe that may be improved? For example, store them in yaml, add a build step that generates markdown and then publish it jekyllized on github pages? Or, maybe readthedocs.

My ulterior motive is to be able to consume it automatically in [MLS](https://github.com/BGforgeNet/vscode-bgforge-mls), and I suppose that'd benefit SFSE too.

**Comment by phobos2077** [comment]
Which docs do you refer to specifically?

**Comment by FakelsHub** [comment]
> Here's what I have already.

Подождем когда будут описания для всех функций)
Откуда "скопипастил" основу описаний?

**Comment by burner1024** [comment]
Там практически все и есть. Тырил с SFSE, с вики. Проблема в том, что если нет одного авторитетного источника, то потом описания начинают расходиться - тут одно поправили, там другое. Руками за этим всем не уследить.

**Comment by phobos2077** [comment]
You want to add this yaml to sfall repo? I still don't understand what this has to do with sfall :) Looks like something that belongs to a script editor of some sort, like function descriptions I used for my older version of Sfall Script Editor.

**Comment by burner1024** [comment]
Well, sfall repo **is** the authoritative source of information about the functions sfall provides, right? Where else do are people supposed to get it from?

All I'm talking about is changing free-style txt format it's published now into a structured, formalized format. Which could look like the yaml file I linked, but not necessary - once it's machine-readable, it's easy to convert/adjust.
And that would profive 2 benefits:
1) Editors (SFSE, SFSE extended, MLS) can consume it automatically instead of copying/updating/deleting doc pieces manually from release notes or elsewhere.
2) If the info is strutured, it doesn't take much effort to generate a web doc that is easy to read and navigate, unlike current wall-of-text/infodump.

**Comment by phobos2077** [comment]
Well if you can convert it to such format, but also provide some kind of human-readable form of the same info pre-generated (so people can read it right away), that'd be great. Maybe .md format, so it can be viewed directly from github?

**Comment by FakelsHub** [comment]
Напиши на русском что ты хошешь сделать с этим файлом, где ты его хочешь разместить, а то на на английском вся суть теряется)
Если бы ваш уml содержал все описания я бы его встроил в редактор, а так мне пока нет резона писать поддержку для yml файлов, когда ваш файл  содержит все что уже есть в opcodes.txt

**Comment by burner1024** [comment]
Я предлагаю складывать оригинал описания в yml тут в репозитории sfall (например, как у меня сделано, но можно и более детально разбить), а из него автоматически (travis или что-нибудь такое) генерировать удобную html доку. Ее публиковать либо просто в .md, либо на github pages, обработанную [jekyll](https://idratherbewriting.com/documentation-theme-jekyll/mydoc_publishing_github_pages.html), либо в [readthedocs](https://docs.readthedocs.io/).

Ну и соответственно будет проще подцеплять в редакторы новые версии.

Скрипт для генерации я написать могу, ну а конкретно по формату и где публиковать - какие у вас предпочтения?

Travis требует доступ к репозиторию, так что либо кому-нибудь с доступом это придется настроить, либо можете меня добавить.

**Comment by FakelsHub** [comment]
Я думаю нужно разбить один файл на два, что бы в одном  было описания к ванильным функциям, в другом те что относятся к sfall.
Для людей все же txt лучше чем yml, поэтому придется еще и писать изменения в yml
поэтому если бы кто-то отдельный человек отслеживал изменения в txt и переписывал их в yml было бы хорошо. (так мне например не очень хочется писать еще и в yml).

Может есть хороший бесплатный визуальный редактор для yml файлов?

**Comment by burner1024** [comment]
Я имею ввиду писать оригинал в yml, а из него генерировать html/md (ну и txt можно, но зачем).
Видимо надо сделать пример, по-моему идея простая, но то-ли я как-то не так объясняю, то ли что.
Для редактирования я использую VScode, он не то что визуальный, но подсветка есть, мне хватает.

**Comment by FakelsHub** [comment]
Мне к примеру не комфортно писать в yml из-за дополнительной технической информации которую он содержит, поэтому нужна хорошая бесплатная прога для того чтобы отказать от записи в txt.

**Comment by phobos2077** [comment]
Формата проще чем yaml по-моему нет. Не должно быть большой проблемой дописывать в него новые функции, это все равно не часто происходит. А старые можно какими-нибудь регулярками перегнать. Я изначально так и делал для Sfall Script Editor. В любом случае иметь документацию в структурированном виде удобно, т.к. всегда легко перегнать всё разом в другой формат. Т.е. вернуться к старому формату можно будет в любой момент.

@burner1024 сделай пулл реквест с yaml + md документацией и напиши что нужно в travis прописать вместе с PR.

**Comment by burner1024** [comment]
Finally got to this. Please check out the [preview](https://bgforgenet.github.io/sfall/). The site is sourced from [this file](https://github.com/BGforgeNet/sfall/blob/better-docs/artifacts/scripting/doc.yml).

It's not quite complete yet, bits and pieces are missing, but I want to gather feedback before polishing. Thoughts, comments, suggestions?

**Comment by phobos2077** [comment]
@burner1024 Man this site looks amazing! :+1:

**Comment by FakelsHub** [comment]
Good.
Для Sfall funcX macros, нужно бы еще под категории сделать, чтобы не все скопом были.

**Comment by FakelsHub** [comment]
И еще самим названия функций цвет поменять на яркий, а то серый еле видно.

**Comment by burner1024** [comment]
Я думаю funcX macros просто распихать в соответсптвующие категории. Моддерам же неважно макрос это или нет, главное чтобы работало.
Все, что не попадает в выделенные категории. остается в Other.

Вот с дополнительным раскрашиванием посложнее, потому что это делают библиотеки (Rouge). Я назначил синтакс c++, кое-как он разбирает, но не все. Лучшим вариантом было бы сделать пулл реквест для поддержки SSL туда, но это я обещать не могу.

**Comment by FakelsHub** [comment]
не надо макросы тасовать, если трудно реализовать под категории, то тогда прямо на одной странице сделать разделение.
с подсветкой имени надо что-то сделать.

**Comment by FakelsHub** [comment]
если в html файле сделать обмен классов подсветки для названий (и ключевых слов с++) с `class="n"` на `class="kt"` то такие слова как int/void становятся серыми а названия красными. получается хороший контраст.
```
<div class="language-c++ highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="n">bool</span> <span class="kt">attack_is_aimed</span><span class="p">()</span>
```

**Comment by FakelsHub** [comment]
в сохраненном фале just-the-docs.js можно в ручную сразу для всего поменять цвета для классов.

**Comment by burner1024** [comment]
Насчет разделения, так или иначе, вся структура сайта должна быть описана в doc.yml. Так как именно ты предлагаешь это прописать?

Если макросы разбивать на отдельные подкатегории, то их будет 15 штук, и 12 из них будут повторять уже существующие - т.е. меню станет в два раза длиннее, и нужную функцию надо будет искать в двух местах вместо одного.
Мне непонятно, какой в этом смысл.

**Comment by FakelsHub** [comment]
Ок. А как это все работает, и взаимодействует, я что-то понять не могу.
Dark тему пробовал?

**Comment by FakelsHub** [comment]
А есть ли возможность добавить новые типы такие как ObjectPtr/string чтобы они не выделялись красным?

**Comment by burner1024** [comment]
Основа сайта в формате jekyll лежит [тут](https://github.com/BGforgeNet/sfall/tree/better-docs/docs). При пуше в выбранную ветку [Travis](https://github.com/BGforgeNet/sfall/blob/better-docs/.travis.yml) ее чекаутит, с помощью небольшой [магии](https://github.com/BGforgeNet/sfall/blob/better-docs/docs/yaml_to_md.py) [генерирует](https://github.com/BGforgeNet/sfall/blob/better-docs/docs/generate.sh) страницы из yaml, и пушит результат в ветку gh-pages. Гитхаб эту ветку публикует как сайт.

Темную тему не пробовал, классы подсветки инвертировал как ты предложил. Разбором синтаксиса занимается библиотека, так что легкого способа добавить новые слова скорее всего нет.

Сейчас есть небольшая проблема с функциями, у которых может быть разное количество аргументов, думаю как их лучше описать.

**Comment by FakelsHub** [comment]
*для макросов надо пометку сделать что это макрос.

**Comment by FakelsHub** [comment]
Чем ты форматируешь .md файлы, руками в браузере/netepad) или есть спец. софт под это?

**Comment by burner1024** [comment]
VScode.

**Comment by burner1024** [comment]
Страница макросов так и называется - макросы.

**Comment by burner1024** [comment]
* Added subcategory [possibility](https://bgforgenet.github.io/sfall/hook-functions/) for pages.
* [Formalized](https://github.com/BGforgeNet/sfall/blob/better-docs/artifacts/scripting/hooks.yml) hook types description as well, and added a separate [generated page](https://bgforgenet.github.io/sfall/pages/hook-types.html) for them.
* `doc.yml` is renamed to more sensible `functions.yml`. File format is simplified and [described in the comments](https://github.com/BGforgeNet/sfall/blob/better-docs/artifacts/scripting/functions.yml).

I'm ready to make a pull request. If you wish to customize the site further, rearrange functions in categories, you can easily do that without my help.

My only concern is that:
1. `functions.yml` and `hooks.yml` format is stable as agreed upon and doesn't change.
2. new information is properly added to these files with new Sfall releases.

That will allow for the updated documentation to be consumed automatically in [BGforge MLS](https://github.com/BGforgeNet/vscode-bgforge-mls).

**Comment by FakelsHub** [comment]
> I'm ready to make a pull request. If you wish to customize the site further, rearrange functions in categories, you can easily do that without my help.

Need to regroup the functions, "List" to move to "Array" as a sub-category.
In general, while there is a mess.

**Comment by burner1024** [comment]
> Need to regroup the functions, "List" move to "Array" as a sub-category.

Well, like I said, you will be able to do that.

**Comment by FakelsHub** [comment]
> - name: DeathAnim2
>   doc: |
>     Runs 

У меня что-то некоррекно показывается что за черточка возле doc: это какаято ссылка куда-то?

**Comment by burner1024** [comment]
В чем ты смотришь?

Палка говорит что текст который идет дальше, надо брать как есть, не проглатывая перенос линии. [Тут расписано.](https://yaml-multiline.info/)
В общем если текст многострочный то лучше ставить палку и не морочиться.

![Captura de pantalla de 2019-06-17 02-59-48](https://user-images.githubusercontent.com/1279852/59568901-1570cf00-90ac-11e9-8eaa-45532041c5e7.png)

**Comment by FakelsHub** [comment]
> В чем ты смотришь?

в браузере/notepad

а если смотреть на сайт то там появляется доп инфа `HOOK_WITHINPERCEPTION (hs_withinperception.int)` которой нет в raw формате это как получается?

**Comment by burner1024** [comment]
Ну ты поставь VScode-то.

> а если смотреть на сайт то там появляется доп инфа `HOOK_WITHINPERCEPTION (hs_withinperception.int)` которой нет в raw формате это как получается?
Тоже [скрипт](https://github.com/BGforgeNet/sfall/blob/c0632e3616d2699162236544a8476e0b38bf0d05/docs/yaml_to_md.py#L94) делает.

**Comment by FakelsHub** [comment]
> offset: 0x8170

Поменять слово offset на opcode можно?
и почему offset ни где не отображается?

**Comment by FakelsHub** [comment]
> Страница макросов так и называется - макросы.

get_explosion_damage - это макрос

**Comment by burner1024** [comment]
> Поменять слово offset на opcode можно?
> и почему offset ни где не отображается?

Все можно, поменял. Он и раньше нигде особо не отображался. Я даже не знаю, для чего он.

> get_explosion_damage - это макрос

Ну переставишь его в макросы, или как тебе нравится. Но мне кажется, люди больше ищут по теме, а макрос это или нет никому особо не интересно.

**Comment by FakelsHub** [comment]
> Он и раньше нигде особо не отображался.

Если это нельзя отобразить то тогда лучше удалить, чтоб не мешался..

**Comment by burner1024** [comment]
> Если это нельзя отобразить то тогда лучше удалить, чтоб не мешался..

Можно отобразить. Я не знаю, нужно ли. Но раз информация в репозитории была, то я ее систематизировал, как и все остальное. Я думаю, она не мешает, в любом случае.

По поводу подсветки, тема использует [Rouge](https://github.com/rouge-ruby/rouge), по идее там не очень сложно должно быть [добавить](https://github.com/rouge-ruby/rouge/wiki/Adding-a-new-lexer) новый лексер и заслать им пулл реквест для поддержки.

**Comment by FakelsHub** [comment]
Нее. Добавлением фичи в сторонний проект я точно заниматься не буду.

**Comment by burner1024** [comment]
Ну смотри сам.

**Comment by NovaRain** [comment]
The read_byte/int/short/string functions don't require enabling AllowUnsafeScripting now.

**Comment by burner1024** [comment]
> The read_byte/int/short/string functions don't require enabling AllowUnsafeScripting now.

In that case you will want to [separate them into subcategories and update the docs accordingly](https://github.com/BGforgeNet/sfall/commit/07b3b8103b8b53554b0f56d0b2c4711784914046).

I also added a [best practices](https://bgforgenet.github.io/sfall/best-practices/) page, hopefully you will be able to expand on that.

I think that will be all.

**Comment by burner1024** [comment]
To publish as a site:
* create "gh-pages" branch (doesn't matter from where, could be empty)
* In repo settings, find "Github Pages". Set source to gh-pages branch
* Create a secure github [token](https://help.github.com/en/articles/creating-a-personal-access-token-for-the-command-line)
* Sign up for [Travis](https://travis-ci.org/), add sfall repository there.
* In Travis repository settings, set GITHUB_TOKEN to the token you got earlier.

Then, assuming that you want to build documentation from master branch:
- merge pull request to develop and develop to master
- in `.travis.yml`, replace "better-docs" with "master"
- in `docs/_config.yml`, replace "BGforgeNet" with "phobos77".
- push to master.

I think that's all. If you have any trouble, let me know.

**Comment by FakelsHub** [comment]
Как перемечстить файлы md файлы в другой каталог чтобы это работало?

**Comment by burner1024** [comment]
Не понял, что ты хочешь сделать?

**Comment by FakelsHub** [comment]
[Тренируюсь на кошках.](https://github.com/FakelsHub/sfall-documentation)

**Comment by burner1024** [comment]
Ну вроде все правильно сделано, директории только в .travis.yml и generate.sh прописаны.

**Comment by FakelsHub** [comment]
Ну я не нашел в крипте где поменять путь к mв там какой-то `pages_dir="pages"` указан

**Comment by FakelsHub** [comment]
> In Travis repository settings, set GITHUB_TOKEN to the token you got earlier.

Там такого нет, т.е. он туда не пишется, там уже записан какой-то токен, и его можно только скопировать.

**Comment by burner1024** [comment]
pages_dir это и есть, туда складываются сгенерированные страницы. (Написанные руками лежат в корне сайта).

Вот скрин для токена

![Captura de pantalla de 2019-06-19 23-42-12](https://user-images.githubusercontent.com/1279852/59784168-024c4200-92ec-11e9-87f3-ecd8d87dd330.png)

**Comment by FakelsHub** [comment]
> (Написанные руками лежат в корне сайта).

вот как изменить чтобы брал из другой папки

**Comment by burner1024** [comment]
Все md файлы должны лежать внутри сайта (там где _config.yml). Где именно - неважно, jekyll их сам найдет. Т.е. написанные руками можно сложить в подпапку scr/manual, будет то же самое.
Для генерированных я выделил подпапку pages, чтобы не путаться.

**Comment by FakelsHub** [comment]
что указать где искать нельзя?

**Comment by FakelsHub** [comment]
`md_path = os.path.join(md_dir, "hook-types.md")`
Тут можно изменить путь на ?
`md_path = os.path.join(md_dir, "..\docs_ru\hook-types.md")`

**Comment by burner1024** [comment]
> `md_path = os.path.join(md_dir, "hook-types.md")`
> Тут можно изменить путь на ?
> `md_path = os.path.join(md_dir, "..\docs_ru\hook-types.md")`

Можно. Но это только генерация md из yaml. А вот html из md генерирует Jekyll.

> что указать где искать нельзя?

Честно говоря, я не знаю, не могу найти как.
Зачем это нужно-то?

**Comment by FakelsHub** [comment]
Да просто чтобы лежали в дном месте.

**Comment by burner1024** [comment]
Можно в generate.sh добавить `cp ../docs_ru/*.md .` перед запуском jekyll.

**Comment by FakelsHub** [comment]
```
0.01s$ ./scr/generate.sh
/home/travis/.travis/functions: line 104: ./scr/generate.sh: Permission denied
The command "./scr/generate.sh" exited with 126.
```

Что-то не так. Ваши коментарии)

**Comment by burner1024** [comment]
`chmod +x src/generate.sh` ?

Если ты хочешь сайт с русифицированной документацией, то ее наверное можно в этот же репозиторий добавить, и генерировать паралельно. Хотелось бы, чтобы был один авторитетный источник, а то пойдут расхождения...

**Comment by FakelsHub** [comment]
В [generate.sh](https://github.com/FakelsHub/sfall-documentation/blob/master/scr/generate.sh) ничего не менял кроме пути папки к yml

**Comment by burner1024** [comment]
Я имею ввиду, судя по всему он у тебя не исполняемый.
```
ls -l scr/generate.sh 
-rw-r--r-- 1 adm admi 258 jun 20 00:27 scr/generate.sh
$ chmod +x scr/generate.sh 
$ ls -l scr/generate.sh 
-rwxr-xr-x 1 adm adm 258 jun 20 00:27 scr/generate.sh
```

**Comment by FakelsHub** [comment]
Ниче не понял. Че оно не Build-дится.

**Comment by burner1024** [comment]
У тебя же windows? Посмотри [тут](https://stackoverflow.com/questions/21691202/how-to-create-file-execute-mode-permissions-in-git-on-windows).

**Comment by FakelsHub** [comment]
Тут у нас у всех Windows.

**Comment by burner1024** [comment]
Ну ты разобрался?

**Comment by FakelsHub** [comment]
нет, мне эти команды не понятны, я не использую терминалы/командную строку.
те. это(скрипт) еще и долно исполняться на локальной машине а не где-то там на серверах?

**Comment by burner1024** [comment]
Исполняется на серверах. Но у скрипта должно быть выставлено разрешение на исполнение.
В твоем git клиенте что-то такое должно быть наверняка.
Ну или можешь мне дать доступ в репозиторий я поправлю.

**Comment by FakelsHub** [comment]
Просто добавить в Collaborators?

**Comment by burner1024** [comment]
да

**Comment by FakelsHub** [comment]
добавил

**Comment by burner1024** [comment]
готово

**Comment by FakelsHub** [comment]
ok

**Comment by FakelsHub** [comment]
тебе лог видно?
```
rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl
Successfully installed dpl-1.10.11
1 gem installed
invalid option "--github_token="
failed to deploy
```

**Comment by burner1024** [comment]
Маловато разрешений токену может дал? 
![Captura de pantalla de 2019-06-20 03-26-02](https://user-images.githubusercontent.com/1279852/59797930-2d925980-930b-11e9-8d8f-a4ab9d58ba67.png)

**Comment by FakelsHub** [comment]
все галки стоят

**Comment by burner1024** [comment]
Environment Variables

**Comment by burner1024** [comment]
В общем я туда подставил свой токен и все сбилдилось. Так что у тебя с этим проблема.

**Comment by FakelsHub** [comment]
Куда ты поставил токен?

**Comment by burner1024** [comment]
Это переменная окружения. Ты можешь ее удалить и создать заново, подставив свой.

**Comment by FakelsHub** [comment]
Ты туда вставляешь строку GITHUB_TOKEN?

**Comment by FakelsHub** [comment]
У тебя стоит в разрешение только та одна галочка?

**Comment by FakelsHub** [comment]
Епрст. Надо было написать в инструкции, что сгененерированый код вставлять. А Travis тупой принимает пустое поле.
Теперь мой токен используется.

**Comment by FakelsHub** [comment]
Тут новая проблема, [сайт]( https://fakelshub.github.io/sfall-documentation/) не работате.

**Comment by FakelsHub** [comment]
Добавь в скрипт чтобы делал иакие лайблы, это пометка для макросов.
https://pmarsceill.github.io/just-the-docs/docs/ui-components/labels/
макрос get_explosion_damage верни обратно этоn макрос не относится к FucnX

**Comment by FakelsHub** [comment]
I made all the labels.
I will do some more formatting for .md files, then rearrange the functions, and you can take the files back to you.

**Comment by burner1024** [comment]
Надо в fucntions.yml размечать тогда, где макросы а где нет.

**Comment by FakelsHub** [comment]
Я уже пометил, они только в разделе Explosion

**Comment by FakelsHub** [comment]
Кстати некоторые ссылки некорректны, например зайди в Hooks и проверь.

**Comment by burner1024** [comment]
Скопировал, поправил там несколько опечаток.

**Comment by Lexx2k** [comment]
Is it possible to add some sort of comment function or similar to the page? This way we could add notes / point stuff out that should be tweaked, reworked, or just precised. There have been a few moments already where stuff confused me while in the end it was pretty simple and obvious. Or just a way to add more code examples as explanations.

**Comment by burner1024** [comment]
> Is it possible to add some sort of comment function or similar to the page? This way we could add notes / point stuff out that should be tweaked, reworked, or just precised. There have been a few moments already where stuff confused me while in the end it was pretty simple and obvious. Or just a way to add more code examples as explanations.

Easy enough to add with disqus or something like that, but... where'd you seen open source docs with comments? I hadn't, and I think the reason is that's not an efficient way to work on software docs. You can't _track_ a comment, you can't _resolve_ a comment. And they stay there forever. It's gonna turn into a pile of garbage after a while.
Anyone who wants to improve the docs can submit a pull request, anyone who thinks they are unclear or imprecise can open an issue about it.

**Comment by FakelsHub** [comment]
Кажется это не работает.

**Comment by burner1024** [comment]
запустится когда в мастер смерджится

**Comment by FakelsHub** [comment]
Я бы предложил парсить сразу изначальный txt и делать из него md.
 т.к. это двойная работа пиши в txt потом в yml (который еще содержит не всю информацию из txt)

**Comment by burner1024** [comment]
txt ты не распарсишь, потому yml и нужен. А txt надо просто выбросить.

**Comment by FakelsHub** [comment]
как это нераспарсить, ерунду неговорите, там есть немнжко разметки, еще добавить и можно без проблем парсить)

**Comment by burner1024** [comment]
Так уже добавили немножко, получился yml.
Я не вижу смысла поддерживать txt, но если кому-то хочется, то мне тоже дела нет.

**Comment by FakelsHub** [comment]
Кстати "сайт" так и не работает, вернее работает, но отображает какие-то синие полосы на весь экран и сверху в левом углу гиперсссылка и текстом "sfall".
В твоем форке сайт фурычит... что-то ты там не доделал.

**Comment by FakelsHub** [comment]
![2021-07-03_00-33-36](https://user-images.githubusercontent.com/21695363/124330807-d597ba00-db96-11eb-860f-353a50d69d48.png)

**Comment by NovaRain** [comment]
Yup, it's a known issue. phobos said he'll check what's wrong later.

**Comment by FakelsHub** [comment]
this is not a problem in phobos, because I have the same thing in the repo.

**Comment by FakelsHub** [comment]
Удалить нужно все что связано с **CNAME** файлом и установить правильный базовый путь.

**Comment by NovaRain** [comment]
> 
> 
> Удалить нужно все что связано с **CNAME** файлом и установить правильный базовый путь.

Oh, OK, now it works, thanks.

**Comment by FakelsHub** [comment]
Set the link (on the right on the main page) to the site pages.

**Comment by FakelsHub** [comment]
И небольшая проблема: Не отображаются стрелочки раскрытия вложености.

**Comment by NovaRain** [comment]
> 
> 
> Set the link (the right on the main sfall page) to the this site pages.

I don't have the permission to change that section. I already notified phobos, so he may update it later.
