### ISSUE TITLE
3.8.14 - broken skill points allocation

### ISSUE THREAD

**Issue by GithubDG** [phobos2077/sfall#226]
Using Fallout 2 (GOG) + RP 2.3.3
With this version of sfall Skill points allocation upon levelling is totally broken - spending 1 point reduces the "total available amount" by 6, trying to remove this assigned point "returns" only 1.

Tried with existing game (and save), totally new game, new character - behavior is the same.
![skillpoints_1](https://user-images.githubusercontent.com/33484270/51084846-efc45000-1730-11e9-9b40-c3a3bad02cdb.jpg)
![skillpoints_2](https://user-images.githubusercontent.com/33484270/51084847-f05ce680-1730-11e9-985f-3e77bc369f73.jpg)
![skillpoints_3](https://user-images.githubusercontent.com/33484270/51084848-f05ce680-1730-11e9-80d6-42ed83ded020.jpg)

Screenshots are taken with a Save made with Editor (changed level), but the idea stays the same for non-edited saves (I caught the bug first on my normal non-edited Save game)

**Comment by NovaRain** [comment]
The same issue also happens on 4.1.4, looks like something went wrong during the code refactoring.

**Comment by FakelsHub** [comment]
in the process...

**Comment by NovaRain** [comment]
Thanks for reporting the issue. It's fixed now, and the hotfix versions (3.8.14.1/4.1.4.1) are released.
