### ISSUE TITLE
A hotkey to center screen on dude

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#23]
As it have been pointed out to me, Home key can do that. But unfortunately, I don't have it (I'm on macbook). I'm really missing it, though. Not sure if many people would need that, but an option to reassign this key would be nice.

**Comment by phobos2077** [comment]
That's ridiculous, seriously :) If your exotic keyboard misses Home key, I'm sure there should be some combination to compensate for it (like Fn+H or something..)

**Comment by burner1024** [comment]
Actually, returning to this - what do you think of generic key reassignment? So that vanilla hotkeys can be changed?

**Comment by phobos2077** [comment]
It is possible, but tedious as keys are spread across entire code and they use type char for them (indistinguishable from regular numbers - difficult to track down).

**Comment by burner1024** [comment]
I see. Thank you for elaborating.

**Comment by phobos2077** [comment]
You can create another issue for this. Maybe someone will be so kind to implement it in future :)
