### ISSUE TITLE
set_fake_perk & set_selectable_perk

### ISSUE THREAD

**Issue by FakelsHub** [phobos2077/sfall#230]
> **set_fake_perk** can be used to add additional perks to the character screen. They will be saved correctly when the player saves and reloads games, but by themselves they will have no further effect on the character. For perks, the allowed range for levels is between 0 and 100; setting the level to 0 removes that perk.
> 
> **set_selectable_perk** can be used to add additional items by setting the 'active' parameter to 1, and to remove them again by setting it to 0.

`set_fake_perk (string name, int level, int image, string desc);`
`set_selectable_perk (string name, int active, int image, string desc);`
What is the difference between these two functions, I can not understand something?

**Comment by NovaRain** [comment]
I didn't use them so it's pretty much a guess: from the code it seems one can have multiple levels and one is only toggleable single level. Timeslip only used set_selectable_perk in her sample trait/perk mod.

**Comment by FakelsHub** [comment]
I'm trying to understand the algorithm in the code. And I can not understand why set_fake_perk is needed.

**Comment by NovaRain** [comment]
Well, as long as they aren't bugged I'd just leave them be. It's not the only case that one function can do pretty much the other one can.

**Comment by FakelsHub** [comment]
I'm not going to delete them. I am making an extension for perks, so I'm trying to understand the meaning between fakePerks and fakeSelectablePerks. :-)

**Comment by nirran** [comment]
as far as i know,set_fake_perk bypasses the select screen and give the amnt of the perk to the player.
and set_selectable_perk sets the perk selectable,at least from looking at my perks script shows this

**Comment by FakelsHub** [comment]
Yes, that is right.
