### ISSUE TITLE
more then 255 maps in map.txt

### ISSUE THREAD

**Issue by nirran** [phobos2077/sfall#231]
as of now megamod is close to max,i know the mapper would have to be altered to,is it possbile?

edit : if it is possible,may as well do the same for city.txt

**Comment by nirran** [comment]
if it is possible,may as well do the same for city.txt

**Comment by FakelsHub** [comment]
You added a 256 maps? what error is shown?
There are no restrictions for cities.

**Comment by nirran** [comment]
i havent,i am assuming it is max FF,am i wrong?

**Comment by nirran** [comment]
ill repost this after i confirm an error,my bad

**Comment by FakelsHub** [comment]
if there is an error, then show the screenshot with this error.

**Comment by nirran** [comment]
this ddraw.dll does exactly what i was refering to ty Stalin
https://github.com/phobos2077/sfall/issues?q=is%3Aissue+is%3Aclosed

**Comment by nirran** [comment]
confirmed,sfallM fixes the 255 limit for maps,set map #'s 256 and 257 linked and it works

**Comment by FakelsHub** [comment]
there is a limit of 1000
