### ISSUE TITLE
Taken Perks

### ISSUE THREAD

**Issue by FakelsHub** [phobos2077/sfall#234]
There is a difference when taking perks when there are several not taken perks
in v3 - you can take several levels of perk at one once.
in v4 & Сrafty - you can take only one level of perk.
I can not understand which variant is correct)

I am inclined that v3 is correct. but how does it work in vanilla game (w/o sfall)?

**Comment by NovaRain** [comment]
> I am inclined that v3 is correct. but how does it work in vanilla game (w/o sfall)?

I think you mean if player has multiple unused perks, in 3.x he doesn't have to exit/open the character screen to pick another one?
I'd say none of them are "correct", since it's sfall that added the ability to accumulate unused perks. In vanilla if you don't pick a perk before next 3/4 levels, you lose that chance of picking perks.

**Comment by FakelsHub** [comment]
No, in v3 you can take several levels for one perk, while in v4 only 1 level.

**Comment by NovaRain** [comment]
> 
> 
> No, in v3 you can take several levels for one perk, while in v4 only 1 level.

OK, now I'm not sure what you really mean.

**Comment by FakelsHub** [comment]
in v3, player level 6, you can take two levels of perks.
In v4, you can also take two perks but different perks.

**Comment by NovaRain** [comment]
> 
> 
> in v3, player level 6, you can take two levels of perks.
> In v4, you can also take two perks but different perks.

Here's how I tested:
I start a new game with an all-10 character and use script to give me enough xp to level 8. I open the character screen, pick "Bonus HtH Damage", and click Done. The perk window pops up again and I can pick "Bonus HtH Damage (1)". This works for both 3.8.17 and 4.1.7.

**Comment by FakelsHub** [comment]
Try to take perk education, with the condition of 6 level player.

**Comment by NovaRain** [comment]
> 
> 
> Try to take perk education, with the condition of 6 level player.

It works the same for the Educated perk (pick the first level, perk list reappears, pick the second level)
And for some reason it seems I can't reproduce the "+2 skill points don't apply to current level" issue. I always get additional skill points right after picking it.

**Comment by FakelsHub** [comment]
Strange today after the system has been rebooted, this bug is gone,
as well as a glitch with a perk educated.

**Comment by NovaRain** [comment]
> 
> 
> Strange today after the system has been rebooted, this bug in v4 is gone,
> as well as a glitch with a perk educated.

I tested both 3.8.17 and 4.1.7 on at least two different PC, and didn't have the issues. Maybe it's related to some processor+OS combination? (like how processor handles the instructions)

**Comment by FakelsHub** [comment]
It is possible that this was affected by the previously launched IDA debugger. There were some problems with this.
