### ISSUE TITLE
Enabling ExtraKillTypes breaks get_kill_counter

### ISSUE THREAD

**Issue by nirran** [phobos2077/sfall#235]
this function is broken with 4.1.7,does not increment when killing ants in temple,the bug is also present in 4.1.5,to verify the bug,download these files into fo2 folder 

the in game spam is  :
ant extra x -> if extra kills are selected in ddraw.ini
ant inc x -> the tracking kills global(should go up with any ant kill)
ant extra count x -> sfall get_kill_counter return
ant vanilla count x -> vanilla kill counter return

[XPMaster.zip](https://github.com/phobos2077/sfall/files/3124490/XPMaster.zip)

**Comment by NovaRain** [comment]
I started a new game and killed a giant ant in the temple. The message is:
```
ant extra 0
ant inc 1
ant extra count 1
ant vanilla count 1
```

**Comment by nirran** [comment]
hmm,ill recheck

**Comment by NovaRain** [comment]
It seems the problem happens with ExtraKillTypes=1. Enabling the option the message is:
```
ant extra 1
ant inc 0
ant extra count 0
ant vanilla count 1
```

**Comment by nirran** [comment]
yea,thats the bug,sfall function doesnt register
thnx

**Comment by FakelsHub** [comment]
> Looks like the refactoring in 4.1.4 is the cause, testing with 4.1.3 and the message is all 1.

How does it work in 4.1.3 if it is only added in 4.1.4? :P
https://github.com/FakelsHub/sFall-Extended/commit/115442e5b9e64ea863c3a9a2ba43c1f6d50e57d2#diff-2825a9e31efc20c96d1642185c74272b

**Comment by NovaRain** [comment]
> 
> 
> > Looks like the refactoring in 4.1.4 is the cause, testing with 4.1.3 and the message is all 1.
> 
> How does it work in 4.1.3 if it is only added in 4.1.4? :P
> [FakelsHub@115442e#diff-2825a9e31efc20c96d1642185c74272b](https://github.com/FakelsHub/sFall-Extended/commit/115442e5b9e64ea863c3a9a2ba43c1f6d50e57d2#diff-2825a9e31efc20c96d1642185c74272b)

well, because the ExtraKillTypes was not actually available for sfall 4.x before 4.1.4. So they didn't have the problem. :P
