### ISSUE TITLE
Ddraw misc section

### ISSUE THREAD

**Issue by FakelsHub** [phobos2077/sfall#236]
I propose to begin to separate the Misc section into several categories, to make 3-4 sections of it.
I have plans to add a module/class for reading from ddraw in one pass, but for this it is desirable that the section is not so big.
(although I think that you can write your own reading function in order not to use winapi, then the partitioning of the section will not be necessary.)

While I propose to make the section [Fixes] and move there all the fixes.

**Comment by FakelsHub** [comment]
arraysBehavior - can be safely moved to [Scripts]

**Comment by NovaRain** [comment]
And what about the backward compatibility?

**Comment by FakelsHub** [comment]
I think that the little-used options can be transferred, then the transition process will not be so sick.

**Comment by NovaRain** [comment]
> 
> 
> I think that the little-used options can be transferred, then the transition process will not be so sick.

I think it's also a good time to review if some options are really needed.

**Comment by FakelsHub** [comment]
SingleCore
OverrideArtCacheSize
Can move to System or Main section.

**Comment by NovaRain** [comment]
Guess we should decide what new sections are needed first.

**Comment by FakelsHub** [comment]
I think for now can just move minor options.
And I would like moved the all fixes to the Fixes section.

**Comment by NovaRain** [comment]
> 
> 
> I think for now can just move minor options.
> And I would like moved the all fixes to the Fixes section.

For fixes I'd think these:
DialogueFix, TownMapHotkeysFix, SaveInCombatFix, CorpseLineOfFireFix, AIBestWeaponFix, AIDrugUsePerfFix, BonusHtHDamageFix, FastShotFix, ObjCanSeeObj_ShootThru_Fix, ObjCanHearObjFix, StartGDialogFix, StartGDialogFix, AttackComplexFix, CanSellUsedGeiger, CarChargingFix, PartyMemberSkillFix.

For NPCStage6Fix there was a [discussion](http://www.nma-fallout.com/threads/fo2-engine-tweaks-sfall.178390/page-79#post-3768655) about whether "only 5 stages for NPCs" is a bug or a cut feature.

**Comment by FakelsHub** [comment]
CanSellUsedGeiger -not fix, (должна была назваться по другому CanSellUsedItems )

**Comment by NovaRain** [comment]
I think it would be better to post the plan of options re-organization on NMA before actually starting the whole thing, like Timeslip did for sfall 2.8.

**Comment by phobos2077** [comment]
We shouldn't move/rename any existing options unless there is some upgrade mechanism or instructions. People usually just extract and replace DLL only so they don't lose their tweaks.

Ideally we should have a tool for automated reorganizing of ddraw.ini without losing setting values and an installer that will run this tool automatically.

**Comment by FakelsHub** [comment]
I myself have no desire to moved options, but when everything placed into one section it is bad.
There is such a tool, sfall configurator, it has the option to load and save settings from another ini.
I would move less used options for now.

**Comment by FakelsHub** [comment]
AIBestWeaponFix, AIDrugUsePerfFix, ObjCanHearObjFix, StartGDialogFix, AttackComplexFix, PartyMemberSkillFix.
These options can be moved, because these are new fixes and practically unused.

**Comment by FakelsHub** [comment]
AIBestWeaponFix, AIDrugUsePerfFix, ObjCanHearObjFix, StartGDialogFix, AttackComplexFix, PartyMemberSkillFix.
These options can be moved, because these are new fixes and practically unused.

**Comment by NovaRain** [comment]
>when everything placed into one section it is bad.

Other than looks cluttering up, what's bad about it?
You said you want to read the whole ini in one pass, what's the benefit? Speeding up the initialization time? Is there any case that the current build is noticeably slow?

**Comment by FakelsHub** [comment]
I mean, read the entire section at a time, the winapi function has a limit on the 32k character buffer, of course the misc section is not that big. Maybe some options and should not be moved.
There is essentially no benefit, just to improve the code.
No problem with speed.

**Comment by NovaRain** [comment]
> I mean, read the entire section at a time, the winapi function has a limit on the 32k character buffer, of course the misc section is not that big. Maybe some options and should not be moved.
There is essentially no benefit, just to improve the code.
No problem with speed.

Wait, 32k char buffer? I remove all comments and all 176 options in [Misc] only takes about 3.3k with their default settings. Seems to me it's not even a problem worth worrying about before all of us stop maintaining sfall.

**Comment by phobos2077** [comment]
> I myself have no desire to moved options, but when everything placed into one section it is bad.
> There is such a tool, sfall configurator, it has the option to load and save settings from another ini.
> I would move less used options for now.

I agree with NovaRain. Either we make auto-converter first and then reorder everything properly, or we leave existing options where they were originally at release. Otherwise **somebody** will have a bad day because his mod would suddenly stop working as intended because of how we care for our code not "being bad".

**Comment by FakelsHub** [comment]
An example of compatibility support without using the auto-converter tool.
```
RetryCombatMinAP = GetConfigInt("CombatAI", "NPCsTryToSpendExtraAP", -1);
if (RetryCombatMinAP == -1) RetryCombatMinAP = GetConfigInt("Misc", "NPCsTryToSpendExtraAP", 0); // compatibility older versions
```

**Comment by FakelsHub** [comment]
```
SingleCore
OverrideArtCacheSize
ProcessorIdle
ConsoleOutputPath
arraysBehavior
```
so what about moving these non-gaming options?

**Comment by NovaRain** [comment]
> so what about moving these non-gaming options?

To be honest, so far I still don't see the valid reason of moving existing options without an auto-converter first. It doesn't seem like about code readability, maintainability, or performance other than making code/ini look "good". Even you said there's no benefit in doing this.
