### ISSUE TITLE
Division by zero when multiplying

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#242]
[Apparently](http://nma-fallout.com/threads/random-questions.207953/#post-4206114), `(x*0)` spits a "division by zero" error, while `0*x` works.
Not a big issue, but it's hard to keep track of all variables values at all times.
Any chance it will be fixed?

**Comment by FakelsHub** [comment]
Ну вы гении математики, зачем умножать на 0?

**Comment by burner1024** [comment]
Наверное чтобы 0 получить.
Конкретно сейчас я ванильные скрипты компилирую, а там такого добра навалом, как оказывается.

**Comment by NovaRain** [comment]
Yeah, I was fixing those error in UP scripts this afternoon while testing Watcom C.

**Comment by burner1024** [comment]
Did you finish? I got through a few, but there's no telling how many there are, it's defines within defines within defines... But the scripts are in fact valid, if badly written.
So I thought it's better to report it.

**Comment by NovaRain** [comment]
Nope, I just fixed a couple of them before getting off from work.

**Comment by FakelsHub** [comment]
Why fix scripts if you need to fix the root of the problem.

**Comment by NovaRain** [comment]
Older versions (pre-3.6) of the compiler don't really check if division by zero during compilation. They just let it pass and the script will fail with `Error during execution: Division (MOD) by zero` in debug log by the engine.
I think adding `(i == '/' || i == '%') &&` to the second `if` condition in term_prime in parse.c should be enough, or just remove the check and let the engine handle the error.

**Comment by burner1024** [comment]
> I think adding `(i == '/' || i == '%') &&` to the second `if` condition in term_prime in parse.c should be enough, or just remove the check and let the engine handle the error like before.

Where's this `parse.c` you're talking about?

**Comment by NovaRain** [comment]
> 
> Edit: found it in modderspack. Don't understand why is it not in the repo, though.

AFAIK sslc doesn't have a proper license, so we didn't put it in a repo. Of course Bethesda (as the current owner of the right) probably won't care about that.

**Comment by burner1024** [comment]
I don't see much difference, if the code is still available in modderspack releases.
Anyway, was it ever compiled under linux?

**Comment by NovaRain** [comment]
> 
> 
> Anyway, was it ever compiled under linux?

Nope, but you can try.

**Comment by NovaRain** [comment]
Closed because the error on script and compiler sides are both fixed,
