### ISSUE TITLE
Optimization seems to be a bit too agressive

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#243]
Trying to compile ncangbis.ssl from UP, sslc drops Node104 (both -O1 and -O2 modes):
```
wine ~/bin/compile.exe -p -l -O1 -d NCANGBIS.SSL | grep Node104
[Message] <NCANGBIS.SSL>:731:24: Eliminating procedure Node104
[Message] <none>:-1: Removing unused string 'Node104' from program namespace
```
But it's called in [force_dialog_start](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/e674fd65b754c37df00f4af197f1d2997bc05bd5/scripts_src/NEWRENO/NCANGBIS.SSL#L143):
```
 force_dialog_start("Node104");
```

This isn't intended behaviour, is it?

**Comment by NovaRain** [comment]
In the decompiled NCANGBIS.int Node104 is still there, I guess it's just the debug output is incorrect.

**Comment by burner1024** [comment]
Are you sure? This doesn't seem to be the case for me:
[1.zip](https://github.com/phobos2077/sfall/files/3350056/1.zip)

**Comment by NovaRain** [comment]
You're right, I forgot I disabled the optimization switch in P.BAT in my work folder.

**Comment by burner1024** [comment]
Or use "@Node104", right? That's what [stringify](http://www.nma-fallout.com/threads/improved-scripting-tools-ssl-and-script-editor.203003/) is for?

I'm concerned that there could be other similar macros, and I'm not sure how to search for them. I found this one just by accident.

Also, does this mean that optimization is officially vanilla incompatible? (As is short-circuit?)

**Comment by NovaRain** [comment]
> 
> Or use "@Node104", right? That's what [stringify](http://www.nma-fallout.com/threads/improved-scripting-tools-ssl-and-script-editor.203003/) is for?
> 

I removed my previous edits since the test I did was a rushed job. The stringify should work since phobos especially mentioned about the issue with optimizer.

**Comment by NovaRain** [comment]
Hmm, maybe it's not. I made a test global script with keypress hook:
```
#include ".\HEADERS\DEFINE.H"
#include ".\HEADERS\COMMAND.H"
#include ".\headers\sfall.h"
#include ".\HEADERS\define_extra.h"
#include ".\headers\dik.h"

variable xnode;

procedure start;
procedure KeyPressHandler;
procedure NodeTest;

procedure NodeTest begin
   display_msg("Node Test!");
end

procedure KeyPressHandler begin
   variable
      event := get_sfall_arg,
      keyDX := get_sfall_arg;

   if (keyDX == DIK_V) then begin
      if event then begin
         xnode := @NodeTest;
         call xnode;
      end
   end
end

procedure start begin
   if game_loaded then begin
      register_hook_proc(HOOK_KEYPRESS, KeyPressHandler);
   end
end
```
I compiled two versions with and without the optimization, while in both decompiled scripts NodeTest is untouched, only the unoptimized one prints the message in game when pressing V key, the optimized one generates `Error during execution: Couldn't find string procedure NodeTest` in debug.log.

**Comment by burner1024** [comment]
Hmm, I get identical scripts (non-working version) both with and without optimization.

**Comment by NovaRain** [comment]
I think it's better to test the stringify operator in vanilla scripts to see if the procedures really work.

**Comment by burner1024** [comment]
`force_dialog_start(@Node104);` seems to do the trick for ncangbis.ssl.

I'm not quite clear, though - what's the expected behaviour here?

**Comment by FakelsHub** [comment]
It is just that the compiler does not delete the unused procedure, because it sees that its only call through a string variable is marked with the symbol '@'

**Comment by burner1024** [comment]
I'm referring to the whole situation. Just to be clear, do I understand correctly that:
1) Behaviour described in the first post is not a bug, it's a feature.
2) Optimization is not supposed to be vanilla compatible.
3) Short-circuit is also not supposed to be vanilla compatible.

and

4. Still, "@" operator appears to not work in a global script (checked with @NovaRain's script), with or without optimization. Do you confirm, and if yes, is that a bug or a feature?
5. Any idea how to check whether there are other macros like this?

**Comment by phobos2077** [comment]
1. It's not a feature and not a bug, just the way optimization works. Original FO compiler didn't have any optimization like that, so it was OK to reference procedures by names. I believe Timeslip (or somebody else) added all these optimizations for fun. I spent some time fixing them.
2. It seems to be so. Removal of unused procedures is the most basic form of optimization there is.
3. Yes because the same code works differently in some cases. It might work for most scripts though, if they don't rely on side-effects of functions being called in conditions. But you can't be sure without studying every line of code.
4. What do you mean "not work"? This operator was added to track references to functions in a string form. It's useful by both compiler (as you know) and for parser (to show usages in Script Editor).
5. Any function/macro that accepts function name and if it's the only way this function is referenced in a script - will lead to this issue. If I remember correctly most code like dialog lines reference node procedures directly, not as strings?

**Comment by FakelsHub** [comment]
Vanilla scripts, I would compile without optimizations.

**Comment by burner1024** [comment]
2. Other than this particular issue, is there any other reason why optimization would be incompatble? (Supposing that such scripts are found and fixed, would that be enough?)


 4) I mean
```
Current script: scripts\gl_nodetest.int, procedure KeyPressHandler
Error during execution: Couldn't find string procedure NodeTest
```
[gl_nodetest.zip](https://github.com/phobos2077/sfall/files/3352109/gl_nodetest.zip)

5. I think you are right about direct referencing. I understand what will lead to the issue. I was hoping for an idea how to identify such scripts.

**Comment by FakelsHub** [comment]
Found a bug.
The last procedure in the script is not checked, and in the script after compiling NodeTest is the last one (by alphabet seems).
By the way, you have a bad habit of placing procedures in reverse order. (it is visible from s / s ++).

**Comment by burner1024** [comment]
so what about 2)?

**Comment by NovaRain** [comment]
Since the problem of UP/RP scripts with optimization is solved in their repos, I think this issue can be closed.
