### ISSUE TITLE
critter_mod_skill can't handle odd numbers with tagged skills

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#244]
It seems to be rounding down to the nearest even number. Example is punching bags in SAD. With Unarmed tagged, you get +4 instead of +5.

**Comment by FakelsHub** [comment]
That's right!

**Comment by burner1024** [comment]
Я так понял на дисплее пишет +5, а на самом деле +4 дает.

**Comment by NovaRain** [comment]
critter_mod_skill adds "raw skill points" (raw values in F12se) to match the actual skill increment requested. So for +5% for a tagged skill, it's impossible to add "2.5" raw points to match "+5%".

**Comment by burner1024** [comment]
I had an alternative in mind - "reverse calculate" the cost and set_critter_skill_points instead. It's going to be longish, thought. Is there a simpler way?

**Comment by NovaRain** [comment]
* Skill level = base_skill_level (calculated from SPECIAL stats) + raw_skill_points * skillMultipiler (always 1 unless modified by skill.ini) + raw_skill_points (if the skill is tagged)

set_critter_skill_points manipulate the "raw_skill_point" field. I don't think it would work for "+odd % for tagged skills".

**Comment by burner1024** [comment]
We could drop one bag and make the other give +10.
But then there's Prizefighter and San Franciso training, I suppose they suffer from the same?

**Comment by NovaRain** [comment]
> 
> 
> We could drop one bag and make the other give +10.
> But then there's Prizefighter and San Franciso training, I suppose they suffer from the same?

Yes, the same case (tagged skills receive 1% less than untagged) happens on all `critter_mod_skill(dude_obj, skill, odd_num)`. I'd take "+1% more for tagged skills" for those cases.

**Comment by burner1024** [comment]
I think it's more about the discrepancy, when display says one thing, and in fact it's the other.
Maybe just drop "5%" and simply say the skill was increased.

**Comment by NovaRain** [comment]
> Maybe just drop "5%" and simply say the skill was increased.

That's also a good solution IMO.

**Comment by burner1024** [comment]
let's go with that, then
