### ISSUE TITLE
What does modified_ini actually do?

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#245]
Can't find any explanation.

**Comment by NovaRain** [comment]
It just simply returns the value of `ModifiedIni` setting in [Main] section of the INI.

**Comment by burner1024** [comment]
It seems to be removed from the latest ddraw.ini. What's its purpose, anyway?

**Comment by NovaRain** [comment]
> 
> 
> It seems to be removed from the latest ddraw.ini. What's its purpose, anyway?

Actually it's never been in default INI.
RP uses it to check/warn if people overwrite RP's ddraw.ini with default one by accident. You can check glmodini.ssl for that.

**Comment by burner1024** [comment]
Yes, that's how I came to find it. I'm not sure what to do about it, maybe just drop that script.

**Comment by NovaRain** [comment]
> Yes, that's how I came to find it. I'm not sure what to do about it, maybe just drop that script.

I think you can choose to annoy/warn people with the big red text, or let them post "bug reports" about something _broken_ because they use default INI.

**Comment by burner1024** [comment]
Right... let it be, then. Thank you.

**Comment by burner1024** [comment]
There's probably no need for a separate opcode, it can just as well be get_ini_setting.
And maybe RP should check for something more meaningful, like ElevatorsFile or WorldMapSlots.

**Comment by NovaRain** [comment]
The opcode won't go away since it's been existed for a long time. But of course you can add more checks on INI settings in RP's global script to ensure key settings are unaltered.
