### ISSUE TITLE
Calling key_pressed in KEYPRESS hook has no effect since 4.1.2

### ISSUE THREAD

**Issue by NovaRain** [phobos2077/sfall#248]
Using a test script like this:
```
#include ".\headers\sfall.h"
#include ".\headers\dik.h"

procedure start;
procedure KeyPressHandler;

procedure KeyPressHandler begin
   variable
      event := get_sfall_arg,
      keyDX := get_sfall_arg,
      tmp;

   if key_pressed(DIK_V) then begin
      display_msg("Pressed V key: " + key_pressed(DIK_V));
   end
end

procedure start begin
   if game_loaded then begin
      register_hook_proc(HOOK_KEYPRESS, KeyPressHandler);
   end
end
```
With 4.1.2+ there's no message displayed when pressing V key. The script works with 4.1.1 or earlier, or 3.8.x.

**Comment by NovaRain** [comment]
`key_pressed` function itself should work because in a global script running repeatedly the `if key_press(DIK_V)` block can print message with no problem.

**Comment by FakelsHub** [comment]
I would never have thought of using  key_pressed in this hook. :)

**Comment by NovaRain** [comment]
> 
> 
> I would never have thought of using key_pressed in this hook. :)

Neither do I. But [it was a valid case in earlier releases](http://www.nma-fallout.com/threads/fo2-engine-tweaks-sfall.178390/page-148#post-4331902) so it's still better to fix it.

**Comment by FakelsHub** [comment]
It could be used like this.
```
procedure KeyPressHandler begin
   Саll func;
end
procedure func begin
   if key_pressed(DIK_V) then begin
       ....
   end
end
```
