### ISSUE TITLE
A small improvement for add_extra_msg_file

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#249]
What if `add_extra_msg_file` could automatically assign a free file number and return it (when fileNumber is not specified explicitly): `filenum := add_extra_msg_file(string fileName)` ?
That'd allow to avoid messing with ddraw.ini, using predefined numbers and possible conflicts from that.

**Comment by NovaRain** [comment]
>That'd allow to avoid messing with ddraw.ini, using predefined numbers and possible conflicts from that.

The ID number used in `add_extra_msg_file` can't conflict with msgs listed in ExtraGameMsgFileList.
The msg files added by add_extra_msg_file are in ID range of 0x3000 to 0x3FFF, while files in ExtraGameMsgFileList are in 0x2000 to 0x2FFF.

**Comment by burner1024** [comment]
but still, you have to choose a unique number somehow, right?

**Comment by FakelsHub** [comment]
Not. In essence, and so issued a unique number after the addition.

**Comment by burner1024** [comment]
Чего?

**Comment by FakelsHub** [comment]
Ни к чему тут явно указывать номер, это только приведет к конфликту. Уникальный номер и так автоматически выдается, после добавления.

**Comment by burner1024** [comment]
Ничего не понял, как он выдается автоматически, если его надо явно указать, и функция ничего не возвращает?

**Comment by FakelsHub** [comment]
Тьфу точно) тогда ок, добавлю другую форму. Странно че это я так сразу не сделал.

**Comment by burner1024** [comment]
Это было бы отлично.

**Comment by NovaRain** [comment]
Maybe just change the func to the new behavior and drop the current `add_extra_msg_file(fileName, fileNumber)`? It's just added in 4.1.9 and I don't think there are many people already using it, so it's probably fine to make some "breaking" changes to it before people get used to the current form.

**Comment by burner1024** [comment]
No objections from me.
