### ISSUE TITLE
UI Scripting

### ISSUE THREAD

**Issue by phobos2077** [phobos2077/sfall#25]
Need to research possibility of extending UI scriptability. 

Main focus:
- Properly handle mouse clicks on buttons and panels (w/o tricks to prevent dude movement)
- Draw text directly on screen 
- Draw on item icons (not sure if it's possible to make something like that scriptable..)
- Use FRMs for graphics instead of PCX
- Need to use the same graphics layer as the actual game (same functions, approach, etc.)

**Comment by phobos2077** [comment]
After digging HeroAppearance.cpp, it appears it contains all necessary hints to implement all kinds of custom windows and UI. All that remains is to add missing UI scripting functions. 
Probably key function here is `get_input`, which basically halts execution while you interact with window using mouse and keyboard.

**Comment by FakelsHub** [comment]
> Draw text directly on screen
Писать прямо на экране можно создав окно CreateWin, но проблема в том, что созданное окно заливается черным, т.е. окно не может быть прозрачным.
Может возможно решить это дело в движке сделав по умолчанию созданные окна прозрачными, или же в функцию заливки FillWin добавить прозрачный фон.

**Comment by phobos2077** [comment]
Да проблема в том что все те функции для работы с UI что есть в ванильных скриптах очень специфичны (они "заточены" под интерфейс по типу такого как в редакторе, могу предположить что они задумывались для Star Trek Klingon Academy). В то время как для отрисовки интерфейса игры используются другие механизмы.

**Comment by FakelsHub** [comment]
> В то время как для отрисовки интерфейса игры используются другие механизмы.

Да это понятно. Но как мне кажется здесь снизу) это самый простой путь в реализации.
Тем более уст. прозрачности окна не помешала бы.

**Comment by FakelsHub** [comment]
Новая функция create_win позволяет разместить только одно окно с активно-рабочими кнопками, вторичные окна заблокированы.
Нужна функция функция которая бы позволяла задать флаг OnTop для уже созданного указанного окна.

**Comment by FakelsHub** [comment]
- [ ] Increase the maximum number of script Windows to 32 (or more).
- [ ] Make an additional layer for drawing on top of the game interfaces (the second transparent surface) on which you can draw without affecting the main window buffer.

**Comment by NovaRain** [comment]
It's kinda hard to imagine that 16 script windows (at the same time?) aren't enough, are you hitting the limit in your invenfiler?
Is the additional layer for script windows only? To separate script windows from game interface windows?

**Comment by FakelsHub** [comment]
> are you hitting the limit in your invenfiler?

there is used at the same time only 6.
16 seems somehow not enough :)

> Is the additional layer for script windows only? To separate script windows from game interface windows?

This is only for interfaces.
-user layer for drawing
-game draw layer

**Comment by FakelsHub** [comment]
We will not be able to increase the number of available scripted windows, as this will require a significant number of hacks to redirect to a new array for windows. 
The problem of a "small count" of scripted windows was solved after implementing an additional drawing layer for interface windows.

**Comment by FakelsHub** [comment]
This issue can be closed.
