### ISSUE TITLE
Hotkey to make an offer in barter screen

### ISSUE THREAD

**Issue by luotettava-asiakas** [phobos2077/sfall#252]
I think this would make bartering easier if one could just press enter or space key to make an offer.
Especially for touchpad players.
Love you guys and love your commitment.

**Comment by FakelsHub** [comment]
Ok

**Comment by luotettava-asiakas** [comment]
i Just noticed that 'm' is already a hotkey for this.

**Comment by FakelsHub** [comment]
I made a mistake I thought this applies to the filter mode.
Sorry, but this is done in a script, so this will not be implemented in sfall.

**Comment by luotettava-asiakas** [comment]
ok, cool. i wasnt sure if it can be done via scripting. I might give it a shot sometime. thanks for the info.
