### ISSUE TITLE
HOOK_ENCOUNTER ?

### ISSUE THREAD

**Issue by Lexx2k** [phobos2077/sfall#253]
Can we get a hook that kicks in once the player is on the worldmap and gets an encounter? 

What I want to do:
1. Player travels on the worldmap.
2. Encounter happens.
3. -> HOOK_ENCOUNTER stops it and runs code / overwrites default behavior.
4. freeze game (game_ui_disable?)
5. Our custom scripted popup window appears (create_win() + text + buttons in hook_encounter script). "Do you want to visit this encounter? yes/no" - return value
6. Depending on choice, enable or disable the encounter. 

Why I would like this:
For the Fo1 in Fo2 conversion we are abusing worldmap.txt - it has only maps assigned, no encounter tables. That means, if player gets an encounter, the flash appears and he will be moved into the encounter. Always. There is never the chance that a good outdoorsman skill roll makes it possible to cancel an encounter.

With a hook_encounter we could move all of our current "encounter determination code" into the hook script, print a fitting text, give the player the option to decline, switch a variable and once the player is in the actual encounter map, the variable will dictate the encounter code that is to load.

Bonus objective: (Optional)
Once encounter appears, overwrite behavior and make it possible to decide between "normal flash" and "special encounter flash".

**Comment by FakelsHub** [comment]
I would do all the encounters in worldmap.txt and wouldn’t work on building crutches in scripts. 

The red circle/sign cannot be changed, since the draw event will occur before the show the dialog box.

**Comment by Lexx2k** [comment]
That flash thing is ok, purely cosmetic anyway.

Problem with using worldmap.txt is that 1. [s]we[/s] I would have to translate all tables from script into Fo2 format and 2. it would *still* not look and feel exactly the same... which is what I want: It to feel the same. 
I mean, we could do another horrible workaround-- every encounter gets some unique script attached to a random scenery object, which then calls stuff like the random environment... but that means having to make lots of tiny scripts and it would *still* not be right, because the encounter description text in Fo1 is not working the same was in Fo2.

**Comment by FakelsHub** [comment]
Give a link to your script.

**Comment by Lexx2k** [comment]
- [Getting current position on the worldmap and determining terrain and zone](https://xp-dev.com/svn/Fo1Port/trunk/Fallout2/Fallout1Port/Mapper/source/scripts/GlobalScripts/gl_worldmap.ssl).
- [Desert encounter map script once the player is in the encounter](https://xp-dev.com/svn/Fo1Port/trunk/Fallout2/Fallout1Port/Mapper/source/scripts/99map/RNDDESRT.ssl) there is also one for mountains, coast and city.

**Comment by FakelsHub** [comment]
OMG 13к lines :)

**Comment by Lexx2k** [comment]
Yup, unoptimized mess to go through. The plan is to improve it in the future... or just never touch it ever again in fear of breaking something. There's so many shitty scripts in the mod package right now, the last two weeks were primarily spend on cleaning up.

**Comment by Lexx2k** [comment]
Ok, let's forget about all this stuff, but there is something else that is annoying me:

Can we get an option to disable the "You Encounter:" message? It's line 2998 in worldmap.msg
The message runs in the log after the player has entered the map, thus all my custom messages appear before it. It's nothing critical, but kinda ruins the look, imo.

**Comment by FakelsHub** [comment]
```
write_int(0x4C1011, 0x90909090);
write_byte(0x4C1015, 0x90);
write_int(0x4C1042, 0x90909090);
write_byte(0x4C1046, 0x90);
```
Paste in script `gl_worldmap.ssl` to start procedure.

**Comment by NovaRain** [comment]
And remember to set `AllowUnsafeScripting=1` (requires sfall debugging mode) in ddraw.ini.

**Comment by Lexx2k** [comment]
This worked, thanks! Message log looks a lot better this way.

Yes, I'm using AllowUnsafeScripting=1 already because of the changes to the endgame credits, etc.

**Comment by FakelsHub** [comment]
> changes to the endgame credits

This change will need to be removed, so there will be an option in ddraw that changes behavior.

**Comment by NovaRain** [comment]
What endgame credits?

**Comment by FakelsHub** [comment]
http://www.nma-fallout.com/threads/fo2-engine-tweaks-sfall.178390/page-149#post-4334005
