### ISSUE TITLE
Incorrect date with StartX time

### ISSUE THREAD

**Issue by Lexx2k** [phobos2077/sfall#254]
I noticed this a while ago but thought the problem would be somewhere else. Did some more testing now and found out the issue is Sfall related:

Comment out **StartYear**, **StartMonth**, **StartDay** in ddraw.ini and start the game. The PipBoy date is default: 25.07.2241 as it should be.

Now set the date to something else, like 05.12.2161 and start the game. The PipBoy date is 06.07.2161

I tried this with latest Sfall, also tested this in the last Restoration Project installation I had, though I'm not 100% sure what Sfall version it is running with. I've now also noticed this issue in my other Fo2 mod.

**Comment by FakelsHub** [comment]
`;Both StartMonth and StartDay are 0-indexed`

**Comment by Lexx2k** [comment]
No idea what that means, but considering it is called "StartMonth" and "StartDay" and not "StartMonth+/-something" and "StartDay+/-something", I'd say it is a bug.

**Comment by FakelsHub** [comment]
This means that 0 is 1, and 12 is 13. :-)
Yes stupidly done. It will be necessary to remove it.

**Comment by NovaRain** [comment]
The behavior of StartMonth and StartDay are like that since the very beginning. Your month stays as July because the value is out of range (0~11).
If you want to set a date of Dec 5, set `StartMonth=11` (0=Jan, 1=Feb, etc.) and `StartDay=4`.

**Comment by Lexx2k** [comment]
> The behavior of StartMonth and StartDay are like that since the very beginning.

Sure, but why not change this now? Surely it kinda just needs a -1 in code to make the values right?

**Comment by NovaRain** [comment]
> 
> 
> > The behavior of StartMonth and StartDay are like that since the very beginning.
> 
> Sure, but why not change this now? Surely it kinda just needs a -1 in code to make the values right?

And make the date of other **existing** TCs shift by 1?

**Comment by Lexx2k** [comment]
Jesus, chill. Sorry to bother you.

**Comment by NovaRain** [comment]
> 
> 
> Jesus, chill. Sorry to bother you.

I'm calm, just wonder if you're fine with that.
Sure, the date itself is actually not _that_ important, but as long as the options work fine, I don't really see the reason to make changes that would (somewhat) break existing configs.

**Comment by burner1024** [comment]
I'm with @NovaRain on this one. Maybe also add a log message if it's out of bounds?

**Comment by NovaRain** [comment]
If the value is out of range, the options will not be enabled, which means no log in sfall-log.txt. I think that's enough as an indicator.
