### ISSUE TITLE
Decreasing size of mark_on_map()?

### ISSUE THREAD

**Issue by Lexx2k** [phobos2077/sfall#255]
I found [this](https://github.com/phobos2077/sfall/commit/28059ce890194dbc22c36dc16be6331e65abc1c1) today. Can we use this to change mark_on_map() to [how it looks like in Fallout 1](https://i.imgur.com/fr5A3oh.png)? 

In Fo1, learning about a new area only marks one zone as "seen" but not "traveled to", while in Fo2 it marks the center zone as "traveled to" and +1 zone around it as "seen".

Would be fancy to get something like _mark_on_map_small_ or something along the way.

**Comment by FakelsHub** [comment]
Then the name will not be visible.

**Comment by Lexx2k** [comment]
You have the name in the location tab to the right of the interface.

**Comment by FakelsHub** [comment]
This is just a bug/flaw in F1. I do not think that you need to copy this bug in F2.
And there is no good reason to copy the same behavior.
