### ISSUE TITLE
Fallback language for add_extra_msg_file

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#256]
`add_extra_msg_file` picks up current language from config. A mod may be not translated into that language yet. In that case, the only workaround would be to copy msg files manually to current language directory. If the mod is packaged into .dat, that also gets cumbersome.

Would it be possible to either add a third optional argument, specifying a fallback language, or just fallback to english, if msg file doesn't exist in current language?

**Comment by FakelsHub** [comment]
Нельзя ничего изменить такова механика движка. Престраивать глобально общую функцию чтения файлов в движке не очень то и хочеться.

**Comment by burner1024** [comment]
Ясно. Плохо, ну ладно. Наверное, можно что-то придумать для проверки в самом скрипте: получить текущий язык, сделать fs_copy, если там ошибка то подгрузить английский файл.

**Comment by FakelsHub** [comment]
А че закрыл. Есть одна идея может и прокатит.

**Comment by burner1024** [comment]
Я думал нет так нет. А так в принципе если через скрипт получится, то сойдет. Надо попробовать.

**Comment by FakelsHub** [comment]
Я что-то единственое не понял, зачем менять имя папки с English на что-то другое?
и если сменить то игра не будет работать.

**Comment by NovaRain** [comment]
I tested in non-English version of Fallout 2. Here's the binary if you want to check:
https://www.mediafire.com/file/wesmc6053cl1ldv/sfall_test20190817.rar/file

**Comment by FakelsHub** [comment]
На dat файлах не проверял, так, что если не заработает, значит не судьба.

**Comment by burner1024** [comment]
Works good with plain files, but unfortunately crashes if using .dats.

As a side note, I noticed that the game with crash if message file is not found (even when using english language).

**Comment by FakelsHub** [comment]
Crash when packed in dat?
For example, my game does not crash when there is no file.

**Comment by burner1024** [comment]
Do you use a message from that file?

**Comment by FakelsHub** [comment]
А как ты будешь использовать сообщения если файл не загружен?
Ставь проверку 
-1: файл с таким номером уже добавлен
-2: файла нет
-3: выход из диапазона

**Comment by NovaRain** [comment]
I also got the crash if the msg file doesn't exist in both current langauage and English directory. With simple code like this:
```
tmp := add_extra_msg_file("foo.msg");
display_msg(message_str_game(tmp, 100));
```
Need to place a check for tmp value to prevent the crash:
```
tmp := add_extra_msg_file("foo.msg");
if (tmp > 0) then display_msg(message_str_game(tmp, 100));
```
I guess it's because add_extra_msg_file returns negative values for errors and causes message_str_game to crash. There should be `if (fileId >= 0 && fileId <= 19)` (or < 20) in message_str_game code.

**Comment by burner1024** [comment]
So will loading from dats be fixed, or mod packaging should go back to directories?

**Comment by FakelsHub** [comment]
Если это сделать(исправить), то это уже будет не для функции, а в целом для движка (всех msg-файлов).

**Comment by burner1024** [comment]
> Если это сделать(исправить), то это уже будет не для функции, а в целом для движка (всех msg-файлов).

Ну в целом я не вижу что в этом плохого, наверное даже наоборот, хорошо.

**Comment by NovaRain** [comment]
Like forcing to read all msg files and build an additional list for them in memory at game start, instead of just using the game built-in & ExtraGameMsgFileList ones?

**Comment by FakelsHub** [comment]
> forcing to read all msg files and build an additional list for them in memory at game start

Sounds harder than make hack provided that the current selected language is not English

**Comment by NovaRain** [comment]
With the latest commit, sfall can now load msg file from .dat w/o any problem.
I packed foo.msg & bar.msg in text\english\game\ in a textplus.dat and put the dat file in `mods` for a non-English version of FO2. Running a script with
```
tmp := add_extra_msg_file("foo.msg");
display_msg(message_str_game(tmp, 100));
tmp := add_extra_msg_file("bar.msg");
display_msg(message_str_game(tmp, 100));
```
will still print the test messages correctly.

**Comment by burner1024** [comment]
Great, I'll keep using dats then. Thank you.
