### ISSUE TITLE
Custom elevators - missing EL_MIL4?

### ISSUE THREAD

**Issue by Lexx2k** [phobos2077/sfall#259]
I noticed that the elevator graphic EL_MIL4 isn't available via elevators.ini file.

Is there a way to get that one back / make it available? Every other elevator graphics seem to work fine (numbers 0 to 23, some graphics appear multiple times, though).

> ;image 0 is 4 levels 1-4 el_bos
>;image 1 is 2 levels G and 1 el_bos2
>;image 2 is 3 levels 1-3 (vt broken) el_mast1
>;image 3 is 2 levels 3 and 4 (vt broken) el_mast2
>;image 4 is 3 levels 1-3 el_mil1
>;image 5 is 2 levels 3 and 4 el_mil2
>;image 6 is 3 levels 1-3 el_mil1? shouldn't it be el_mil4
>;image 7 is 3 levels 3 4 6 el_mil3
>;image 8 is 3 levels 1-3 el_vault
>
>;image ????? is 3 levels 4 5 6 el_mil4 <<< this graphic is not available?
>
>;image 11 is 2 levels 3-4  el_mil2
>;image 12 is 4 levels 1-4 military (need el_base1 from f2)

/Edit: I just saw that exactly this is possible now with latest Sfall. However, if I take the values from the new elevators.ini as a test, the game will crash as soon as I step into the elevator.

/Edit2: Also overwriting existing elevators. If I use - as example - elevator 9, set image=10 and then try to overwrite the graphic via MainFrm, nothing seems to change either?

**Comment by FakelsHub** [comment]
Nothing is clear from your story. :)
Need more data.

**Comment by FakelsHub** [comment]
Elevators.ini works, you only need to learn how to work with it.
Somewhere there was a discussion where I told NovaRain how Image and MainFrm work.

**Comment by Lexx2k** [comment]
I did it exactly as stated in the example elevators.ini file in the modders pack:
https://pastebin.com/B68yqhmv

But it had no effect or crashed the game. The info in your link is correct, I did the same mistake as NovaRain. Everything is working now as it should be.
