### ISSUE TITLE
Remove hardcoded carry weight limit

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#26]
It seems that carry weight is hard limited to 999. Even when bonus is set to more, it still caps to 999 in game. If it's not complicated, I'd request to unhardcode it.

**Comment by NovaRain** [comment]
I've added CarryWeightLimit option to allow player changing the carry weight limit. Max value is 2^32 - 1, probably an overkill.

**Comment by burner1024** [comment]
Great, thank you!

**Comment by NovaRain** [comment]
The option will be removed in next version, because it can be scripted easily with set_stat_max function in a global script. I should have checked if there's any existing script functions that can do the same thing instead of implementing address hack.

**Comment by burner1024** [comment]
Hmm, I also didn't notice that. I'll try this function and report back.

**Comment by NovaRain** [comment]
I've already tested it. The function can rise carry weight limit to 2147483647 maximum.

**Comment by burner1024** [comment]
Can you elaborate why is it only available in a global script? Or it's the same for all new functions?

**Comment by NovaRain** [comment]
I never say it's only available in global script. It's just me preferring using global scripts for those functions that changes stuff globally (set_stat_max affect stats for both PC and other critters, and it's the same as how CarryWeightLimit works.)

Of cause you can try using set_pc_stat_max in OBJ_DUDE script, but I haven't tried it.

**Comment by burner1024** [comment]
I tried it in arroyo temple script... it didn't work, then I switched to global script like you suggested, and it worked. That's why I assumed it was only working in globals.
Is it a good place for this conversation, or better move to forums?

**Comment by NovaRain** [comment]
Since I don't have advanced knowledge about how the engine works, I can only assume the engine keeps checking/reloading its internal value in a short time interval or something.

**Comment by burner1024** [comment]
But regardless of how it works, the very same code did work in global script and didn't in map one.
Well, anyway, in my use case global is fine and might be even preferable. I just wanted to clarify that for future reference.
