### ISSUE TITLE
Changing main menu font color

### ISSUE THREAD

**Issue by Lexx2k** [phobos2077/sfall#261]
This is a super low-tier issue, but I want to ask anyway... Is there a way to change [the main menu font color](https://i.imgur.com/wyD57xl.png)?

We have `MainMenuFontColour=` but this only changes the Sfall version string (right side), and not the Fallout copyright (left side text).

Bonus question: How the hell do you convert a color to the correct byte?

**Comment by NovaRain** [comment]
> 
> Bonus question: How the hell do you convert a color to the correct byte?

The byte is the index number of color in [the palette](https://falloutmods.fandom.com/wiki/Color.pal).
The default `3c` is 60 in decimal, so the color is RGB 184/156/40 by the line 61 in color.pal.

**Comment by FakelsHub** [comment]
![palette](https://user-images.githubusercontent.com/21695363/63279648-0aa40780-c2b2-11e9-9344-5427dbdf5ae9.png)

**Comment by Lexx2k** [comment]
@FakelsHub got the color working, thanks to NovaRain mentioning the palette. In hindsight it makes a lot sense that the "3c" was referring to the color position and not the color itself.

Still, stupid copyright text is not covered by MainMenuFontColour, which sucks. :>

**Comment by FakelsHub** [comment]
> stupid copyright text is not covered by MainMenuFontColour

this will not work because everything spoils HRP

**Comment by Lexx2k** [comment]
But it can't be changed in HRP either? At least I haven't found an option for that.

**Comment by FakelsHub** [comment]
in HRP there is no such option. HRP wedges into the engine code and redraws the test in its own way.

**Comment by Lexx2k** [comment]
Welp, what a shame.

**Comment by ghost2238** [comment]
If you want to change the copyright text color rendered by HRP, you can change the following: 

"or ecx, 0x6000000" -> "mov ecx, 0x6000055; nop" which was the 

location of the code can be found by searching for this bytestring in f2_res.dll: E8 C0 69 FF FF 83 C4 10 85 C0 74 4A 8B 0D D8 EB 06 10 85 C9 74 10 8B 09 0F B6 09 
(it's the instruction after this bytestream)

I manually patched the DLL for our project but it might be nice to have as an ini option in sfall.
