### ISSUE TITLE
Using bag item shows wrong image in inventory

### ISSUE THREAD

**Issue by Lexx2k** [phobos2077/sfall#262]
Using a bag item in BIS mapper works correctly. It shows the "bag on ground" item in the inventory. However, using the bag in the game, the icon is wrong: [See screenshot](https://i.imgur.com/HtN7SbO.png).

I'm not 100% sure, but this might be an Sfall issue? (Otherwise it also wouldn't work in the mapper?)

I could swear that I've read something about this already, but I can't find it anymore. Is there anything we can do to fix this?

**Comment by FakelsHub** [comment]
ohoho, this bug lasts from v4.0.
Strange I saw a few months ago, the display of the bag was correct.

**Comment by Lexx2k** [comment]
The same issue happens in my other Fo2 mod, but strangely the icon in the inventory is the unopened grave, while here it is the grenade.

**Comment by NovaRain** [comment]
Maybe it's due to trying to load frm with incorrect offsets, and got different result with different .lst files. Since 3.8.x doesn't have such issue, I'd guess the cause is some newer hook (adjustFid?)

**Comment by Lexx2k** [comment]
Does the Fid drastically change depending on objects (scenery, etc) added? Because all the vanilla objects are the same in my other Fo2 mod, I haven't touched them. So *in theory* the wrong inventory image should be the same in both mods? It's weird..

**Comment by FakelsHub** [comment]
Hero app. mod

**Comment by NovaRain** [comment]
Some refactored functions in Hero app mod for 4.x caused this issue?

**Comment by FakelsHub** [comment]
Yes.

**Comment by FakelsHub** [comment]
also there will again be a conflict of interest, between AdjustFidHook and changing the fid in the hero mod, how should this be handled, send the changed fid from the hero mod to hook or not?
does the overridden fid in the hook need to be sent to hero mod?
headache again.

**Comment by NovaRain** [comment]
IMO AdjustFidHook should be able to modify/override the hero mod.

**Comment by FakelsHub** [comment]
If look at the code it’s redefining it now, in 4.0 it did not redefine. (I can’t check it now for sure)
Okay, I’ll do it easier, add a second argument to the hook with the modified fid value.

**Comment by NovaRain** [comment]
Fixed.
