### ISSUE TITLE
Force read-only protos

### ISSUE THREAD

**Issue by wipe2238** [phobos2077/sfall#263]
Is there a chance to enforce read-only protos by simply changing files attributes on disk to read-only during some early init (before engine start messing with them) and set them back to read-write when game exits?

If current solution should stay (even if current `DontDeleteProtos` description clearly says _"don't use me"_ :P), it could be enabled by `DontDeleteProtos=2`.

**Comment by NovaRain** [comment]
What's wrong with setting read-only attribute to protos with operating system?

**Comment by wipe2238** [comment]
> What's wrong with setting read-only attribute to protos with operating system?

Absolutely nothing.
But.

It could simplify mod packaging - modder doesn't need to pack protos just to avoid their deletion.
It could simplify mod installation - player doesn't need to remember/know about protos files.
It could simplify editing protos - modder can update protos inside game folder without setting them to ro every time before starting game.
It could simplify testing - testers can simply pull game content from mod repo and launch it. Git/SVN/etc. can and will complain about missing files, plus they won't like ro files either if they need updates. And modder doesn't need to remind about setting protos read-only on each report which might be related to them.

It's about saving everyones time, nothing more really.

**Comment by FakelsHub** [comment]
wipe2238 - you are outdated, mods do not need to be installed in the data folder. For this, separate folders for mods already exist.

**Comment by Lexx2k** [comment]
As far as I remember, the mapper doesn't read files from /mods/ ?

**Comment by FakelsHub** [comment]
DontDeleteProtos - needed only for the mapper if you want to edit prototypes of items and critters in it.
There are third-party editors for prototypes that automatically set R/O attribute on files.

**Comment by Lexx2k** [comment]
>There are third-party editors for prototypes that automatically set R/O attribute on files.

There is a pretty good tool for items and critters, but nothing for walls, scenery, etc. :>

**Comment by FakelsHub** [comment]
> but nothing for walls, scenery, etc. 

Because it is not in demand, and the official mapper does this job well.

**Comment by burner1024** [comment]
> It could simplify mod packaging - modder doesn't need to pack protos into .dat just to avoid their deletion.
> It could simplify mod installation - player doesn't need to remember/know about protos files.
> It could simplify editing protos - modder can update protos inside game folder without setting them to ro every time before starting game.
> It could simplify testing - testers can simply pull game content from mod repo and launch it. Git/SVN/etc. can and will complain about missing files, plus they won't like ro files either if they need updates. And modder doesn't need to remind about setting protos read-only on each report which might be related to them.
> 
> It's about saving everyones time, nothing more really.

I'd say this a job for a separate launcher (with potentially many more possibilities, such as managing settings and _mods_ - tss, don't tell @FakelsHub)

**Comment by wipe2238** [comment]
Closing it before someone suggests bytepatching exe.
