### ISSUE TITLE
v4.2 expanded actionpoint bar and no HRP

### ISSUE THREAD

**Issue by git-0003** [phobos2077/sfall#264]
works in 4.1.9.1 but not in 4.2

line from 4.2 logs:
Applying expanded action points bar patch. Incorrect HRP version!Applying world map cities list patch. Done

**Comment by NovaRain** [comment]
What's the first line in the log? Is it like this?
`Loaded f2_res.dll library at the memory address: 0x0`
If yes than it's possible your exe is patched to load HRP but you didn't have or you removed f2_res.dll.
If you don't want to use HRP, you need to run HRP's f2_res_Config.exe to disable the patch in exe.

**Comment by git-0003** [comment]
you are right fallout2.exe was patched.
it is working now thank you
