### ISSUE TITLE
Some savegames still won't load

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#265]
I'm getting [multiple](https://github.com/BGforgeNet/FO2tweaks/issues/47) [reports](https://forums.bgforge.net/viewtopic.php?f=26&t=201) about being unable to load savegames, rectified by enabling debugging. Wasn't it fixed?

**Comment by NovaRain** [comment]
I tested the fix with games saved with sfall 3.4, 3.6, 3.7 in original RP 2.3.3.
The Slot08 from jvs3 has script array broken in sfallgv.sav, not sure why/how it happened.

**Comment by burner1024** [comment]
> The Slot08 from jvs3 has script array broken in sfallgv.sav, not sure why/how it happened. But it seems both cases happen when using your FO2tweak, not just RP/RPU itself.

Right, and there's 3 cases. But still it somehow starts to work once debugging is enabled?

**Comment by NovaRain** [comment]
> 
> 
> > The Slot08 from jvs3 has script array broken in sfallgv.sav, not sure why/how it happened. But it seems both cases happen when using your FO2tweak, not just RP/RPU itself.
> 
> Right, and there's 3 cases. But still it somehow starts to work once debugging is enabled?

Because enabling sfall debugging mode forces passing the check, even if data in sfallgv.sav is broken.
So while the game loads, it's highly possible the sfall global variables or saved array data are broken and some script mods might not work properly.

**Comment by burner1024** [comment]
If it's possible to corrupt array data with scripting (not counting "unsafe" functions), that looks like a problem by itself to me.
Is there a reason it's not stored as plain text, btw? Would probably be easier to debug.
Anything I can do? Honestly, I don't see how to approach the issue from scripting side.

**Comment by FakelsHub** [comment]
В каких скриптах у тебя используются сохраняемые масивы?
Может проблема в других модах?

**Comment by FakelsHub** [comment]
Кстати там у jvs3 логи тоже какие-то битые, может это проблема компьютера у jvs3.
И я не вижу проблемного кода в sfall.

**Comment by jvs3** [comment]
If you mean that the logs don't have a beginning or end, I alt-tabbed out of the game and cleared the log before loading and copy-pasted it after loading so it would only contain the loading part.
I'm using google translate so if I understood it wrong just ignore this.

**Comment by FakelsHub** [comment]
@jvs3 - which OS is used?

**Comment by burner1024** [comment]
> If you mean that the logs don't have a beginning or end, I alt-tabbed out of the game and cleared the log before loading and copy-pasted it after loading so it would only contain the loading part.

Please keep the logs complete, it's not a problem.

**Comment by burner1024** [comment]
> Кстати там у jvs3 логи тоже какие-то битые, может это проблема компьютера у jvs3.

Проблема не только у него, как минимум еще 2 человека жаловались.

**Comment by FakelsHub** [comment]
Я смотрел битый sfallgv, я так и непонял, почему так криво записались массивы в файл, по сути их нет в игре, но инфа о них записалась, и то криво.
Может такой эффект дает то, что ты постоянно применяешь save_array() к уже ранее сохраняемому масиву.

**Comment by burner1024** [comment]
Ну скрипт-то я изменю, но насколько я понимаю, это все равно баг в sfall.

**Comment by jvs3** [comment]
> @jvs3 - which OS is used?

The OS is Linux using Wine v2.22

**Comment by FakelsHub** [comment]
Вопрос к знатокам @phobos2077 Есть такой код и скрипт 
```j
arra := create_array(0, 0);
save_array("t_array_a", arra);
arrb := create_array(0, 0);
save_array("t_array_b", arrb);
```
``` c++
// if another array is saved under the same key, clear it
ArrayKeysMap::iterator savedIt = savedArrays.find(sArrayElement(key.rawValue(), key.type()));
if (savedIt != savedArrays.end()) {
	dlog("SavedArrays: Key is exist.\n", 0);
	//BREAKPOINT
	if (savedIt->second == id) return; // exit, array is already savedabled
	dlog("SavedArrays: Replace to other array.\n", 0);
	// arrays have different ID, search the ID of the "saved" array in collection of arrays
	if ((it = arrays.find(savedIt->second)) != arrays.end()) {
		dlog("SavedArrays: Unset prev array.\n", 0);
		it->second.key.unset(); // "saved" array still exists, delete key value
	}
}
// make "saved" array
dlog("SavedArrays: Make saved array.\n", 0);
itArray->second.key.setByType(key.rawValue(), key.type());
savedArrays[itArray->second.key] = id; // add new element or replace value
dlog_f("SavedArrays count: %d\n", 0, savedArrays.size());
```
Это лог:
> SavedArrays count: 2  - уже имется два массива, 
и мы перезапивываем уже существующий сохраняемый массив, другим массивом
> SavedArrays: Key is exist.
> SavedArrays: Replace to other array.
> SavedArrays: Unset prev array.
> SavedArrays: Make saved array.
> SavedArrays count: 3
> 
> SavedArrays: Key is exist.
> SavedArrays: Replace to other array.
> SavedArrays: Unset prev array.
> SavedArrays: Make saved array.
> SavedArrays count: 4

Вопрос почему `savedArrays[itArray->second.key] = id; // add new element or replace value`
добавляет новый элемент в карту, а не перезаписывает уже существующий?

**Comment by FakelsHub** [comment]
Here I need help programmers!
Because the use of a class `sArrayElement` as the key is not very stable, or in the class is something wrong implemented.

**Comment by phobos2077** [comment]
@FakelsHub я уже не помню этот код если честно, надо отлаживать. На первый взгляд похоже на то что хеш для sArrayElement как-то неправильно считается или не считается, поэтому добавляет второй раз элемент. Надо в отладчике смотреть что там происходит. Этот код после меня не правили? Текст в логах какой-то незнакомый.

**Comment by FakelsHub** [comment]
> @FakelsHub я уже не помню этот код если честно, надо отлаживать. На первый взгляд похоже на то что хеш для sArrayElement как-то неправильно считается или не считается, поэтому добавляет второй раз элемент. Надо в отладчике смотреть что там происходит.

Уже разобрался, два дня голову ломал.
Оказывается после очистки/уданения си строки в `it->second.key.unset(); // "saved" array still exists, delete key value` меняется и хеш ключа в маp, т.к. строки для ключа уже небудет.
Приходится удалять ключ перед очитской (и создавать заново).
В общем неверную ты реализацию выбрал с unordered_map, тут наверное надо было обычный вектор с парой применить, чтобы простое значение хеша хранил.

>Этот код после меня не правили? Текст в логах какой-то незнакомый.

Нет. Это я текст понатыкивал, чтобы понять какого хрена это неработает.
А как отлаживать в отладчике (в студии)?
а то я только логами отлаживаю, да в IDA в ассемблере..

**Comment by phobos2077** [comment]
> Оказывается после очистки/уданения си строки в `it->second.key.unset(); // "saved" array still exists, delete key value` меняется и хеш ключа в маp, и для `savedArrays[itArray->second.key] = id` си-строки для подсчета хеш-ключа уже небудет. Теперь приходится удалять ключ/пару перед очитской (и добавлять заново).
> В общем неверную ты реализацию выбрал с unordered_map, тут наверное надо было обычный вектор с парой применить, чтобы простое значение хеша хранил.

Как-то сомнительно звучит если честно. Но разбираться самому пока некогда. 

> А как отлаживать в отладчике (в студии)?
> а то я только логами отлаживаю, да в IDA в ассемблере..

Брейкпоинты ставить)) Запускать sfall в режиме отладки.

**Comment by FakelsHub** [comment]
> Брейкпоинты ставить)) Запускать sfall в режиме отладки.

В студии брейкпоинты?
Это же библиотека как ты ее запустишь, без fallout.exe.

**Comment by phobos2077** [comment]
> 
> 
> > Брейкпоинты ставить)) Запускать sfall в режиме отладки.
> 
> В студии брейкпоинты?
> Это же библиотека как ты ее запустишь, без fallout.exe.

Легко, в настройках проекта можно сделать команду отладки на запуск Fallout2.exe. Он будет билдить DLL, запускать ЕХЕ и подключаться отладчиком к DLL. У меня ещё было копирование DLL настроено прямо в папку с основной игрой, оттуда и запускалась отладка.

**Comment by NovaRain** [comment]
Here's the test build from the fix commit:
https://www.mediafire.com/file/5pkwnvzi0lsqeqp/sfall_test_20190924.rar/file

I used @jvs3's save (slot20) with fo2tweak v10 (healing_revision=1) to get myself a "corrupted" save, and got no "ERROR reading data" on sfallgv.sav in log (i.e. sfall should stop loading the game without enabling debugging mode) anymore.

**Comment by burner1024** [comment]
Wasn't the point of fix to prevent corruption in the first place?

**Comment by NovaRain** [comment]
> 
> 
> Wasn't the point of fix to prevent corruption in the first place?

I also tried to save his slot20 with new sfall build, and "unfixed" sfall 4.2 can load the re-saved game without any problem.

**Comment by burner1024** [comment]
Ok, so if it's prevented, then all should be good, at least eventualy. Thank you @NovaRain, @FakelsHub, @phobos2077. Waiting for the new release then.
