### ISSUE TITLE
Removing an object equipped  & Hook_Invenwield

### ISSUE THREAD

**Issue by FakelsHub** [phobos2077/sfall#266]
https://github.com/phobos2077/sfall/blob/8d29e047129a3e5c53c669d9d3f6b8245cc5634e/sfall/Modules/HookScripts/InventoryHs.cpp#L493
https://github.com/phobos2077/sfall/blob/8d29e047129a3e5c53c669d9d3f6b8245cc5634e/sfall/Modules/HookScripts/InventoryHs.cpp#L494

Question: Should run a hook, when the object is removed from the inventory?.
Something seems to me that should not be, as obj_drop / obj_drop_all not cause the run of the hook.
I think that it is necessary to remove these two lines.
Your opinion?

**Comment by NovaRain** [comment]
Honestly I'm not sure.  How many ways in the engine to wield/unwield weapon/armor for critters?
If it's for the consistency, maybe do the opposite to add the other two (drop_obj / obj_drop_everything) to the hook as well?

**Comment by FakelsHub** [comment]
`rm_obj_from_inven` -  it also works for the player.
But as I understood from the description of the hook,  the hook for the player should not run?.

**Comment by NovaRain** [comment]
> But as I understood from the description of the hook, the hook for the player should not run?.

No, I don't think HOOK_INVENWIELD would run for the player.

**Comment by FakelsHub** [comment]
I think that can then add obj_drop for the NPC, and remove move_obj_inven_to_obj ( it works for NPCs only for weapons)
In general, this hook is somehow very bad done, the original purpose of the hook is not clear why this is done for npc and can not be performed for the player?, some kind of mismatch.

**Comment by FakelsHub** [comment]
If you add obj_drop and obj_drop_all - the question remains why this cannot work in most cases for the player?
One minus - if you do this for the player, you will have to change the code in the engine a lot.

**Comment by NovaRain** [comment]
> 
> 
> I think that can then add obj_drop for the NPC, and remove move_obj_inven_to_obj ( it works for NPCs only for weapons)

But calling move_obj_inven_to_obj(party_member, other_critter) also transfer the armor. And that makes me start to think whether it should be applied to "destroy object" functions as well...damn. :\
I guess for now in my opinion it's easier to just cut off the two to let the hook run in a more strict fashion (one has to really "wield/unwield" items for NPCs).

> In general, this hook is somehow very bad done, the original purpose of the hook is not clear why this is run for npc and can not be performed for the player?, some kind of mismatch.

I think it was designed for party members, so one can change the appearance/stats of PMs. I remember that's my first impression for the hook. Also phobos made a prototype script of npc armor appearance with it (before new hooks in 4.0), I tested on Sulik and it worked decent enough, although not as good and configurable as the current one.

>If add obj_drop and obj_drop_all - the question remains why this cannot work in most cases for the player?
One minus - if do this for the player, will have to change the code in the engine a lot.

That's what I don't really like to see. I'd say keeping the hook as it is (works for NPCs).

**Comment by FakelsHub** [comment]
I think, that need the hook lead to order, and add all functions which remove equipped objects.
For the player, hook can be excluded (not to spoil a lot of code in the engine), so the player will have to be excluded from the rm_obj_from_inven function.
These are my thoughts.

**Comment by NovaRain** [comment]
> so the player will have to be excluded from the rm_obj_from_inven function.

No. We shouldn't modify vanilla game functions especially "limiting" their behavior, as there are already many scripts using `rm_obj_from_inven(dude_obj, ...)`. For now I prefer your initial proposal to just remove the two opcode from the hook and make things simpler.

**Comment by FakelsHub** [comment]
Then need add player to hook.
By the way, have you tried the script npcarmor.ssl with controlled PM?

**Comment by NovaRain** [comment]
> 
> 
> By the way, have you tried the script npcarmor.ssl with controlled PM?

No, are there issues with using both of them?

**Comment by FakelsHub** [comment]
>  rm_obj_from_inven(dude_obj,...).

I'm not talking about the function, about call the hook for the player, when you use this function to remove the equipped item from the player.

**Comment by FakelsHub** [comment]
> No, are there issues with using both of them?

Just I want to know what will happen when the player will control the PM, because the hook does not work for the player, how it will work correctly for a change FID.
Incidentally, I had a problem with that, when controlled PM, I did not understand his problem, (it can no setting mod or lack of frm file).

**Comment by FakelsHub** [comment]
>  For now I prefer your initial proposal to just remove the two opcode from the hook and make things simpler.

I've changed my mind about this)
So we summarize:
Adding obj_drop/all functions and remove the trigger hook for the player from the function `op_rm_obj_from_inven_`
Such an embodiment would be acceptable than now.

**Comment by NovaRain** [comment]
> Just I want to know what will happen when the player will control the PM, because the hook does not work for the player, how it will work correctly for a change FID.

I'd suggest we should just block all wearing/removing armor action for controlled critters to prevent a new can of worms. Most of people using combat control probably only want to control movement/attack/used weapons for critters.

> remove the trigger hook for the player from the function `op_rm_obj_from_inven_`

I still don't know why it's only rm_obj_from_inven, not move_obj_inven_to_obj which also shares the same hook code (CorrectFidForRemovedItemHook).

**Comment by FakelsHub** [comment]
> I'd suggest we should just block all wearing/removing armor action for controlled critters to prevent a new can of worms

why block, it's terrible, as in the crafty version.
Set of armor in the slot should influence simplicity (without the npcarmor mod) on the armor parameters as it is done in the control panel.

**Comment by NovaRain** [comment]
> 
> 
> > I'd suggest we should just block all wearing/removing armor action for controlled critters to prevent a new can of worms
> 
> why block, it's terrible, as in the crafty version.

Let's just say I prefer simpler solution than yet another tons of code for trivial things.
