### ISSUE TITLE
Inappropriate weapon for the player.

### ISSUE THREAD

**Issue by FakelsHub** [phobos2077/sfall#267]
https://github.com/phobos2077/sfall/blob/1b6d6179a1ad30f4aa08e763f81522297fb92d01/sfall/Modules/PartyControl.cpp#L285

May allow the code and for the player? - enable this for a regular game, so that the player could not take into the hands of inappropriate items.

**Comment by NovaRain** [comment]
What do you mean by "inappropriate items" for the player?

**Comment by FakelsHub** [comment]
> Like guns for player's tribal appearance?

yes

**Comment by NovaRain** [comment]
I just did a simple test with 3.8 (because the inventorymove hook is always injected) and it seems OK, as I can't put a pistol in either slots while in tribal appearance. I only commented out isControllingNPC check in `SwitchHandHook()`.

**Comment by FakelsHub** [comment]
Always.
it’s just not entirely clear if that makes sense.

**Comment by NovaRain** [comment]
> it’s just not entirely understand if that makes sense.

I think that could be a bit confusing for people.

**Comment by NovaRain** [comment]
OK, now the player can't equip a weapon if the current appearance doesn't have the animation for it (i.e. trying to equip a rifle when in the tribal appearance).
This applies to both 4.x and 3.8.x (commit 614cade & c7eaff7).
