### ISSUE TITLE
Geckos won't attack when they don't see PC

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#268]
Load save from https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/issues/26 (RP or RPU), pass turn. Most of the time, Sulik will attack the gecko, but the gecko won't retaliate.
The script is pretty straightforward, attack is invoked 2 times: [1](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/4e8d3491a5dcae78f8da893900e6cb1e3c4fd32e/scripts_src/generic/zcgecko.ssl#L93), [2](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/4e8d3491a5dcae78f8da893900e6cb1e3c4fd32e/scripts_src/generic/zcgecko.ssl#L133).

Something prevents the lizard from attacking. Does `attack` stack targets instead of keeping the latest one, by chance?

**Comment by NovaRain** [comment]
And for some reason I can't reproduce the issue with the save in RP on both of my PCs, after passing my turn the golden gecko just attacks Sulik.

**Comment by FakelsHub** [comment]
Ради интереса можешь попробовать не официальную версию для "русских мужиков" где было доработано подобное поведение AI, когда криттеры не атаковали игрока и его напарника, настройки в секции [CombatAI]

**Comment by NovaRain** [comment]
It would be nice to know if there is indeed some bug/reason in this case rather than depending on some custom logic.

**Comment by FakelsHub** [comment]
There was no Bugs. there was simply no logic.
For example, if a player was blocked, the critter did not switch to another target, due to the fact that this was not provided by the code.

**Comment by NovaRain** [comment]
Just curious, did you try the save?
Because if that's the case, I don't know why in my game the gecko can "correctly" switch to his new target (Sulik) after I move behind the cave wall (LOS is blocked, their outlines turn yellow).

**Comment by FakelsHub** [comment]
I'll try later.

**Comment by FakelsHub** [comment]
It really does not attack not on one version sfall, it looks like depends on where the player went(tile).

**Comment by NovaRain** [comment]
> 
> 
> It really does not attack, on any version sfall, it looks like depends on where the player went (tile).

Hmm, weird. I tried moving downward:
![Imgur](https://i.imgur.com/mHnuO7y.png)

**Comment by FakelsHub** [comment]
go to the wall in a straight line Southeast (direction 2) :)

**Comment by NovaRain** [comment]
> 
> 
> go to the wall in a straight line to the southeast (direction 2) :)

Like this?
![Imgur](https://i.imgur.com/bqOIVli.png)
the gecko still attacks Sulik after I pass my turn, strange. :\

**Comment by FakelsHub** [comment]
yes

**Comment by NovaRain** [comment]
> 
> 
> yes
> try again

I've tried several times in a row (load the save, move to the tile, pass my turn, if gecko attacks then reload the save and try again), and it acts "normal" every time. I don't think it's yet again related to my 24/7 PCs power-on time right?

**Comment by FakelsHub** [comment]
it is random

**Comment by FakelsHub** [comment]
> my 24/7 PCs power-on time right?

It may)

**Comment by NovaRain** [comment]
> 
> 
> it is random

I mean, maybe it's random in your guys' games, but for me it's consistent (on two different PCs).

> 
> 
> > my 24/7 PCs power-on time right?
> 
> It may)

Maybe there are some reason behind this and could be used as some sort of fix (other than employing a new set of logic)?

**Comment by burner1024** [comment]
There's no need to move anywhere, just pass the turn.

> There was no Bugs. there was simply no logic implementation.
> For example, if a player was blocked, the critter did not switch to another target, due to the fact that this was not provided by the code.

Not sure about that, because, [sometimes](https://www.loom.com/share/b8234378c2dc4324930f58cb05bf2acc) gecko does attack.

**Comment by NovaRain** [comment]
> Not sure about that, because [sometimes](https://www.loom.com/share/b8234378c2dc4324930f58cb05bf2acc) gecko does attack.

In my game the gecko always attacks Sulik right after passing my turn, and the two fights normally in following turns. From the video it seems the gecko constantly forgot(?) his target, either the player or Sulik who just attacked & hit him, in nearly every turn.

**Comment by burner1024** [comment]
Erratic behaviour is strange. Maybe build a debug sfall version, logging target selection?

**Comment by burner1024** [comment]
> Ради интереса можешь попробовать не официальную версию для "русских мужиков" где было доработано подобное поведение AI, когда криттеры не атаковали игрока и его напарника, настройки в секции [CombatAI]

Какую-какую?

**Comment by NovaRain** [comment]
I think it's TryToFindTargets.

**Comment by burner1024** [comment]
> EDIT: OK, I tested the save in a Windows VM and can reproduce the issue reliably.

What were you testing before? (Because I'm running on Wine.)

**Comment by NovaRain** [comment]
> 
> 
> > EDIT: OK, I tested the save in a Windows VM and can reproduce the issue reliably.
> 
> What were you testing before? (Because I'm running on Wine.)

I was testing in real Windows 7 on my two PCs. Just set up a VMware Player and installed WinXP/2000 for testing.

**Comment by burner1024** [comment]
My wine is set to win 7 emulation... x32 vs x64, maybe?

**Comment by FakelsHub** [comment]
> Does attack stack targets instead of keeping the latest one, by chance?

an attack called in for a critter having the "in combat" flag does not change its target.

**Comment by FakelsHub** [comment]
@burner1024
Вы там точно не забыли положитьх анимации для сулика, в ваших RPUP?
потомуто проблема какаято с открытием файла
что такое rpu_npc_armor.dat ? если я его удаляю то сулика нет, ищите проблему в файлах.

**Comment by NovaRain** [comment]
> 
> 
> My wine is set to win 7 emulation... x32 vs x64, maybe? Mine is win32.

I just reboot one of my PCs (Win7 x64) and can't reproduce the issue, but can reproduce it in 32-bit WinXP/2000 VMs. Now _that's_ weird.

**Comment by burner1024** [comment]
@FakelsHub `rpu_npc_armor.dat` это анимациии для мода NPC armor. Если ты их удаляешь, то конечно он пропадает. Вот [здесь](https://github.com/BGforgeNet/Fallout2_Restoration_Project/tree/master/components) компоненты лежат.

Indeed, it appears that `nmsulaao.frm` is missing. I checked RP 2.3.3 manual and installer versions, and some files from [Drobovik's database](https://www.mediafire.com/folder/2aheaguwymint/Welcome_to_Fallout_Database#jyian5ns9e5ql) - it's simply not there.

**Comment by NovaRain** [comment]
Yes it was missing from RP 2.3.3. Darek has posted the missing FRM on [NMA](https://www.nma-fallout.com/threads/up-and-rp-updates.217877/page-3#post-4337197).

**Comment by burner1024** [comment]
Oh, great. Added to the repo. Thank you for your help and sorry for disturbance.
