### ISSUE TITLE
Default animation setting

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#269]
[This](https://github.com/BGforgeNet/Fallout2_Restoration_Project/issues/24) issue got me thinking - maybe it would be useful to add a "default animation" setting? So that if an frm isn't found, the game would fall back to displaying something generic instead, along with an error message?
The reason is that crash messages are cryptic and hard to debug. And missing animations are often the reason. At least that would allow to detect them easily.

**Comment by NovaRain** [comment]
> The reason is that crash messages are cryptic and hard to debug

Currently the deliberate crash (interruption) from missing art file for critter will print a `Error: file not found: (supposed frm file name)` in debug log, so it's not _that_ cryptic.

**Comment by burner1024** [comment]
> Currently the deliberate crash (interruption) from missing art file for critter will print a `Error: file not found: (supposed frm file name)` in debug log, so it's not _that_ cryptic. That's also why I can find out which script is the cause quickly.

Ah ok, I didn't know that.

**Comment by Lexx2k** [comment]
Out of curiosity, is the crash "to stay" or will it get fixed at some point? Had the same issue now with the Robobrains and it's kinda shit having to disable DebugMode for that.

**Comment by NovaRain** [comment]
It's for notifying modders to add missing frames or don't set up incorrect animations for critters.
I think if you constantly get the "crash" you need to check the reason behind that.

**Comment by Lexx2k** [comment]
Well yeah, the reason is obvious. The Robobrain is missing the *al.frm because it doesn't exist in vanilla Fo1/2. It's most noticeable on the shotgun wielding critters, because they have to reload after 2 times using the rifle.
I can't add a .frm file that never existed unless I make my own. :>

**Comment by FakelsHub** [comment]
You want to be in the normal mode the game just crash and show error?

**Comment by NovaRain** [comment]
> 
> 
> You want to be in the normal mode the game just crash and show error?

I think he wants the game not crashing but proceed normally like in non debug mode.

**Comment by Lexx2k** [comment]
> I think he wants the game not crashing but proceed normally like in non debug mode.

Yes, this. 
Generally the issue is nothing super serious. I've set DebugMode=0 for now until I'm done with what I'm doing. As AllowUnsafeScripting is now independent of DebugMode, normal players should never notice it either.
It's just a bit of a convenience thing not having to disable DebugMode.

**Comment by FakelsHub** [comment]
> Yes, this
 
add a dummy file. :)

**Comment by Lexx2k** [comment]
Did this already, but then the game kept using it, which looked awkward (aa -> al, but now the robot swings its arms when reloading).

**Comment by FakelsHub** [comment]
> The old "wiggle the rifle for a few frames" looked better. :>

I have no animation reloading, it just continue shoot.
Use simply empty FRM without animation.

**Comment by burner1024** [comment]
Please consider this again.
It'd be great if there was something distinct, and communicating clearly to the player what the problem is, so that we don't have to play the guess fame.
[Here](https://github.com/BGforgeNet/Fallout2_Restoration_Project/issues/106) corpses were missing, and the only reason it was noticed is because we know in advance that they are supposed to be there. If not for that, we wouldn't even know there was a bug.

**Comment by NovaRain** [comment]
I think there should be a message about missing animation frames in the debug log?

**Comment by burner1024** [comment]
You won't look in debug log if you don't know that something's wrong.

**Comment by NovaRain** [comment]
Maybe enable the missing frame log to always display in the message window in game?

**Comment by burner1024** [comment]
You mean PDA? I think that'd work. "Error: missing animation XXXXXX.frm" or similar.

**Comment by egornovivan** [comment]
> Maybe enable the missing frame log to always display in the message window in game?

then you should probably enable the log for all lost files(acm, etc)

**Comment by Lexx2k** [comment]
Not sure if that is a good idea. Wasn't this enabled already before? And critters like plants, etc. were then spamming the message log with missing walking animations, etc.

**Comment by burner1024** [comment]
> Not sure if that is a good idea. Wasn't this enabled already before? And critters like plants, etc. were then spamming the message log with missing walking animations, etc.

First time I hear about it, got a link?

**Comment by NovaRain** [comment]
> First time I hear about it, got a link?

I got some `ERROR: File not found: art\critters\magunnlb.frm` logs after defeating Frank Horrigan and the combat ends. It seems like the allied turrets try to "walk".

**Comment by burner1024** [comment]
But that's debug log, not message log?
And I suppose they always tried to walk, but that never crashed the game? This must be at some other code point.

**Comment by egornovivan** [comment]
> > First time I hear about it, got a link?
> 
> I got some `ERROR: File not found: art\critters\magunnlb.frm` logs after defeating Frank Horrigan and the combat ends. It seems like the allied turrets try to "walk".

In such cases, can we put a transparent frm so that players do not complain?

**Comment by NovaRain** [comment]
> But that's debug log, not message log?

I got it in both debug log and in-game message window because I enabled the debug patch and sfall's debugging mode.

**Comment by egornovivan** [comment]
Well, probably the AI ​​of plants and turrets should be corrected so that they do not try to walk and only then turn on the log with a message

**Comment by Lexx2k** [comment]
Spending hours on fixing a problem that isn't one. :D

**Comment by egornovivan** [comment]
A temporary solution is to make a list of exceptions for the message log.

**Comment by FakelsHub** [comment]
An exception can be made for **Walking** animation messages. Since there is no need for these messages.
I will not do any other code complications for missing animations.

**Comment by Lexx2k** [comment]
I really see no point in this. Generic player won't be able to do anything with that, and for us it's not really a mystery.

**Comment by burner1024** [comment]
I feel like we're going in circles...

Turrets or whatever trying to walk is a different issue and is not the point here. They didn't crash the game. This is about about missing animations that crashed the game.

The point is that there was a clear indication that animation is missing: game crash. Now there isn't.
Generic player was able to _notice and report_ the issue. Now, unless it's a specific known in advance case like Klamath canyon corpses, they won't even get reported.

**Comment by FakelsHub** [comment]
Проблемы отсутствующих art-файлов и анимаций выводятся в лог.
Ты должен был попросить включить отладку для "Generic player" и посмотреть, что не так.
