### ISSUE TITLE
Bug 4.2.1

### ISSUE THREAD

**Issue by FakelsHub** [phobos2077/sfall#270]
https://github.com/phobos2077/sfall/blob/09d97464c878af6dac9785a0a4ad4d0b2e7fbe4b/sfall/Modules/BugFixes.cpp#L2454
It should be [4]
Make hotfix and release without new features.

**Comment by NovaRain** [comment]
Huh? with
`static const DWORD CorpseShotBlockFix_continue_loop[] = {0x48B99B, 0x48BA0B};`
Shouldn't the second element `CorpseShotBlockFix_continue_loop[1]` is 0x48BA0B?

**Comment by FakelsHub** [comment]
In assembler bytes, the second starts at 4

**Comment by NovaRain** [comment]
Oh damn, you're right. In asm code loop[1] is `0xB0048B9`. :(

**Comment by NovaRain** [comment]
I couldn't trigger the supposed crash after some quick tests, but obviously the game will crash when running that section of code (jump to wrong memory address). Hotfix is released.
