### ISSUE TITLE
Fallout 1 Support

### ISSUE THREAD

**Issue by shoober420** [phobos2077/sfall#271]
I know there’s some deprecated versions of stall for Fallout 1 out there, but it would be nice to have a maintained version of sfall for Fallout 1. Would you please consider, or maybe build one last final sfall for Fallout 1?

**Comment by FakelsHub** [comment]
No, this version of sfall is for Fallout 2 and is not suitable for Fallout 1.

**Comment by shoober420** [comment]
@FakelsHub 

I’ve seen at least two different versions from different people for sfall. Which one do you recommend?

I’m mainly interested in the d3d9 render from sfall, so that Wine/Proton wraps it to Vulkan. I know it’s a little excessive to desire that on such a old game that doesn’t barely demand anything in the graphical department, but I feel it’s best to convert all older d3d titles to use d3d9, for many other reasons.

**Comment by FakelsHub** [comment]
> I’ve seen at least two different Fallout1 versions from different people for sfall. Which one do you recommend?

use last from Crafty.

> I’m mainly interested in the d3d9 render from sfall,

Some kind of a hard question (probably because it question on English and I did not quite understand its essence)
sfall library (ddraw.dll) is a simple proxy library, it always references to the original ddraw.dll

**Comment by shoober420** [comment]
I’ve been reading about sfall, and it says it comes with a replacement d3d9 render to the original ddraw render. Although one could argue that a native d3d9 render is superior to a wrapped ddraw to d3d9.

**Comment by burner1024** [comment]
[FO1 in FO2](https://github.com/rotators/Fo1in2) is playable already, why'd you care about FO1 engine anymore? It's in the past.
