### ISSUE TITLE
Feature Request: Use Party Skills

### ISSUE THREAD

**Issue by darlinggj** [phobos2077/sfall#272]
Crafty's sfall2 v1.8.28 (EcCo_Patch) from https://www.nma-fallout.com/attachments/4-1b_fo2_ecco_patch-0-6-2-12-exe-zip.12844/  has ddraw.ini with these lines:

;Set to 1 to always use party members with highest level of skills (first aid, doctor, lockpick, traps, science, repair)
;Set to 2 to add time when party member used the skill first aid, doctor or repair on critters and add experience at successful using skill
UsePartySkills=1

I request that this option be incorporated into sfall's main branch here.

It only makes sense that the one with the highest skill in the party always perform or assist with that skill when it's needed.

For instance, I'd like to be able to use companion Myron's higher science skill to acquire the best brain for Skynet in SAD.

**Comment by NovaRain** [comment]
For script cases like getting the brain for Skynet it requires to modify the terminal's script to take party member skill into account, it has nothing to with built-in engine hacks.

**Comment by darlinggj** [comment]
I see. Looks like this is outside sfall, then. Thanks, I'll look elsewhere for getting SAD's terminal to check party skill in getting the brain.
