### ISSUE TITLE
game_time going negative?

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#275]
According to [UP sources](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/7e214f8a3f96909f2b2cda9a958f085e81e38a8f/scripts_src/sanfran/figuntbl.ssl#L157), there was some problem with game_time, it would go negative after 7 years. I imagine it would be fixed long ago by sfall, but I can't really find any reference in changelog, nor in sfall code.
Could you clarify whether there was such an issue and if yes, is it fixed now?

**Comment by NovaRain** [comment]
The issue exists because how 32-bit integer works and game_time returns the tick value in "signed" form, which is pretty much the norm in scripting.

**Comment by burner1024** [comment]
So it exists, and there are no plans to do anything about it?

**Comment by Lexx2k** [comment]
I'm actually surprised that this didn't lead to more bug reports. After how many people always QQ about the 13 years timer... guess I was right and barely anyone really plays this long.

**Comment by NovaRain** [comment]
> 
> 
> So it exists, and there are no plans to do anything about it?

I thought the scripting fix that checks negative tick value works, no?

**Comment by burner1024** [comment]
> 
> I thought the scripting fix that checks negative tick value works, no?

You mean in UP? I guess. But it's not in RP for some reason. Plus it's really overly scattered and verbose. I'd rather do something like
```c++
procedure game_time2 begin
  variable x=game_time;
  if x >= 0 then return x;
  else return (2^31-game_time)
end
```
And then do a mass replace.

**Comment by burner1024** [comment]
In fact, I don't see any other way to deal with this, given that `game_time` has over 500 invocations in UP alone, and killap's added his fixes to some 10% of that.
But what's the limit for int with sfall? Is it bumped to 64 bit? What about other types?

**Comment by NovaRain** [comment]
> But what's the limit for int with sfall? Is it bumped to 64 bit?

It's the same normal 32-bit int.

**Comment by burner1024** [comment]
Ah, then it's not possible to even represent anything over 2^31 and `game_time2` trick won't work...

**Comment by FakelsHub** [comment]
нужны безнаковые функции сравнения, если вы хотите проверять числа больше чем `2 147 483 647`.

**Comment by burner1024** [comment]
Да не то чтобы хотели особо, просто есть уже пять сотен сравнений.

**Comment by burner1024** [comment]
I don't see a way to work around this easily in scripts code or sfall. Basically, it would require adding a helper procedure that'll take this quirk into account and convert all time comparisons to use it.

Since there are many such comparisons, and 0 related bug reports, I think it's best to just leave it for now. If/when there will be some, I'll revisit.
