### ISSUE TITLE
Getting coordinates of existing interface windows?

### ISSUE THREAD

**Issue by Lexx2k** [phobos2077/sfall#276]
Can we somehow grab in script the actual position of the PipBoy / Dialog interface?

Yesterday I've updated to Win10, and here I've noticed that in window mode with a non-default window size, the "Tell Me About"-interface in dialog gets misaligned. Even enabling the window rounding fix didn't help it. I didn't experience this issue with Win7 ...

Anyways. 
This made me think if it wouldn't be easier and more fool-proof if we could grab the coordinates of existing windows? So that instead of calculating the window coordinates myself, I just do `get_x(PipBoy) + 50px` and `get_y(PipBoy) + 50px` to get the exact position where to draw my new window?

This way we would not have to deal with stuff like `get_screen_width / 2` AND we are sure the window is always in its right place. This would also reduce some additional checks for certain hi-res patch settings.

**Comment by FakelsHub** [comment]
this variant is suitable for getting? a little bit is not standard :)
```
pos = sfall_func1("get_interface_position", 1);
if (pos != -1) then begin
    x = (pos / 65536);
    y = (pos bwand 0xFFFF));
end
```
or make getting x/y through the array?

**Comment by FakelsHub** [comment]
or make separate?
"get_interface_xpos"
"get_interface_ypos"

**Comment by FakelsHub** [comment]
or so `sfall_func2("get_interface_position", win, x/y/w/h);` ?

**Comment by FakelsHub** [comment]
or make separate?
"get_interface_xpos"
"get_interface_ypos"

or so `sfall_func2("get_interface_position", win, x/y/w/h);` ?
this type probably through an array will be better

**Comment by Lexx2k** [comment]
I'm not an expert in the field, but I think `get_interface_xpos()` would be the easiest to use? 

Basically this:
`create_win("tellme_interface", (Scr_Width - 320), Scr_Height, 640, 190);`
would become this:
`create_win("tellme_interface",get_interface_xpos(DIALOG), (get_interface_ypos(DIALOG) + 290), 640, 190);`
... which would create the new window at 0,290px coordinates... relative to top left dialog interface position.

**Comment by NovaRain** [comment]
> or make separate?
> "get_interface_xpos"
> "get_interface_ypos"
> 
> or so `sfall_func2("get_interface_position", win, x/y/w/h);` ?
> this type probably through an array will be better

I suppose these can be macros?
```c
#define get_interface_xpos(win) sfall_func2("get_interface_attrib", win, 0);
#define get_interface_ypos(win) sfall_func2("get_interface_attrib", win, 1);
```

**Comment by FakelsHub** [comment]
> I suppose these can be macros?

so I did, but so far only for x/y, if necessary, can be add others.
'attrib` - hard word, can replace it with something else.

**Comment by FakelsHub** [comment]
`get_win_attributes` - ?

**Comment by wipe2238** [comment]
I'd go with single macro which accepts window id and property type as argument, and just provide available values as defines; modders can write their own wrappers.
```pascal
#define WINDOW_INFO_X 0
#define WINDOW_INFO_Y 1
#define WINDOW_INFO_W 2
#define WINDOW_INFO_H 3
variable x := get_window_info(windowId, WINDOW_INFO_X) + 50;
```
If someday someone wants to add info about buttons, just reuse same defines and call it a day
```pascal
variable buttonW := get_window_button_info(windowId, buttonId, WINDOW_INFO_W);
```
Easier to create/access array with all data in scripts, if anyone wants to cache that.
```pascal
variable win_info_cache := create_array(4,0), idx;
for( idx := 0; idx <= WINDOW_INFO_H; idx++ ) begin
    win_info_cache[idx] := get_window_info(windowId, idx);
end
// ...time passes... //
variable y := win_info_cache[WINDOW_INFO_Y];
```

**Comment by NovaRain** [comment]
While `get_window_attribute` works as it should, combining with HOOK_GAMEMODECHANGE and `get_game_mode` results in an unexpected issue according to Lexx:
```pascal
#include ".\headers\define.h"
#include ".\headers\sfall\sfall.h"

procedure start;
procedure hook_test;

procedure start begin
   if game_loaded then begin
      register_hook_proc(HOOK_GAMEMODECHANGE, hook_test);
   end
end

procedure hook_test begin
   variable
      event := get_sfall_arg,
      pmode := get_sfall_arg,
      x, y;

   if (get_game_mode bwand PIPBOY) then begin
      x := get_interface_x(WINTYPE_PIPBOY);
      y := get_interface_y(WINTYPE_PIPBOY);
      create_win("PIPWIN", x + 10, y + 20, 150, 200);
      SelectWin("PIPWIN");
      sfall_func5("draw_image", "art\\inven\\5mmap.frm", 0, 5, 10, false);
      ShowWin;
   end else begin
      DeleteWin("PIPWIN");
      display_msg("Pip-Boy closed.");
   end
end
```
The result was supposed to be like this:
![Imgur](https://i.imgur.com/w585fI0.jpg)

But instead it's:
![Imgur](https://i.imgur.com/UXjkl2o.jpg)

It seems game mode is triggered before UI window is actually created (so `get_window_attribute` can return proper values). Is there a better way to set up the scripted window? Or maybe the game_mode triggers need to be adjusted so flags are set after related UI windows are created?

**Comment by FakelsHub** [comment]
This is of course a jamb, all modes are basically started before the window is created.
 let it go back to using functions to get the screen size with an offset.

**Comment by FakelsHub** [comment]
Can make the function `window/interface_is_show(name)`

**Comment by FakelsHub** [comment]
Add new attribute to code
```c++
void sf_get_window_attribute(OpcodeContext& ctx) {
	fo::Window* win = fo::GetWindow(ctx.arg(0).rawValue());
	if (win == nullptr) {
		if (ctx.arg(1).rawValue() != 0) ctx.printOpcodeError("%s() - Failed to get the interface window.", ctx.getMetaruleName());	
		return;
	}
	if ((long)win == -1) {
		ctx.printOpcodeError("%s() - The number for the interface window is not correct.", ctx.getMetaruleName());
		return;
	}
	long pos = 0;
	switch (ctx.arg(1).rawValue()) {
	case 0: // window is show
		pos = 1;
		break;
	case 1: // x
		pos = win->wRect.left;
		break;
	case 2: // y
		pos = win->wRect.top;
		break;
	}
	ctx.setReturn(pos);
}
```

**Comment by NovaRain** [comment]
That's OK. I added a small delay before calling window creation procedure, and it works so far on my fastest spec.

**Comment by FakelsHub** [comment]
I finally redid some of the hooks for the game modes, so that the window is already created when the hook is called.

**Comment by NovaRain** [comment]
> 
> 
> I finally redid some of the hooks for the game modes, so that the window is already created when the hook is called.

All those `get_window_attribute` window related ones?

**Comment by FakelsHub** [comment]
pipboy, worldmap all inventory, the rest is not so important.

**Comment by NovaRain** [comment]
> 
> 
> pipboy, worldmap all inventory, the rest is not so important.

Oh, I thought it should be at least the seven window types (minus IfaceBar) in `fo::GetWindow`.

**Comment by Lexx2k** [comment]
Hope this doesn't have an influence on the window draw speed. Because we noticed that it can be quite slow already - take the PipBoy water timer note in etTu as example: If you have slower hardware or if you keep pressing P (hotkey) fast, you can see how slow the new window gets created/deleted.

**Comment by NovaRain** [comment]
Here's a list of tests I did to check if `get_game_mode` is faster than `get_window_attribute(winType)` in HOOK_GAMEMODECHANGE:
Test code, is supposed to draw a small blank window on the interface window:
```pascal
#include ".\HEADERS\DEFINE.H"
#include ".\headers\sfall\sfall.h"

procedure start;
procedure show_testwin;
procedure hook_test1;

variable winshown := false;

procedure start begin
   if game_loaded then begin
      register_hook_proc(HOOK_GAMEMODECHANGE, hook_test1);
   end
end

procedure show_testwin begin
   variable x, y;
   x := get_interface_x(WINTYPE_XXX);
   y := get_interface_y(WINTYPE_XXX);
   create_win("TESTWIN", x + 10, y + 20, 50, 40);
   SelectWin("TESTWIN");
   ShowWin;
   winshown := true;
end

procedure hook_test1 begin
   variable
      event := get_sfall_arg,
      pmode := get_sfall_arg;

   if (get_game_mode bwand YYY) then begin
      call show_testwin;
   end else begin
      if winshown then begin
         DeleteWin("TESTWIN");
         winshown := false;
      end
   end
end
```
Combinations and results:
1. WINTYPE_INVENTORY + INVENTORY/INTFACEUSE/INTFACELOOT - incorrect win position.
2. WINTYPE_DIALOG + DIALOG - OK.
3. WINTYPE_PIPBOY + PIPBOY - incorrect win position (already tested in post above).
4. WINTYPE_WORLDMAP + WORLDMAP - incorrect win position.
5. WINTYPE_IFACEBAR - OK, since it's pretty much always there when on local map in game.
6. WINTYPE_CHARACTER + CHARSCREEN - incorrect win position.
7. WINTYPE_SKILLDEX + SKILLDEX - incorrect win position.
8. WINTYPE_ESCMENU + ESCMENU - incorrect win position.

**Comment by FakelsHub** [comment]
> AUTOMAP - maybe add its window type to get_window_attribute?

For it, there is no global variable where the window's index is stored. need to do an additional hack.

**Comment by NovaRain** [comment]
> 
> 
> > AUTOMAP - maybe add its window type to get_window_attribute?
> 
> For it, there is no global variable where the window's index is stored. need to do an additional hack.

Oh, OK. I don't really need it myself, just giving suggestion because I thought it has a global variable like the rest of interface windows.

**Comment by FakelsHub** [comment]
It seems that need revert all the changes, and add a gamemode hook to create the window.

**Comment by NovaRain** [comment]
> 
> 
> It seems that need revert all the changes (for INVENTORY/INTFACEUSE/INTFACELOOT), and add a gamemode hook to create the window.

Huh? What's the issue with current implementation? And not WORLDMAP/DIALOG/PIPBOY flags?

**Comment by FakelsHub** [comment]
Yes, something like a new flag.
there are no problems yet, but I can see that after changing inventory modes, there are some restrictions for scripting.

**Comment by NovaRain** [comment]
> there are no problems yet, but I can see that after changing inventory modes, there are some restrictions for scripting.

It's a bit unclear. Could you give some examples about the possible restriction or how the new flag would help in such cases?

**Comment by FakelsHub** [comment]
Any actions that needed to be performed before the window was displayed.
In part, this applies not only to inventory windows.
The flag is necessary to indicate that the window was created (I think the existing SPECIAL flag is suitable for this).

**Comment by NovaRain** [comment]
> The flag is necessary to indicate that the window was created

So for example it would be:
```pascal
if (get_game_mode bwand ABCD) then begin
   x := get_interface_x(WINTYPE_XXX); // 0, window not created yet
   y := get_interface_y(WINTYPE_XXX); // 0, window not created yet
   // do things, but obviously go wrong
```
To:
```pascal
if (get_game_mode bwand (ABCD bwor NEWFLAG)) then begin // whether you want to re-use SPECIAL or a new flag
   x := get_interface_x(WINTYPE_XXX); // valid, window created
   y := get_interface_y(WINTYPE_XXX); // valid, window created
   // do things
```

**Comment by FakelsHub** [comment]
I thought that with an additional flag there would be a re-execution of the mode hook,
for cases: `if (get_game_mode bwand ABCD)` which is not good. :(
need to come up with another way to inform about the creation of the window.

**Comment by FakelsHub** [comment]
either make a new HOOK_INVENTORY for all inventory windows.
it seems this option will be ideal.

**Comment by NovaRain** [comment]
> 
> 
> either make a new HOOK_INVENTORY for all inventory windows.
> it seems this option will be ideal.

You mean keep the flags as they are, and a new hook to be triggered before creating all kinds of inventory windows?

**Comment by FakelsHub** [comment]
yes. and this is not a priority, I can think of another way.
