### ISSUE TITLE
Dividing a negative value results in a positive

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#278]
I'm not sure if this is common knowledge, but I couldn't find any reference. Dividing a negative integer results in a large positive number. Apparently, the numerator is treated as uint.

```cpp
#define SCRIPT_REALNAME "gl_g_test"
#include "headers/fo2tweaks/fo2tweaks.h"
#include "headers/rp/modreact.h"


procedure start begin
  if game_loaded then begin
    Karma_Perception := KARMA_PERCEPTION1;
    display_msg(parse_str_2("%1%", check_general_rep, 0));
    display_msg(parse_str_2("%1%", REACTION_BONUS_COMP_KARMA, 0));
    display_msg(parse_str_2("%1%", REACTION_BONUS_COMP_KARMA/KARMA_MODIFIER, 0));
    display_msg(parse_str_2("%1%", (-1*REACTION_BONUS_COMP_KARMA)/KARMA_MODIFIER, 0));
    display_msg(parse_str_2("%1%", -1.0*REACTION_BONUS_COMP_KARMA/KARMA_MODIFIER, 0));
  end
end
```

![Captura de pantalla de 2020-01-29 21-53-47](https://user-images.githubusercontent.com/1279852/73367795-99e22c00-42e2-11ea-83f4-f0e7c5a244f8.png)

Now I don't know how my scripts even work. Probably using float saves them in most cases.
Also, F2 devs [knew](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/blob/2234d5ec1c7be1c654092c13ed6c366c2d6782e4/scripts_src/headers/modreact.h#L299) about it and just added bandaids instead of fixing.

**Comment by NovaRain** [comment]
I think it's because the engine uses hex arithmetic.

**Comment by FakelsHub** [comment]
There is no such thing as "hex arithmetic", there are 0 and 1 for the processor, it does not know about any Hex numbers.
To divide numbers used `div` processor instruction, i.e. unsigned division.

**Comment by FakelsHub** [comment]
Now what do I need change the instruction to 'idiv'?
Such large numbers are not used in scripts, but negative ones are often used.

**Comment by NovaRain** [comment]
Hmm, I tried changing `div ebx` in `op_div_` to idiv, but it doesn't seem to work.

**Comment by FakelsHub** [comment]
```
cdq
idiv
```

**Comment by NovaRain** [comment]
OK, so it should be `SafeWrite32(0x46A51D, 0xFBF79990); // nop; cdq; idiv ebx;`

**Comment by FakelsHub** [comment]
Only why change it, it will disrupt the calculations.

**Comment by NovaRain** [comment]
> 
> 
> Only why change it, it will disrupt the calculations.

You mean it might break the calculation in existing scripts?

**Comment by FakelsHub** [comment]
Yes.

**Comment by NovaRain** [comment]
I think the incorrect result (got a large positive number) from vanilla behavior would bug some scripts in the past (like negate operator for floats). I'm not sure if there is any script in vanilla/RP/TCs depends on the incorrect behavior. Does changing it to signed division make the current `-1*(-1*` "bandaid" by the devs not working?

**Comment by FakelsHub** [comment]
Сan add a character for the signed division to the compiler. like a new '-/' sign )))
At the same time, can add >> << shift operations.

**Comment by FakelsHub** [comment]
> -1*(-1* "bandaid" by the devs not working?

Yes, it won't work.

**Comment by NovaRain** [comment]
> Сan add a character for the signed division to the compiler. like a new `-/` sign )))

For floats the `op_div_` does using signed division (-10.0 / 5.0 = -2.0), I think it should be the same for integers.

**Comment by FakelsHub** [comment]
Well, you need to convert `int > floats > int` every time

**Comment by NovaRain** [comment]
> 
> 
> Well, you need to convert `int > floats > int` every time

You mean for the current `op_div` (unfixed)?
Guess for integer case it can't be simply treated as a direct fix, because there's already bandaids in existing scripts for that, unlike floats.

**Comment by FakelsHub** [comment]
Funcx is not very convenient in this regard for division. Just like a unsigned comparison with a procedure, is not convenient to use.

**Comment by FakelsHub** [comment]
Shift functions via funcx will also be inefficient and slower to run (since the funcX function is slower than the direct handler).
it is also faster to use divide or multiply operations for shifting than to write Maros.

**Comment by FakelsHub** [comment]
> You mean for the current op_div (unfixed)?

yes

**Comment by burner1024** [comment]
> Hmm, right, the bandaid becomes a source of bug if `op_div` is "fixed".

Sorry, I don't understand, what's the bug?

**Comment by NovaRain** [comment]
> 
> 
> > Hmm, right, the bandaid becomes a source of bug if `op_div` is "fixed".
> 
> Sorry, I don't understand, what's the bug?

Maybe I should say the bandaid become unneeded. If `op_div` is fixed to use the signed division, the existing bandaid will turn all previously correct results (negative reaction_bonus_karma) to positive values.

**Comment by NovaRain** [comment]
> 
> 
> > Hmm, right, the bandaid becomes a source of bug if `op_div` is "fixed".
> 
> Sorry, I don't understand, what's the bug?

No, it's me being stupid for getting numbers wrong earlier.
```
// if op_div_ is fixed with SafeWrite32(0x46A51D, 0xFBF79990);
tmp := -10; // emulate negative REACTION_BONUS_COMP_KARMA value
val := 5;
display_msg("Val: " + (tmp / val));
display_msg("Val: " + (-1 * (-1 * tmp / val))); // bandaid by F2 devs

Results:
Val: -2
Val: -2
```
Yeah, it doesn't seem breaking stuff.

**Comment by FakelsHub** [comment]
You can't fix op_div, you will break existing calculations. You can't check all scripts.

**Comment by NovaRain** [comment]
> 
> 
> You can't fix op_div, you will break existing calculations. You can't check all scripts.

Fine, just wonder what's the difference between it and the negate operator fix for float years ago. So I guess it will be:
* `op_div` - keep as it is: signed division for float and unsigned for int
* add an operator do signed division for both float and int (`-/`?)
* keep the macros (since they work if op_div isn't changed), or add unsigned comparision operators and remove macros?

**Comment by FakelsHub** [comment]
> difference between it and the negate operator fix

this is not a very used operation

**Comment by FakelsHub** [comment]
> add an operator do signed division for both float and int (-/?)


need to think of another way, is not very beautiful shape for the division.
Maybe just use a short keyword 'div' (-3334 div 567)?
or symbols `:` as used in the formulas often?
(But with the addition of characters in the compiler I am having difficulties, so I was not able to add `&&` and `||` )

**Comment by NovaRain** [comment]
> need to think of another way, is not very beautiful shape for the division.
> Maybe just use a short keyword `div` (-3334 div 567)?
> or symbol `:` as used in the formulas often?

I'd choose the short keyword `div`, since `:/` doesn't look good IMO (also it looks like an emoticon).

**Comment by FakelsHub** [comment]
I meant to single `:` instead of a couple

**Comment by NovaRain** [comment]
> 
> 
> I meant to single char `:` instead of a couple

Oh, OK. But I still prefer the short keyword, because it's a bit more straight forward than the colon symbol.

**Comment by Lexx2k** [comment]
Make it this:
`( ͡° ͜ʖ ͡°)`

**Comment by FakelsHub** [comment]
> Oh, OK. But I still prefer the short keyword, because it's a bit more straight forward than the colon symbol.

I'll try adding both variants.

**Comment by NovaRain** [comment]
> 
> I'll try adding both variants.

That would be nice. But which one will be used in decompiled scripts from int2ssl?

**Comment by FakelsHub** [comment]
here I do not care, div as a more visual

**Comment by Mingun** [comment]
> You can't fix op_div, you will break existing calculations. You can't check all scripts.

Can you add preprocessor directive to compiler that change how this operator behaves? Like `'use strict';` in JS?

**Comment by burner1024** [comment]
It's true that changing the operator is not backwards compatible. However the only scripts that would be broken are the ones that use this feature intentionally, and honestly, I can't even imagine such scenario.
I would say it's more likely that existing calculations will be _fixed_.

Whatever path is chosen: new op or fixing old one, it would really be helpful to have it centralized, like a flag or an option. Because replacing every division op in every UP/RP script to make sure they really do what they are supposed to would be really tedious.

**Comment by NovaRain** [comment]
> I can't even imagine such scenario.

The only scenario using the uint division behavior intentionally is probably the new unsigned_comp() procedure, Because it requires both a and be to be treated as unsigned.

**Comment by FakelsHub** [comment]
> Because replacing every division op in every UP/RP script to make sure they really do what they are supposed to would be really tedious.

Утомительно проверять все скрипты во всех модах.
Если делать исправление для текущей функции, то то в таком случае sfall должен быть выпушен отдельной версией, чтобы обкатать все игры и удостовериться, что после фикса ничего не сломалось в расчетах.

**Comment by FakelsHub** [comment]
> Can you add preprocessor directive to compiler that change how this operator behaves?

типа опции для компилятора, чтобы все '/' заменились на div (для новой реализации)?

**Comment by Mingun** [comment]
Да. Можно также сделать, чтобы опция включалась только при компиляции определенных файлов, если в начале этих файлов включить специальную директиву. Тогда те файлы, которые к ней не готовы, будут компилироваться со старым поведением, а все новые и исправленные смогут компилироваться с более логичным новым. Я ведь правильно понимаю, что вы можете технически это сделать?

**Comment by burner1024** [comment]
> The only scenario using the uint division behavior intentionally is probably the new unsigned_comp() procedure, Because it requires both a and b to be treated as unsigned.

I think so too. If you want to be really cautious, maybe add a switch now, and drop it in 5.0, making default.

> Утомительно проверять все скрипты во всех модах.
> Если делать исправление для текущей функции, то в таком случае sfall должен быть выпущен отдельной версией, чтобы обкатать все игры и удостовериться, что после фикса ничего не сломалось в расчетах.

Я понимаю о чем ты, но дело в том, что обкатывать глобальные изменения особо некому. Единичные правки разработчики могут тестировать сами, но проверять каждый скрипт это надо игру целиком проходить. Поэтому в подобных случаях основное тестирование ляжет на пользователей, как ни крути номерами версий.
Ну а вообще да, принято увеличивать мажорную версию при несовместимых изменениях.

**Comment by FakelsHub** [comment]
Я думаю что нужно исправить текущий `op_div`, а исправление сделать через опцию.
Потому, что есть не большое не соответствие, оптимизатор в компиляторе оптимизирует деление со знаком.
А новый опкод `div` будет беззнаковым делением, это внечет ясность между idiv/div.

I think that need to fix the `op_div`, and fixed it through the option.
Because there is not a large mismatch, the optimizer in the compiler optimizes signed division.
The new opcode `div` will be a unsigned division, this will make it clear between 'idiv` and 'div'.

**Comment by NovaRain** [comment]
> 
> I think that need to fix the `op_div`, and fixed it through the option.
> Because there is not a large mismatch, the optimizer in the compiler optimizes signed division.
> The new opcode `div` will be a unsigned division, this will make it clear between `idiv` and `div`.

So it would be an option for op_div fix (the SafeWrite32 earlier?), a new `div`/`:` operator for unsigned division, and unsigned comparison operators?

**Comment by FakelsHub** [comment]
I think so.
I need to think about it.

**Comment by FakelsHub** [comment]
Why are we so stupid and not who did not offer us this variant.
```
procedure div_func(variable val0, variable val1) begin 
   if (val0 < 0) then return -(-val0 / val1);
   return val0 / val1;
end
```
I'm not sure, but I think the DivisionOperatorFix option should be disabled.

**Comment by NovaRain** [comment]
> I think the DivisionOperatorFix option should be disabled.

Well, oops. Or just keep things as they are now? Since we've already implemented the `div` opcode that made this macro unneeded.

**Comment by FakelsHub** [comment]
It seems that the option does not disrupt the operation of this method.

**Comment by NovaRain** [comment]
> 
> 
> It seems that the option does not disrupt the operation of this method.

IMO with this universal signed division macro it's still better to leave the option enabled (i.e. vanilla `/` operator does signed int division by default), because I think people would intend to use signed int division in most of cases. And we've already had the new `div` operator to deal with more rarely used unsigned int division. Of course it doesn't hurt to include the macro in lib.math.h.
