### ISSUE TITLE
QuestList.cpp fails to compile

### ISSUE THREAD

**Issue by wipe2238** [phobos2077/sfall#279]
```cpp
#define WINVER       0x502
#define _WIN32_WINNT 0x502
```
When added to `stdafx.h` (to make sure nothing is used what XP cannot handle), compiler complains about `'MAXINT': undeclared identifier`

**Comment by NovaRain** [comment]
I suppose all `MAXINT` can be replaced with `INT_MAX` which is available in `limits.h` and isn't effected by `_WIN32_WINNT` value, or you can add `#define WINDOWS_ENABLE_CPLUSPLUS` before WINVER.

**Comment by wipe2238** [comment]
Yeah, it works fine with `WINDOWS_ENABLE_CPLUSPLUS`, thanks.
