### ISSUE TITLE
Hotkey for switching current item mode

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#28]
Lots of clicking goes into "single/aimed/burst/reload" mouse right click routine. If possible, a hotkey for it would be more efficient and thus greatly appreciated.

**Comment by phobos2077** [comment]
A hotkey for what exactly? Switching to the next mode?

**Comment by NovaRain** [comment]
There's already a hotkey "N" for changing active item mode.
Also a hotkey "M" for changing mouse cursor modes (command/movement/targeting).

**Comment by burner1024** [comment]
Damn... I can't believe it. And all this time I was clicking. Sorry for bothering you, then.
