### ISSUE TITLE
Using binocular on dead critter costs AP

### ISSUE THREAD

**Issue by Lexx2k** [phobos2077/sfall#280]
Hilarious bug in Fo2: 

![lol](https://i.imgur.com/g8n23wj.png)

Kill any critter that has the "no loot"-flag. Step on the body or get very close to it, then use the binocular. You will use up the action points that would be required to loot the body.

Can we fix that? :>

**Comment by FakelsHub** [comment]
We don't have that problem.

**Comment by Lexx2k** [comment]
I tested this in the mapper in etTu and in RP, so it's not related to our ddraw.dll (Sfall doesn't work at all in the mapper). Just step on the corpse and use binoculars while in combat - this should take remove the action points.

**Comment by FakelsHub** [comment]
ok

**Comment by NovaRain** [comment]
Yep, looks like the engine thinks the player was trying to "loot" the corpse (by simply clicking) and subtracts 3 AP before checking critter flags.
