### ISSUE TITLE
Black edges bug with the HRP

### ISSUE THREAD

**Issue by Lexx2k** [phobos2077/sfall#282]
Not sure how much we can do about this, but let's try anyway...

With some maps in etTu I've noticed that the black screen edges of the HRP are bugged on some maps: If you enter a map with a big edge area, then go to an elevation with a smaller edge area, the outside borders will still show the previous map until you scroll around (if you can scroll), or reload, etc. 

Basically, switching the map elevations will not refresh the black borders drawn on screen. Can't make screenshots of it, because there everything is alright. 

When we noticed this the first time in etTu, we made a shitty workaround that would [refresh the screen](https://github.com/rotators/Fo1in2/blob/46a6e233aa25706b6d2dd780f39af5375a309d37/Fallout2/Fallout1in2/Mapper/source/scripts/headers/voodoo.h#L187) in the map_update proc (map_enter was too early and didn't have any effect). Now this was when I still thought it's only one map where this bug appears... now I know it happens everywhere. A good example is the Cathedral tower maps, or any of the Vault maps if you are running a HUGE screen resolution.

I don't know of any examples like this in Fo2 (haven't played it in a long time, tbh), but maybe there the map edges are either always consistent, or it just doesn't feature that many smaller / bigger map elevations.

To get back to our `VOODOO_display_win_redraw` ... it solves the issue, but I don't think it's a good solution to redraw the window in every map_update cycle... besides, I don't really want to add it to every map script, because technically this issue can appear in every location with multiple elevations ... it just depends on the screen resolution you are playing with.

**Comment by FakelsHub** [comment]
Record a video of how this happens.
ps. maybe it's a win10 problem

**Comment by Lexx2k** [comment]
Here is a video of the problem in action: 
https://www.youtube.com/watch?v=KwAzANLtIHU

As said, it only happens if you switch elevations in the same map. Loading a new map works fine.

**Comment by FakelsHub** [comment]
This problem seems to be solved by enabling DX9 mode in sfall.

**Comment by Lexx2k** [comment]
Just a heads up: I am using `Mode=4` (DX9 fullscreen) in ddraw.ini, and `GRAPHICS_MODE=2` in fo2_res.ini on Win10, but I still experience this issue.

**Comment by FakelsHub** [comment]
Do you have a save where this problem consistently appears?

**Comment by Lexx2k** [comment]
Here's a savegame from Adytum, just enter one of the 3 basements in that map. The map edges are very small here, so even on lower resolutions the bug should be visible.

[SLOT07.zip](https://github.com/phobos2077/sfall/files/5044297/SLOT07.zip)

**Comment by FakelsHub** [comment]
> My workaround right now is to use our custom VOODOO_display_win_redraw macro to redraw the screen on every map_update. This works reliably, but of course it refreshes constantly...

I hope this shit wasn't in the release?))

**Comment by Lexx2k** [comment]
It's not and it's likely not our worst piece of code.

**Comment by Lexx2k** [comment]
Just tested it and it's working now. Removing the floating text on elevation change is good as well.
