### ISSUE TITLE
The problem with HOOK_ONDEATH

### ISSUE THREAD

**Issue by FakelsHub** [phobos2077/sfall#283]
it seems there is a difference in the runs of the hook when you have, and no party members.
It seems that if there is a party member, then the hook is performed before dropped items from the explosion.

**Comment by FakelsHub** [comment]
при тестах крючка и взрывчатки в бою вскрылись проблем со взрывом происходящем в бою, 
взрыв происходит в как-то не стабильно в начале хода, может произойти посреди во время хода противника или в конце хода, от этого происходит много багов, от анимационных до крашей игры.
вероятно от этого и появляется [баг с получением опыта у напарниках](https://github.com/phobos2077/sfall/issues/223#issuecomment-587112378) при переходе контроля к ним во время взрыва.

*dirty translation:*
when testing the hook and explosives in battle revealed problems with the explosion occurring in battle, 
the explosion occurs in a way that is not stable at the beginning of the turn, can occur in the middle during the opponent's turn or at the end of the turn, this causes a lot of bugs, from animation to game crashes.
probably from this and appears [bug with getting experience from partners](https://github.com/phobos2077/sfall/issues/223#issuecomment-587112378) when passing control to them during the explosion.

**Comment by NovaRain** [comment]
Not sure if I understand you correctly, are you saying any explosion in combat (by weapon attacks like grenade or rocket, or a bomb exploded due to timer) is unstable, or it's specifically for "explosion death" (normal or blown to pieces)?

**Comment by FakelsHub** [comment]
I just set the timers and a series of explosions occurs during the battle, damaging and tearing the Npc, while I get various troubles in game :-)

**Comment by FakelsHub** [comment]
Неприятности которые я получил:
1. Удаление установленной взрывчатки, если на нее кто-то наступил :-) 
2. Стояцие трупы после взрыва, если в момент взрыва, врага атакует мой напарник.
3. Получение очков опыта напарником в момент взрыва ”за уничтожение врагов”.
4. Иногда просто происходит краш игры, по непонятной причине.
======
The trouble I got:
1. Removing installed explosives if someone stepped on them :-) 
2. Standing corpses after the explosion, if at the time of the explosion, the enemy is attacked by my partner.
3. Getting experience points for your partner at the time of the explosion ”for destroying enemies".
4. Sometimes the game just crashes, for some unknown reason.

**Comment by FakelsHub** [comment]
Maybe it's the case in my test map, which I always find strange trouble in tests :-)

**Comment by FakelsHub** [comment]
You can check the behavior of the hook when exploding and destroying the armor of the npc.?
I get different results in tests, sometimes the armor is removed and sometimes not.
armor is removed if the explosion occurs at the beginning of the turn, i.e. the function of dropping items is performed after the hook.
You can take the script from issue f1

**Comment by NovaRain** [comment]
I'm not sure what you mean by "the explosion occurs at the beginning of the turn".
I checked the script (newest version with ondeath hook) in RP, using my party members for testing (told them to leave party). I start the combat and use rocket launcher to kill them.
If they died in "blown to pieces" animation, the armor is not removed and dropped on the ground. If they died in other animations (i.e. with lower violence level, or knock them down before killing them with rockets), the armor is removed as it should.

**Comment by FakelsHub** [comment]
I was interested in tests with dymamite explosives, not explosions of grenades and rocket.

**Comment by NovaRain** [comment]
> 
> 
> I was interested in tests with dymamite explosives, not explosions of grenades and rocket.

Oh, OK. I never tested explosives extensively like you.

**Comment by FakelsHub** [comment]
> I think ONDEATH is not the ideal choice for case like this, which requires checking equipped items before the engine starts running death processes that might "unequip" items for certain deaths (its description clearly says "runs after a critter dies").

Sometimes the hook for dynamite explosions is executed before dropping items.

**Comment by FakelsHub** [comment]
I think there are no more problems with this. 
Except for the case of triggering the hook before dropping items (by the way, this needs to be checked again, since the moment when the explosion occurs from the timer explosives has changed).

_Кроме случая срабатывания крючка до сбрасывания предметов (кстати это нужно повторно проверить, так как изменился момент когда происходит взрыв от заложенной взрывчатки)._
