### ISSUE TITLE
4.2.3 fails to compile script

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#284]
FO2tweaks [damage mod script](https://github.com/BGforgeNet/FO2tweaks/blob/master/source/gl_g_damage_mod.ssl) compiles fine with `compile.exe` from 4.2.2 modderspack, but [fails](https://travis-ci.org/BGforgeNet/FO2tweaks/builds/652936282) on 4.2.3.

**Comment by wipe2238** [comment]
Wasn't `div` added as operator recently? You still have [variable](https://github.com/BGforgeNet/FO2tweaks/blob/3730e2bca0a7a2c2e64e6b15783b1d3357a26b1e/source/gl_g_damage_mod.ssl#L199) named like that in there.

**Comment by NovaRain** [comment]
Yep like wipe said, changing "div" variable in fix_ammo_stats procedure to some other names will solve the problem.

**Comment by burner1024** [comment]
Ugh, I'm stupid I guess. Thank for pointing it out.
