### ISSUE TITLE
Expose SafeMemSet() to scripts

### ISSUE THREAD

**Issue by wipe2238** [phobos2077/sfall#285]
Would be nice if it could be done by adding optional `length` argument to existing opcode, `write_byte(address, value, length)`. Maybe same thing could be added to `write_short`/`write_int` for consistency, but that's not that useful i think.

Use case is to clear carefully selected parts of memory for adding custom fixes/patches in mod, and use them as live examples when suggesting changes here. Benefit over doing that in [custom] ddraw.dll is that such suggestions can be tested with any Fallout2 install.

---

While it is possible clear required memory [in own proc](https://github.com/rotators/Fo1in2/blob/4df066093d5c862398692c8dc78295aa720a205d/Fallout2/Fallout1in2/Mapper/source/scripts/headers/voodoo.h#L13-L36), it takes awful amount of calls to clear even a small area and it gets worse and worse with each extra byte 😢

Dunno how useful it can be, but we [ported `write_X` functions](https://github.com/rotators/sfall/blob/ac66ffade6e67529f19049dc48576ab9e4a9d1e5/sfall/Modules/Rotators.Script.cpp#L300-L339) to C++ some time ago, maybe it could be done here too.

**Comment by FakelsHub** [comment]
I don't see the sense of this function, use your method to call the cleanup function `call Voodoo_MemSet`. :-) 

ps: you are suffering some nonsense using the occupied space of fallout2.exe to fix its own code, these fixes will later be implemented in sfall.
No one will write mods using this low-level method.

**Comment by wipe2238** [comment]
> No one will write mods using this low-level method.

We do.

**Comment by NovaRain** [comment]
I think it can be done with `for` loop in script? Like:
```pascal
variable patch := [0xBA, 0xDC, 0x0F, 0xFE, 0xE0, 0xDD, 0xF0, 0x0D];
for (i := 0; i < 8; i++) begin
   write_byte(addr + i, patch[i]);
end
```

**Comment by wipe2238** [comment]
That's even more `write_X` calls than what we have now - majority of area is cleared with `write_int`, `write_short`/`write_byte` are used to clear leftovers (if there are any). We don't have problem with writing patch, i just wanted non-shitty way to clear whole area before patch code is written, that's all.

I still fail to understand how having `AllowUnsafeScripting` was/is fine to have since years, but actually using it and/or suggesting minor improvements to it is seen as a crime.
