### ISSUE TITLE
Money not showing in dialog

### ISSUE THREAD

**Issue by wipe2238** [phobos2077/sfall#286]
Minor visual glitch that happens after going to the barter screen and then back. The amount of bottle caps is not shown anymore, after clicking on any dialog answer the value is shown again.

<img src="https://i.imgur.com/fw3yRu3.png"/>

---

[Working fix](https://github.com/rotators/Fo1in2/blob/0015846e7f667c3a421bb4bc0b8a894401a77a5a/Fallout2/Fallout1in2/Mapper/source/scripts/headers/voodoo.h#L167-L182) (unsafe scripting, asm as comments)

**Comment by Lexx2k** [comment]
But this should be fixed already?

**Comment by FakelsHub** [comment]
Your fix has already been added to sfall.

**Comment by Lexx2k** [comment]
Huh, when? I didn't even notice.

**Comment by FakelsHub** [comment]
This is not yet pushed to the remote repository.

**Comment by Lexx2k** [comment]
So it's not yet added to Sfall. :>

**Comment by NovaRain** [comment]
> 
> 
> This is not yet pushed to the remote repository.

I think it's easier for me to work with if you can push individual commits with a more real-time fashion, instead of pushing one "merged" commit with many code changes, or lots of commits at once.
