### ISSUE TITLE
Fill_W behavior like in Fallout 1

### ISSUE THREAD

**Issue by ghost2238** [phobos2077/sfall#287]
As mentioned in https://github.com/rotators/Fo1in2/issues/16. Is there any interest in adding it to sfall?

Here's some code that implements it: https://raw.githubusercontent.com/ghost2238/sfall-asm/master/patches/fo1in2/10_fill_w.asm

**Comment by NovaRain** [comment]
I tested the fix with setting all sub-tiles in [Tile 10] of vanilla FO2 to `Fill_W`, it should work for Et Tu.

**Comment by ghost2238** [comment]
Many thanks and nice code for the implementation! We'll test and see if it works as expected in Et Tu.
