### ISSUE TITLE
START_VALID_ADDR and END_VALID_ADDR

### ISSUE THREAD

**Issue by ghost2238** [phobos2077/sfall#288]
UnsafeScripting is needlessly crippled by <code>START_VALID_ADDR</code> and <code>END_VALID_ADDR</code> which are currently set to <code>0x410000</code> -<code>0x6B403F</code>.

Would be really awesome if these could be configured in the ini file, with a -1 or 0 to disable the limit altogether. 

This would allow the use of vanilla sfall memory functions for reading/writing/calling addresses in other modules than fallout2.exe. Even dynamically allocated memory could be used. 

The alternative of making it a requirement that the _audacious_ people who want to use this marvelous functionality reinvents or patches the sfall code to allow themselves the full range of usage is suboptimal in my very humble opinion.

**Comment by wipe2238** [comment]
`call_offset` is even more limited, could be configurable as well...
