### ISSUE TITLE
Sfall version detection

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#29]
Is it possible to detect sfall version in ddraw.dll? The reason I'm asking is that I've a mod that requires sfall 3.5+. I want to bundle the last version with the mod, and upgrade ddraw.dll if required. However, the only information I have about the version is a comment in ddraw.ini, which I'd rather not rely upon.

Or, am I overthinking this too much and it's always safe to upgrade ddraw.dll (leaving ddraw.ini intact, to preserve user settings)?

**Comment by phobos2077** [comment]
Check out dll version information, it should state correct version number.

**Comment by burner1024** [comment]
Yes, it does. Thank you.
