### ISSUE TITLE
Allow HOOK_GAMEMODECHANGE to run before loading game

### ISSUE THREAD

**Issue by wipe2238** [phobos2077/sfall#290]
```pascal
procedure ExitHook
begin
    variable exit_ := get_sfall_arg;
    if(exit_) then
    begin
        display_msg("*** EXIT ***"); // saved in debug.log
    end
end

procedure start
begin
    if(game_loaded) then
    begin
        register_hook_proc(HOOK_GAMEMODECHANGE, ExitHook);
    end
end
```

Currently hook runs only before exiting to main menu - it would be nice if it could run before loading game while already playing. From script perspective both events (exiting or loading) are same thing, but only one of them works.

**Comment by FakelsHub** [comment]
Concept: sfall scripts do not work Before loading.

**Comment by wipe2238** [comment]
> loading game while already playing

I know i can't run script from main menu :P but this is about hook running before QuickLoad or CTRL+L and selecting save slot.

**Comment by FakelsHub** [comment]
I do not understand your issue, for what purposes to perform the hook before loading?
I can not think of a situation where it may be needed.
After loading all data is destroyed, and the scripts are reloaded, what's the point of running this hook?

**Comment by FakelsHub** [comment]
I wanted to add this, but it was not a priority, because there was no real event suggested where this should be applied.

**Comment by wipe2238** [comment]
Huh, sorry, forgot about this one.

I wanted this one to always free memory which was nmalloc'd on game start. Without knowing that game is reloaded there was a small memory leak, as i had to blindly (re)alloc data every time...

That's no longer a problem, as later sfall changes allowed to rewrite and simplify whole thing; don't think there's any reason left to work on this as of today - regular scripting doesn't really need info like that.
