### ISSUE TITLE
Default argument takes value from non-default arguments

### ISSUE THREAD

**Issue by wipe2238** [phobos2077/sfall#291]
```pascal
procedure test(variable a, variable b, variable c := 0)
begin
    if(c == 0) then
    begin
        display_msg("OK");
    end
    else
        display_msg("VERY NOT OK :: c="+c);
end
```
If procedure looks exactly like code above, `call test(2,1);` results in error with `c=2`
If procedure uses all arguments, behavior changes:
```pascal
display_msg("a=" + a + " b=" + b + " c="+c);
```
Adding this at top/bottom of procedure (or tweaking "VERY NOT OK" to print `a` and `b`) makes it work correctly, for gods knows what reasons.

**Comment by FakelsHub** [comment]
source
```js
procedure test(variable a, variable b, variable c := 0)
begin
    if(c == 0) then
    begin
        display_msg("OK");
    end
    else
        display_msg("VERY NOT OK :: c="+c);
end
procedure start begin
   call test(1, 2);
end
```
after decompile script
```
procedure start;
procedure test(variable arg0, variable arg1, variable arg2);

procedure start begin
   call test(1, 2, 0); // all GOOD
end

procedure test(variable arg0, variable arg1, variable arg2) begin
   if (arg2 == 0) then begin
      display_msg("OK");
   end
   else begin
      display_msg("VERY NOT OK :: c=" + arg2);
   end
end
```

**Comment by wipe2238** [comment]
What the- i can't reproduce it anymore and i don't know why oO

It's been too long to tell what changed in script, but i'll try to get .ssl **and** .int when/if i spot it next time.

**Comment by FakelsHub** [comment]
There is no error on the part of the compiler, the script is compiled correctly. Then only the problem in the interpreter. if this error of course exists.
