### ISSUE TITLE
remove_script inside pickup_p_proc requires two pickups

### ISSUE THREAD

**Issue by JuanCruzSanFran** [phobos2077/sfall#292]
```
procedure pickup_p_proc begin
   remove_script(self_obj);
end
```

First one stops prematurely and second one picks up item with removed script

![remove_script](https://user-images.githubusercontent.com/61908392/76517969-58ab7300-646f-11ea-99e5-b2cd3ecc8522.gif)

**Comment by NovaRain** [comment]
I think it's because the script is terminated by calling `remove_script`, which causes the execution of pickup_p handler being interrupted, so you got the pickup animation abruptly stopped for the first try.

**Comment by JuanCruzSanFran** [comment]
Is this an intended behaviour? @burner1024 suggested it was a bug, so I filed it as an issue.

**Comment by NovaRain** [comment]
I'd say it's normal since your code tries to terminate & remove itself from the object in the middle of the execution of pickup_p handler and its related animation. Honestly I wouldn't code the script like that in the first place.

**Comment by JuanCruzSanFran** [comment]
Gotcha, thanks!

**Comment by FakelsHub** [comment]
Strange behavior, looks like a bug.

**Comment by NovaRain** [comment]
Hmm, to me it seems normal that the engine stops the script before removing it from an object. It just happened to be in the middle of some action procedure.

**Comment by FakelsHub** [comment]
The strange thing is that the pickuping of the object is interrupted as if it was forbidden from the script.
For me, removing the script does not have to affect the pickuping of the object.

**Comment by NovaRain** [comment]
I guess it might need to check how `obj_pickup_` or `scr_remove_` work?
