### ISSUE TITLE
HOOK_DESCRIPTIONOBJ is named misleadingly

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#293]
Took me while to figure out that it only works on items...
I guess it's my fault for not paying enough attention to the docs, but still I think it would be better to name it something like `HOOK_DESCRIPTION_ITEM` instead. Or make it work on all objects.

(As a side note, I tried to use `HOOK_STDPROCEDURE` to override look_at/description procs for scenery object, and it doesn't even trigger - I presume because they either don't have a script, or their scripts don't contain these procedures?)

**Comment by FakelsHub** [comment]
Крючек был придуман, чтобы можно было динамически выводить в инвентаре игрока какие-либо дополнительные параметры для предметов.

С таким подходом к модификациям как у тебя, тебе нужно разработать собственный инструмент (патчер), который будет заменять в текстовых файлах строчку на вашу.

Ну или тут, нужны совсем другие функции для подмены, типа тех же функций виртуальных фалов, которые толком не работают.

**Comment by burner1024** [comment]
Ну мое предложение хотя бы назвать его нормально, чтобы было ясно, что только на предметы работает.

**Comment by NovaRain** [comment]
> (As a side note, I tried to use `HOOK_STDPROCEDURE` to override look_at/description procs for scenery object, and it doesn't even trigger - I presume because they either don't have a script, or their scripts don't contain these procedures?)

Yes, the hook requires a script and those standard procedures to be triggered. Because the engine doesn't try to execute procedures if there's no script.

**Comment by FakelsHub** [comment]
Rename the hook is not necessary, since I initially had it so that it worked for everyone, then I thought that this would be unnecessary because the descriptions change from the object scripts, and no one in their right mind would think to do it from the hook. :)
