### ISSUE TITLE
Combat AI glitch

### ISSUE THREAD

**Issue by timchenw** [phobos2077/sfall#294]
Updated Sfall to 4.2.4, noticed that party member and enemy AI seem rather weird: party member enemies seem to be making 1~2 fewer attacks per turn. Enemy only glitch when attacking other NPC's like party members

Problem was not present in 4.1.9.1.

**Comment by timchenw** [comment]
Need to do more tests to confirm what circumstances causes glitch

**Comment by NovaRain** [comment]
Try some other older versions like 4.2.2.

**Comment by FakelsHub** [comment]
I do not understand the essence of the problem.
