### ISSUE TITLE
SpeedKeys do not function without modifier key

### ISSUE THREAD

**Issue by Kokkolar** [phobos2077/sfall#297]
Example 1:
```
SpeedModKey=-1
SpeedKey0=0x11 ;W
SpeedKey1=0x12 ;E
```
Ctrl+W/E - go well

Example 2:
```
SpeedModKey=0
SpeedKey0=0x11 ;W
SpeedKey1=0x12 ;E
```
Press W/E - do not function at all

**Comment by NovaRain** [comment]
Speedkeys are combo keys that require a modifier key + slot key. SpeedModKey=0 disables the modifier key, which means also disabling SpeedKey#.
