### ISSUE TITLE
adding weapon_used as arg8 in TOHIT hook

### ISSUE THREAD

**Issue by zorchar** [phobos2077/sfall#299]
Hi.

How about adding the weapon being used with as arg8 in TOHIT hook?
I am trying to reduce accuracy using a global script, in case a certain weapon is used. Wouldn't it be useful? I can't figure out a way to check this condition otherwise.

**Comment by NovaRain** [comment]
You can already get the weapon pointer from the attacker.
There's a thread on NMA about [giving weapon AC reduction ability](https://www.nma-fallout.com/threads/weapon-reducing-ac-possible.204324/) few years ago.

**Comment by zorchar** [comment]
Thanks NovaRain. You are awesome. 
I was actually in the middle of the exact same process that the thread originator was in, but I'm glad I asked cuz it saved me a bunch of time experimenting with active_hand and stuff.
