### ISSUE TITLE
Docs on set_critter_burst_disable

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#30]
Please add some docs on set_critter_burst_disable. I've tried to use it, but it doesn't seem to do anything in a companion script (or at least, nothing that one would expect judging by the name).

**Comment by phobos2077** [comment]
Well first argument is a critter ID, second is flag: 1 to enable "no burst mode", 0 to disable. I'm not sure if it really works, it is an old function. From the code it is hard to tell.

**Comment by burner1024** [comment]
Critter id is prototype id, correct? Anyway, some details are [here](http://www.nma-fallout.com/showthread.php?204654-sfall-set_critter_burst_disable). If it's not working it probably should be either fixed or removed.

**Comment by phobos2077** [comment]
Usually such functions take object ID, not proto ID.
