### ISSUE TITLE
Weather mod is broken

### ISSUE THREAD

**Issue by blackpaulillyria** [phobos2077/sfall#300]
I can't get it to display the textures properly. I just see big white blocks going across the screen. The interface mask works fine though.

**Comment by FakelsHub** [comment]
This works fine for all shaders. 
[test.zip](https://github.com/phobos2077/sfall/files/5269397/test.zip) here is the script for the test without any extra bullshit.

**Comment by blackpaulillyria** [comment]
Hi, I tested it now using your script and it's working properly! Thank you!

**Comment by NovaRain** [comment]
Strange, I got nothing when it's raining, and yellow blocks when it's sandstorming.
![Imgur](https://i.imgur.com/2sWvI5z.png)

**Comment by FakelsHub** [comment]
In any case, the problem is in hardware, your the graphics card is not an office? :D

**Comment by NovaRain** [comment]
> 
> 
> In any case, the problem is in hardware, your the graphics card is not an office? :D

I'm at home now and it's RTX2070.
I just copy the textures and shaders from the old weather mod and use your script with my old RP saves.

**Comment by FakelsHub** [comment]
then some incompatibility with the old Directx 9 and shaders.

**Comment by FakelsHub** [comment]
try change to pixel shaders on 3.0
```
technique T0
{
	pass P0 { PixelShader = compile ps_2_0 ps_p0(); } <<<< replace ps_2_0 to ps_3_0 <<<
}
```

**Comment by NovaRain** [comment]
> try change to pixel shaders on 3.0 in rain-def.fx

Still nothing. I'll check on my office PC later.

**Comment by NovaRain** [comment]
On my office PC (Intel HD Graphics 630) the rain and snow shaders are showing, but in big gray blocks:
![Imgur](https://i.imgur.com/nmzYL1e.jpg)
Oh well, I'm not even sure if it worked when sfall 2.0 got released.

**Comment by FakelsHub** [comment]
always it working, even 10 years ago)

**Comment by FakelsHub** [comment]
![FALLOUT2 2020-09-24 05-48-32-359](https://user-images.githubusercontent.com/21695363/94095351-3cc75780-fe2a-11ea-8dcc-fbf7e0487608.png)
![FALLOUT2 2020-09-24 05-50-18-291](https://user-images.githubusercontent.com/21695363/94095397-52d51800-fe2a-11ea-9d77-504c81d94922.png)
![FALLOUT2 2020-09-24 05-51-42-226](https://user-images.githubusercontent.com/21695363/94095395-523c8180-fe2a-11ea-8c2d-361bf6a5230d.png)

**Comment by NovaRain** [comment]
> 
> 
> always it working, even 10 years ago)

I guess it's pretty hardware dependent then.

**Comment by FakelsHub** [comment]
I don't know, shaders are the same everywhere.

**Comment by FakelsHub** [comment]
maybe your DX software doesn't work with png textures

**Comment by FakelsHub** [comment]
have you tried using 32bitHeads (option) with png images?

**Comment by NovaRain** [comment]
> 
> 
> have you tried using 32bitHeads (option) with png images?

Yes, at least the old example set (a dog) you gave me works when I replace Cassidy's talking head with it.
