### ISSUE TITLE
MP4 video support

### ISSUE THREAD

**Issue by blackpaulillyria** [phobos2077/sfall#303]
Is it possible to add support for MP4 videos so we can keep the quality as in AVI and reduce the file size?

**Comment by NovaRain** [comment]
I already did a few tests with MEPG4 encoded videos. You can simply rename the file extension to .avi, and sfall will try to play it if your system has compatible codec.

**Comment by FakelsHub** [comment]
Support for the AVI format is in beta testing state. : )

**Comment by blackpaulillyria** [comment]
> I already did a few tests with MEPG4 encoded videos. You can simply rename the file extension to .avi, and sfall will try to play it if your system has compatible codec.

Thanks! I suggest adding that info to the ini file
