### ISSUE TITLE
Increase scenery dimensions limit

### ISSUE THREAD

**Issue by blackpaulillyria** [phobos2077/sfall#304]
Is it possible to increase the dimensions limit of scenery art so it doesn't have to be cut up in smaller pieces?

**Comment by FakelsHub** [comment]
We'll need to do some research.

**Comment by blackpaulillyria** [comment]
> We'll need to do some research.

Thank you!

**Comment by FakelsHub** [comment]
I completely forgot that the art of decoration is not necessary to cut, since the game engine handles it without problems, unlike the mapper.

**Comment by Lexx2k** [comment]
You sure about that? Years ago when I used big scenery graphics I had to reduce them in size or pixels on the borders would fuck up.

However, one has to keep in mind how the object highlight works in the engine --- big scenery graphics don't necessarily look good in non-day light levels.

**Comment by FakelsHub** [comment]
> You sure about that? Years ago when I used big scenery

how big is it?
I checked on the size of 400x540 no glitches with art did not notice.

**Comment by Lexx2k** [comment]
Dunno, it was years ago. Did you also try to shift the image offsets or kept them at 0,0?

**Comment by FakelsHub** [comment]
> Did you also try to shift the image offsets or kept them at 0,0?

shift to bottom

**Comment by FakelsHub** [comment]
Does not require fix. Or provide information about when a large art image becomes unstable to displaying.

**Comment by blackpaulillyria** [comment]
Hi, this wasn't a bug report but a feature request. 

I made this after losing too much time cutting up the artwork and adjusting the offsets correctly. I have scenery artwork which I had to cut up into 40 separate 300x200 pieces and then adjust the offsets in a slow process of trial and error. And that is not even my largest scenery artwork so I postponed cutting the bigger ones until I see if this gets implemented or not.

I know large tiles have been supported so I thought this could be too. If you can't make this happen, then feel free to close this.

**Comment by FakelsHub** [comment]
I don't quite understand what you want to increase? the number of available ART FILES is more than 4096? (as MoreTiles)
A single object can store up to 6 image directions (so theoretically the maximum number of available images will be 4096*6 = 24K)
Package the same type of object images into a single multi-directional FRM.
And all will be happy. :)

**Comment by blackpaulillyria** [comment]
That is a good suggestion but here I am looking for a way to increase max scenery dimensions from 300px x 200px to something more than that. If I go for a larger scenery, its upper right part starts to disappear/appear and glitch inside the game.

**Comment by FakelsHub** [comment]
I wrote above that check the size of 400x540, which causes no problems in the game
