### ISSUE TITLE
Global shader doesn't work on some screens

### ISSUE THREAD

**Issue by blackpaulillyria** [phobos2077/sfall#306]
It seems the global shader doesn't work on Load Game, Options and Credits screens.

**Comment by FakelsHub** [comment]
Where is the proof?

**Comment by NovaRain** [comment]
It works for me.
w/o global shader.
![Imgur](https://i.imgur.com/EEFoP0M.png)

w/ global.fx from modders pack
![Imgur](https://i.imgur.com/KZiUrTu.png)

**Comment by FakelsHub** [comment]
It works for me.

**Comment by blackpaulillyria** [comment]
The color of letters is changed by the shader. I just used the default global.fx and enabled all passes. Here's are the letters from the Main Menu and the Options screen. As you can see they're not the same but they should be.

![Untitled](https://user-images.githubusercontent.com/58548291/83697188-45cfb700-a5f6-11ea-898e-93df46083d81.png)

**Comment by FakelsHub** [comment]
Everything works. in the bloom effect, the selection is based on the brightness of the pixel, not on the color.

**Comment by NovaRain** [comment]
I removed the comment in `pass P2/P3` lines in global.fx but didn't get the different color letters in the main menu or game perf.

**Comment by blackpaulillyria** [comment]
Ahh, so it's a local problem then. You can close the issue if you want. 
Thanks for helping me!
