### ISSUE TITLE
Add get_stat_max/min script functions

### ISSUE THREAD

**Issue by FakelsHub** [phobos2077/sfall#307]
https://github.com/phobos2077/sfall/blob/703073e25598ee6f63a6ac9733e67730f84c77dc/sfall/Modules/Scripting/Opcodes.cpp#L353

**Comment by NovaRain** [comment]
I suppose it can be done with adding GetPC/NPCStatMax/Min funcs in Stats module and just adding another six metarules corresponding to the six `set_###` opcodes.

**Comment by FakelsHub** [comment]
why make this separation into pc/npc ?.

**Comment by NovaRain** [comment]
> 
> 
> why make this separation into pc/npc ?.

Because by nature PC doesn't have exactly the same limit on stats as NPCs? If we are going to add the "get" functions, I think it's better to just match the "set" opcodes.

**Comment by FakelsHub** [comment]
It seems that it is enough to make two forms.
`get_stat_max/min(stat)`
`get_stat_max/min(critter ,stat)`

**Comment by NovaRain** [comment]
Or maybe just the one with two arguments? The set_stat_max/min() is a combination of pc_ and npc_ variant. But for "get" version what will it return if I set pc_ and npc_ with different values?

**Comment by burner1024** [comment]
I think just one is enough, and the rest can be done with defines
```
get_stat_max(critter, stat)
get_self_stat_max()
get_pc_stat_max()
```

**Comment by FakelsHub** [comment]
get_npc_* is not a particularly useful function

`#define get_npc_stat_max(stat)  sfall_func2("get_stat_max", -1, stat)`
what is -1?

where else?
```
#define get_stat_max(stat)   sfall_func2("get_stat_max", stat)
#define get_stat_min(stat)   sfall_func2("get_stat_min", stat)
```

**Comment by NovaRain** [comment]
> 
> 
> get_npc_* is not a particularly useful functions
> 

Because there are set_npc_* fucntions, pairing the functions seems more natural IMO.

> `#define get_npc_stat_max(stat) sfall_func2("get_stat_max", -1, stat)`
> what is -1?
> 

Because critter arg can't be 0 in my prototype code (unless allowing its validation type to be int instead of object), I set the -1 as a "fake" object pointer value that just makes GetStat*() return NPC stat limit values.

**Comment by FakelsHub** [comment]
> Because critter arg can't be 0 in my prototype code (unless allowing its validation type to be int instead of object), I set the -1 as a "fake" object pointer value that just makes GetStat*() return NPC stat limit values.

In this case, do not need to pass the critter pointer, otherwise it is misleading.
Use simple values: 0-pc, 1-npc

**Comment by FakelsHub** [comment]
> I guess you just want to get the stat limit for the player? TBH I'm not really sure what you're planning to use the new get_stat_max/min for.

need a common function, so as not to create a cumbersome macro in the script from the two added functions.
I can write the logic myself if you don't.

**Comment by NovaRain** [comment]
> 
> In this case, do not need to pass the critter pointer, otherwise it is misleading.
> Use simple values: 0-pc, 1-npc

Hmm, I did think of a bool switch for arg. Just don't know if it's better.

> 
> 
> > I guess you just want to get the stat limit for the player? TBH I'm not really sure what you're planning to use the new get_stat_max/min for.
> 
> need a common function, so as not to create a cumbersome macro in the script from the two added functions.
> I can write the logic myself if you don't.

Well, you're obviously better than me on coding so I guess I'll just wait to see/test your implementation. But what do you mean by cumbersome macro? The four macros for pc/npc's min/max in my prototype?
