### ISSUE TITLE
AllowDShowSound doesn't seem to work

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#308]
Version 4.2.5.1, I tried using wavs instead of acm, looks like they aren't found:
```
Playing movie: credits.mve
Buffered not scaled
Movie aborted
Frames 12, dropped 0
Loading background sound file 07desert.ACM... finding background sound by copy Unable to find music file 07desert to copy down.
failed because the file could not be found.
```
```
$ ls data/sound/music
01hub.wav     04brthrh.wav  07desert.wav  10labone.wav  13carvrn.wav  16follow.wav  19reno.wav  22vcity.wav  akiss.wav
02mstrlr.wav  05raider.wav  08vats.wav    11chilrn.wav  14necro.wav   17arroyo.wav  20car.wav   23world.wav  maybe.wav
03wrldmp.wav  06vault.wav   09glow.wav    12junktn.wav  15shady.wav   18modoc.wav   21sf.wav    24redd.wav
```

```
[sound]
cache_size=448
debug=1
debug_sfxc=1
device=-1
dma=-1
initialize=1
irq=-1
master_volume=22281
music=1
music_path1=data\sound\music\
music_path2=sound\music\
```

**Comment by NovaRain** [comment]
I tested my own mp3 & wav files and they work in the game. Are you sure you set `AllowDShowSound=2` (since you don't have acm in folder) in the ini?

**Comment by burner1024** [comment]
yes
```
[Sound]
;Sets the number of allowed simultaneous sound effects
;Set to 0 to leave the default unchanged (i.e. 4)
NumSoundBuffers=0

;Set to 1 to allow attaching sound files to combat float messages
AllowSoundForFloats=0

;Set to 1 to automatically search for alternative formats (mp3/wma/wav) when Fallout tries to play an acm
;Set to 2 to play alternative music files even if original acm files are not present in the music folder
;This does not effect the play_sfall_sound and stop_sfall_sound script functions
AllowDShowSound=2

;Set to 1 to override the music path used by default (i.e. data\sound\music\) if not present in the cfg
;Set to 2 to overwrite all occurances of the music path
OverrideMusicDir=1
```

File is too large for upload, here https://ufile.io/yca49m67

**Comment by NovaRain** [comment]
Your file plays fine in the game with `AllowDShowSound=2` and without .acm, I just open Load Game and I can hear the desert music. It's just the engine didn't find the .acm so it complains in the debug log.

**Comment by burner1024** [comment]
Very strange, I don't hear any music in main menu or before ToT.
Of course, I'm running on Wine. Is there anything else I can try to debug?

**Comment by FakelsHub** [comment]
Да это не будет работать вне windows, ну или когда wine сделает full-поддержку window для Unix, или если найдется человек, который напишет/встроит декодер mp3 в sfall (у меня нету временем экспериментировать над этим).

**Comment by burner1024** [comment]
да фиг с ним mp3, я про wav, a уж он-то везде должен играться без проблем.

**Comment by FakelsHub** [comment]
> да фиг с ним mp3, я про wav, a уж он-то везде должен играться без проблем.

Да нафиг он нужен этот wav. Ктому же это тоже нужно делать эксперменты чтобы подсунуть pcm данные вместо декодированного acm.

**Comment by burner1024** [comment]
Ну тому кто хочет lossless видимо. А вот mp3 с этой точки зрения не особо лучше acm.
В wine есть специальные фишки для проигрывания directsound, так что я думаю должно заработать если найти как. Я потом еще отпишусь.

**Comment by FakelsHub** [comment]
У асм звук паршиво кодируется (шипяше-свистяше качество) хуже чем у mp3 при тех же 22кгц

**Comment by burner1024** [comment]
OK, I was able to get it working, the trick is to install gstreamer wav plugin _and make sure package architecture matches wineprefix arch_ (I had 64bit version installed, but not 32bit):
```
sudo apt install gstreamer1.0-plugins-good:i386
```
For future reference, this is Ubuntu 18.04 x64, with Wine-staging v5.9, and 32 bit wine prefix.

Probably worth adding to the ini/doc/wiki.

**Comment by NovaRain** [comment]
I'll add a note to the "For Wine users" section in the readme.
