### ISSUE TITLE
HP and Armor display counter

### ISSUE THREAD

**Issue by nirran** [phobos2077/sfall#31]
is it possible to disable the animation and have the counter update instantly?would greatly appreciate it

**Comment by NovaRain** [comment]
Partially soIved with integrating the expanded SpeedInterfaceCounterAnims from Crafty's mod. With SpeedInterfaceCounterAnims=2 the counter updates the number instantly, but only when it's not negative. If the number drops below zero, like player with 20 HP got hit 100 damage, it won't display -80 instantly but only a fast counter animation for 0 to -80.
