### ISSUE TITLE
Death animation bugs in Hero Appearance Mod

### ISSUE THREAD

**Issue by blackpaulillyria** [phobos2077/sfall#310]
It seems if you have Hero Appearance Mod enabled and if the player dies from electrical or fire damage the default animations don't play. I can get them to play once I turn the mod off.

**Comment by FakelsHub** [comment]
Which version of sfall started this bug, because I don't even know where this error might be.

**Comment by NovaRain** [comment]
> 
> 
> Which version of sfall started this bug, because I don't even know where this error might be.

Looks like at least it has existed for a very long time. The oldest version I tested having this issue is 3.5 (since I use keypress hook to kill PC).
