### ISSUE TITLE
Possible bug with gvar 7

### ISSUE THREAD

**Issue by blackpaulillyria** [phobos2077/sfall#312]
Not sure if this is a bug or a known thing, but using GVAR_ENEMY_ARROYO at index 7 and setting it to 1 will make the game play the last Hakunin video and exit to main menu

**Comment by NovaRain** [comment]
Not bug, it's just hardcoded in the engine.

**Comment by blackpaulillyria** [comment]
I didn't know it was hardcoded, I discovered how it worked by chance. 
Are there others hardcoded?

**Comment by Lexx2k** [comment]
Yes, Fo2 has lots of hardcoded GVARs. Some are commented in the vault13.gam / global.h files.

**Comment by FakelsHub** [comment]
> Are there others hardcoded?

[Objects and IDs used by the F2 engine](https://github.com/FakelsHub/sFall-Extended/wiki/%D0%9E%D0%B1%D1%8A%D0%B5%D0%BA%D1%82%D1%8B-%D0%B8-%D0%B8%D0%B4%D0%B5%D0%BD%D1%82%D0%B8%D1%84%D0%B8%D0%BA%D0%B0%D1%82%D0%BE%D1%80%D1%8B-%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D1%83%D0%B5%D0%BC%D1%8B%D0%B5-%D0%B4%D0%B2%D0%B8%D0%B6%D0%BA%D0%BE%D0%BC-F2)

**Comment by blackpaulillyria** [comment]
Thank you!!
