### ISSUE TITLE
Add support for GVAR value 0 to Perks.ini

### ISSUE THREAD

**Issue by blackpaulillyria** [phobos2077/sfall#313]
`Perks.ini` supports using GVARs as conditionals but some of the hardcoded GVARs have their initial value set to `0` and that is not an acceptable conditional value for min/max requirements as it expects a positive or an negative value to check against.

An example...

This would check if `GVAR_PLAYER_REPUTATION` is `0` and resolve as true, any other value than that would resolve as false

```
Skill1=67108864
Skill1Mag=0
```

**Comment by Lexx2k** [comment]
Why do you want / need to use hardcoded GVARs? Just use your own?

**Comment by FakelsHub** [comment]
Zero refers to the positive numbers. The condition for this: `X> = 0`

**Comment by NovaRain** [comment]
He wants the perk to be only available when the GVAR is exactly 0. I think it's better to use scripting instead of perks.ini, or set another/reserved GVAR for perk availability if the check passed.

**Comment by Lexx2k** [comment]
A game mode change hook script that checks the value and then sets a custom GVAR to value x would require 5 or so lines of code and work the same way.

**Comment by blackpaulillyria** [comment]
> Why do you want / need to use hardcoded GVARs? Just use your own?

I want to use some hardcoded GVARs as prerequisites for perks.

> He wants the perk to be only available when the GVAR is exactly 0. I think it's better to use scripting instead of perks.ini, or set another/reserved GVAR for perk availability if the check passed.

So I have to disable somehow the original perk and make a fake copy of it which supports my conditions?

**Comment by FakelsHub** [comment]
> I want to use some hardcoded GVARs as prerequisites for perks.

Nothing can be changed here, otherwise it will affect everything else.

I understand you need the perk to be available at 0, but not for the other values? - it seems impossible to implement this for a vanilla perk.

**Comment by blackpaulillyria** [comment]
Thank you for the suggestion, I'll try to come up with a workaround
