### ISSUE TITLE
Function for redrawing the Character Screen

### ISSUE THREAD

**Issue by blackpaulillyria** [phobos2077/sfall#314]
If I create a fake perk that changes some stat, that change isn't visible until I close and reopen the Character screen.
Could a function for redrawing the Character screen be made?

**Comment by FakelsHub** [comment]
This is already redrawn after taking any perk, the script probably starts working after closing the character window, you need to rebuild the logic of your script.
Show your script and how he applies the effects of the perk.

**Comment by blackpaulillyria** [comment]
That is great to hear! 
I used the default global script for perks that comes with modders package `gltschardev2.ssl` 
Didn't touch the existing logic, just added a new `Test` perk that increases Perception when selected

**Comment by blackpaulillyria** [comment]
And I renamed the script to `glperks.ssl` -> `glperks.int`

**Comment by Lexx2k** [comment]
Uhh... you don't rename the script from .ssl to .int. You compile it.

**Comment by blackpaulillyria** [comment]
No, I didn't rename an SSL script to an INT one. 
What I meant is that I renamed `gltschardev2.ssl` to `glperks.ssl` and then compiled it to `glperks.int`. 
Should have clarified that better
