### ISSUE TITLE
Linux?

### ISSUE THREAD

**Issue by dextreFreeman** [phobos2077/sfall#315]
Wanted to know how to make this compatible with Linux/Ubuntu -- and if it is not, is that planned? Last of all, if that isn't planned, then how could I go about replicating this for Linux?

**Comment by NovaRain** [comment]
You can already run the game with sfall in Wine. You just need to change some settings. In sfall-readme.txt:
> For Wine users:
You need to set DLL overrides for ddraw.dll to 'native, builtin' in winecfg or use WINEDLLOVERRIDES="ddraw=n,b" to run Fallout from the command line.

And if you want to play alternative sound files, you'll also need to install GStreamer Good 32-bit plugins as described here: https://github.com/phobos2077/sfall/issues/308#issuecomment-639456330
