### ISSUE TITLE
Elevators are a bit buggy

### ISSUE THREAD

**Issue by blackpaulillyria** [phobos2077/sfall#318]
I tried to override elevator under ID 2 and had issues.
The elevator has 2 levels: G and 1.

Graphics weren't displaying correctly until I set the `Image=1` variable.
`MainFrm=150`, `ButtonCount=2` and `ButtonsFrm=150` didn't work correctly.

Also, for level 1 the gauge was all wrong/glitched until I edited the Elevator stub and set `Elev Level` to `0` which is incorrect, it should be `1` as the level G is `0`. However, that made the elevator work.

**Comment by FakelsHub** [comment]
`ButtonCount` does not supported for the first 23 elevators.
Show the configured data from the ini file for which your Elevator number 2 does not work

**Comment by blackpaulillyria** [comment]
Does `Elev Level` stand for Elevation Level or Elevator Level? The setting makes sense if it stand for Elevation Level

`
[2]
MainFrm=150
ButtonCount=2
ButtonsFrm=150

ID1=11
Elevation1=0
Tile1=25878

ID2=12
Elevation2=0
Tile2=10312
`

![image](https://user-images.githubusercontent.com/58548291/86058502-e9c34b80-ba58-11ea-8de7-4c3e3fcdcb6a.png)

**Comment by FakelsHub** [comment]
> I tried to override elevator under ID 2 and had issues.
> The elevator has 2 levels: G and 1.

The elevator [2] used are 3 buttons, you can not change the number of buttons.

**Comment by blackpaulillyria** [comment]
I'm not sure how overriding functions work then. I manged to fix this by using `Image=1`. It seems some of those functions work only for new elevators which wasn't clear from the examples in Elevators.ini
