### ISSUE TITLE
Change music with script function

### ISSUE THREAD

**Issue by blackpaulillyria** [phobos2077/sfall#319]
Is it possible to change music with a script function?

**Comment by FakelsHub** [comment]
Only mp3.
> play_sfall_sound and stop_sfall_sound are used to play mp3/wav/wma files.
The path given is relative to the Fallout folder. Specify mode as 1 to loop the file continuously, 2 to replace the current background game music with playing the specified file in loop mode, or 0 to play the file once. If you don't wish to loop, play_sfall_sound returns 0. If you do loop, it returns an id which can be passed back to stop_sfall_sound when you want to stop the effect. All sounds effects will be stopped on game reload, looping or not.

**Comment by FakelsHub** [comment]
`set_map_music(int MapIndex, string sfxFileName)` - for ACM

**Comment by blackpaulillyria** [comment]
I didn't know that function existed!
