### ISSUE TITLE
Pathfinding issues with multihex critters

### ISSUE THREAD

**Issue by blackpaulillyria** [phobos2077/sfall#321]
It seems critters have trouble doing their pathfinding around multihex critters.
They get stuck in a loop on one tile trying to get past them until they waste all of their APs.

**Comment by NovaRain** [comment]
It would be more helpful if you could provide a savegame for the issue.

**Comment by blackpaulillyria** [comment]
I don't think my save game would help you as I'm creating a total conversion.

But you could try replicating this by putting around 10 single hex critters in one indoor room and one multihex, Brahmin or Mr. Handy for example. Then start a fight with them all and watch single hex critters get stuck when trying to pass by multihex critters.

**Comment by burner1024** [comment]
If you're creating a whole total conversion, I guess it wouldn't be too hard for you to edit the usual starting area with enough critters to demonstrate and provide a savegame along with that area.

**Comment by blackpaulillyria** [comment]
Here you go, no save game needed. You can load the map from inside the Mapper and initiate combat with the brahmin to see the bug happen.

[artemple.zip](https://github.com/phobos2077/sfall/files/4851781/artemple.zip)

**Comment by NovaRain** [comment]
Looks like the issue happens when the player is completely surrounded by critters and one of them is multihex (i.e. brahmin + 5 villagers). Villagers near the brahmin will behave strangely. If I didn't get completely surrounded (e.g. I killed a villager so there's an open) then other villagers can still move around the brahmin to get me normally.

**Comment by FakelsHub** [comment]
> Villagers near the brahmin will behave strangely. 

I didn't see anything strange.

**Comment by NovaRain** [comment]
> 
> 
> > Villagers near the brahmin will behave strangely.
> 
> I didn't see anything strange.

Here's a save in combat in vanilla 1.02d: [SLOT04.zip](https://github.com/phobos2077/sfall/files/4852189/SLOT04.zip)
You can just load the save and pass the turn. The two female villagers on the left of the brahmin should be stuck in a loop trying to move closer.

**Comment by blackpaulillyria** [comment]
Multihex was introduced in Fallout 2 right?
Seems like this is a 22 year old bug we've got here

**Comment by Lexx2k** [comment]
> Multihex was introduced in Fallout 2 right?

Fallout 1.
