### ISSUE TITLE
Death animation issues persist

### ISSUE THREAD

**Issue by blackpaulillyria** [phobos2077/sfall#323]
I'll have to reopen this ( was #310 ) as there are still issues in the latest release.
Female animations still don't work correctly and it seems those for male do but they always use default ones even when I have custom BH and BN animations. Problem could be present in BK too but I dunno how to test that.

**Comment by NovaRain** [comment]
Weird, in my game at least it can play default fire/electrical death animations for female player (RP 2.3.3 in blond/red haired appearance).

**Comment by blackpaulillyria** [comment]
When I wrote custom, I meant that I edited BH and BN animations and they're being ignored regardless of gender.

And for female animations not firing, I'm not using RP, just vanilla Fallout 2 1.02d with HAM enabled in the latest sfall.
Tried them all and all have the issue.  I even tried copying over working male animations and renaming them and they're not playing.

I'm doing this test using `critter_dmg`

**Comment by NovaRain** [comment]
I'm also doing the test with `critter_dmg`. Getting killed by enemies or scripts doesn't matter here.
If you want to use your custom BH/BN frames for the player, you need to name them `hmjmpsbh.fr0~fr5`(split frames for each direction) and `hmjmpsbn.frm` and put them in `Data\art\critters\`, not the appearance folders.

**Comment by blackpaulillyria** [comment]
Thanks for the detailed explanation, that helps to better understand why the custom installation won't play.

However, regarding the female animation - it's definitively a sfall bug as I can replicate it in vanilla Fallout 2 installation from Steam.
If I delete ddraw.ini and ddraw.dll the correct animation plays upon death, but if I leave them, the generic one with a pool of blood is played.

**Comment by NovaRain** [comment]
I really have no idea about your problem with death animations for female player.
I use `critter_dmg(dude_obj, 10000, DMG_fire);` and `critter_dmg(dude_obj, 10000, DMG_electrical);` with maximum violence setting, and all female appearance (default, blond, redhair, punk girl) can play "fire dance" and "electrified" with no problem with sfall 4.2.6.

**Comment by blackpaulillyria** [comment]
Updating sfall to 4.2.6 on vanilla Steam Fallout 2 didn't resolve the issue with female deaths. I even got the default animation for plasma death now. I'm not sure what's going on honestly as I use the same settings as you.

Can you try testing it on Steam version too?

**Comment by blackpaulillyria** [comment]
P.S. I had to go offline to avoid Steam reverting the changes to sfall after I updated it.
Maybe you're using a different exe than I do, but I presume it's US 1.02d?

**Comment by NovaRain** [comment]
> 
> 
> Updating sfall to 4.2.6 on vanilla Steam Fallout 2 didn't resolve the issue with female deaths. I even got the default animation for plasma death now. I'm not sure what's going on honestly as I use the same settings as you.
> 
> Can you try testing it on Steam version too?

There's really nothing special with Steam/GOG version other than some game text/vaultboy frm censorship.

I just downloaded Steam version, extracted sfall 4.2.6 to the game folder, set EnableHeroAppearanceMod=1 in ddraw.ini, copied my test script (suicide with key press) to the game, started a new game with female player, and the "fire dance" and "electrified" death anims are played normally.

> Maybe you're using a different exe than I do, but I presume it's US 1.02d?

It's US 1.02d. sfall doesn't work with other exe unless you set debugging options.
TBH this starts getting tiring.

**Comment by blackpaulillyria** [comment]
Sorry, I thought you were interested in debugging this. Have a nice day, I won't be bothering you again.

**Comment by NovaRain** [comment]
I'm interested in debugging stuff when the whole situation is clear and reproducible on different systems.
You want me to test Steam version and I did with the steps in my previous comment, but the issue seems to only happen on your side.

**Comment by blackpaulillyria** [comment]
OK, I have to reply to get the record clear..

The thing you're saying how the "whole situation is clear" sounds great but in real world you have situations where the bug cannot be easily reproduced everywhere.
I've been a software engineer for 20 years now and I've seen thousands of bugs that could be reproduced only on the client's machine. Maybe it's my Bitdefender antivirus involved in this somehow?

The latest thing I found out is that the bug is occurring randomly on my machine. Sometimes the animation plays, sometimes it doesn't. I have no clue why is that but I'm getting there. If I give up and start giving off excuses how this is tiring, I'm ending up with a flawed product at the end of the day and that won't do. I'd rather throw everything out the window and revert to an ancient sfall than release a TC where animations don't play as they should.

I reproduced the bug in the Steam version by encountering the Enclave patrol and getting wasted.
In my TC, I reproduced the bug by creating a spatial script and damaging the played with 500 fire/electricity damage.

**Comment by Lexx2k** [comment]
To me this sounds like the problem with fr0, etc. files that were still used by older Hero Appearance mod packages.
You sure you have updated these files to their latest version?

**Comment by blackpaulillyria** [comment]
My HAM should be the latest one.

But I'm not sure it makes a difference as I can easily reproduce the bug in vanilla Fallout 2 with disabled sfall. 
The problem is that it's random. Sometimes it occurs, sometimes it doesn't.

**Comment by FakelsHub** [comment]
@blackpaulillyria

**Comment by blackpaulillyria** [comment]
Here's a couple of videos of vanilla Fallout 2 Steam + sfall 4.2.6. 
Sorry about the black area, OBS would only capture a windowed Fallout 2.
Sfall doesn't play a role, the bug is reproducible with or without it.
Notice how the HP timer always stops at 000 when the wrong animation is played.

https://we.tl/t-8PxskYcS3O
0:18: Gauss doesn't cause big hole death
0:55 Plasma doesn't cause melting death
1:33: Electrical death occurs! A rare occasion when the animation plays correctly
2:06: Gauss doesn't cause big hole death
2:36: Electrical death doesn't occur

https://we.tl/t-TjPsHHDNy9
Longer video with loads of wrong death animations except at 1:50 and 3:20 when Gauss causes correct big hole death. There are also gauss deaths here that play the wrong animation

https://we.tl/t-JYzZQ4j2eV
Longer video with loads of wrong death animations except at 0:50 and 3:40 when Gatling laser causes correct slice death.

**Comment by Lexx2k** [comment]
That animation bug on 0hp exists since forever.

**Comment by blackpaulillyria** [comment]
Except that I didn't know that until now so I couldn't have mentioned it earlier.
But yeah, seems like something that wasn't playtested enough at Interplay.

**Comment by FakelsHub** [comment]
Everything seems normal.
> Notice how the HP counter almost always stops at 000 when the wrong animation is played.

the only bug that I noticed is that there is no death animation in this case.

**Comment by NovaRain** [comment]
> the only bug that I noticed is that there is no death animation in this case.

Looks like for some reason the procedure for setting up death anim got skipped.

Here's how I reproduce the issue:
I added five bounty hunters (attached ecbhuntr.int) with weapons of various damage types to artemple.map, wrote a CombatDamage hook script to force all damage on the player is 99 point so I can always get killed in one shot (for lv1 player), and another script with DeathAnim1, DeathAnim2, and OnDeath hooks to display related info.

I started the game, run to them and got killed, but the death anim failed to play, with the HP counter dropped to exact 0 instead of negative values it should be. DeathAnim hooks didn't get triggered (only OnDeath), and the message like "and were killed" didn't show up.
But if I go into the temple and fight giant ants, or load some saves in town (tested Arroyo & SanFran) and provoke NPCs, I can get killed normally (with anim and msg, DeathAnim hooks triggered).

**Comment by blackpaulillyria** [comment]
Is the flag DMG_NOANIMATE set for some reason when the bug occurs?

**Comment by FakelsHub** [comment]
The video files have already been deleted?
do not use here such shitty files exchangers.

**Comment by FakelsHub** [comment]
>That animation bug on 0hp exists since forever. 

> But if I go into the temple and fight giant ants, or load some saves in town (tested Arroyo & SanFran) and provoke NPCs, I can get killed normally (with anim and msg, DeathAnim hooks triggered).

This bug is fix by enabling the AttackComplexFix option.

**Comment by NovaRain** [comment]
> 
> This bug is fix by enabling the **AttackComplexFix** option.

Is the issue fixed because the result flags setting is altered in the option?
But since it changes how some of arguments work, I'm not sure if it should be default on (if there's anyone really uses `attack_complex` with custom arguments, not the `attack()` macro).
Or maybe it's possible to really fix the function so it works according to the description in BIS commands.doc, not "repurpose unused arguments"?

**Comment by blackpaulillyria** [comment]
> The video files have already been deleted?
> do not use here such shitty files exchangers.

If still needed I can upload them again somewhere else.

**Comment by FakelsHub** [comment]
> If still needed I can upload them again somewhere else.

See if there were moments in the video when the corresponding animation was not played in cases when HP was not set to 000

**Comment by FakelsHub** [comment]
>But since it also changes how some of arguments work, I'm not sure if it should be default on (if there's anyone uses attack_complex with custom arguments, not just the attack() default macro).

These two arguments `called_shot/num_attacks` have never worked, I don't think anyone has ever used them.
In addition, the last two arguments also worked specifically. If not for those flags it would be possible enable the fix by default.

**Comment by Lexx2k** [comment]
At least the regulator one in Fo1 Adytum that kills Zimmerman is using custom arguments:
`attack_complex(JonPtr, 0, 1, 100, 250, 300, 0, 128);`

This attack is supposed to only kill Zimmerman, but in one of my playthroughs he missed and hit me instead, which killed me instantly. Was kinda funny.

Just saying.

**Comment by blackpaulillyria** [comment]
> > If still needed I can upload them again somewhere else.
> 
> See if there were moments in the video when the corresponding animation was not played in cases when HP was not set to 000

Yes there is. On one occasion, the HP went below 000 into minus after being killed by a plasma pistol yet the animation that played was the fall on back with blood pool instead of melting one.

**Comment by FakelsHub** [comment]
> This attack is supposed to only kill Zimmerman, but in one of my playthroughs he missed and hit me instead, which killed me instantly.

AttackComplexFix was enabled ?

**Comment by Lexx2k** [comment]
No, I never used it.

**Comment by FakelsHub** [comment]
> No, I never used it.

You are probably mistaken, the player should not have been killed in any way, if the  option is disabled.

**Comment by NovaRain** [comment]
> 
> 
> > No, I never used it.
> 
> You are probably mistaken, the player should not have been killed in any way, if the option is disabled.

I think the player is killed because the min damage is set to 100?

**Comment by FakelsHub** [comment]
Min damage is 250.
This does not mean to kill instantly since the damage was done, the function uses the value 128 flag of death, killing regardless of the number of lives.
But in the original f1/f2, this construction with flag would not work.

**Comment by Lexx2k** [comment]
¯\_(ツ)_/¯
Anyway, that wasn't why I mentioned it. Just wanted to point out that there is at least one situation where custom arguments are used for attack_complex().

**Comment by FakelsHub** [comment]
> Yes there is. On one occasion, the HP went below 000 into minus after being killed by a plasma pistol yet the animation that played was the fall on back with blood pool instead of melting one.

I can't reproduce this bug.
Please upload this video where there is this moment.

**Comment by blackpaulillyria** [comment]
> @blackpaulillyria
> 
> > Yes there is. On one occasion, the HP went below 000 into minus after being killed by a plasma pistol yet the animation that played was the fall on back with blood pool instead of melting one.
> 
> I can't reproduce this bug.
> Please upload this video where there is this moment.

Hi, here is the link. It happens at 0:55.
https://drive.google.com/file/d/16uwBvsP0UMZyPXXT7LmoL0fKrtwOeiUj/view?usp=sharing

If needed I can upload the other two videos I posted earlier too.

**Comment by FakelsHub** [comment]
> Hi, here is the link. It happens at 0:55.

Set the violence level to NORMAL.

**Comment by blackpaulillyria** [comment]
> > Hi, here is the link. It happens at 0:55.
> 
> Set the violence level to NORMAL.

Female death animations work if violence level is set to NORMAL?

**Comment by FakelsHub** [comment]
Strangely, ANIM_charred_body animation was not implemented for female characters.
I wonder if all the female characters don't have this animation?

**Comment by blackpaulillyria** [comment]
Seems like female death animations are totally screwed up. I wonder how they missed this. 
Maybe it's working in 1.00 vanilla FO2? Or even in vanilla FO1? 

I find it hard to believe that during the production of two games nobody noticed that.

**Comment by FakelsHub** [comment]
The fact is that the in engine does not specify that this animation should be taken from a male character, as it is done for other animations. 
Okay, so it's time for me to implement a fix/feature that I've been wanting for a long time.

**Comment by NovaRain** [comment]
> 
> 
> Strangely, ANIM_charred_body animation was not implemented for female characters.
> I wonder, all the female characters don't have this animation?

From the jumpsuit set, female character doesn't have ANIM_charred_body, ANIM_electrify, ANIM_burned_to_nothing, ANIM_electrified_to_nothing, and the single frame version of them. Supposedly the game should take them from male since they looks pretty much gender neutral.

**Comment by FakelsHub** [comment]
> EDIT: it seems some animations in death2 group don't work for both sex. I tried to kill the male player with plasma and electrical damage with normal violence level, he also just plays "fall on back" anim instead of charred body.

I don't have any problems with animations for male

**Comment by blackpaulillyria** [comment]
> EDIT: it seems some animations in death2 group don't work for both sex. I tried to kill the male player with plasma and electrical damage with normal violence level, he also just plays "fall on back" anim instead of charred body.

Wait, is you issue related to #310 ?

**Comment by NovaRain** [comment]
No. That was a problem on my side.

**Comment by blackpaulillyria** [comment]
I just tested it in FO1 and the same bug exists there too. Looks like this slipped everyone's attention at Interplay

**Comment by NovaRain** [comment]
Now ANIM_charred_body and ANIM_charred_body_sf are available for all armor appearances, just like electrify and fire_dance. Before the death anim can only be played when in the male vault suit appearance (HMJMPS).

**Comment by blackpaulillyria** [comment]
Great! At least one issue is resolved.

**Comment by NovaRain** [comment]
You can grab [the current build](https://ci.appveyor.com/project/rotators/sfall) for testing.

**Comment by blackpaulillyria** [comment]
Thanks, I'll definitively do that and report back!

**Comment by blackpaulillyria** [comment]
OK, I tested this in Fallout 2 with the help of Enclave troopers and here's what happened..

HPs properly fell below 000 each time.

Plasma pistol death played charred body death instead of melting death.
Gauss pistol always played fall back with blood pool death instead of big hole.

Other death animations such as laser cut and electrify (the short one) played correctly.

I still can't get the female long electrify animation to play, it just plays for males.

**Comment by FakelsHub** [comment]
> Plasma pistol death played charred body death instead of melting death.

There is no simplified death animation for plasma, the melting is set to the level of maximum violence, or for critical damage.
Of course, a burned body looks strange for a plasma death.

**Comment by blackpaulillyria** [comment]
Ah yes, I forgot to mention the tests I did was with violence set to normal.
I'll repeat the tests with violence set to maximum level.

**Comment by blackpaulillyria** [comment]
OK, finished the tests with maximum violence setting.
Almost all of the animations work correctly now but I did find some bugs/weird things.

- Weapon/death screams sounds failed to play properly in vanilla FO2 encounters with the Enclave. Death scream would play only about 25% of time, weapon sounds about 50% of time and sometimes even both wouldn't play. The behavior is completely random and I even got a CTD with a memory error at one point.
- Custom fire dance animation for HAM plays correctly but electrify death still defaults to the one for HMJMPS.
- Female fire dance animation doesn't play at all now. This is the error message the game spits out in debug mode

![image](https://user-images.githubusercontent.com/58548291/89182155-1523e380-d58d-11ea-8d34-2ccdc4315d61.png)

This happened for HFJMPS

**Comment by blackpaulillyria** [comment]
OK, seems the sounds didn't play because of this:

```
Gsound: playing ambient map sfx: pebble1
Loading background sound file 07desert.ACM... finding background sound  playing succeeded.
Loading sound file HFJMPSAA.ACM...tyring HFXXXXAA.ACM succeeded (with alias).
Loading sound file iciboxx1.ACM...succeeded.
Loading sound file icombat1.ACM...succeeded.
computing attack...
sequencing attack...
Enclave Patrolman is using Enclave Patrol packet with a 25% chance to taunt
Loading sound file WAF1XXX1.ACM...failed because there are already 4 active effects.
Loading sound file WFF1XXX1.ACM...failed because there are already 4 active effects.
Loading sound file WHF1XXX1.ACM...failed because there are already 4 active effects.
Loading sound file HFJMPSBM.ACM...failed because there are already 4 active effects.
running attack...
```

Which is weird as I don't remember this happening in the vanilla game.

Anyway, found this in my debug.log too, might be worth checking out

`Somebody died and I don't know why! Run!!!`

**Comment by FakelsHub** [comment]
`Loading sound file WAF1XXX1.ACM...failed because there are already 4 active effects.`
Increase the buffer for the number of sounds in ddraw. ini

**Comment by blackpaulillyria** [comment]
> `Loading sound file WAF1XXX1.ACM...failed because there are already 4 active effects.`
> Increase the buffer for the number of sounds in ddraw. ini

Yeah I did after seeing that message but it's strange that it's happening in vanilla game. I don't remember that at all. Will ddraw.ini need to have the sound buffer set from default 0 to 8 because right now the issue is present with the default setting?

**Comment by blackpaulillyria** [comment]
@NovaRain did you manage to take a look at these? This two are from the 4.2.7 test I did

> * Custom fire dance animation for HAM plays correctly but electrify death still defaults to the one for HMJMPS.
> * Female fire dance animation doesn't play at all now. This is the error message the game spits out in debug mode
> 
> ![image](https://user-images.githubusercontent.com/58548291/89182155-1523e380-d58d-11ea-8d34-2ccdc4315d61.png)
> 
> This happened for HFJMPS

**Comment by FakelsHub** [comment]
> Female fire dance animation doesn't play at all now. This is the error message the game spits out in debug mode
I don't have any problems with these animation.

> but electrify death still defaults to the one for HMJMPS.

I'm not sure what you're talking about.

**Comment by blackpaulillyria** [comment]
> I don't have any problems with these animation.

I'm not surprised. Things that are broken for me, always work for you :)
This bug happens with 4.2.7 dev build.
I take default female character HFJMPS. I setup a spatial script 

```
procedure spatial_p_proc begin
      critter_dmg(source_obj, random(150, 300), DMG_fire);
end

```
This error appears 
![image](https://user-images.githubusercontent.com/58548291/90275751-b6971900-de5a-11ea-9ad4-6e0d201e19b4.png)

and she doesn't die. If I take another appearance using HAM, the correct fire dance animation plays and the player dies.

 > I'm not sure what you're talking about.

This bug also happens with 4.2.7 dev build.
I change the female character style with HAM. She has custom fire dance and electricity animations.
If she dies from fire, her custom fire dance animation plays.
If she dies from electricity, her custom electricity animation doesn't play and instead the one for HMJMPS plays.
This one's not a big deal but if it could be changed to support custom electricity animations, people would see something new after 22 years :)

**Comment by FakelsHub** [comment]
HAM - ?

**Comment by FakelsHub** [comment]
> If she dies from electricity, her custom electricity animation doesn't play and instead the one for HMJMPS plays.

I have already checked it, the playing animation belongs to HAM critters.

You should probably make a video. otherwise, you do not Express your thoughts fully, as was the case with custom video subtitles.

**Comment by FakelsHub** [comment]
> I take default female character HFJMPS. I setup a spatial script

I don't have a problem with that either. death animation plays for both cases.

**Comment by FakelsHub** [comment]
https://user-images.githubusercontent.com/58548291/90275751-b6971900-de5a-11ea-9ad4-6e0d201e19b4.png
why do you an error image with animation for combat armor?

**Comment by blackpaulillyria** [comment]
> You should probably make a video. otherwise, you do not Express your thoughts fully, as was the case with custom video subtitles.

I'll make the videos and try to make much more detailed bug reports in the future. You have to understand that I can't post all the info immediately because sometimes I'm not aware of factors X, Y, or Z that could play the role in the issue.

But I also think the problem is that you are not a native English speaker. Some of the things I wrote previously native English speakers would understand immediately.

> why do you an error image with animation for combat armor?

I have no clue why is my HFJMPS character trying to load combat armor fire death animation when she dies from fire damage.
All I know is that it wasn't happening in 4.2.6 only in 4.2.7

**Comment by blackpaulillyria** [comment]
Here are the videos.

**Error:** https://drive.google.com/file/d/1eG8V4KH9Ga_FMhGBx3687h-9v9EOqx2B/view?usp=sharing
**OK:** https://drive.google.com/file/d/1uar4f_dEmDyb1luKN1I6aGK6d0_Q4XmA/view?usp=sharing

**Comment by FakelsHub** [comment]
try this version 
[ddraw.zip](https://github.com/phobos2077/sfall/files/5076852/ddraw.zip)
and report the result.

**Comment by blackpaulillyria** [comment]
Sadly, that didn't help but I found a solution :D

I added `HFJMPSBJ` animations to `appearance\hfr00s00\art\critters` and it worked!
Seems, I'll have to duplicate all the default female animations for `critter.dat` to HAM from now on

**Comment by FakelsHub** [comment]
I added HFJMPSBJ animations to appearance\hfr00s00\art\critters

Do you use folders for HAM? - you see how little information you give)

**Comment by blackpaulillyria** [comment]
Yes, I use folders. I didn't mention it earlier because I didn't think it mattered at all until 10 minutes ago. 
I'm not giving little information on purpose

**Comment by FakelsHub** [comment]
Disable the HAM mod and check the animations again.

**Comment by blackpaulillyria** [comment]
All is working good, I just needed to create additional death animation files for each female armor. I'm now testing all possible death animations with all possible armors with all HAM styles to see if this is it

**Comment by FakelsHub** [comment]
I have already checked all possible options with the deaths no problems were found. I'm tired of it.
Additionally, check it all on the original game without any mods.

**Comment by blackpaulillyria** [comment]
It would probably save us all time if HAM would be better documented. With the recent changes it doesn't work the same way as before. 

I'm sorry to hear you're tired. I work sometimes 20h for 4 days in a row and never complain because I love this game to death

**Comment by FakelsHub** [comment]
> I just needed to create additional death animation files for each female armor.

I have a default HAM and I don't need to copy anything for `HFJMPS` in` appearance\hfr00s00`

**Comment by FakelsHub** [comment]
> I'm sorry to hear you're tired. I work sometimes 20h for 4 days in a row and never complain because I love this game to death

I'm tired of looking for your problem in game)
let him try to find her  @NovaRain :)

**Comment by blackpaulillyria** [comment]
Since I found a solution for the issue, you don't need to look for the cause of it anymore.

**Comment by Lexx2k** [comment]
I don't think it's a good solution. Now I'm wondering if the issue is also present in ettu, but I don't have time to test anything and honestly I don't even know what's up with anything now.

**Comment by blackpaulillyria** [comment]
I don't think it's a good solution too but after 2 months, I also just want to move on to other stuff.

Anyway, the solution consists of copying over `BE, BH, BJ, BK` and `BN` animations for the armor set that is causing the trouble into the appropriate HAM folder.

**Comment by FakelsHub** [comment]
@blackpaulillyria
Apparently you have some kind of problem with your game.
Have you solved your problem with displaying subtitles?

**Comment by blackpaulillyria** [comment]
I haven't solved my issue with displaying subtitles but I will do more testing this weekend.
I'm not totally conviced I have a problem just with my own game, I'm using vanilla 1.02d exe and every time people would tell me I don't have an issue, NovaRain would eventually find the bug and fix it and it would start working.

However, I am working on a big total conversion so there's a possibility I'm pushing the engine to it's limits with almost all files being replaced. 

For example, I managed to discover the engine cannot handle huge dialog files and it would spit out *errors* instead of expected strings if you write the dialog logic in such a way that it has to *jump* too much up and down the dialog file. So I had to  fix it by keeping all the dialog nodes close to each other physically in the file.

I'm bumping into these edge case errors all the time. It kind of reminds me of my RL job, where I'm working on a new feature and suddenly find 10 obscure bugs haha

**Comment by Lexx2k** [comment]
> For example, I managed to discover that the engine cannot handle huge dialog files and it would spit out _errors_ instead of expected strings if you write the dialog logic in such a way that it has to _jump_ too much up and down the dialog MSG file.

What??
How big is your dialog file?

**Comment by blackpaulillyria** [comment]
21 Kb.

> This is the first time ever that I hear about such a thing.

What can I tell you, only shrug my shoulders. 
That's what I encountered and I fixed it by arranging the nodes' text closer to each other physically.
So my MSG file indexes go from 100 ... 1200 -> 2300 -> 1300 -> 1600 ... 1700 -> 1400 ... etc.

If I arrange them numerically , the issue comes back and instead of my strings the game starts returning `Error` strings. 
Anyway, it was a pain in the ass to discover what's causing the error in the first place because why would all of a sudden a proper Dialog file start producing Error strings

**Comment by Lexx2k** [comment]
You should [use the debugger](https://www.nma-fallout.com/threads/scanmsg.215339/) to scan your dialog files for errors.

**Comment by FakelsHub** [comment]
> That's what I encountered and I fixed it by arranging the nodes' text closer to each other physically depending on where the dialog logic goes next.

there is no such thing as a physical arrangement of strings.
the only restriction is that the maximum number of characters per replica is limited to 1024 characters.

the size of the dialog files I saw in other mods was 30-35 KB

**Comment by Lexx2k** [comment]
The biggest dialog file in my Fo2 mod is 37kb. The biggest file in et Tu is 102kb. So it really can't be that.

Pretty sure there is either a typo, or duplicated line somewhere in that dialog file.

**Comment by blackpaulillyria** [comment]
If it helps, the NPC replies were huge so that might have played the role. Anyway, if any of you have my game Fallout Yesterday you can open MSG file `tbodytrl.msg`, rearrange the nodes numerically and see the error with your own eyes since no one here believes me. I fixed it the way I could and don't intend to go back to it as I have to work on the next release.
