### ISSUE TITLE
VAULT13.GAM / GLOBAL.H wrongly indexed GVARs

### ISSUE THREAD

**Issue by blackpaulillyria** [phobos2077/sfall#324]
I noticed there are two 101 GVARs, which means all GVARs below them are wrongly indexed/referenced in GLOBAL.H.

How can this be fixed without affecting hardcoded GVARs below 101 such as GVAR_ADDICT_JET or GVAR_TOWN_REP_GHOST_FARM?

**Comment by Lexx2k** [comment]
The GVARs below aren't wrong. It's fixed in the UPU. https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/issues/20

**Comment by blackpaulillyria** [comment]
Thanks, it's good to know VAULT13.GAM doesn't require changes except reindexing the comments

**Comment by Lexx2k** [comment]
Well, all affected scripts must be recompiled after changing GVAR defines.

**Comment by blackpaulillyria** [comment]
So am I able to change the order of GVARs or that plays a role?

**Comment by Lexx2k** [comment]
You can put them in whatever order you want, but as I said, all scripts which handle the changed GVARs must be recompiled. The only exception are hardcoded GVARs, which of course need to keep their ID.

**Comment by blackpaulillyria** [comment]
I see, that's exactly the impression I got after doing tests just wanted to confirm it with other modders. Thank you!
