### ISSUE TITLE
Allow Hero Appearance Mod to be added into a DAT file

### ISSUE THREAD

**Issue by blackpaulillyria** [phobos2077/sfall#328]
I would like to move Hero Appearance Mod files into DAT file but I see they don't follow the usual directory structure.
Maybe I'm mistaken but if that feature is missing, it would be good to have it.

**Comment by NovaRain** [comment]
Packing appearance into DAT file is already supported: https://github.com/BGforgeNet/Fallout2_Hero_Appearance

**Comment by blackpaulillyria** [comment]
Thanks! So I just have to pack them into separate DATs. Good to know
