### ISSUE TITLE
Support for two monitors

### ISSUE THREAD

**Issue by blackpaulillyria** [phobos2077/sfall#329]
Is sfall working with two monitors? I cannot verify this but one player contacted me telling me the game was crashing with the lastest sfall upon startup until he disabled the second monitor in Windows.

**Comment by Lexx2k** [comment]
I have 3 monitors and no issue.

**Comment by blackpaulillyria** [comment]
Thanks! P.S. How did you know I posted a thread so fast? 👀

**Comment by Lexx2k** [comment]
Sadly I get notifications about every single post.

**Comment by blackpaulillyria** [comment]
Ahh I see, it's your cross to bear :)

**Comment by FakelsHub** [comment]
I have 2 monitors and no issue.

**Comment by blackpaulillyria** [comment]
Thanks, I'll close this! Must be a local issue then
