### ISSUE TITLE
Add support for subtitles for custom movies

### ISSUE THREAD

**Issue by blackpaulillyria** [phobos2077/sfall#330]
I'm unable to add subtitles to custom movies. After properly creating the SVE files in Text/English/Cuts they are not showing.

It seems they depend on grayscale PAL files found in art/cuts directory. Their names seem to be hardcoded into the engine and the palette files are all different with color indexes all over the place. Is it possible to do something about this?

**Comment by FakelsHub** [comment]
For all videos that do not have their own palettes predefined, they have one common palette file named subtitle.pal

**Comment by blackpaulillyria** [comment]
Still no luck. The file was already there.
All I can see in the debug log is this

```
Playing movie: test.mve
Opening subtitle file text\english\cuts\test.SVE
Read 16 subtitles

```
The SVE file is following this format

```
FRAME_NUMBER:SUBTITLE_TEXT
FRAME_NUMBER:SUBTITLE_TEXT
FRAME_NUMBER:SUBTITLE_TEXT
FRAME_NUMBER:SUBTITLE_TEXT
```

**Comment by FakelsHub** [comment]
For me, subtitles are displayed.
But how did you check this for movies if custom movies didn't work. :)

**Comment by blackpaulillyria** [comment]
> For me, subtitles are displayed.
> But how did you check this for movies if custom movies didn't work. :)

Not sure what you mean exactly? 
My custom movies work, it's just that I can't get the subtitles to work.
So you managed to create a brand new movie, add your own subtitles, and they worked?

**Comment by blackpaulillyria** [comment]
@NovaRain can I grab the latest build and test it?

**Comment by wipe2238** [comment]
You can [here](https://ci.appveyor.com/project/rotators/sfall/) (ReleaseXP -> Artifacts)

**Comment by blackpaulillyria** [comment]
Thanks, already found it! I'm on gitlab though so I managed :)

I tested it and it didn't help. If it's of any help, the video where subtitles are failing is Movie3 in `ddraw.ini`, previously called `elder.mve`, now `test.mve`

Maybe the subtitles work only if I add them as Movie18, Movie19, etc.?

**Comment by blackpaulillyria** [comment]
Some further info...

If I restore the old `elder.mve` to `Movie3` position the original subtitles work.
And then, if I just ovewrite `elder.mve` with my new movie, they stop working.

**Comment by FakelsHub** [comment]
Look for the problem on your side.
I rename elder.mve > start.mve and elder.sve/elder.cfg > start.*
it for me showing subtitles.

**Comment by blackpaulillyria** [comment]
Can you send me your start.mve so I can test what you did locally? I'm out of ideas what could be wrong here

**Comment by FakelsHub** [comment]
> Can you send me your start.mve

I just converted the first video I saw, wrote random words in .sve, this is all my actions.
Try replacing the subelder.pal file

**Comment by blackpaulillyria** [comment]
@FakelsHub Can you send me the command you used to convert your AVI to MVE?
I want to compare it to my own to see if there's a difference.

P.S. I even tried converting `avi2mve`'s pal file to Interplay format using their own tool, but it didn't help.

**Comment by FakelsHub** [comment]
I just used the avi2mve tool and its shell Conv2mve.exe, in which I selected convert.
For a release, you always need to use the-old option, and the video size will be very large.
no other combination of options will make your video normal for perception.

**Comment by blackpaulillyria** [comment]
Haha say that again! I never used the `-old` switch but now that I have the quality increased a lot. However the video size went from 260MB to 4,1GB 😂 

Anyway, since I can't think of anything else to make the subtitles work, I'll close this now and update it if I ever find a solution.

**Comment by blackpaulillyria** [comment]
I think I figured out why are subtitles not showing up for me. My movies don't have black stripes at top and bottom, that is they aren't in "cinema" aspect ratio. Will experiment with that.

**Comment by FakelsHub** [comment]
ahahha
I thought about it, but I didn't write about it, because it's a trivial reason to mention it.
use HRP, it will make black stripes for mve subtitles.
