### ISSUE TITLE
Allow play_sfall_sound to play ACM files 

### ISSUE THREAD

**Issue by blackpaulillyria** [phobos2077/sfall#331]
Currently `play_sfall_sound` cannot be used to play ACM files, so please add support if you are able. I need to use it together with `stop_sfall_sound`

**Comment by FakelsHub** [comment]
soundplay(string file, int mode);

**Comment by blackpaulillyria** [comment]
Thank you! 👍

**Comment by FakelsHub** [comment]
why didn't you tell us that the `soundplay` function doesn't play .acm files, it only works without header wav files. I even do not know never used this feature.
I will try to add support for .acm for `soundplay`  in the next version of sfall.

*req. reopen*

**Comment by NovaRain** [comment]
You mean `op_sound#` functions only support raw audio files (headerless wav)? No wonder why they are never used in game scripts.

**Comment by blackpaulillyria** [comment]
> why didn't you tell us that the `soundplay` function doesn't play .acm files, it only works without header wav files. I even do not know never used this feature.
> I will try to add support for .acm for `soundplay` in the next version of sfall.
> 
> _req. reopen_

Honestly, I thought I did something wrong and moved on to work on other things
