### ISSUE TITLE
Is it possible to get rid of the gap from play_sfall_sound with loop set to 1?

### ISSUE THREAD

**Issue by blackpaulillyria** [phobos2077/sfall#332]
In some places, I'm using `play_sfall_sound` with loop set to 1. 
However, each time the sound reaches its end, I can hear a short gap/pause. The gap doesn't exist in the sound file but is produced by `play_sfall_sound` rewinding/reloading or whatever it's doing.

The only workaround I have is to use an audio editor to create a new, longer sound so it doesn't restart as often.
That however just increases the game's size.

**Comment by FakelsHub** [comment]
Nothing can change, this is the specifics. Use mp3 format that doesn't take up much space.

**Comment by blackpaulillyria** [comment]
Thanks, I'll try with the mp3. Right now I'm using wav.

**Comment by FakelsHub** [comment]
[You can try using acm for looping.](
https://github.com/FakelsHub/sFall-ScriptEditor/blob/improve/ScriptEditor/Descriptions/opcodes_rus.txt#L659)

**Comment by FakelsHub** [comment]
What is the duration of this latency, ~100ms or less.?

**Comment by blackpaulillyria** [comment]
Hi, 
thanks for your help, I appreciate it!
On my SSD the duration of latency seems to be ~200ms.

I recorded a sample from the game if you want to hear it.
https://drive.google.com/file/d/15HcI8lx4lqEa9FdzKzhajkXMW-Ea_T2G/view?usp=sharing

I'll try using the ACM format. From what I remember, when I looped an ACM file as a map music file there were no gaps.

**Comment by FakelsHub** [comment]
Yes it is 200ms.

**Comment by FakelsHub** [comment]
I measured it on my old P4 & HDD - I have a delay of 100-120ms. (for wav)
After a small cleaning in the code, the delay was reduced by 20ms (maybe less)
This the ceiling. :)

**Comment by blackpaulillyria** [comment]
Hehe, push it to the max :)
