### ISSUE TITLE
Maximum encounter table size

### ISSUE THREAD

**Issue by blackpaulillyria** [phobos2077/sfall#333]
Hi! 

Not really a bug but I wanted to mention it anyways.
I see that the maximum encounter table size can be set to 127 but that is unusable in practice as WORLDMAP.MSG limits each table to 50 entries max.

**Comment by FakelsHub** [comment]
Then can remove the option and set the maximum possible value to 50?

**Comment by NovaRain** [comment]
Better to check/verify the code before removing it.

**Comment by FakelsHub** [comment]
>way to increase the limit for worldmap.msg as well.

Message string of table 1 (if greater than 50) will simply be taken from messages of table 2, etc.
```
enc table 1 messages
1000  = enc00
...
1049 = enc49
enc table 2 messages
1050 = enc00
...
1099 = enc49 
```
the limit of 50 I think is a good number) without additional engine hacking.
Otherwise, the moder will have to move all the lines in `worldmap.msg` to the new size.
still, the size will have to be set to 100 for a more correct perception.

**Comment by NovaRain** [comment]
> 
> Message string of table 1 (if greater than 50) will simply be taken from messages of table 2, etc.
> the limit of 50 I think is a good number) without additional engine hacking.

Oh, I see it. If that's the case then a fixed limit of 50 (from vanilla 40) should be good enough.

> Otherwise, the moder will have to move all the lines in `worldmap.msg` to the new size.
> still, the size will have to be set to 100 for a more correct perception.

Huh? You mean for example `# Encounter Table 6` can have message line numbers from 3300 to 3399?
Wouldn't this also require to move all the lines in worldmap.msg?

**Comment by FakelsHub** [comment]
> # Encounter Table 6 can have message line numbers from 3300 to 3399?

yes.

> Wouldn't this also require to move all the lines in worldmap.msg?

Yes, it will be required

**Comment by FakelsHub** [comment]
Action plan:
Set the limit to 50 by default.
For the option `EncounterTableSize`, make a special fix that increases the size from 50 to 100, which will require moving all the rows in worldmap. msg.

**Comment by NovaRain** [comment]
To be honest I doubt if anyone really needs more than 50, even FoN or Sonora doesn't have that many, right?
Maybe just increase the default max limit to 50, axe the option and call it a day.

**Comment by Lexx2k** [comment]
50+ entries in a single encounter table sounds like bad game design to me.

**Comment by FakelsHub** [comment]
> Changing the option to work more like ExtraKillTypes (a 0/1 toggle to double the limit)?

If the value is greater than 50, an additional correction for messages rows will be enabled.

> 50+ entries in a single encounter table sounds like bad game design to me.

I don't think it should worry you - good/bad.
Another thing is that 50+ it is too much, but it can be applied for example to one encounter square and not to all.
Just need to make the most of what have. )))

**Comment by Lexx2k** [comment]
If you need 50+ encounter types, you are doing something wrong. Use scripts for variation. That's much less data clutter and much easier to manage.

**Comment by FakelsHub** [comment]
> If you need 50+ encounter types, you are doing something wrong. Use scripts for variation. That's much less data clutter and much easier to manage.

With a script, you won't do some things as easily as you can do in a file, plus it's the wrong approach and terribly inconvenient, an example with a cumbersome script in fo2fo1.
blackpaulillyria - man is doing everything right.

**Comment by Lexx2k** [comment]
If want 10 different types of raider encounters, a simple script can do exactly the same (and even more) than 10 data entries in the encounter table.

> an example with a cumbersome script in fo2fo1

I never said that the ettu scripts are a good approach. We are doing it this way because nobody can be arsed to port this stuff over to Fo2.

**Comment by blackpaulillyria** [comment]
Of course, I'll always use native functions/methods first to achieve a goal. But if those aren't available, I'll resort to workarounds, hacks, alternative solutions... So if Mr. Stalin makes this available, I'll use it. If not, I'll use Lexx's solution. Either way, it's getting done and everybody wins! :)

**Comment by FakelsHub** [comment]
This should have been tested before closing. :-)

**Comment by blackpaulillyria** [comment]
I'll test it over the weekend, no problem! 👍

**Comment by blackpaulillyria** [comment]
Sadly, couldn't make this work. I reindexed the WORLDMAP.MSG and all of the encounters within 0-49 are working.
However, as soon as I hit an encounter in 50-99 range, it crashes.

![image](https://user-images.githubusercontent.com/58548291/92313846-392d7700-efc8-11ea-82b6-7ddb4c22cf5c.png)

**Comment by NovaRain** [comment]
I tried to add 50 placeholder encounters (unable to trigger, so original encounters start from 51) to some encounter tables (around San Francisco) in RP for testing `EncounterTableSize=100`.
I didn't have any crash, but some encounters would display "Error" while some others are OK, not sure if I made mistakes in the files: [RP_enc_test.zip](https://github.com/phobos2077/sfall/files/5338021/RP_enc_test.zip)

**Comment by FakelsHub** [comment]
My tests also did not reveal any problems with this, the messages correspond to their `enc_##` numbers without any "error".

**Comment by blackpaulillyria** [comment]
Great news, I'll give those tests another go although for now I've split up my huge encounter tables into smaller ones.
