### ISSUE TITLE
Strange behaviour with critter_dmg and foreach loop

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#337]
As discovered [here](https://github.com/BGforgeNet/Fallout2_Restoration_Project/issues/63):

> The loop works only for the first time; the rest of it are all zero. It seems there's some conflict between critter_dmg and looping through an array.

```pascal
key := [1, 2, 3, 4, 5];
foreach i in key begin
   display_msg("Number " + i);
   critter_dmg(dude_obj, i, DMG_normal_dam BWOR DMG_NOANIMATE BWOR DMG_BYPASS_ARMOR);
end
```

Some kind of memory corruption?

**Comment by NovaRain** [comment]
Two loops that should have the same result:
```pas
arr := [1, 2, 3, 4, 5];
foreach i in arr begin
   display_msg("Number: " + i);
   critter_dmg(dude_obj, i, DMG_normal_dam BWOR DMG_NOANIMATE BWOR DMG_BYPASS_ARMOR);
end

for (i := 1; i < 6; i++) begin
   display_msg("Number: " + i);
   critter_dmg(dude_obj, i, DMG_normal_dam BWOR DMG_NOANIMATE BWOR DMG_BYPASS_ARMOR);
end
```
`foreach` loop runs with "1, 0, 0, 0, 0" and `for` loop runs with "1, 2, 3, 4, 5".
There doesn't seem to have anything strange in the decompiled script:
```pas
LVar7 := temp_array(0, 0) + arrayexpr(0, 1) + arrayexpr(1, 2) + arrayexpr(2, 3) + arrayexpr(3, 4) + arrayexpr(4, 5);
LVar9 := 0;
LVar8 := len_array(LVar7);
while (LVar9 < LVar8) do begin
   LVar10 := array_key(LVar7, LVar9);
   LVar6 := get_array(LVar7, LVar10);
   display_msg("Number: " + LVar6);
   critter_dmg(dude_obj, LVar6, 0 bwor 512 bwor 256);
   LVar9 := LVar9 + 1;
end

LVar6 := 1;
while (LVar6 < 6) do begin
   display_msg("Number: " + LVar6);
   critter_dmg(dude_obj, LVar6, 0 bwor 512 bwor 256);
   LVar6 := LVar6 + 1;
end
```

**Comment by FakelsHub** [comment]
Explanation:
The` kb_clear_` function clears keyboard buffers, which also affects temporary arrays (and other processes, by running nested loops of sfall scripts execution).

**Comment by FakelsHub** [comment]
It is necessary to check the execution of global scripts with set_global_script_type mode 1, it seems that their execution frequency decreased.

**Comment by burner1024** [comment]
If possible, please share a test 4.x build, so I could verify the scenario mentioned in the original issue.

**Comment by NovaRain** [comment]
> 
> 
> If possible, please share a test 4.x build, so I could verify the scenario mentioned in the original issue.

Here: https://ci.appveyor.com/project/rotators/sfall

**Comment by burner1024** [comment]
Oh, cool, hopefully those will be able to publish artifacts too.
The test went well.

**Comment by NovaRain** [comment]
> 
> 
> It is necessary to check the execution of global scripts with set_global_script_type mode 1, it seems that their execution frequency decreased.

I made a test script to try checking the frequency, not sure if this counts:
```pas
variable timer;

procedure start;

procedure start begin
   if game_loaded then begin
      set_global_script_type(1);
      set_global_script_repeat(10);
      timer := get_uptime;
   end else begin
      if (get_game_mode bwand WORLDMAP) then begin
         debug_msg("Time interval: " + (get_uptime - timer));
         timer := get_uptime;
      end
   end
end
```
I disable the random encounters and move around on the world map for a while. The time interval didn't change when using 4.2.7 or the current build.

**Comment by FakelsHub** [comment]
it seems that the no running execution scripts when entering the dude combat turn [004229E6].
other kb_clear calls are not critical for scripts.

**Comment by NovaRain** [comment]
> 
> 
> it seems that the no running execution scripts when entering the dude combat turn [004229E6].

Really? But my test script still keeps running (printing time msg to debug.log) when I start the combat.

**Comment by FakelsHub** [comment]
Yes, I checked the combat is all right with it. I do not think that a single call could affect something.
