### ISSUE TITLE
Max map destination for stairs hardcoded to 151

### ISSUE THREAD

**Issue by blackpaulillyria** [phobos2077/sfall#338]
Hi!

How can I enter a number higher than 151 for stairs map destination?

![image](https://user-images.githubusercontent.com/58548291/93253727-346a7f00-f78f-11ea-954b-2daf6a9c708b.png)

**Comment by Lexx2k** [comment]
Huh, the max is 245 for me.
![scr00002](https://user-images.githubusercontent.com/4844938/93254168-35ec7500-f798-11ea-9f71-9af180c28501.png)

By the way, keep in mind that maps in this high range will not show up in the PipBoy automap screen anymore.

**Comment by blackpaulillyria** [comment]
> By the way, keep in mind that maps in this high range will not show up in the PipBoy automap screen anymore.

:'(

**Comment by blackpaulillyria** [comment]
I see how it works. It's dynamic. I added 2 new maps and the number went up.

![image](https://user-images.githubusercontent.com/58548291/93256160-d8095e80-f792-11ea-8fb7-d73838fc5dff.png)

Maybe we should rename this issue to make automaps work for all maps 😂

**Comment by FakelsHub** [comment]
https://github.com/phobos2077/sfall/issues/96
