### ISSUE TITLE
Requesting an extra argument for TOHIT Hookscript

### ISSUE THREAD

**Issue by Cyrus-FO2** [phobos2077/sfall#339]
The current tohit hookscript exposes the hit chance after the 0 and 95% capping. This causes a significant use case problem. It significantly limits the usefulness of the hookscript and makes it difficult to work with.

### Explanation:
(sorry, long but necessary)

It is more often the case that the usecase of the tohit chance is that people want to give a certain weapon or a certain situation an extra bonus or penalty in to hit chance. Lets say I want to give a 30% tohit bonus to all throwing, or to grenades, or I want to give a heavy gun a 20% tohit penalty to simulate heavy recoil (harder to control). Lets assume the natural hit chance is 50%. Right now I can easily take that 50% and add or subtract 20 from it. And it will work. However lets say the hit chance is 95% and I want to apply a 20% penalty. If I deduct 20% then I will get 75%. However the raw hit chance might have been higher, ex 140% before capping. If I could see the raw hit chance before capping then I could deduct 20 from 140 and I would get 120, which would still be 95%. In other words, once the tohit chance gets capped its no longer clear what the raw hit chance is to deduct 20 from. If I deduct 20% from 95% then the tohit chance even at close range would be limited to 75% abd 75 becomes the new maximum tohit chance of the gun no matter the distance. This is bad obviously.

The same issue exists in regards to capping at 0. Lets say I want to give a bonus of +30. If the current to hit is 0, then its not clear if I should add 30 to 0, or if the raw number would have been lower. adding 30 to 0 would give the result of making the weapons minimum hit chance 30, at even the longest of ranges. This doesn't work.

The solution then is you have to rewrite the whole tohit chance formula in order to get things right. With a big emphasis on the words "HAVE TO". Yes, you HAVE TO rewrite the whole tohit chance formula, or order to be able to make any reasonable adjustments to tohit chance at all.

The problem with that ofcourse is that rewriting the tohit chance correctly is no easy task and there are only a few modders in the community who are knowledgeable enough and have the technical prowess to be able to do it. But despite the fact that the tohit hookscript has been around for quite a few years, they too have not done it and it appears that it is unlikely that it will ever get written by any of them in the foreseeable future given their expressed lack of interest.

This essentially leaves a tohit hookscript that is essentially unusable by people because of lack of the written formula and either lack of technical knowhow or lack of willingness to write it.

Again, while writing the formula may still be necessary if someone wants to do deeper modding with tohit chances, the majority of cases are simpler and do not require it necessarily if they could have access to the raw tohit chance before the 0 and 95 capping. If we could have access to the raw tohit chance just before it gets capped then we wouldn't need to rewrite the formula at all. We could take advantage of the already existing engine calculations without the hassle of having to rewrite it and we could simply modify the raw hit chance with simple code and let the engine finish the capping. This essentially makes the the hook script highly usable without much effort.

Which brings me to this request.

### Conclusion:

I am requesting that an additional argument be added to the tohit hook script that exposes the **final** **RAW** hit chance before it gets capped and allows a return argument that would replace this value.

This would basically allow us to easily modify the raw hit chance with the new argument, while keeping all the other arguments for their usecases.

**Comment by FakelsHub** [comment]
Don't need to change anything, there are special script functions that can disable 95% of the cap.
They need to be improved a little.

**Comment by NovaRain** [comment]
It's done. Here's the test build if you want to check it before the formal 4.2.8 release: https://ci.appveyor.com/project/rotators/sfall

**Comment by Cyrus-FO2** [comment]
Hey guys, thanks for getting this done, and so fast.

Its kind of a BIG DEAL, what you've done here.

Much appreciated.

**Comment by zorchar** [comment]
Very cool. I appreciate it also very much.
