### ISSUE TITLE
Not a repost - Request: HOOK_REMOVEINVENOBJ - adding return argument.

### ISSUE THREAD

**Issue by zorchar** [phobos2077/sfall#341]
Hi guys. Hope this isn't as silly a request as the last one.
Would it be possible for you to add a return int to HOOK_REMOVEINVENOBJ  , similar to the one in steal, or inventorymove hooks?
"int     ret1 - overrides hard-coded handler (1 - force success, 0 - force fail, -1 - use engine handler)"
"int     ret1 - Override setting (-1 - use engine handler, any other value - prevent relocation of item/reloading weapon/picking up item)"

**Comment by FakelsHub** [comment]
Deleting an item cannot be undone because in some situations, the subsequent mechanics of the game are violated.
You are definitely doing something wrong if you need such an exceptional situation.
describe your problem

**Comment by zorchar** [comment]
The problem is like so:

This is my current script.
```
procedure start begin
   if (game_loaded)  then begin
      register_hook_proc(HOOK_REMOVEINVENOBJ, reminvobj_handler);
   end

procedure reminvobj_handler begin
   if (hook_stop == true) then begin
   end
   else begin
        orig_owner := get_sfall_arg;
        the_item := get_sfall_arg;
        num_removed_objects := get_sfall_arg;
        reason_removed := get_sfall_arg;
        dest_obj := get_sfall_arg;

        call calc_how_many_delete_extra_weights;
   end
end

procedure calc_how_many_delete_extra_weights begin
   //calc extra weight
   if obj_pid(the_item) == PID_EXTRA_WEIGHT then begin
      if orig_owner!=0 then
         amount_to_destroy_giver:= obj_is_carrying_obj_pid(orig_owner,PID_EXTRA_WEIGHT);
      if dest_obj!=0 then
         amount_to_destroy_receiver:= obj_is_carrying_obj_pid(dest_obj,PID_EXTRA_WEIGHT);
   end
   else begin
      if orig_owner!=0 then
         amount_to_destroy_giver:= obj_is_carrying_obj_pid(orig_owner,PID_EXTRA_WEIGHT);
      if dest_obj!=0 then
         amount_to_destroy_receiver:= obj_is_carrying_obj_pid(dest_obj,PID_EXTRA_WEIGHT);
   end
   call get_ini_data;
end

procedure get_ini_data begin
variable sections,i,pid_and_weight,the_pid_number,the_pid_weight,pid_number_and_weight;

   sections := get_ini_sections("Items_Weight.ini");
   //for each section in sections
   foreach i in sections begin
      the_pid_number := get_ini_setting("Items_Weight.ini|" + i +"|pid");
      the_pid_weight := get_ini_string("Items_Weight.ini|" + i +"|weight");
      if obj_pid(the_item) == the_pid_number then
         the_item_section := i;


      //check how many of this pid exists, times weight, and add to weight before transfer
      if orig_owner!=0 then
         orig_weight_before:=(orig_weight_before) +((obj_is_carrying_obj_pid(orig_owner, the_pid_number))*(0.0+atof(the_pid_weight)));
      if dest_obj!=0 then
         dest_weight_before:=(dest_weight_before) +((obj_is_carrying_obj_pid(dest_obj, the_pid_number))*(0.0+atof(the_pid_weight)));
   end

call add_remove_extra_weights;

end

procedure add_remove_extra_weights begin

   //calculate amounts
   weight_removed_pid := atof(get_ini_string("Items_Weight.ini|" + the_item_section + "|weight"));
   weight_removed_items := (0.0+num_removed_objects * weight_removed_pid);

   //get total to be added weight after transfer for both giver and receiver
   if orig_owner!=0 then
      orig_weight_after := 0.0+orig_weight_before - weight_removed_items;
   if dest_obj!=0 then
      dest_weight_after := 0.0+dest_weight_before + weight_removed_items;


//add amounts
   hook_stop := true;
   if orig_owner!=0 then
      give_pid_qty(orig_owner, PID_EXTRA_WEIGHT, ceil(0.0+orig_weight_after))
   if dest_obj!=0 then
      give_pid_qty(dest_obj, PID_EXTRA_WEIGHT, ceil(0.0+dest_weight_after))
   hook_stop := false;

   //delete extra weight
   hook_stop := true;
   if orig_owner!=0 then
      remove_pid_qty(orig_owner, PID_EXTRA_WEIGHT, amount_to_destroy_giver)
   if dest_obj!=0 then
      remove_pid_qty(dest_obj, PID_EXTRA_WEIGHT, amount_to_destroy_receiver)
   hook_stop := false;
//reset variables

orig_owner:=0;
the_item:=0;
num_removed_objects:=0;
reason_removed:=0;
dest_obj:=0;

amount_to_destroy_giver:=0;
amount_to_destroy_receiver:=0;


the_item_section:=0;
orig_weight_before:=0;
dest_weight_before:=0;

orig_weight_after:=0;
dest_weight_after:=0;

weight_removed_pid:=0;
weight_removed_items:=0;

end
```
This script works fine, unless:
 I'm clicking "take all" from an inventory, when at least one item "PID_EXTRA_WEIGHT" is in the items I'm taking (orig_owner inventory). In this case, the game gets stuck, like in a loop or something.

So I added the lines "if obj_pid(the_item) == PID_EXTRA_WEIGHT then          script_overrides;"
to here:
```
procedure reminvobj_handler begin

   if (hook_stop == true) then begin
   end
   else begin
        orig_owner := get_sfall_arg;
        the_item := get_sfall_arg;
        num_removed_objects := get_sfall_arg;
        reason_removed := get_sfall_arg;
        dest_obj := get_sfall_arg;

        if obj_pid(the_item) == PID_EXTRA_WEIGHT then 
            script_overrides;
        else
            call calc_how_many_delete_extra_weights;
   end
end

Now, the game doesn't crash/gets stuck, but I can't seen to prevent moving the item PID_EXTRA_WEIGHT between inventories. 

On top of that, it seems that a simple -
```
procedure reminvobj_handler begin

   if (hook_stop == true) then begin
   end
   else begin
        orig_owner := get_sfall_arg;
        the_item := get_sfall_arg;
        num_removed_objects := get_sfall_arg;
        reason_removed := get_sfall_arg;
        dest_obj := get_sfall_arg;

        if obj_pid(the_item) == PID_EXTRA_WEIGHT then begin
            script_overrides;
            **if num_removed_objects< who_inven_free_amt(dest_obj) then begin
              give_pid_qty(orig_owner, PID_EXTRA_WEIGHT, num_removed_objects)
              remove_pid_qty(dest_obj, PID_EXTRA_WEIGHT, num_removed_objects)**
            end
        end
        else
            call calc_how_many_delete_extra_weights;
   end
end
```
Does nothing.

**Comment by FakelsHub** [comment]
`script_overrides` doesn't actually do anything in global scripts.

**Comment by zorchar** [comment]
That is weird, since if I remove this line, the game will get stuck if take all condition. (I tried it now, simply removing this line.)

So anyway, that is why I need either to have a HOOK_REMOVEINVENOBJ  that gets turned on **after** items have being moved to inventory, or have the ret argument added. I don't know how to both avoid the crash once "take all" is clicked, **and** to make the script calculate the amounts properly. And again, simply adding the amount doesn't seem to work.

If I should find another solution, please say so.

**Comment by FakelsHub** [comment]
I'll see, can do this for inventory.

I don't understand your idea with extra weight, what is PID_EXTRA_WEIGHT is some fake item weighing 1 ?
Also You can delete items after they are moved using the delay call `call <procedure> in <sec>;`

**Comment by zorchar** [comment]
Thank you for looking into that.

Yes, this will be a fake item, a new or edited proto which will weigh 1.

Thanks for the suggestion. I will check it out. 

Meanwhile, I will not post anymore on the subject, unless you have news for me.

**Comment by FakelsHub** [comment]
> Yes, this will be a fake item, a new or edited proto which will weigh 1.

So it will always be present in the inventory? "that doesn't sound very good."
you have a strange idea with all this.

**Comment by zorchar** [comment]
It is certainly not ideal. But I just figured its very unrealistic to have a hundred stimpaks, xander roots, 20 zippo lighters without weighing anything. Plus, I want merchants to have like 5 cartridges of .223 for sale, instead of a hundred (which is weight 2), that way, I can make each cartridge weigh 0.025 lbs. for example.

Since, as you know:), hidden items don't work, I just can't think of a better solution. I hope that it will be a good balancing/realistic mod.

**Comment by Lexx2k** [comment]
Wouldn't the player see this item in his inventory? I don't think this is a good idea. Are you sure you can't just change the weight of the proto item when opening/closing interface screens?

**Comment by zorchar** [comment]
> Wouldn't the player see this item in his inventory?
Yes, he would see it. It will have a description.

> Are you sure you can't just change the weight of the proto item when opening/closing interface screens?
Changing the weight to which number? You can't change proto weight to a non integer. 
If I'll change this to 0, then dude will be able to take more than his max weight, thus becoming encumbered. That isn't so bad, but the player will have no easy way to see the _difference_ . So I think the better solution would be to see the extra item. This isn't such a bad idea IMO.

**Comment by zorchar** [comment]
I got it to work using FakelsHub/Mr. Stalin's suggestion to delay the procedure call in 1 second. 
Thanks a lot.
It would still be nice to have the option to fail inventorymove IMO, though I no longer immediately need it.

**Comment by FakelsHub** [comment]
You can also use call in 0 second. then the delay will be minimal.
I myself use these methods in the filter script.

**Comment by Lexx2k** [comment]
> Changing the weight to which number?

Round down? Is 0.5 really making a bigger difference than 0? Once you hit 1.1 you can round to 1.0, etc. I have a hard time imagining players enjoying to shuffel inventory just to get that extra 0.1 somewhere.

**Comment by FakelsHub** [comment]
here the emphasis is on the fact that there will be a lot of items.
let's say 100 stimpacks of 0.25 will give an additional weight of 25, while 5 steampacks will weigh 1

**Comment by zorchar** [comment]
> Round down? Is 0.5 really making a bigger difference than 0? Once you hit 1.1 you can round to 1.0, etc.
>

I **am** rounding it (I round up, but what the hell).

I don't really understand what you mean. Please explain.
Right now, if it will hit 1.1 it will got to 1.0 (or 2.0). That's exactly it. I still need to add an item who's weight is 1.
