### ISSUE TITLE
Some way of tracking active hand change or red button click

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#342]
It turned out that [ammobox](https://github.com/BGforgeNet/FO2tweaks#ammobox) script isn't updating the tag when the switch is made by clicking the red button.
I have tried AdjustFID, InvenWield - they don't fire, and MouseClick fires both events before the switch is made.
Unless I'm missing somehting, the only other alternative I see is a fast loop, and I'd like to avoid that.

**Comment by FakelsHub** [comment]
Ну так наверное нужно отслеживать в скрипте активный слот.

**Comment by burner1024** [comment]
с отложенной будет задержка

**Comment by FakelsHub** [comment]
Не думаю.
```
procedure mouseclick_hook begin
  variable pressed = get_sfall_arg;
  variable button = get_sfall_arg;
  if not in_combat then return;
  if not pressed then return;
  if button == MOUSE_BTN_MIDDLE then begin //middle
    call update_box(0);
    ndebug("update box - mouse");
  end else if (button == MOUSE_BTN_LEFT) then begin
         current = active_hand();
         call check_swith in 0;
  end
end
```

**Comment by burner1024** [comment]
Хм, я не знал про конструкцию call... in, спасибо.
But it turns out that CalcAPCost is good enough for this scenario, so I went with it. No problem here.
