### ISSUE TITLE
Centering camera on the player

### ISSUE THREAD

**Issue by blackpaulillyria** [phobos2077/sfall#343]
I can't seem to center the camera on the player if I use `move_to` or `critter_attempt_placement` to move the player to a different tile on the same map. I tried using `set_viewport_x/y` but it didn't have any effect.

**Comment by NovaRain** [comment]
Maybe `tap_key(DIK_HOME);`?

**Comment by Lexx2k** [comment]
`tile_set_center(tileNum)`

**Comment by blackpaulillyria** [comment]
Thanks, wasn't aware of these two!

**Comment by Lexx2k** [comment]
set_viewport_x/y is for the worldmap if I remember right.
