### ISSUE TITLE
[Feature Request] Allow for 32-bit texture loading of all sprites, not just talking heads.

### ISSUE THREAD

**Issue by ChrisNonyminus** [phobos2077/sfall#344]
I'm working on something regarding classic fallout, and I realized that to make said thing work, sfall would need to extend FRM loading. In other words, there would need to be a way to make a FRM have more than 256 colors and be more than 640x480. Perhaps an easier thing to do would be to expand the "32-bit talking heads" hack to all FRMs.

**Comment by FakelsHub** [comment]
> 32-bit talking heads" hack to all FRMs.

Talking heads are just a texture superimposed on top of the head image via a Shader, there is no FRM hacking here.
To make graphics more than 256 colors, you need to write a new graphics system for the fallout, which will work and support, for example, the format. png
What is equivalent to the engine: https://github.com/falltergeist/falltergeist

**Comment by ChrisNonyminus** [comment]
Maybe a better thing would be to allow to dump loaded FRMs and RIXs as pngs, and load replacement pngs, ala certain emulators like Dolphin.

**Comment by FakelsHub** [comment]
Once again, to add 32-bit colors, need to rewrite all code of the graphics component of the game, which is implemented on the principle of palette graphics, to a modern DIRECTX/OPENGL graphics system.

**Comment by NovaRain** [comment]
> Which is equivalent to writing a new graphics engine for the game.

That doesn't sound worth the work, at least in the foreseeable future.
