### ISSUE TITLE
Сhanging the numbering of hook arguments in HooksScripts.txt

### ISSUE THREAD

**Issue by FakelsHub** [phobos2077/sfall#345]
https://github.com/phobos2077/sfall/blob/50755832e3ae1921e876f9dafd9bdc8756a324bb/artifacts/scripting/hookscripts.txt#L83

Maybe we should renumber all so that it starts with 0. ?
because sometimes it's confusing using the get_sfall_arg_at or get_sfall_args functions.

**Comment by NovaRain** [comment]
Sure. Sometimes I do mistake the arg numbers when writing test hook scripts.

**Comment by burner1024** [comment]
What about call_offset-* and sfall_func_* ? It'd be good to be consistent.

**Comment by FakelsHub** [comment]
sfall_func_ - everything is fine there.
for call_offset - there is no point in renumbering something.
