### ISSUE TITLE
[Feature Request] Allow melee/unarmed damage to add to min damage of attacks

### ISSUE THREAD

**Issue by Question2** [phobos2077/sfall#346]
As i understand it, the melee/unarmed damage stat only adds to the max damage of attacks so even sulik with 9 melee damage tends to do low damage with melee weapons.

Is it possible to add a feature where the stat will add to the min damage of attacks as well? I think it would make melee/unarmed much more powerful for high str characters.

**Comment by Lexx2k** [comment]
You could just use a hook script and modify damage dealt with the weapon types.

**Comment by Question2** [comment]
Do you know how to do that?

**Comment by NovaRain** [comment]
Use `HOOK_ITEMDAMAGE` hook script.

**Comment by Question2** [comment]
> 
> 
> Use `HOOK_ITEMDAMAGE` hook script.

Do you have an example of how that works? And do you need to attach the script to something?

**Comment by NovaRain** [comment]
> 
> 
> > Use `HOOK_ITEMDAMAGE` hook script.
> 
> Do you have an example of how that works? And do you need to attach the script to something?

Read the documents in sfall modders pack first.
