### ISSUE TITLE
Some issues with the "make NPCs use left over AP" function

### ISSUE THREAD

**Issue by Question2** [phobos2077/sfall#347]
I thought this would allow NPCs to reload their weapons earlier, unfortunately it does not do that.

For example, lets say a NPC has a shotgun. If they cant fire two shots in one round (most NPCs do not have the 10 AP required to do this), they will fire one shot then try to use left over AP for a punch or kick (which is pointless).

Another problem is with NPCs that have a melee + ranged weapon. For example, salvatore guards with a laser pistol + combat knife.

With this feature active, they will shoot once with the pistol, then swap to the combat knife. Unfortunately, they do not swap back to the pistol and will use the combat knife for the rest of the knife even though it does much less damage than the pistol.

**Comment by FakelsHub** [comment]
Use sfall-extended with improved AI behavior where these problems have long been solved.

**Comment by NovaRain** [comment]
I was thinking about implementing NPCSwitchingWeaponFix, but not sure if it can be left always on.

**Comment by Lexx2k** [comment]
Personally I disabled this feature because it just made critters run into melee range all the time. It's pretty lame and rather dumb, tbh. 

Would be cool if critters with long range weapons would spend their remaining AP on getting distance to the player .. especially if the player doesn't have a long range weapon, etc... You know, stuff like that ... at least a little more intelligence in their behaviour.

**Comment by FakelsHub** [comment]
NPCSwitchingWeaponFix - this option is not related to what the author wrote.

**Comment by NovaRain** [comment]
> 
> 
> NPCSwitchingWeaponFix - this option is not related to what the author wrote.

Oh, just thought it'd help to reduce the case NPCs switching weapons before ending their turn.

**Comment by Question2** [comment]
> sfall-extended

Is this an updated version of sfall or something else? Im looking at the github page but the description for sfall extended is in russian. What does it do exactly?

**Comment by Lexx2k** [comment]
It's a different Sfall branch with features that aren't in the "vanilla" Sfall.
