### ISSUE TITLE
Game is being saved, check.

### ISSUE THREAD

**Issue by Buneks** [phobos2077/sfall#348]
Happy new year.

Sfall has that option to disable saving if you made NPCs aggro the MC, for example planting explosives on a NPC and failing an assassination attempt. After using an exit grid you're able to save again.

What functions were used to check if the user is saving the progress while a fight is going on? _combat_is_initialized_ immediately comes to mind, and I have used it in one of my global scripts, it helped changing the AP cost of certain attacks.

I tried using _get_game_mode_, and _SAVEGAME_ in a new script, and it's failing(?) to trigger whenever I save the game. If I try to play a specific sound when the game is saved, it doesn't do anything. Any idea, guys?

**Comment by NovaRain** [comment]
> Sfall has that option to disable saving if you made NPCs aggro the MC, for example planting explosives on a NPC and failing an assassination attempt. After using an exit grid you're able to save again.

Huh? There's no such option. `SaveInCombatFix=1` prevents the player from saving games in combat if any action point is spent.

**Comment by Buneks** [comment]
> 
> 
> > Sfall has that option to disable saving if you made NPCs aggro the MC, for example planting explosives on a NPC and failing an assassination attempt. After using an exit grid you're able to save again.
> 
> Huh? There's no such option. `SaveInCombatFix=1` prevents the player from saving games in combat if any action point is spent.

I though NPCs initiating combat mode if the player aggro any of them (Vault 15 village for example), and sFall blocking quick saves or normal saves was clear enough. Sorry if I brain farted, english is not my native language.
Is there a way of checking if the game is being saved? In a script, I mean.

**Comment by Buneks** [comment]
I don't want to prevent the player from ever saving - if someone feels like save scumming, who am I to deny that.
I want to increase the game difficulty, but to do that I would need to use a trigger - every time the player saves, a block of code is executed.

**Comment by FakelsHub** [comment]
There is no clear way to check if the player has saved the game.
