### ISSUE TITLE
Hook Explosions

### ISSUE THREAD

**Issue by VonZorch** [phobos2077/sfall#35]
Would it be possible to hook explosions.  I recently had the odd experience of having several bundles of dynamite in a bag, I set timers on two and after the explosions there sat the bag undamage with dynamite still in it.  I want to write a script to trigger sympathetic detonations and destroy or scatter items in the hex the explosion was in.

**Comment by phobos2077** [comment]
So you want some hook to be run when explosive timer expires? Have you tried playing around with something like **destroy_p_proc**?

**Comment by VonZorch** [comment]
Yes,  that was the first thing I tried.  When that didn't respond I tried
all the other _p_proc routines, no response with anything.  My usual
starting method is to write a script that just has a display_msg with a
distinctive message such as Destroy or Talk.

**Comment by FakelsHub** [comment]
Есть ли какие-либо мысли по этому Hook'у? - реально не хватает функционала для взрывов.
К примеру когда кинутая граната не попадая в цель взрывается, и хотелось бы как-то получить координаты куда она прилетела, или на какой координате произошел этот самый взрыв.
