### ISSUE TITLE
Make fallout2.exe large address aware

### ISSUE THREAD

**Issue by blackpaulillyria** [phobos2077/sfall#353]
If not already implemented, can we research if fallout2.exe would benefit from being large address aware?

**Comment by FakelsHub** [comment]
translator does not translate this issue :D

**Comment by NovaRain** [comment]
I don't see the point making FO2 able to access 4GB address under 64-bit Windows.

**Comment by FakelsHub** [comment]
ha, that's impossible.

**Comment by wipe2238** [comment]
> ha, that's impossible.

Just to add to this comment, it's impossible _for sfall_ to "make fallout2.exe LAA". IIRC that stuff has to be changed in .exe itself; read: you're free to distribute mod with bytepatched fallout2.exe but that has hardly anything to do with sfall.

**Comment by FakelsHub** [comment]
how enable.
https://www.toolgir.ru/wp-content/uploads/2014/09/2gbl-CFF-Explorer.png

**Comment by FakelsHub** [comment]
how enable.
https://www.toolgir.ru/wp-content/uploads/2014/09/2gbl-CFF-Explorer.png

**Comment by phobos2077** [comment]
There's no information to fill all that space with... First let someone make a huge mod with super-crisp graphics 🤣
