### ISSUE TITLE
Small Frame Trait

### ISSUE THREAD

**Issue by FakelsHub** [phobos2077/sfall#354]
Bonus points of Strength from Power armor give +25 to weight, instead of +15 when a Small Frame trait is taken.
is this even normal or bug? 

when dude has 6 strength and armor gives 4 points * 25 = 100, now we get to weight: 115 + 100 = 215 max. weight
when dude has 7 strength and armor gives 3 points * 25 = 75, now we get to weight: 130 + 75 = 205 maximum weight (lost 10 units)

code in engine: `*(proto + offsetof(critter_data, base_stat_carry_weight)) = 25 * ST + 25;`
for bonus points, the formula always (25 * ST)

**Comment by NovaRain** [comment]
Hmm, I wrote about the reason of that on local forums before.
The negative effect of Small Frame is not actually changing carry weight formula to `ST * 15` but `Normal Carry Weight - (base ST * 10)`. Bonus ST is not counted in for its negative effect.

The description in the manual is the simplified result from:
* Normal Carry Weight = 25 + (ST * 25) // ST here is the total, base + bonus.
* Has Small Frame trait = Normal Carry Weight - (ST * 10) // ST here is only the base.
* so the result = 25 + (ST * 15) // actually it's `25 + (base ST * 15) + (bonus ST * 25)`

Not sure if changing the `stat_get_base_direct_` in `trait_adjust_stat_` (0x4B3F7F) would work or it might break something else.

**Comment by FakelsHub** [comment]
> personally I'd say it's normal because I think power armor should give the wearer equal extra/boosted strength output (i.e. additional carry weight from bonus ST is the same for normal person and "small" person.) 

Think logically:
1. The maximum weight carried depends on the strength, and nothing else. 
2. The character additionally has some bonus or negative condition for calculating the final weight.

The question of why the maximum transportable weight must be considered according to two different formulas?

**Comment by NovaRain** [comment]
> The question of why the maximum carried weight must be considered according to two different formulas?

I don't quite get what you mean, fix or not there are still two different formulas for the max carry weight.
* Normal guy: `25 + (base ST * 25) + (bonus ST * 25)` // (25 + ST * 25)
* Small Frame: `25 + (base ST * 15) + (bonus ST * 25)` // (25 + ST * 15)

It's just normally the player doesn't know there are two fields (base & bonus) for a stat, so the FO1 manual only gives a general (or partial) description on the formula change.

> 
> ps: If not for the weak bonus that gives the trait +1ag, I would not have created this issue and would have fixed it no matter what.

What's your idea on the fix? Changing the base ST (stat_get_base_direct_) in `trait_adjust_stat_` to total ST so the resulted formula is exactly `25 + (ST * 15)`?

**Comment by fedprod** [comment]
Um, there was the old bug that allowed you to have your strength incresed even AFTER you unequipped your PA. Pretty sure that was because the engine didn't allow to reduce the base stat correctly ^^"

**Comment by Lexx2k** [comment]
Agree with NovaRain on this. I don't think the devs made a mistake here and we probably shouldn't touch it to not stray away too far from the original.

**Comment by FakelsHub** [comment]
ok. can make this an optional fix.
because the trait bonus is too small.

**Comment by NovaRain** [comment]
> 
> 
> ok. can make this an optional fix.
> because the trait bonus is too small.

I don't know, but IMO there are some other traits with the similar "small bonus vs big negative", for example Kamikaze (no natural AC vs +5 Sequence) and Fast Metabolism (0% poison/rad resistance vs +2 Healing Rate). I think that's kinda the point of traits.

And I still don't know what's your take on Small Frame, do you think "1 bonus ST still gives +25 carry weight" is a hidden benefit for it because the trait only give +1 AG? Or you think the case of "increasing base ST results in less carry weight" is a mismatch bug? Are you going to fix the subtraction in the way I said in my previous reply or something else?

**Comment by FakelsHub** [comment]
Kamikaze: max -10 AC vs +5 Sequence
Fast Metabolism: max -70% resistance vs +2 Healing Rate
(resistance against poison/radiation can be raised by chemistry at any time, and these stats are not as important as the weight carried). 
Small Frame: max -100 carry weight vs +1ac (+1ap) + small percent for some skills
it is obvious that the negative bonus of SmallFrame is greater than that of other Traits

> Are you going to fix the subtraction in

that there is another way?

**Comment by NovaRain** [comment]
> > Or you think the case of "increasing base ST results in less carry weight" is a mismatch bug?
> 
> yes

I think it's only noticeable when the player maxed out ST with power armor. For a ST 5-6 "average" character there shouldn't be any mismatch.
* base ST 5 with T-51b power armor (+3 ST): 100 + 3 * 25 = 175
* base ST 6 with T-51b power armor (+3 ST): 115 + 3 * 25 = 190

I just wonder if it's an option how many people would enable it for "less carry weight but unified calculation" (the option itself becomes kinda "useless" right after it's born because most people don't really wants to use it.)

**Comment by FakelsHub** [comment]
> I think it's only noticeable when the player maxed out ST with power armor. For a ST 5-6 "average" character there shouldn't be any mismatch.

The problem is that the strength points are cut off at the value of 10 (cap), this is the whole problem with the discrepancy with the weight.

**Comment by FakelsHub** [comment]
> I just wonder if it's an option how many people would enable it for "less carry weight but unified calculation" (the option itself becomes kinda "useless" right after it's born because most people don't really wants to use it.)

It is true that no one will enables it to their own detriment. But the fix may come in handy for a mod that doesn't have this weird calculation.

**Comment by NovaRain** [comment]
The option is implemented in commit 23d5041 and 7eab9ff.
