### ISSUE TITLE
Animation not played when using object at point blank range

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#356]
According to my tests, when using a spray in EPA, the plant doesn't play "falling" animation when used from a point blank range.
If used from a distance, dude walks to the plant and the animation does play.

Relevant [issue](https://github.com/BGforgeNet/Fallout2_Restoration_Project/issues/87), with a save to test.

Probably related to [punching bag](https://github.com/rotators/Fo1in2/issues/70) one, and also magic hands not working in "[trap door](https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/issues/61)"?

epac8.ssl:
```
/*
  ***   Script conwerted to Interplay format by Fallout Script Edytor (by Jargo)  ***
*/

#define SCRIPT_REALNAME "epac8"
#include "../headers/define.h"
//#include "../headers/<TownMapName.h>"

#define NAME                    SCRIPT_EPAC8          //Script name from scripts.h
#define TOWN_REP_VAR            GVAR_TOWN_REP_           //Global variable name for this Town

#include "../headers/command.h"

#define LVAR_Herebefore                 (4)
#define LVAR_Hostile                    (5)
#define LVAR_Personal_Enemy             (6)

#define max_attack_distance 16

procedure start;
procedure critter_p_proc;
procedure map_enter_p_proc;
procedure destroy_p_proc;
procedure use_p_proc;
procedure look_at_p_proc;
procedure description_p_proc;
procedure use_skill_on_p_proc;
procedure use_obj_on_p_proc;
procedure damage_p_proc;
procedure map_update_p_proc;
procedure talk_p_proc;

procedure timed_event_p_proc;

procedure start begin
   if not self_obj then return;
   set_self_team(TEAM_RND_SPORE_PLANT);
   set_self_ai(AI_SPORE_PLANT);
end

procedure critter_p_proc begin
   if not self_obj then return;
   // if self_can_see_dude and (distance_dude <= max_attack_distance) then attack(dude_obj);
end

procedure map_enter_p_proc begin
   variable item;
   if (map_first_run) then begin
      item:=create_object(PID_PLANT_SPIKE_EPA,0,0);
      add_mult_objs_to_inven(self_obj,item,10);
   end
end

procedure destroy_p_proc begin
  inc_global_var(GVAR_KILL_EPAPLANTS);
  if (global_var(GVAR_KILL_EPAPLANTS) >= 26) then begin
   display_msg(mstr(100));
  end
end

procedure use_p_proc
begin
end

procedure look_at_p_proc
begin
end

procedure description_p_proc
begin
end

procedure use_skill_on_p_proc begin
   if (action_being_used == SKILL_STEAL) then
      script_overrides;
end


procedure damage_p_proc
begin
   if (source_obj == dude_obj) then begin
      attack(dude_obj);
   end
end

procedure map_update_p_proc
begin
end

procedure talk_p_proc
begin
end

procedure timed_event_p_proc
begin
end

procedure use_obj_on_p_proc begin
   script_overrides;
   if ((obj_pid(obj_being_used_with) == PID_PLANT_SPRAY)) then begin
      inc_global_var(GVAR_KILL_EPAPLANTS);
      if (global_var(GVAR_KILL_EPAPLANTS) >= 26) then begin
        display_msg(mstr(100));
      end
      switch self_pid begin
         case PID_EPA_SPORE_PLANT: give_xp(150);
         case PID_RED_SPORE_PLANT: give_xp(200);
         case PID_GIANT_SPORE_PLANT: give_xp(350);
      end

      reg_anim_combat_check(0);
      reg_anim_clear(self_obj);
      reg_anim_begin();
         reg_anim_animate(self_obj,ANIM_fall_back,-1);
      reg_anim_end();
      // kill_critter(self_obj, ANIM_melted_to_nothing_sf);
   end
end
```

**Comment by FakelsHub** [comment]
попробуй другую анимацию.

**Comment by burner1024** [comment]
пробовал

**Comment by FakelsHub** [comment]
Сделал на цветке такую же процедуру, и все нормально.
```c++
procedure use_obj_on_p_proc begin
   script_overrides;
   if ((obj_pid(obj_being_used_with) == PID_KNIFE)) then begin
      reg_anim_combat_check(0);
      reg_anim_clear(self_obj);
      reg_anim_begin();
         reg_anim_animate(self_obj,ANIM_fall_back,-1);
      reg_anim_end();
      // kill_critter(self_obj, ANIM_melted_to_nothing_sf);
   end
end
```

**Comment by burner1024** [comment]
Ну скрипт же есть, сейв есть. Ты проверь не такую же а именно ту же. Тут у тебя оружие, возможно оно по другому работает.

**Comment by FakelsHub** [comment]
пошел проверил все работает.
нубы вы) кто же kill_critter использует в сочетании с reg_anim. понятное дело что анимации не будет.

**Comment by FakelsHub** [comment]
проверял на русской сборке сборке 2.3.3 с вот этим апдетом https://yadi.sk/d/0x1Br5gdqvzRIw

**Comment by burner1024** [comment]
что за русская сборка?

**Comment by FakelsHub** [comment]
Я ктому что kill_critter - Моментального действия, а reg_anim действует отложенно, уже после килл.

**Comment by FakelsHub** [comment]
Опция для увеличения количества одновременых анимаций в ddraw  надеюсь у вас на макс установлена.

**Comment by burner1024** [comment]
> Я ктому что kill_critter - Моментального действия, а reg_anim_animate действует отложенно, уже после килл.

 Да, но все равно сначала надо бы разобраться почему не играет, а остальное уже потом.
 
> Опция для увеличения количества одновременых анимаций в ddraw надеюсь у вас на макс установлена.?

Установлена.

> проверял на русской сборке 2.3.3 с вот этим апдетом https://yadi.sk/d/0x1Br5gdqvzRIw

Что за сборка, дай ссылку. В апдейте этом нету `epac8.int`.

**Comment by FakelsHub** [comment]
оттуда скачал http://www.nuclear-city.com/index.php/topic/937-restoration-update-pack-rup-rp-fixes-mods/

Скрипт вроде лежит в patch000.dat, я его только что доставал и переделывал.

**Comment by burner1024** [comment]
А, нашел.. Попробовал, никакой разницы не вижу.
Давай свой, скомпилированный.

**Comment by FakelsHub** [comment]
Да какая разница, твой, мой.
Значит это баговина система зависимая, дебажить надо у тех  на компах у кого она имеется.

**Comment by FakelsHub** [comment]
Я так понял анимации нет только когда стоишь в упор?

**Comment by burner1024** [comment]
> Да какая разница, твой, мой.

Ну так надо сравнить строчка в строчку и узнаем, разница есть или нет.

> Я так понял анимации нет только когда стоишь в упор?

Да, вот [видео](https://www.loom.com/share/49ae3a3574ab4b0fa24cb476ec7d9f20).

**Comment by FakelsHub** [comment]
> Ну так надо сравнить строчка в строчку и узнаем, разница есть или нет.

никакой разницы я просто скопипастил твой новый кусок для анимации и все.

**Comment by FakelsHub** [comment]
> Да, вот [видео](https://www.loom.com/share/49ae3a3574ab4b0fa24cb476ec7d9f20).

на видео вообще другая ситуация. первый клик по цветку похож на миссклик. и проверяли в бою.

**Comment by burner1024** [comment]
Именно та ситуация, я не знаю, что ты проверял.
Мисклика нет, смотри на сообщения, там пишет "used spray", это мой дебаг из скрипта epac8. Анимации никогда и не было.

**Comment by FakelsHub** [comment]
> Именно та ситуация, я не знаю, какую ты проверял.
обе ситуации не в RP
в RP только не в бою.

**Comment by burner1024** [comment]
Мне непонятно, какие обе. EPA это RP, ситуация с ней.
В общем, надеюсь теперь ясно, какая именно проблема обсуждается.

**Comment by FakelsHub** [comment]
> Мне непонятно, какие обе. 

На своей тестируемой карте (не RP), проверял в плотную в бою, и не в бою. результат работы OK.

**Comment by burner1024** [comment]
Ну а смысл тестировать что-то другое. Что-то другое может работать, может нет.
Сэйвы же для этого и нужны, чтобы проверять конкретную ситуацию, воспроизводить баг.

**Comment by FakelsHub** [comment]
> Ну а смысл тестировать что-то другое.

Что бы быть уверенным что баг есть везде.

**Comment by FakelsHub** [comment]
> Без боя то же самое, кстати.

без  `reg_anim_combat_check(0);` также нет анимации?

**Comment by FakelsHub** [comment]
```
/* Anim Commands */
#define RB_UNRESERVED   1    // unreserved animation sequence, may fail if no available slots
#define RB_RESERVED     2    // reserved animation sequence, should never fail
#define reg_anim_begin()    reg_anim_func(REG_ANIM_BEGIN, RB_UNRESERVED)
```
Еще попробуй использовать RB_RESERVED в reg_anim_begin()

**Comment by burner1024** [comment]
> без reg_anim_combat_check(0); также нет анимации?

Да.

Первое не помогает, второе играет но потом коржеит и застывает.
Может быть, связано с [пропуском](https://www.nma-fallout.com/threads/fo2-engine-tweaks-sfall.178390/page-118#post-4046889) фреймов?
Вроде где-то 1 из 10 все же срабатывает, как и с динамитом на дверях.

**Comment by FakelsHub** [comment]
Точто там писал фобос про пропуск, оказалость совсем другой причиной.
Наверняка там что-то с регистрацией или с запуском анимации и это явно завязано на быстродействии системы, многопоточность какая-нибудь шалит.
У меня на древнем железе норм. На  современном жележе у меня нет возможности дебажить.

Еще совет, сделать цикл и
While( здесь проверять текущее состояние если анимиация равна stand то продолжить цикл ) {
reg_anim_begin();
reg_anim_animate(self_obj,ANIM_fall_back,-1);
reg_anim_end();
}
Осторожно может повиснуть.

**Comment by FakelsHub** [comment]
Я потом еще раз проверю на вашем оригинальном sfall есть у меня одна мысля почему это может не работать.

**Comment by FakelsHub** [comment]
Проверил, этот баг есть с оригинальным sfall, на моей версии все OK.

**Comment by FakelsHub** [comment]
@NovaRain 
Wait with the release, if there is not a difficult bug search, then we will include it in the version.

**Comment by NovaRain** [comment]
> Проверил, этот баг есть с оригинальным sfall, на моей версии все OK.

I guess it's related to the tweak of `action_use_an_item_on_object_` in animations.cpp in your build?

**Comment by FakelsHub** [comment]
no.

**Comment by NovaRain** [comment]
> 
> 
> no. but that's what gave me the idea of where to look for the problem.

Oh, OK. It's not like we're hurrying for something. If it can fix both RPU's and EtTu's problem I'm all for it.

**Comment by egornovivan** [comment]
@FakelsHub там в EPA кстати еще робот был, его анимации так колбасило что fps в 0 падало. Гдето даже на стриме этот момент был записан.

**Comment by NovaRain** [comment]
That has been fixed in RPU.

**Comment by burner1024** [comment]
Ah, so the reason it's not present in extended sfall is that it forces magic hands always?
Maybe add some hack with a single-frame dummy animation?

**Comment by FakelsHub** [comment]
Фиктивная? она должна быть зарегистрирована в списке анимаций, а если это что-то левое двиг ее не зарегистрирует, много всяких проверок.
Просидел 4 часа в пошаговом режиме искал где баг, так и не понял в чем отличие, есть анимация,  или нет анимации. Голова квадратная.
Меня вполне устраивает анимация рук. главное это естественно, что при пользование предметов должна быть анимация, а не как миссклик в пустоту)
Искать надо где баг.

**Comment by NovaRain** [comment]
I didn't add it because I was dubious about if it's really a fix or the devs added it purposely. In FO1 the magic hand is always played for all interactions; in FO2 "using" stairs and using items on objs are excluded. Yes, I do understand you said "it's natural", but personally I feel it becomes somewhat lengthy when you need to use items on the same obj repeatedly (e.g. superstim assassination or healing seriously wounded party members with normal stims) and there's at least one guy complained it on NMA already.

**Comment by FakelsHub** [comment]
what is it `0x0C75` ?

**Comment by NovaRain** [comment]
> 
> 
> what is it `0x0C75` ?

Restore the original state (no magic hand for using items on objs).

**Comment by FakelsHub** [comment]
I don't understand your idea.

**Comment by NovaRain** [comment]
> 
> 
> I don't understand your idea.

My idea is if your tweak helps the case of EPA plant spray, calling the `0x9090` (the same as in your code) before the anim sequence to apply it and restoring to vanilla state after the sequence could work, and the "force magic hand" tweak only applies during this script case only so people won't complain suddenly they got magic hand anim when using items on objs in other cases.

**Comment by FakelsHub** [comment]
your idea is not untenable
action_use_an_item_on_object_ вызывается до выполнения скрипта с reg_anim**

**Comment by NovaRain** [comment]
> 
> 
> your idea is not untenable
> action_use_an_item_on_object_ called before executing the script with reg_anim**

Oh, that doesn't work if the write_short lines are in `use_obj_on_p_proc` procedure?

**Comment by FakelsHub** [comment]
> But the ext tweak doesn't seem to help the case of punching bag in Et Tu, which has a similar "anim plays if the player walks one hex, but no anim if at point blank range" issue.

Where to find this script. maybe in that sequence it is easier to detect a bug than in here?

**Comment by NovaRain** [comment]
> 
> 
> > But the ext tweak doesn't seem to help the case of punching bag in Et Tu, which has a similar "anim plays if the player walks one hex, but no anim if at point blank range" issue.
> 
> Where to find this script. maybe in that sequence it is easier to detect a bug than in here?

In its issue 70:
https://github.com/rotators/Fo1in2/issues/70

**Comment by FakelsHub** [comment]
```c
 if ( scenType != scenery_type_stairs && !_item ) <<<< here tweak
      {
         register_object_animate_(_source, useAnim, -1);
      }
      if ( _item )                                                              // если применяем предмет
      {
         register_object_call3_(_source, _target, _item, obj_use_item_on_, -1); <<<< here execute use_obj_on_p_proc
      }
```

**Comment by NovaRain** [comment]
Thanks, but I already know what your tweak does.

**Comment by FakelsHub** [comment]
> that doesn't work if the write_short lines are in use_obj_on_p_proc procedure?

yes

**Comment by NovaRain** [comment]
You show the pseudocode like the `if (_item)` is inside the `if ( scenType != scenery_type_stairs && !_item )`, but it's:
![code](https://user-images.githubusercontent.com/8564973/106678492-d92e1180-65f5-11eb-9435-82bbaeeb6f31.png)

**Comment by FakelsHub** [comment]
it just shifted)

**Comment by NovaRain** [comment]
> 
> 
> it just shifted)

Ah, OK, at least I know my idea doesn't work now, back to square one I guess.

**Comment by FakelsHub** [comment]
> It probably has a different cause than EPA plant spray, but the symptom is similar.

there in the use_p_proc procedure as opposed to here in use_obj_on_p_proc

**Comment by FakelsHub** [comment]
Well, there's no problem with the punching bag.
They just remove the animation of "hands" in the hook, so this bug appears.

Ну с грушей никакой проблемы нет.
Там просто убирают в крючке анимацию "рук" поэтому и появляется этот баг.

**Comment by egornovivan** [comment]
> Искать надо где баг.

Может имеет смысл потыкать старые версии sfall? Может тогда станет ясно где и когда свернули не туда?

**Comment by FakelsHub** [comment]
Думаю эту проблему следует отложить на следующие версии, нужно разбираться в функциях движка как он анимирует это все. там все сложно код ни черта не понятен и не разобран в большинстве частях.

I think this problem should be postponed to the next versions, you need to understand the functions of the engine as it animates it all. everything is complicated there, the code is not clear and is not disassembled in most parts.

**Comment by NovaRain** [comment]
> 
> 
> Well, there's no problem with the punching bag.
> They just remove the animation of "hands" in the hook, so this bug appears.

Not sure if I understand the cause correctly: both cases (no anim if the player is at point-blank range, but works if the player walks to the obj) are because there should be an animation (magic hands or movement) registered prior to `use_obj_on_p_proc` and `use_p_proc` for the anim sequence inside them to work?

For EPA plant spray, there's no animation because by default the engine doesn't register an anim for using items on obj, and your tweak forces the engine to register magic hands for it?
For Et Tu punching bag, it's the original magic hand anim got blocked so the follow-up sequence in the hook doesn't work?

**Comment by FakelsHub** [comment]
Yes, you understand all this correctly :-)

**Comment by NovaRain** [comment]
> 
> 
> Yes, you understand all this correctly :-)

OK, it would be nice if the requirement of having an anim registered prior to the proc can be fixed or removed somehow.

**Comment by burner1024** [comment]
More findings:
If you start combat standing near the critter, then move away, then back close and use the item, the animation is still not played.

**Comment by FakelsHub** [comment]
Нашли еще один баг связанный с этим, авто-закрытие контейнеров так-же может не работать по этой же причине (через раз их закрывает).

**Comment by NovaRain** [comment]
The issue in the first post should be fixed by now with the new tweak. I tested a similar animation sequence with Klint (using any item on him will play "knocked down" anim), and the anim plays when using items at point blank range in/out of combat.

**Comment by NovaRain** [comment]
Test build: [sfall_fc53df5.zip](https://github.com/phobos2077/sfall/files/6451025/sfall_fc53df5.zip)
Or you can just make a global script that simply runs `write_short(0x4120B8, 0x9090);` on game start, which is exactly how the tweak works.

**Comment by NovaRain** [comment]
> 
> 
> > The issue in the first post should be fixed by now with the new tweak.
> 
> This tweak is not a solution to this problem.

Well, it does prevent the issue of animation not playing as when you tested with your build.

**Comment by burner1024** [comment]
Well, however it works under the hood, it does work. Thanks!

**Comment by burner1024** [comment]
So apparently the change forces magic hands, I somehow missed that and thought it was a clean fix. And of course, [not everyone likes it](https://www.nma-fallout.com/threads/magic-hand-animation-upon-using-an-item-to-an-object.220586/).

> В таких случая нужна небольшая задержка перед регистрацией.
Функция anim_busy должна помочь в этом деле.
reg_anim_clear(self_obj); - не очищает приоритетные анимации.
возможно сделаю макрос: reg_anim_force_clear

Any example?
