### ISSUE TITLE
AI teams fighting each other on accidental hits

### ISSUE THREAD

**Issue by Lexx2k** [phobos2077/sfall#357]
This is an issue that we've talked about already a couple times in the past, as example [here](https://github.com/rotators/Fo1in2/issues/25) and the latest [here](https://github.com/rotators/Fo1in2/issues/80).

**What exactly is the issue:**
If any ai critter from team A hits team B, they will start fighting each other. This in general is _not an issue_. However, it becomes a problem if the _player_ is currently neutral and watches team A and B fight, and a critter accidentally hits him or party members - the player team will then be dragged into the combat no matter what.

As far as I can tell, this issue isn't very prominent in Fo2, because the combat encounters are setup more straight forward (player team vs one other team almost all the time).

However, in Fo1/ettu this makes problems, because there are more situations where multiple teams are fighting each other (example Junktown with Killian's guards, or the Brotherhood Paladins from the above linked issue ticket). 
The Brotherhood paladins are the worst, because their miniguns have a very high chance to hit the player or a party member ... once this happens, they will not stop attacking the player party.

Note: It's not just these "Ooops x accidentally hit y" attacks, but *any* hit (burst attacks or splash damage, as example). Any critter that gets accidentally hit will join the combat and start fighting the players party.

**A suggested way to address this:**
1. If a critter accidentally hits _the player or a party member_, both groups will not get hostile at each other.
2. If a _party member_ accidentally hits another critter, both groups will not get hostile at each other.

This way it acts as a sort of safety net - the player can't abuse the mechanic, and ai retardation is less annoying and more forgiving.

Thoughts?

**Comment by FakelsHub** [comment]
I have already said that this is not a bug, this is the specifics of the game engine.

> A suggested way to address this:
>    1. If a critter accidentally hits the player or a party member, both groups will not get hostile at each other.

Only this variant is reasonable.

**Comment by Lexx2k** [comment]
This is 100% a bug, if you like it or not. Having a whole group (that should be friendly to me) go nuts just because Private Dumbass hit me with 1 bullet of his 100 rounds minigun burst, I should not become the target of his and his friends anger. This has serious gameplay implications.

**Comment by FakelsHub** [comment]
An allied team is one that has the same number as the player, i.e. zero. 
All other commands are considered neutral by default.
Perhaps you should change the number of teams in the allied battles in your Ettu, and the allied strikes will not cause pain in the fifth point. :-)

**Comment by Lexx2k** [comment]
I don't understand how you can't see that this is total bullshit. Or maybe this is language barrier? Or are you just trolling me?

To get back to the brotherhood paladins ... if I would set them to team 0, player party members would more than ever run into combat even though they should not.

**Comment by egornovivan** [comment]
Не ну это реально тупо, нейтрал случайно попадает по нам, а потом еще и агрится на нас за это.

**Comment by burner1024** [comment]
> A suggested way to address this:
    If a critter accidentally hits the player or a party member, both groups will not get hostile at each other.
    If a party member accidentally hits another critter, both groups will not get hostile at each other.

I agree. Although for fairness, other teams should not aggro on each other because of accidental hits as well (party vs one team scenario.)

**Comment by Lexx2k** [comment]
I don't think that it is bad if other ai teams start fighting each other. It adds more dynamic to the fight. I just hate how the player gets fucked over due to something he has no control over.

**Comment by burner1024** [comment]
Is it possible to distinguish accidental hits? Maybe something like `set_object_data(self_obj, OBJ_DATA_WHO_HIT_ME, self_obj);` would work?

**Comment by FakelsHub** [comment]
@burner1024 Теоретически скритово это можно исправить.
Взять изначальную цель атакующего из крючка TOHIT и проверить ее потом где-нибудь в крючке Damage, если цель не совпадает то это случайное попадание, тут же берем текущую цель `OBJ_DATA_WHO_HIT_ME` у того в кого попали, что бы потом ее восстановить.
Но тут одно но с восстановлением цели `OBJ_DATA_WHO_HIT_ME` у цели (в которую случайно попали) явно могут быть проблемы, потому, что это вроде назначается уже после крючка Damage (насколько я помню).

**Comment by NovaRain** [comment]
@Lexx2k Here's the test build if you want to check the fight in Et Tu:
[sfall_build_bdebed8.zip](https://github.com/phobos2077/sfall/files/6138532/sfall_build_bdebed8.zip)

**Comment by Lexx2k** [comment]
Seems to be working. However, with this build my game crashes when entering encounters on my own with `023b76b9 memory 00000078`. The crash doesn't happen if the game pulls me into an encounter on its own.

**Comment by NovaRain** [comment]
The crash seems related to the fix for the attached script of objects, as the same crash happens with the build from the previous commit (for issue 359).

**Comment by Lexx2k** [comment]
I had copy&pasted code from my other Fo2 mod, which has more scenery objects. :D Apparently vanilla Fo2 doesn't care if it can't find scenery objects, it simply won't spawn them. However, with the latest change about trying to call script id on spawn, it crashes the game. Maybe this should print a fitting error message into the debug.log? `Error: Can't find scenery object PID` or something?
