### ISSUE TITLE
WorldMapFPSPatch this seems to be not working anymore?

### ISSUE THREAD

**Issue by FakelsHub** [phobos2077/sfall#358]
`WorldMapFPSPatch` and `WorldMapDelay2` don't seem to do anything for me.
The speed of movement on the global map is always the same (normal) both with the `WorldMapFPSPatch` option enabled and disabled.
`WorldMapDelay2` also has no effect on anything.
In general, I'm confused, I've noticed this for a long time.
I can't understand what the problem is.!!!

**Comment by NovaRain** [comment]
They both work on my PC. The world map travel speed is noticeably different with WorldMapFPSPatch=1 or 0, or WorldMapDelay2=66 or 6.

**Comment by FakelsHub** [comment]
Maybe can delete WorldMapdelay2 and set its value to 60 = 15*4 based on the fact that the GetTicksCount function returns an average value of 15ms.
By the way, where did this strange number 66 come from ?)

**Comment by NovaRain** [comment]
> By the way, where did this strange number 66 come from ?)

Dunno, that's the default value when Timeslip implemented the patch from Ray from TeamX forums, you might want to dig into their old discussion since that's in your native language.

**Comment by FakelsHub** [comment]
interested in how strong is the difference between 66 and 6 ?

**Comment by NovaRain** [comment]
> 
> 
> interested in how strong is the difference between 66 and 6 ?

Tested with the same travel distance in one of my saves, from Modoc to Vault City, and used a stopwatch.
It takes 29.84 sec with `=66` and 6.08 sec with `=6`.

**Comment by FakelsHub** [comment]
Do you have a speed difference between 66 and 77 ?

> So do you find the cause of the speed issue on your spec?

Somehow the difference is not noticeable, it feels like there is some third-party patch in the exe.

**Comment by NovaRain** [comment]
> 
> Do you have a speed difference between 66 and 77 ?
> 

It seems `=77` not having any difference from 66: 29.98 sec.

> 
> Somehow the difference is not noticeable, it feels like there is some third-party patch in the exe.

You're testing with Sonora?

**Comment by FakelsHub** [comment]
> It seems =77 not having any difference from 66: 29.98 sec.

this confirms that the values must be multiples of 15ms.

> Are you testing with Sonora?

No.

Okay, I'll close this Issue.

**Comment by NovaRain** [comment]
> 
> 
> > It seems =77 not having any difference from 66: 29.98 sec.
> 
> this confirms that the values must be multiples of 15ms.
> 

I don't think it's a fixed (X * 15 ms) for all specs, according to MSDN:
The resolution of the GetTickCount limited to the resolution of the system timer, which is typically in the range of **10** milliseconds to **16** milliseconds.

**Comment by FakelsHub** [comment]
> 10 milliseconds

No matter how many forums I read, no one has ever confirmed that this can produce a stable 10ms
I can make a function to determine the average value, and output this value to the game log.

**Comment by NovaRain** [comment]
> 
> 
> > 10 milliseconds
> 
> No matter how many forums I read, no one has ever confirmed that this can produce a stable 10ms

Oh, OK. The default timer resolution on Windows is 15.6 ms:
https://randomascii.wordpress.com/2013/07/08/windows-timer-resolution-megawatts-wasted/
