### ISSUE TITLE
map_update_p_proc stops running for some reason

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#359]
Can't quite pinpoint, but I figure it's an engine bug either way.
Basically, [this script](https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/843104558b80d4279f30a3e665c5305254b917d3/scripts_src/sierra/wsklaxon.ssl) doesn't work for some reason. Klaxons are not destroying themselves when `GVAR_SIERRA_BASE_SECURITY` is flipped back and forth. As far as I can tell, `map_update_p_proc` is not even run. But if you use "look" action on klaxons, they seem to get back on track and switch state.
Described [here](https://github.com/BGforgeNet/Fallout2_Restoration_Project/issues/70#issuecomment-753483781), with saves to test. (Need to add `set_global_var(GVAR_SIERRA_BASE_SECURITY,SIERRA_SECURITY_ON);` into [terminal script](https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/843104558b80d4279f30a3e665c5305254b917d3/scripts_src/sierra/wsterm1b.ssl#L227) to get it flipping).

**Comment by FakelsHub** [comment]
Не могу въехать в ситуацию, а зачем это все повесили на `map_update_p_proc`? т.е. куда повесили то и получили.

**Comment by FakelsHub** [comment]
> As far as I can tell, map_update_p_proc is not even run. 

С чего это он должен запускаться, если у него запуск раз в 20сек и при входе на карту (все остальные его вызовы можно считать багом движка).

**Comment by burner1024** [comment]
> С чего это он должен запускаться, если у него запуск раз в 20сек и при входе на карту

Ну так нет этого раз в 20 секунд. Не выключается. А лупой посмотришь - выключается.

**Comment by FakelsHub** [comment]
>Ну так нет этого раз в 20 секунд.

В первый раз такое слышу/вижу. Ну ладно. Сохранение сюда прикрепи.

**Comment by burner1024** [comment]
[SLOT03.zip](https://github.com/phobos2077/sfall/files/6013947/SLOT03.zip)

**Comment by FakelsHub** [comment]
> А биноклем посмотришь - выключается.

Может там карта не прорисовывается, поводи курсором, ниче?

**Comment by burner1024** [comment]
Да нет. Ну и не у меня одного же это.

**Comment by FakelsHub** [comment]
```
procedure Node002a begin
   
   set_map_var(49, 1);
   call Node001();
end
```
Что сюда впихнуть?

**Comment by FakelsHub** [comment]
У меня все работает, лампочки загораются после выхода из диалога, там как раз в движке сделано запуск map_update_p_proc при входе/выходе из диалога.

единственное что я увидел в WSKlaxon.int то что номер скрипта неверный написан, не 251 должен быть (так как в нотепаде в SCRIPTS.LST как раз строка с номером совпадает а должно быть различие на 1). 
`LVar0 := create_object_sid(33555340, tile_num(self_obj), elevation(self_obj), 251);`

**Comment by burner1024** [comment]
Загораются-загораются. А потом не выключаются.

**Comment by FakelsHub** [comment]
потому, что скрипта там не верный прикрепляется.

**Comment by burner1024** [comment]
Так... а как тогда работают все остальные вызовы create_obj_sid?
Ну вот например
https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/843104558b80d4279f30a3e665c5305254b917d3/scripts_src/redding/rcjane.ssl#L506
https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/843104558b80d4279f30a3e665c5305254b917d3/data/scripts/scripts.lst#L534
https://github.com/BGforgeNet/Fallout2_Restoration_Project/blob/843104558b80d4279f30a3e665c5305254b917d3/scripts_src/headers/scripts.h#L553

**Comment by FakelsHub** [comment]
Ане пардон, все верно 251 номер скрипта.
В общем ладно надо тогда разбираться.

**Comment by FakelsHub** [comment]
Все я понял причину, скрипты которые привязываются через create_object_sid не инициализируются должным образом.

**Comment by NovaRain** [comment]
Can confirm the script attached by `create_object_sid` only gets initialized (`start` proc gets executed) when there is some interaction with the object, or when you re-enter the map.

I spawned a scenery object with a test script attached, which has `start`, `look_at_p_proc`, `use_skill_on_p_proc`, and three `map_*_p_proc` (just print messages). When it got spawned at the first time, map_update_p_proc never runs no matter what I did (wait in the game, talk to party members, etc.), but once I "look at" it with the cursor, `start` and `look_at_p_proc` runs at the same time, then `map_update_p_proc` starts running normally.

**Comment by Lexx2k** [comment]
Oh, I had this issue some months ago when spawning a critter. I had to put a timer event into the start_proc to get the shit to work.

**Comment by NovaRain** [comment]
Here's the test build: 
[sfall_build_d76f513.zip](https://github.com/phobos2077/sfall/files/6136004/sfall_build_d76f513.zip)

**Comment by burner1024** [comment]
Great. Although I already made a fix [in a different way](https://github.com/BGforgeNet/Fallout2_Restoration_Project/commit/1402f7b65c2d509d9514b3890a5c383f5a836999).

**Comment by NovaRain** [comment]
OK, at least now people can spawn objects and the attached script got initialized right away without interaction from the player.

**Comment by FakelsHub** [comment]
> Although I already made a fix in a different way.

Ужасно тормозной путь) каждый раз перебирать 100+ объектов карты, что бы изменить парочку из них.

**Comment by burner1024** [comment]
> OK, at least now people can spawn objects and the attached script got initialized right away without interaction from the player.

Yes, and I'm fairly sure this fix will do away with a handful of other silent bugs.

> Ужасно тормозной путь) каждый раз перебирать 100+ объектов карты, что бы изменить парочку из них.

Клаксонов там не парочка а десятки. И до этого каждый из них на каждое биение map_p_proc дергал скрипт. Так что какой путь тормознее это еще вопрос.

**Comment by FakelsHub** [comment]
We have a problem, the water chip is broken after this fix! :)
