### ISSUE TITLE
CheckWeaponAmmoCost option.

### ISSUE THREAD

**Issue by FakelsHub** [phobos2077/sfall#360]
It is suggested to remove the option from ddraw. ini and make the cost check permanent.
This will also require exclude checking for a count of rounds for the burst mode, because this violates the firing mode. Can't to attacking if, for example, one round is not enough for the burst mode, оr do I somehow misunderstand the essence of this option?

**Comment by NovaRain** [comment]
Forcing this option on you will have vanilla mega power fist to be only able to attack 12 times with 1 cell left instead of 13 times.

**Comment by FakelsHub** [comment]
Something I can't figure out, the code in the check_item_ammo_cost function is clearly working somehow incorrectly.
example for a single shot
currAmmo = 2
rounds = 3 (implied as a cost)
cost: `3 / 2 = 2 (with round up)`
return result 1 (must be 0)

```c++
        long cost = 1; // default cost
	if (currAmmo > 0) {
		cost = rounds / currAmmo;
		if (rounds % currAmmo) cost++; // round up
	}
	return (cost > currAmmo) ? 0 : 1;  // 0 - this will force "Out of ammo", 1 - this will force success (enough ammo)
```

> AFAIR this option doesn't cause normal burst attacks not to work if ammo in mag is less than the amount of one burst.

If this is the case, then why is this done for queue attacks, what does it check for, is a very strange function.

**Comment by NovaRain** [comment]
> If this is the case, then why is this done for burst attacks, what does it check for, is a very strange function.

It's for the example in my message above.

**Comment by FakelsHub** [comment]
Need to look at its older implementations, I may have made some mistakes somewhere.

**Comment by FakelsHub** [comment]
> Huh? I thought integer division doesn't have rounding.

`if (rounds % currAmmo) cost++; // round up`

**Comment by FakelsHub** [comment]
> It's for the example in my message above.

I still didn't understand what the function should check for in the case of burst attacks

**Comment by FakelsHub** [comment]
Okay, I'll deal with this function in the afternoon (now I have a night).

**Comment by NovaRain** [comment]
> I still didn't understand what the function should check for in the case of burst attacks

Hmm, I re-tested my old script. Enabling the option seems causing burst attacks to go wrong.
```pas
procedure start;
procedure hook_test;

procedure start begin
   if game_loaded then begin
      register_hook_proc(HOOK_AMMOCOST, hook_test);
   end
end

procedure hook_test begin
   variable
      weapon    := get_sfall_arg,
      burstAmmo := get_sfall_arg,
      ammoCost  := get_sfall_arg,
      event     := get_sfall_arg;

   // now assault rifle costs 3 ammo per shot
   if (obj_pid(weapon) == PID_ASSAULT_RIFLE) then begin
      set_sfall_return(3 * burstAmmo);
   end
end
```
I changed the proto to have mag size of 30, 5 rounds per burst, and the min/max damage to the same fixed value of 3 (so I can check the hit rounds easier). Shooting a junkie with no armor:
* With `CheckWeaponAmmoCost=0`, single attack costs 3 ammo, and burst attack costs 15 ammo for 5 hits. If the gun has only 12 ammo, a burst attack empties the gun but can still have 5 hits on the target (should be 4 hits only).
* With `CheckWeaponAmmoCost=1`, single attack costs 3 ammo (correct), and burst attack costs only 6 ammo for 2 hits. If the gun has only 12 ammo, a burst attack costs no ammo(!) and can cause damage higher than it should be, sometimes even over 500.

Testing 4.1 (the first version when the option got rewritten) the problems are similar. With 4.0.x the test case works normally with the option enabled.

**Comment by FakelsHub** [comment]
> and burst attack costs only 6 ammo for 2 hits. If the gun has only 12 ammo, a burst attack costs no ammo(!) 

Here I can't understand the logic of what you wrote (as in your previous message when you enable the option)

> Testing 4.1 (the first version when the option got rewritten) the problems are similar. With 4.0.x the test case works normally with the option enabled.

the current implementation of divide_burst_rounds_by_ammo_cost, which is responsible for calculating ammo for the burst, is completely identical to version 4.0.4

**Comment by NovaRain** [comment]
> Here I can't understand the logic of what you wrote (as in your previous message when you enable the option)

One single shot cost 3 ammo, and one full burst of 5 shots costs 15 ammo. If the gun has only 12 ammo left, it should only fire 4 shots (12 / 3 = 4) for a "partial" burst, just like a normal 10mm SMG has only 3 ammo left when trying to use the burst attack.

**Comment by FakelsHub** [comment]
```
// now assault rifle costs 3 ammo per shot
 if (obj_pid(weapon) == PID_ASSAULT_RIFLE) then begin
    set_sfall_return(3 * burstAmmo);
 end
```
It would be correct if the hook initially returned the value of the cost, and not the count of rounds multiplied by the cost.
this confuses the whole process.

**Comment by FakelsHub** [comment]
> With 4.0.x the test case works normally with the option enabled.

You say that in 4.0/3.8 it all works correctly???
but for my calculations, it still does not work correctly.

**Comment by NovaRain** [comment]
> You say that in 4.0/3.8 it all works correctly???
> but for my calculations, it still does not work correctly.

Yes, in 4.0.x/older 3.8.x my tests work correctly, at least the burst related stuff that you "don't understand a damn thing" works exactly as my description/explanation.

**Comment by NovaRain** [comment]
> 
> 
> I don't understand a damn thing))
> change the function to this and try what you get
> 

Now a burst attack just uses all ammo in the magazine, ignoring the set value in the proto.

**Comment by FakelsHub** [comment]
in general, I was fucked up and I created my own test, as it turned out in the current version everything works well, you just incorrectly applied the hook. Why does it work in older versions?! Because there's a bug, which has been fixed in new versions.

**Comment by NovaRain** [comment]
> n general, I was fucked up and I created my own test, as it turned out in the current version everything works well, you just incorrectly applied the hook.

Then what's your test setup and the correct code for the hook, if I want a weapon that costs 3 ammo per shot in both single and burst attacks?

**Comment by FakelsHub** [comment]
Fixed hook
```
if (obj_pid(weapon) == PID_ASSAULT_RIFLE) then begin
      set_sfall_return(3 * ammoCost);
end
```

**Comment by NovaRain** [comment]
> Fixed hook

Oh, OK, now it works.

> will need to adjust the description for the hook

You mean the main description or for the arguments?

**Comment by FakelsHub** [comment]
> But the option still prevents burst weapons from firing

I made corrections in another function. there was a wrong calculation.
