### ISSUE TITLE
Large number of quests per location breaks the Pip-Boy UI

### ISSUE THREAD

**Issue by blackpaulillyria** [phobos2077/sfall#361]
If you have a large number of quests for one location, 16 for example, one of the quests will always go to top position not respecting the order inside quests.txt. 
Further increasing this number, for example to 18, creates a pagination where the second page is inaccessible. 

EDIT: OK, I figured out where the pagination controls are. I expected it to work like when you're reading long holodisks.
Still not sure why one of the quests is always on top, although it's 20th on the list.

**Comment by FakelsHub** [comment]
There are no problems with this.

**Comment by FakelsHub** [comment]
> Still not sure why one of the quests is always on top, although it's 20th on the list.

You must follow the order (sort) of the location numbers:
```
1500, description, gvar_index, display_threshold, completed_threshold
...
1501, description, gvar_index, display_threshold, completed_threshold
...
1510, description, gvar_index, display_threshold, completed_threshold
...
etc.
```

**Comment by NovaRain** [comment]
OK, now the in-game quest list follows the order in quests.txt.

**Comment by blackpaulillyria** [comment]
Thank you!
