### ISSUE TITLE
Add support for f2_res_dat and f2_res_patches to be loaded last

### ISSUE THREAD

**Issue by blackpaulillyria** [phobos2077/sfall#362]
Currently the order of patches makes `f2_res.dat` changes being overwritten which is undesirable behavior in scenario where you want to change the default Fallout 2 interface elements and also add support for changing them depending on whether the High Resolution mod is enabled or not. 
The problem I have is that my updated interface elements are inside `patch001.dat` while the high resolution UI is in `f2_res.dat`.
Because of the order of patches files loading, my high resolution files are never used in case they also exist inside `patch001.dat`.

```
;Set to 1 to use the modified data load order for the engine to find game data
;Original: patchXXX.dat > critter_patches > critter_dat > f2_res_patches > f2_res_dat > master_patches > master_dat
;Modified: master_patches > critter_patches > patchXXX.dat > critter_dat > f2_res_patches > f2_res_dat > master_dat
DataLoadOrderPatch=1
```

This feature request would allow the `DataLoadOrderPatch` to be set to `2` which would provide the following order

`f2_res_patches > f2_res_dat > master_patches > critter_patches > patchXXX.dat > critter_dat > master_dat`

**Comment by NovaRain** [comment]
Why packing your UI files in two separate dat files? For example, you can pack your own HR_IFACE_800.FRM in patchXXX.dat, and HRP will use them as long as you name the file correctly.
Also you should consider using the newer `PatchFileXX` options instead of old patchXXX.dat, Et Tu is a good example of how to use them for organizing mod files.

**Comment by blackpaulillyria** [comment]
> Why packing your UI files in two separate dat files? For example, you can pack your own HR_IFACE_800.FRM in patchXXX.dat, and HRP will use it intead as long as you name the FRM file correctly. It doesn't load UI files only from f2_res.dat and f2_res_patches.

Those files aren't my concern. Files such as death.frm and similar are causing me trouble.

> 
> Also you should consider using the newer `PatchFileXX` options instead of old patchXXX.dat, Et Tu is a good example of how to use them for organizing mod files.

I'll look into it.

**Comment by FakelsHub** [comment]
I suggest removing the option. since there is no reason to disable it.
the current path chain can be considered standard.

**Comment by NovaRain** [comment]
> 
> 
> I suggest removing the option. since there is no reason to disable it.
> the current path chain can be considered standard.

DataLoadOrderPatch? Sure, it's been set to 1 for both internal code and ini setting since 4.1.9.
