### ISSUE TITLE
High Resolution mod disables some sfall Main Menu options

### ISSUE THREAD

**Issue by blackpaulillyria** [phobos2077/sfall#363]
If I turn on the High Resolution mod, some of the sfall Main Menu options related to copyright/version text stop functioning.
In my case these are `MainMenuCreditsOffsetX, VersionString` and `sfall version string`.

**Before**

![Screenshot (187)](https://user-images.githubusercontent.com/58548291/112143400-b967a280-8bcf-11eb-9021-2a3457f049b7.png)

**After**

![Screenshot (186)](https://user-images.githubusercontent.com/58548291/112143420-bec4ed00-8bcf-11eb-8cb5-f58f95caaa35.png)

**Comment by FakelsHub** [comment]
don't use `MainMenuCreditsOffsetX` option.

**Comment by blackpaulillyria** [comment]
> don't use `MainMenuCreditsOffsetX` option.

Why?

**Comment by NovaRain** [comment]
With HRP it shifts the game/sfall version strings instead of the copyright one.
The game/sfall version strings in your second screenshot are shifted right out of the screen.

**Comment by blackpaulillyria** [comment]
OK, thanks for revealing that to me. Closing
