### ISSUE TITLE
Add support for High Resolution Patch with zoom

### ISSUE THREAD

**Issue by id259** [phobos2077/sfall#364]
Currently sfall works only with normal High Res Patch and will crash if version with [zoom](https://www.nma-fallout.com/members/mash.54659/#info) is used instead. Is it possible to implement support for it?

**Comment by FakelsHub** [comment]
This version has never been supported, and will not be maintained in a working state.
When using it, there may be some other crashes, or glitches in the game.

**Comment by NovaRain** [comment]
> 
> **Use HRP zoom version with sfall 3.8.x**

Nah, sfall 3.8.x doesn't work with the zoom version either.

**Comment by FakelsHub** [comment]
for me, Zoom does not work with any versions at all... probably requires some kind of password? :)

**Comment by NovaRain** [comment]
> 
> 
> for me, Zoom does not work with any versions at all... probably requires some kind of password? :)

I tested with UP in the windowed mode and replaced sfall's dll one by one. The current 4.2.9 crashed on start. With 4.2.2-4.2.8.1 the game can load normally, but only zooming in (Ctrl+Up) works; with 4.2.1.1 or older the zoom function works, at least I can zoom in/out fine.

**Comment by FakelsHub** [comment]
You can disable these hacks when using an incompatible version with 4.1.8
https://github.com/phobos2077/sfall/blob/0fbc29e8fd92c4e945cebc50c4f8cd89e9ff31e2/sfall/Game/render.cpp#L182

**Comment by NovaRain** [comment]
You mean like this?
```cpp
if (!hrpIsEnabled || hrpVersionValid) {
    // Custom implementation of the GNW_win_refresh function
    sf::MakeJump(0x4D6FD9, GNW_win_refresh_hack, 1);
    // Replace _screendump_buf with _screen_buffer for creating screenshots
    sf::SafeWriteBatch<DWORD>(FO_VAR_screen_buffer, {0x4C8FD1, 0x4C900D});
}
```

**Comment by FakelsHub** [comment]
> You mean like this?

Yes.

> It only lets the game load but still cannot zoom out.

You can search for which hack broke this.
In addition, there are still glitches.

**Comment by NovaRain** [comment]
> You can search for which hack broke this.
> In addition, there are still glitches

Found the commit that broke the zooming, commit 5053ab5. Commenting out `HookCall(0x447A7E, gdialog_bk_hook);` for _that_ commit works. But even if the "SPECIAL" flag code in LoadGameHook.cpp is disabled for the current build, the zooming is still broken, so there are more code conflicting with the zooming.

Also using `if (!sf::hrpIsEnabled || sf::hrpVersionValid)` to exclude the hacks in render.cpp seems to be an incorrect condition ("apply func replacmemts if no HRP or only HRP 4.1.8 normal"), as the hacks in render.cpp actually work with other older version of HRP. Unless you plan to dig into this further, I think we should just add a note in the readme saying the zoom version is not supported by the current sfall.

**Comment by FakelsHub** [comment]
> Unless you plan to dig into this further, I think we should just add a note in the readme about the experimental zoom version.

I do not plan to search problems for this version.

**Comment by NovaRain** [comment]
> 
> 
> > Unless you plan to dig into this further, I think we should just add a note in the readme about the experimental zoom version.
> 
> I do not plan to search resolve problems for this version.

OK, neither do I.
Maybe add this note under "Known issues" in the readme:
`Starting from 4.2.2, sfall is not compatible with the experimental 'Zoom' version of the hi-res patch v4.1.8.`

**Comment by FakelsHub** [comment]
Add.
