### ISSUE TITLE
on enter map sfall causes freeze

### ISSUE THREAD

**Issue by nirran** [phobos2077/sfall#365]
tested with and without any sfall scripts,sfall v 4.2 doesnt freeze,v 4.2.9 does,happened in modoc and in den

edit : v 4.2.8.1 freezes too

edit2: running modified megamod,tho den and modoc arent altered

**Comment by NovaRain** [comment]
I installed MM 2.47.6 and set the starting map to denbus1.map/modmain.map. Didn't have any freeze when starting the game on those maps. Maybe you can zip your ddraw.ini and debug.log and upload it here for examination.

**Comment by nirran** [comment]
sure,donno how to enable debug.log tho

**Comment by NovaRain** [comment]
> edit : ack,how do i enable debug.log?

`DebugMode` option in [Debugging] section.

**Comment by nirran** [comment]
ok thnx 

[Fallout 2.zip](https://github.com/phobos2077/sfall/files/6216076/Fallout.2.zip)

**Comment by FakelsHub** [comment]
here, apparently, you need to Savegame with which the game freezes.

**Comment by nirran** [comment]
load this and enter denbus1

sometimes doesnt bug

[SLOT95.zip](https://github.com/phobos2077/sfall/files/6347026/SLOT95.zip)

**Comment by nirran** [comment]
just wondering,should I edit posts here or not?

**Comment by nirran** [comment]
have u guys been able to verify this bug?

**Comment by FakelsHub** [comment]
Unfortunately, your save doesn't work on the Russian version of MM. so I delegate the search for the problem to another one.

**Comment by NovaRain** [comment]
Trying to load your save in MM 2.47.6 crashes the game (the save is not even loaded, crashed on the load game screen). And from your description:
> i donno if it is related but i **started a new game and sulik and vic were at smitty in den**,seems it is loading some of the previous saves

It seems either you accidentally mix the map file with the one from your saved games, or something is seriously wrong with your modded game, which I have no idea what or how much stuff you changed.

**Comment by FakelsHub** [comment]
I try on 2.47.3 - this is loaded but crashes in the game itself when loading the den map.

**Comment by nirran** [comment]
Anything I can do to help?

**Comment by FakelsHub** [comment]
archive your version of the game and upload it here.

**Comment by nirran** [comment]
i removed all sfall scripts from 'vanilla' megamod(2.47.6) and made a master.dat of it,this is the current data folder with my modded files

https://www.dropbox.com/s/wx5p4tkxhtrvdbq/Data.zip?dl=0

**Comment by FakelsHub** [comment]
I placed your data folder in mm2. 47. 3 with sfall version 4.2.9 and I didn't get any hang when enter to denbus1.

**Comment by FakelsHub** [comment]
determine the most recent version of the sfall with which you do not have a freeze.

**Comment by nirran** [comment]
tested a bunch,seems 4.2.6 is most recent w/o freeze

**Comment by FakelsHub** [comment]
[M_ddraw.zip](https://github.com/phobos2077/sfall/files/6525203/M_ddraw.zip)
confirm that you don't have a freeze with this.

**Comment by nirran** [comment]
that fixed it thxn dude,you guys rock !
