### ISSUE TITLE
cur_town seems broken

### ISSUE THREAD

**Issue by blackpaulillyria** [phobos2077/sfall#366]
I can't get `cur_town` to work even in vanilla Fallout 2. It's always returning `-1`.

**Comment by Lexx2k** [comment]
Works fine for me in ettu.

**Comment by blackpaulillyria** [comment]
I installed Fallout 2 from Steam, decompiled `obj_dude.int`, added `display_msg("" + cur_town);` to `critter_p_proc`, compiled it and it's giving back `-1`.

**Comment by blackpaulillyria** [comment]
Correction, I added this line `display_msg("" + metarule(46, 0));` which should be the same

**Comment by blackpaulillyria** [comment]
Steam is on sfall 4.1.2.
I updated it to 4.2.9 and it's still the same.

![image](https://user-images.githubusercontent.com/58548291/113103326-0dd5d800-91f7-11eb-8360-376e759dd3af.png)

**Comment by NovaRain** [comment]
If you go into the temple or load an existing save, the message should print the area number correctly.

**Comment by Lexx2k** [comment]
On start the game never knows your current location. It needs at least one map change.

**Comment by blackpaulillyria** [comment]
Ooooh, so that's what's going on here. OK, thanks for letting me know! Closing

**Comment by Lexx2k** [comment]
Just a headsup, because I just stumbled over our old notes: Entering through dialog teleport or caravan does not update cur_town either.

**Comment by FakelsHub** [comment]
The engine code shows that this should be updated whenever the map/game is loaded.
I will check if there is a bug, I do not remember that this function would not work.
