### ISSUE TITLE
Make translations.ini great again

### ISSUE THREAD

**Issue by Lexx2k** [phobos2077/sfall#368]
I'll make it short ... Why can't we put all languages into one translations.ini file? We already know which language version the player is using from language= string in the fallout2.cfg file. Based on that, the correct translated strings could be picked.

Wipe proposed a structure like this:
```
[sfall:english]
blabla=pleple

[sfall:french]
blabla=le pleple

[sfall:polish]
blabla=zażółć gęślą jaźń
```

Would make things easier to manage + players wouldn't need to manually swap out the language file they want to use.

**Comment by wipe2238** [comment]
In case someone wants to keep backward compatibility (hi NovaRain!) `[sfall]` could be left intact for english language.

**Comment by FakelsHub** [comment]
> language= string in the fallout2.cfg 

This can always be set to English, and does not reflect the language being used, so this is a bad way to known the language being used.
Sfall should have purchased its own installer long ago, which would install localized files depending on the user's choice during installation.

**Comment by Lexx2k** [comment]
Installers are shit. Besides, I don't want to support a custom installer for ettu. At the same time I loath the file shuffeling with the .ini translations.

**Comment by FakelsHub** [comment]
@Lexx2k
your idea is untenable because the .ini file must be in the encoding in which it will be supported in the game.
for example, Russian files must be encoded in win1251 or OEM866 (for the original exe).
chs.ini/cht.ini files also have other encodings.
therefore, this idea of merging everything into a single file is only good for some languages where the encoding corresponds to ASNI.

@NovaRain 
You can use it if you think it's a viable idea.
[Translation.cpp.txt](https://github.com/phobos2077/sfall/files/6338448/Translation.cpp.txt)
[Translation.h.txt](https://github.com/phobos2077/sfall/files/6338449/Translation.h.txt)

**Comment by Lexx2k** [comment]
Then delete the .ini file and instead move everything to a new .msg file which can be easily overwritten by mods.

**Comment by FakelsHub** [comment]
This makes the code in sfall inconvenient in some places, more care will be needed.
Example:
```
LoadGameHook::OnAfterGameInit() += [] {
	saveFailMsg = Translate::Get("sfall", "SaveInCombat", "Cannot save at this time.");
	saveSfallDataFailMsg = Translate::Get("sfall", "SaveSfallDataFail",
		"ERROR saving extended savegame information! Check if other programs interfere with savegame files/folders and try again!");
};
```

**Comment by wipe2238** [comment]
Heh, right.
How about reading translation strings on sfall init? All mess with file / language selection will be done only once, and later `Translate::Get()` will simply pass already-known results back (so last argument won't be needed anymore).

Something like
```cpp
std::map<std::string, std::map<std:string, std::string>> Translation;

void Translate::Init()
{
    IniReader::SetConfigFile(Translate::FindIni());

    std::map<std::string, std::string> sfall& = Translation["sfall"];
    sfall.insert( std::make_pair( "SaveInCombat", IniReader::GetConfigString("sfall", "SaveInCombat", "Cannot save at this time.")));
}

std::string Translate::FindIni()
{
    // this is where all detection mess could live,
    // without messing up outside code
}

std::string Translate::Get(std::string& section, std::string& key) const
{
    if(Translations.find(section) != Translations.end())
        return Translation[section][key];

    return "error";
}

///

if (saveInCombatFix == 2 || PartyControl::IsNpcControlled() || !(inLoop & PCOMBAT))
{
    fo::DisplayPrint(Translate::Get("sfall", "SaveInCombat"));
    return 0;
}
```

Could be simplified even more by always assuming "sfall" section... except there's still `[AppearanceMod]` ini :/
```cpp
Translate::Get("SaveInCombat");
```

**Comment by FakelsHub** [comment]
your method is very beautiful, but its disadvantage is that it requires constant search for the key during the game.
current, in most cases, all the strings are loaded into the buffers before the game starts.

I'm still choosing the most appropriate implementation method.

**Comment by Lexx2k** [comment]
I tested the new translation features:

1. \premade\german\ works perfect.

2. I'm an idiot, because I completely forgot about font files in \data\ ... Different languages might need different font files, which now still requires an extra sub-mod.

3. It seems that \language\ folders are causing issues with sub mods.
I have moved all \fo1_german\ files to the correct folders and they are working as they should. However, if I now load another mod after like `fo1_interface` here:
```
PatchFile0=mods\fo1_base
PatchFile1=mods\fo1_interface
```
Then `\fo1_interface\art\german\` will not be read. The game will take the files from `\fo1_interface\art\` and apparently nothing else. Kinda weird, because I could swear this worked in normal patch .dat files?

**Comment by FakelsHub** [comment]
this should be placed in `...\art\german\intrface\file.frm`

**Comment by Lexx2k** [comment]
The files are in `\mods\fo1_interface\art\german\intrface\..` and that seems to be ignored. The game is reading the files from `\mods\fo1_itnerface\art\intrface\..`

I also noticed that if I load `PatchFile4=mods\InterfaceUpscaled` additionally after everything else, the splash screen files will not override the german files, even though they should, so there seems to be a load order issue when it comes to these language files?

Now with that stuff popping up as well... I'm beginning to wonder if the "language pack as extra mod"-method isn't the better way after all ...

**Comment by FakelsHub** [comment]
PatchFile0=mods\INTERFACE0
PatchFile1=mods\INTERFACE1

INTERFACE1 overrides the `\art\lang\intface\*` files from INTERFACE0

**Comment by Lexx2k** [comment]
> (HRP files dont work)

Ok, this is the problem. I made two test mods to check out which IFACE files will load, and as soon as the resolution requires the HRP files, it stops working. 

Anything we can do about that or is this "shit happens"?

**Comment by burner1024** [comment]
> Language folders don't just work in \text\ but also in \art\.

Crap, why isn't it documented anywhere? I spent so much time on translations packaging and installing... I would love to just drop everything into game folder.

Although technically, it might be needed to override any file for a translation. Not just art or font. Sound, for example. UPU changes a sound for Marcus in German.

I think putting sfall translations into msg is a good idea anyway.

**Comment by burner1024** [comment]
So do all assets work in language directories now, or? If not, then what about `sound` in particular?
