### ISSUE TITLE
Make stairs highlightable by pressing shift

### ISSUE THREAD

**Issue by KeyboardGecko** [phobos2077/sfall#369]
Would be cool to make it optional, like automatic door opening.
Some mods (like Olympus 2207) are not very good with their stairs placement.

Also, would be cool to combine it with a LoS highlighting system.

**Comment by NovaRain** [comment]
You can use the [expanded highlighting in fo2tweaks](https://github.com/BGforgeNet/FO2tweaks#expanded-highlighting) and add PIDs of the stairs in `transitions=` list in fo2tweaks.ini.
