### ISSUE TITLE
AIBestWeaponFix

### ISSUE THREAD

**Issue by Lexx2k** [phobos2077/sfall#370]
**Background:**
The AI weapon preference check doesn't work on the Red Ryder LE rifle at all. The calculation is `((max dmg - min dmg) / 2) * weapon perk modifier`. As the LE rifle has 25 min damage and 25 max damage, it will always have a rating of 0.

After researching more into it, I figured ... wait a moment, this whole formula is complete bullshit! Not just for the LE rifle, but in general. A weapon with min dmg 5 and max dmg 25 has a higher pick chance than a weapon with 20 min dmg and 25 max dmg, even though the later is the much better choice.

Currently we have 2 options for that in the ddraw.ini via AIBestWeaponFix. However, none of these will fix the underlying problem ... checking weapon preference based on `(max dmg - min dmg) / 2` is stupid.

**Conclusion:**
After talking with NovaRain about this, it seems a better solution would be to take the average weapon damage for the calculation, and not the difference between min and max damage.

So maybe `AIBestWeaponFix = 3` should do exactly that, check for average damage? 
-> `((max dmg + min dmg) / 2) * weapon perk modifier`

At first I was thinking of writing a script based on the new HOOK_BESTWEAPON for that case, but we already have the AIBestWeaponFix-option, so ... might as well just keep using that (or completely remove AIBestWeaponFix because it seems neither option is really a fix)?

/Edit:
When using average damage, the weapon perk modifier might cause pretty crazy results. I wouldn't mind to either drastically reduce it (x2?) or just completely remove it, as I can't really see a scenario right now where this modifier is useful. 
NPCs usually don't have more than 2 weapons anyways, and I can't see how this modifier is useful for party members either.

Anyone got any thoughts on this?

**Comment by Lexx2k** [comment]
NovaRain prepared a sheet file with the weapon stats to compare the old formula with a damage average. https://docs.google.com/spreadsheets/d/1rZ9UiZDehPNlpY14V2Y-f79Mb7H2YiKJsqBUkVRc71o/edit?usp=sharing

On first look it seems pretty reasonable, even with the x2 weapon perk modifier applie.
However, it is clear that damage average has a clear bias against burst weapons ... Not sure what to do with that.

**Comment by FakelsHub** [comment]
If change the formula, then change it without any off/on options.

_Attach an Excel file here. (google docs is crap and saves the file in a corrupted form)._

**Comment by Lexx2k** [comment]
Need to ask NovaRain about that then, because I only use google docs and nothing else. :>

**Comment by NovaRain** [comment]
Here's the list: [wpn_priority_list.zip](https://github.com/phobos2077/sfall/files/6386081/wpn_priority_list.zip)

**Comment by FakelsHub** [comment]
Maybe it was originally calculated for the average calculation of but, but due to an error, it turned out to be a minus, not a plus in the calculation.
`(max dmg - min dmg) / 2` is stupid.
`(max dmg + min dmg) / 2`

**Comment by NovaRain** [comment]
If we are going to remove the option and change it to a pure fix, using average damage instead and removing/skipping the weapon perk multiplier seems a more reasonable (and simpler) way. Something like this?
```cpp
SafeWriteBatch<BYTE>(0x01, {0x4294E2, 0x429675}); // sub > add
SafeWriteBatch<BYTE>(CodeType::JumpShort, {0x429553, 0x4296DC}); // jz > jmp (skip perk multiplier)
//SafeWriteBatch<BYTE>(0x15, {0x42955E, 0x4296E7}); // lea eax, [edx]; (2x multiplier)
```

**Comment by FakelsHub** [comment]
I would apply this formula: `((max dmg + min dmg) / 4) * (2 perk mod)` the values are very similar to x3 mult.
And would remove the other fixes from the option AIBestWeaponFix.

**Comment by NovaRain** [comment]
> 
> 
> I would apply this formula: `((max dmg + min dmg) / 4) * (2 perk mod)` the values are very similar to x3 mult.
> And would remove the other fixes from the option AIBestWeaponFix.

So the base is half of the average damage, and 2x multiplier for having weapon perk?

> Some items suffer because of the new formula for example

The examples are about a tie of score if using avg dmg, but if it's a tie then the function should compare the item price instead, no? And I don't really consider pulse grenade here, as it's limited in both games by default (in FO1 traders don't restock, in FO2 no one sells it), and it only has effect against robots, which is also scarce in the games.

**Comment by Lexx2k** [comment]
I think this would only be noticeable on party members, as critters in Fo1 / 2 rarely have more than two weapons (ranged and melee).

Going by item price in a tie doesn't sound so bad to me. It's ... abstract, but it shows which item has more value. Could be useful if we have to compare e.g. 10mm Pistol vs. 10mm SMG, I guess.

**Comment by FakelsHub** [comment]
> The examples are about a tie of score if using avg dmg, but if it's a tie then the function should compare the item price instead, no? 

yes, the price is compared, but only if the [internal counter](https://github.com/FakelsHub/sFall-Extended/blob/d1a48b0033e754463b43e8bcd34115cdd09dac60/sfall/Modules/SubModules/AI.Inventory.cpp#L117) is the equal for the two items.

> I think the base score would be even lower for some weapons.

Change **Avg. Dmg** and compare it with **Vanilla Score** you will be surprised.

**Comment by wipe2238** [comment]
> critters in Fo1 / 2 rarely (never?) have more than two weapons

Can't they pickup weapons during fight nowadays? Also, don't forget about mods which might be more generous than vanilla :p

**Comment by NovaRain** [comment]
> > I think the base score would be even lower for some weapons.
> 
> Change **Avg. Dmg** and compare it with **Vanilla Score** you will be surprised.

The (not so) surprising thing is I made a mistake in my formula edits so the numbers were wrong (only in my local excel, not the uploaded one), now I see what you mean. Guess I'm fine with your new idea for calc fix.

**Comment by FakelsHub** [comment]
> I made a mistake in my formula

where the error? (I downloaded from google and applied manual editing).

**Comment by NovaRain** [comment]
> 
> 
> > I made a mistake in my formula
> 
> where the error? (I downloaded from google and applied manual editing).

Just a silly copy&paste error when I was trying to add another column "half of avg dmg" locally (the uploaded ones are OK), the formula became the average value of D and E columns, of course the values were all wrong. And I didn't pay attention to that when I was posting the reply earlier.
