### ISSUE TITLE
Missing button sfx on worldmap interface

### ISSUE THREAD

**Issue by Lexx2k** [phobos2077/sfall#373]
It is time for a new issue ticket. :D

Some weeks ago I noticed that *none of the buttons on the worldmap interface* are making click-noises (right-side buttons, and the green triangles on the town/world screen). Ever since I have noticed that, it is driving me mad. In Fo1, all buttons on the interface would play sfx when used.

I'm begging for a fix.

**Comment by Lexx2k** [comment]
I just realized that it's not just the button sfx that is missing - in Fo1, there is a click sound even if you set a new travel destination directly on the map.

**Comment by FakelsHub** [comment]
> new travel destination directly on the map.

I don't think these sounds are necessary.

ps: don't wait this, before implementing the HRP code in sfall.
pss: maybe someone else will do this for you before.

**Comment by Lexx2k** [comment]
Did some toying around [with a global script](https://fodev.net/pastebin/?p=93). :D 
[gl_fo1_wm_clicks.zip](https://github.com/phobos2077/sfall/files/6515438/gl_fo1_wm_clicks.zip)

The result is pretty bad and hacky, but it's a good way to show how much the sfx are adding to the interface. :>

The script only works with `ExpandWorldMap=1` because I couldn't be arsed to make the coordinates work on the vanilla wm interface. Also there are issues with the Town/World interface switch (we can't detect when it's open, so we try to track it via button press, but it's still possible to open the T/Winterface via green triangle in the map area).
I probably would have been able to get sound to the green triangles on the T/W interface as well, but there is no point in trying, as the script solution will never feel good.

**Comment by Lexx2k** [comment]
You know what? I'm getting really used to my shitty gl script. The only thing bugging me now is that we can't reliably detect if the Town/World screen is up. Any chance for a new get_game_mode for that one? :>

**Comment by FakelsHub** [comment]
Well, in general, the implementation of sound clicks through the script is complete madness. :)

ps: use `AndElse` and `OrElse` in global scripts.

**Comment by Lexx2k** [comment]
It's absolutely stupid :D but you gotta work with what you got. That being said, even though a part of me wants to, I'm not going to put this into any official release.

**Comment by wipe2238** [comment]
> ps: use `AndAlso` and `OrElse` instead of `and / or` in global scripts.

All EtTu scripts are always compiled with `-s`

**Comment by Lexx2k** [comment]
I see buttons make a sound now. Very nice. Though for Fo1 there are still some sounds missing - clicking anywhere on the worldmap produces a sound, also clicking the triangles produces a sound. :>

That said, now I was able to delete almost everything in my wm click script. :>

**Comment by ghost2238** [comment]
I have implemented this as an ASM patch: https://github.com/ghost2238/sfall-asm/blob/master/patches/fo1in2/sound_on_wm.asm
It's currently in Fo1in2. Want me to send a PR to the develop branch with an implementation for sfall?

We could use `WorldMapFallout1Sounds=1` in the config under `[Interface]` to enable it?

**Comment by Lexx2k** [comment]
I would merge it into Fallout1Behavior to avoid config clutter.

However, at the same time the clicking sfx could be seen as a bugfix/improvement, so might warrant a short of "WM click sounds"-setting.

**Comment by NovaRain** [comment]
Given that the button sfx was added as "bugfix" I'd probably treat clicking sfx for other WM elements in the same way. Also it might not need `pushad`/`popad` on all registers.

**Comment by ghost2238** [comment]
Guess it being a bugfix or not depends on if the original devs intended to remove the sounds or not I guess. It feels like a pretty big oversight if they didn't notice that these sounds are gone, but who knows if it happened in a crunch period.

>Also it might not need `pushad`/`popad` on all registers.

Yep, lazy code. Will make sure the sfall version is a bit cleaner and uses defined symbols.
