### ISSUE TITLE
Issues with floating text

### ISSUE THREAD

**Issue by Lexx2k** [phobos2077/sfall#377]
With Sfall version 4.2.7 we got this:
> Added a fix to remove floating text messages on the map when moving to another map elevation

I have now found out that it is causing issues in ettu. Some NPCs won't have visible floating text anymore (example: Killian when attacking Gizmo, or the junktown guards when attacking the Skulz in the Scum Pitt). There might be more issues like that, but that's the ones we have identified so far.

At first I tried to rewrite the scripts, but it just causes lots of other issues ... Now I think would be easier to do something about the fix itself.

Or as alternative, a new float-command that runs in any case and is ignored by the above mentioned fix. I'm not a fan of that solution, but I also don't like brahmin floats on map change ...

**Comment by NovaRain** [comment]
Here's an example to emulate the issue in RP:
1. Add a test script ZZZTEST.ssl to RP:
```pas
#include ".\headers\define.h"
#include ".\headers\command.h"

procedure start;
procedure map_enter_p_proc;

procedure start begin
end

procedure map_enter_p_proc begin
   display_msg("map_enter proc of ZZZ.");
   float_msg(self_obj, "HELLO WORLD!!", FLOAT_MSG_NORMAL);
end
```
2. Add a `spawn_stuff` procecure to Arroyo temple cave map script (ARCAVE.ssl):
```pas
procedure map_enter_p_proc begin
   if (map_first_run) then begin
       display_msg(mstr(100));
       call spawn_stuff;
   end
//...

procedure spawn_stuff begin
   variable i := create_object_sid(0x02000005, 28105, 0, 1559); // script ID of ZZZTEST.int
end
```
3. Start a new game and go into the temple, before 4.2.7 (or comment out the fix in MiscPatches.cpp) the spawned metal barrel will have a floating message. With the fix it won't show any float, only the message printed in the message box.

**Comment by Lexx2k** [comment]
Latest Sfall build has fixed it for me. Thanks.
