### ISSUE TITLE
CreateObjectSidFix issue

### ISSUE THREAD

**Issue by Lexx2k** [phobos2077/sfall#378]
With latest dev-build Sfall there seem to be quite a few broken scripts in ettu. It took me a while to figure out this is connected to the  `CreateObjectSidFix` fix.

Example: [Spawned critters won't run their destroy_p_proc procedure anymore](https://github.com/rotators/Fo1in2/blob/master/Fallout2/Fallout1in2/Mapper/source/scripts/03junktown/GENSKULZ.ssl#L106).

It seems to work if I set `CreateObjectSidFix=1` - is this on purpose? I have no idea if setting it to 1 would break any other scripts. Testing this will be a real pain in the ass.

Right now it seems like this fix is breaking more than it fixes?

**Comment by NovaRain** [comment]
> I have no idea if setting it to 1 would break any other scripts.

Setting it to 1 enables the "original" variant of the fix, which breaks Frank Horrigan script in vanilla FO2. That's why there's a new default (=0) variant of the fix. Maybe just set the option to 1 for Et Tu.

**Comment by Lexx2k** [comment]
I found one issue already with a spawned rat in the Necropolis sewers.

With =0 the rat works (moves around randomly), with =1 the rat won't move around until I reload the game or re-enter the map.

**Comment by FakelsHub** [comment]
There is probably an incorrect description for CreateObjectSidFix, the option just does not need to be enabled. This is intended for TC only.

Give your save to check destroy_p_proc.

**Comment by Lexx2k** [comment]
Here is the savegame: 
[SLOT03.zip](https://github.com/phobos2077/sfall/files/6502739/SLOT03.zip)

Talk to Lars. In dialog pick 3 - 2 and you will be teleported to the bar. Replace junkcas.int with this script for debug message:
[JUNKCAS.zip](https://github.com/phobos2077/sfall/files/6502744/JUNKCAS.zip)

With the script you will see the current MVAR state on map update. Killing the Skulz gangers should reduce it.

**Comment by FakelsHub** [comment]
I haven't checked your save yet.
But damn it, this create_object_sid works somehow differently depending on where it was called.

**Comment by Lexx2k** [comment]
Latest Sfall build has fixed it for me. Thanks.
