### ISSUE TITLE
Allow ending combat

### ISSUE THREAD

**Issue by Lexx2k** [phobos2077/sfall#379]
Not really(?) a bug, I guess, but something I noticed:

In Fo1, when fighting Decker and his goons, [the survivors will surrender](https://github.com/rotators/Fo1in2/blob/e3a69b3e0fdeecc3d82631c0f1696185b1f9dd54/Fallout2/Fallout1in2/Mapper/source/scripts/06hub/DECKGRD.ssl#L81) if Decker and Kane are dead. Once this happens, the combat will keep going, but the player can stop the combat whenever he wants.

In ettu, the same fight keeps going and can't be ended. The player needs to kill everyone. Now in order to get around this, I've added `terminate_combat;` which is an ok-ish solution. However, I was wondering if we can somehow allow the player to manually end the combat instead, the way it worked in the original?

NovaRain suggested to try `set_object_data(x, OBJ_DATA_WHO_HIT_ME, 0);` which I've put into the combat_p_proc, but sadly it has no influence on the scene. I've also tried to set a different team for them, but again, no change. I can't end the combat - the game thinks there are still hostile critters around.

Here is savegame to check it out:
[SLOT07.zip](https://github.com/phobos2077/sfall/files/6506613/SLOT07.zip)
Talk to the sheriff, report Decker, then shoot Decker and Kane. Once done, the other thugs will surrender, but the player can't end the combat on his own.

/Edit:
Maybe some sort of `allow_terminate_combat;` would be useful for scenes like that?

**Comment by FakelsHub** [comment]
critter_stop_attacking

**Comment by NovaRain** [comment]
If the player can kill both Decker and Kane in his first turn, the goons will surrender, and the combat will end automatically. After player's first turn the combat cannot be ended by the player manually, as friendlies will still attack and kill all goons.
If I set OBJ_DATA_WHO_HIT_ME of all critters (goons, police, and party members) to 0 with CombatTurn hook, the combat will also end automatically due to the fix (no hostiles in combat). The same goes pretty much the same if I remove goons' team and replace it with player's team.

**Comment by Lexx2k** [comment]
Yeh, I just tested `critter_stop_attacking(self_obj);` and it pretty much results in the same as if I would run `terminate_combat;`.

**Comment by FakelsHub** [comment]
critter_stop_attacking or terminate_combat - are quite suitable for this situation.

**Comment by FakelsHub** [comment]
You can make the crutch catch pressing "End combat" and end the combat. (if you want to suffer from this nonsense, of course).

**Comment by Lexx2k** [comment]
> critter_stop_attacking or terminate_combat - are quite suitable for this situation.

Not if you want the player to be able to kill the surrendering thugs. Both commands will terminate the combat and then you will get teleported out of the map. This is the issue.

That being said, I don't feel very attached to this scene, so I might just terminate the combat and the surrendering thugs will survive in any case.

**Comment by FakelsHub** [comment]
> Both commands will terminate the combat and then you will get teleported out of the map. This is the issue.

Oh, that's it. Well, in any case, without the consciousness of a special hook, you can not do here.

**Comment by FakelsHub** [comment]
By the way, there is one simple way, hooks HOOK_FINDTARGET or HOOK_WITHINPERCEPTION for these NPCs to return 0 after they give up, then the combat can be terminated.

**Comment by burner1024** [comment]
> pressing "End combat" 

Is there a hook for interface buttons?

**Comment by FakelsHub** [comment]
Нет. Только отслеживать нажатие мышки по x/y/w/h координатам.

**Comment by burner1024** [comment]
> Только отслеживать нажатие мышки по x/y/w/h координатам.

Может лучше в этом направлении подумать тогда? x/y же от разрешения зависит, так просто не сделать? Может даже не напрямую в sfall, а в библиотеку добавить функций/дефайнов, которые на основе разрешения будут ловить нажатые кнопки?

**Comment by Lexx2k** [comment]
Check out [my horrid script](https://github.com/phobos2077/sfall/issues/373#issuecomment-845002707) for catching button positions. I'm pretty much just calculating it's position from the screen center, which is possible thanks to Fallout interface being so inflexible. 
However, there might still be issues with rounding, etc. but I imagine this would always happen anyways, even with some sort of native function.

**Comment by burner1024** [comment]
Horrid as it may be, if it works, I think adding it to sfall lib si worthy :).

**Comment by FakelsHub** [comment]
> Может лучше в этом направлении подумать тогда? x/y же от разрешения зависит, так просто не сделать?

там все уже подумано. есть размеры окна, есть разрешение игры.

**Comment by FakelsHub** [comment]
> By the way, HOOK_WITHINPERCEPTION

It is better to use HOOK_FINDTARGET this is related to the battle.

**Comment by Lexx2k** [comment]
NovaRain tested with HOOK_FINDTARGET, but it doesn't seem to work. I can't get it to work eithe.

```
procedure start begin
   if game_loaded then begin
      register_hook_proc(HOOK_FINDTARGET, FindTargetHandler);
   end
end

procedure FindTargetHandler begin
   variable
      attacker := get_sfall_arg,
      target1  := get_sfall_arg,
      target2  := get_sfall_arg,
      target3  := get_sfall_arg,
      target4  := get_sfall_arg;

   if (cur_map_index == MAP_HUBDWNTN and dude_elevation == 1) then begin
      if (attacker != dude_obj and global_var(GVAR_UNDERGROUND_STATUS) == 1) then begin
         display_msg("FindTarget: Decker and Kane are dead!!");
         set_sfall_return(0);
         set_sfall_return(0);
         set_sfall_return(0);
         set_sfall_return(0);
      end
   end
end
```

**Comment by FakelsHub** [comment]
>Set to 1, to force the NPC find more suitable targets every his combat turn
>Set to 2, the same, but without an internal algorithm, use this if you want to write your own algorithm in the hs_findtarget script;This option affects the run of the hs_findtarget hook
>**TryToFindTargets=2**

As far as I remember, this option is needed. Then use HOOK_WITHINPERCEPTION.

**Comment by Lexx2k** [comment]
In any case, we got it working now. If someone complaints, I'll just go back to terminating combat and done. :>
