### ISSUE TITLE
Get item in player's inactive hand slot

### ISSUE THREAD

**Issue by phobos2077** [phobos2077/sfall#38]
When using `critter_inven_obj(ObjectPtr who, int where)` on `dude_obj`, this vanilla function always returns 0 for non-active hand. 
Maybe it was an oversight, but we can't simple "fix it" as this is vanilla behavior and function is used extensively in F2 and TC's.

Need to find some easy workaround or add new opcode with desired behavior.

**Comment by VonZorch** [comment]
I have a partial solution for the what's in the inactive hand problem, this may provide you with a start for a complete solution

variable Count:=inven_count(dude_obj);
display_msg("Slot 1 "+obj_pid(inven_ptr(dude_obj,Count-1))); //Armor
display_msg("Slot 2 "+obj_pid(inven_ptr(dude_obj,Count-2))); //Right Hand
display_msg("Slot 3 "+obj_pid(inven_ptr(dude_obj,Count-3))); //Left Hand

If a specific slot is not being used, the open slot returns an item PID from general inventory that I have been unable to predict, not that I tried to.
For instance, if the left hand slot has nothing in it then some item from inventory not in armor or right hand will be returned.

**Comment by VonZorch** [comment]
From the Vault-Tec site save.dat file article, in the players inventory item at , "offset 0x28 length 0x04, A bitfield: 0x01000000 indicates the item is held in the right hand, 0x02000000 - in the left hand, and 0x04000000 - worn (as armor). Use of other bits is unknown. "
I hope this is useful.

**Comment by phobos2077** [comment]
It's actually quite trivial to do. This was delayed because we couldn't find perfect solution that will not make code harder to understand (read: shitcode). 

Right now I'm leaning towards adding critter_inven_obj2 function... Bad, but it's:
a) Fast to do.
b) Won't break anything.
c) Fulfills the requirement.

**Comment by phobos2077** [comment]
Added command: sfall_func0("critter_inven_obj2", obj, type)
