### ISSUE TITLE
Loading an in-combat save freezes

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#380]
[This](https://github.com/BGforgeNet/Fallout2_Restoration_Project/issues/100) issue:
> Saving a game in Den Residential (During a fight with Laura and the Metzgers guards that are having a party in Den Residential)
And then attempting to load it, the game freezes.
> In the save attached, tell Laura that you are ready, you will be teleported to Den Residential, attempt to save, and then load, the game will crash.

```
LOADSAVE: ** Error reading load function #11 data! **
LOADSAVE: Load function #11 data size read: 28 bytes.
```

I exhausted my arsenal and am no closer to solving it. Editing the save with F12SE and using "clear combat data" removes the crash, but also removes the dealer. Don't know what else to try.

There were some non-critical error messages about visibillity, I cleaned them up, no difference. (Latest build is [here](https://github.com/BGforgeNet/Fallout2_Restoration_Project/actions/runs/866978229))
[SLOT04.zip](https://github.com/phobos2077/sfall/files/6526902/SLOT04.zip)

I know that saving in combat is never recommended, of course. By itself it's of low priority, but it could be a symptom of some deeper issue I think.

**Comment by FakelsHub** [comment]
Там нужно удалять все из их скритов, чтобы на эту группу бандюков в комнате не действовали не одни скрипты.
Это даст понтять, что это точно не скриптовая проблема переноса этой группы на другой уровень карты, и тогда уже разбираться с тем что происходит там с сохраненнием карты.

**Comment by burner1024** [comment]
из чьих?

**Comment by FakelsHub** [comment]
Пустой скрипт уже после сохранения?
Может там "внешние" скрипты их переносят.
В общем я не разбирался в их скриптах.

**Comment by burner1024** [comment]
Дилер это тот который пропадает, в верхнем правом углу. До сохранения. Из-за кого глючит мне неясно.
Даже если скрипты где-то косячные, всю игру вешать им не должно быть позволено.

**Comment by FakelsHub** [comment]
Да тут проблема не в зависании. А в невозможности загрузить сохранение.

**Comment by burner1024** [comment]
> Вобщем уже понятно, что проблема не в сохранении карты и не в скриптах.

Хорошо. Как в общем я и предполагал =).

**Comment by FakelsHub** [comment]
> Хорошо. Как в общем я и предполагал =).

А вот и нет, в данном случае все таки эта пролема скриптовая. Я в движке отключил обработку всех скритов и игра номально загрузиась.
Ищи проблему в переносе NPC на другой уровень карты.

**Comment by burner1024** [comment]
Я не знаю как найти. Добавил `not is_loading_game` в перенос, не помогло.
Можно хотя бы в лог писать строчку когда скрипт пытается на этапе загрузки выполнить невозможное действие (и какое именно)? Чтобы дебажить легче было.

**Comment by FakelsHub** [comment]
Добавь в скрипты отладочные сообщения и смотри, что когда выполняется.
Скрипт карты смотрел что там?

**Comment by burner1024** [comment]
Да добавлял уже.
Вроде всех пропустил, все равно виснет.

**Comment by FakelsHub** [comment]
Ну значит как буду заниматься допиливанием **Sfall Script Editor** гляну на скрипты.

**Comment by Lexx2k** [comment]
Looks like someone else is experiencing this (or a similar?) issue: https://www.reddit.com/r/classicfallout/comments/nrbupz/fallout_2_combat_freezes_during_after_next_turn/

**Comment by burner1024** [comment]
Don't think so, here combat itself works normally, it's loading the save that breaks.

**Comment by dlpnd** [comment]
Yeah for me the steps were:

1. I started the quest for Laura.
2. Do the first fight.
3. Approach her to finish the quest.
4. She tells me its not over yet (RPU content).
5. I say sure lets go.
6. We teleport to the Den Residential.
7. I check the time, its super late, I save the game before taking any turns.
8. The following evening I continue my quest, I attempt to load the save, and it crashes the game

**Comment by FakelsHub** [comment]
Удалось вычислить скриптовую функцию приводящую к ошибке, как не странно это `move_to` в `map_enter_p_proc`

**Comment by burner1024** [comment]
> elevation(dude_obj)

Полный список функций есть, которые неверно работают во время загрузки?
В https://github.com/BGforgeNet/Fallout2_Restoration_Project/issues/100#issuecomment-830699997 ты предложил почистить ошибки, ну я [почистил](https://github.com/BGforgeNet/Fallout2_Restoration_Project/commit/d313d0849439ee1c64a6d8dfdd77d0ad1e41605a#diff-7948893faca43c7633c59eaeea72ea647f2095660687568333e1eb142a249f65L453) там и в других местах заодно, так сломались [караваны](https://github.com/BGforgeNet/Fallout2_Restoration_Project/issues/111#issuecomment-891388352) (не только из-за этого, там другие баги тоже есть, но в том числе).

**Comment by FakelsHub** [comment]
> Полный список функций есть, которые неверно работают во время загрузки?

Нет конечно. Узнается только в ходе тестов.

Неправильно почистил так, что поломались корованы?))

**Comment by FakelsHub** [comment]
> elevation(dude_obj)

Всегда во время загрузки возвращает 0, потому что некоторые данные игрока еще не были загружены при выполнении map_enter.
Я даже незнаю как это без последствий все исправлять.

**Comment by burner1024** [comment]
> Неправильно почистил так, что поломались корованы?))

Почистил правильно. Только фунция работает во время загрузки.

**Comment by FakelsHub** [comment]
Что значит нечего чинить у бисов в map_enter в большенстве случаев используется  is_loading_game, в RP ей пренебрегли.
Вон минимальный список скриптов я показал где нужно вставлять функцию.

**Comment by burner1024** [comment]
Так вот я починил, караваны сломались.

**Comment by egornovivan** [comment]
> Так вот я починил, караваны сломались.

Караваны скорей всего от этого сломались `https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/commit/1687f4e97c5695514c0f98f8c19e3a36a9661d57`

**Comment by burner1024** [comment]
Это тоже, но это другое. Отдельно караванщики пропали, и отдельно клерк появился.

**Comment by FakelsHub** [comment]
> Так вот я починил, караваны сломались.

Явно ты что-то  не то чинил,  в скпритах надо было чинить код, а не макрос/ы для всех.

**Comment by burner1024** [comment]
Так а с чего не для всех? Та же самая функция у одних работает при загрузке, а у других нет?

**Comment by FakelsHub** [comment]
> Я правильно понимаю? Во всех скриптах, все тело map_enter_p_proc обернуть в is_loading_game?

Да. Как у бис, у них большинство обернуто, по соображению "при загрузке игры код не должен выполняться", по сути он и не должен выполняться при загрузке, это нужно только в редких случая.

**Comment by burner1024** [comment]
например в каких случаях?

**Comment by FakelsHub** [comment]
> Так а с чего не для всех? Та же самая функция у одних работает при загрузке, а у других нет?

хз, ты уверен что ты правильно исправил макрос. и зачем-то условие туда пристоил.

**Comment by FakelsHub** [comment]
> например в каких случаях?

по логике скрипта смотреть надо, например запустить таймер при загрузке.

**Comment by burner1024** [comment]
В смысле, ну изменение же ты видишь, ровно одно условие, одна строка, если неправильно то говори.
Лог `Error: attempt to set_obj_visibility in load/save-game`,  из этого я сделал вывод, что set_obj_visibility надо оборачивать  в is_loading_map. Я неправ?

**Comment by FakelsHub** [comment]
прав. но почему тогда сломались караваны если ты просто подправил макрос.

**Comment by burner1024** [comment]
Что-то здесь не то: в обоих скриптах весь map_enter_p_proc обернут целиком в is_loading_game.
В первом скрипте set_obj_visibility без доп. проверок. Во втором он тоже (дополнительно) обернут в is_loading_game.
Т.е. первая проверка проходит, а вторая (внутри первой) - нет. Как такое может быть?
На [этом](https://github.com/BGforgeNet/Fallout2_Restoration_Project/issues/111#issuecomment-892715724) сейве можно проверить.

**Comment by FakelsHub** [comment]
Посмотрел в движке  set_obj_visibility их можно отдельно не помещать в is_loading_game в движке уже это сделано.
Верни макросы как было. :)

**Comment by FakelsHub** [comment]
> Т.е. первая проверка проходит, а вторая (внутри первой) - нет. Как такое может быть?

хз, нет возможности проверить.

**Comment by burner1024** [comment]
> Посмотрел в движке set_obj_visibility их можно отдельно не помещать в is_loading_game в движке уже это сделано.

Да это ясно, ошибку движок и печатает. Макросы вернул уже, но все равно непонятно поведение описанное выше.

На текущий момент по этому issue конкретно: раз move_to виноват, можно тогда для него такое же поведение сделать (писать ошибку в лог, что move_to вызван в процессе загрузки), чтобы в следующий раз так долго не дебажить?

**Comment by FakelsHub** [comment]
> раз move_to виноват, можно тогда для него такое же поведение сделать (писать ошибку в лог, что move_to вызван в процессе загрузки 

нет лучше оборачивайте.
проблема не в самой move а в том, что бисовцы накосячили с последовательностью функций загрузки игры.
ей можно продолжать пользоваться и при загрузке только с умом.

**Comment by burner1024** [comment]
Так я предлагал в движок это добавить, а не в скриптах.
Как именно с умом? Можно тогда добавить ошибку в лог когда без ума используется?

**Comment by FakelsHub** [comment]
> Как именно с умом?

На пример переместить на другой гекс, без проблем бы работало.
Слишком много функций не работает в загрузке, и делать это именно для move нет смысла.

По поводу функций думаю.

**Comment by burner1024** [comment]
Ну как не имеет... В следующий раз придут с таким же крэшем, либо я сразу сам увижу в логе где косяк и зачиню, либо буду разбираться неделю, потом открою тут еще один баг, все вместе будем еще неделю копаться.
А что другие не работают в загрузке, так их тоже можно помаленьку добавлять, по мере того как баги приходят.

**Comment by FakelsHub** [comment]
Нет смысла.
Что я к примеру должен буду написать в отладке "Вы выполнили move_to в загрузке..." так ей можно пользоваться в загрузке, только нельзя перемещать на другой уровень в бое, а до загрузки боя невозможно узнать игра в бою или нет. (поэтому только обертывание кстати это касается и map_update).
С другими функциями тоже непонятки какие работают какие нет.
Из-за того что не работает `elevation(dude_obj)` (некоторые данные игрока еще не до загружены) и криттера пытается переместить с 1 уровня на 0 и выполняется move_to

Все намного сложнее чем тебе кажется.

**Comment by burner1024** [comment]
Не надо в загрузке. Падает в конкретном месте. Вот том месте и можно добавить лог. Есть крэш, записываем причину крэша.
Ну или если тебе хочется самому с нуля каждый крэш дебажить, тогда пусть будет как есть.

**Comment by FakelsHub** [comment]
> Падает в конкретном месте.

Игра не падает, просто не возможно загрузить игру. И совсем в другом месте (не в move_to, функция выполняет свою задачу без проблем) в следствии неправильного использования функций в map_*.
Если бы я видел смысл в этих сообщениях, я бы добавил.
Я тебе еще тогда сразу сказал что в каком-то скрипте идет перемещение криттеров, но из-за сраных макросов кто-то) не нашел функцию перемещения, я только вчера взялся за эти скрипты.

**Comment by FakelsHub** [comment]
Я могу немного поправить движок чтобы map_enter/update при загрузке выполнялись уже после того как все данные загрузятся.
НО не знаю как это повлияет на скрипты.

**Comment by NovaRain** [comment]
> 
> 
> Я могу немного поправить движок чтобы map_enter/update при загрузке выполнялись уже после того как все данные загрузятся.
> НО не знаю как это повлияет на скрипты. Настораживает почему бис это не сделали, и вместо этого сделали функцию is_loading_game.

I just hope it won't trigger yet another hidden "flaw" in scripts as we did for re-ordering the process execution on map exiting.

**Comment by FakelsHub** [comment]
After some time analyzing the code, I'm still afraid to make any changes, there are too big chance of breaking something in the scripts.
