### ISSUE TITLE
Scanner-function

### ISSUE THREAD

**Issue by Lexx2k** [phobos2077/sfall#381]
Out of curiosity - can we somehow force-enable the scanner item ability without the player actually having the item?

/edit: I mean independent of whatever is set for MotionScannerFlags.

**Comment by FakelsHub** [comment]
no. you can write a voodoo hack for this)

**Comment by Lexx2k** [comment]
I don't have the skills for this, so I can't. :>

**Comment by wipe2238** [comment]
Does Fallout even allows items in inventory to be invisible/impossible to interact with (like PID_WORKBENCH in almost all FOnlines)?
If yes, then let's theorycraft about adding PID_INVISIBLE_SCANNER and...

- read and cache `jmp` address @ `0x41bbe9`
  this is where sfall [installs its own jump](https://github.com/phobos2077/sfall/blob/5e3f1eeaad2614154ee83a8c085f67e5d2519a2b/sfall/Modules/MiscPatches.cpp#L508) if `MotionScannerFlags` > 0
- duplicate [automap_hack()](https://github.com/phobos2077/sfall/blob/5e3f1eeaad2614154ee83a8c085f67e5d2519a2b/sfall/Modules/MiscPatches.cpp#L119-L134) with different PID
  `jmp ScannerHookFail` is changed to previously cached address
- overwrite `jmp` @ `0x41bbe9` - point it to our version of automap_hack()
  always installed, ignoring `MotionScannerFlags`

If theory above is correct, that implements secondary motion scanner working from inventory (no matter what sfall settings are), which has higher priority than regular one. Scripts would be responsible for recharging it, as it will most likely sit in inventory for a looong time, and we can't (?) reliably simulate `MotionScannerFlags=2` affecting our PID only; it has to be done "manually".

**Comment by NovaRain** [comment]
I made a rough script mod for freen motion scan in my lunch break:
```pas
// gl_freescan.ssl

#include ".\headers\define.h"
#include ".\headers\sfall\sfall.h"
#include ".\headers\sfall\define_extra.h"

#define get_inactive_hand(slot)  if (active_hand == 0) then slot := INVEN_TYPE_RIGHT_HAND; \
                                 else slot := INVEN_TYPE_LEFT_HAND

variable item;
variable tmpScanner := false;

procedure start;
procedure GameModeChangeHandler;

procedure start begin
   if game_loaded then begin
      register_hook_proc(HOOK_GAMEMODECHANGE, GameModeChangeHandler);
   end
end

procedure GameModeChangeHandler begin
   variable
      event    := get_sfall_arg,
      prevMode := get_sfall_arg,
      slot, tmpItem, flag;

   if (get_game_mode bwand AUTOMAP) then begin
      get_inactive_hand(slot);
      item := critter_inven_obj2(dude_obj, slot);
      if (obj_pid(item) != PID_MOTION_SENSOR) then begin
         unwield_slot(dude_obj, slot);
         tmpItem := create_object(PID_MOTION_SENSOR, 0, 0);
         add_obj_to_inven(dude_obj, tmpItem);
         if (slot == INVEN_TYPE_LEFT_HAND) then begin
            set_flags(tmpItem, get_flags(tmpItem) bwor FLAG_LEFT_HAND);
         end else begin
            set_flags(tmpItem, get_flags(tmpItem) bwor FLAG_RIGHT_HAND);
         end
         tmpScanner := true;
      end
   end else if (tmpScanner andAlso (prevMode bwand AUTOMAP)) then begin
      get_inactive_hand(slot);
      tmpItem := critter_inven_obj2(dude_obj, slot);
      if (tmpItem andAlso obj_pid(tmpItem) == PID_MOTION_SENSOR) then begin
         rm_obj_from_inven(dude_obj, tmpItem);
         destroy_object(tmpItem);
         if (slot == INVEN_TYPE_LEFT_HAND) then begin
            set_flags(item, get_flags(item) bwor FLAG_LEFT_HAND);
         end else begin
            set_flags(item, get_flags(item) bwor FLAG_RIGHT_HAND);
         end
         tmpScanner := false;
         item := 0;
      end
   end
end
```
It's rather quick 'n' dirty and unoptimized, and there will be some errors about null value in debug log because I didn't do extra checks when the player has nothing in the inactive slot, but it shouldn't affect the game itself, just makes debug log ugly.

**Comment by FakelsHub** [comment]
only add it not to the slot, but directly to the inventory. With an additional flag in **MotionScannerFlags**.

**Comment by Lexx2k** [comment]
Something completely different, but also scanner-related: Can't we enable the scanner function automatically when opening the map interface? Right now you have to manually press the scanner button ... every single time. It's tedious and kinda useless. Makes people use it even less than they already do.
