### ISSUE TITLE
Game Freezes during combat.

### ISSUE THREAD

**Issue by venom9891** [phobos2077/sfall#386]
I think this is an issue with the latest version. I saw another post that said saving during combat freezes the game. Well, in my experience it also just freezes without saving and just by playing normally. I think it usually happens when it's transitioning to the next turn. Couldn't exit the game or anything, had to restart the computer. Downgrading to a previous version seems to have fixed it. I should mention this only seemed to be an issue with random encounters in the wastes.

**Comment by NovaRain** [comment]
It would be nice if you can provide a bit more info like what patch you're using (UP/RP or just vanilla) and maybe a savegame that can check/verfiy the issue faster.

**Comment by FakelsHub** [comment]
waiting savegame...

**Comment by venom9891** [comment]
I told you I downgraded to an earlier version. I've since overwritten that save.

**Comment by venom9891** [comment]
Like I said, I downgraded to a previous version and I've since overwritten my old saves. I could upload my current saves with the downgraded version if that's any help. I'm not sure how to upload saves on here. I tried to attach them to this message but it didn't work.

**Comment by venom9891** [comment]
I do sometimes get really bad lag with the downgraded version as I do with the latest version when walking into a new area. Maybe you could try to help with that if you're unable to identify the freezing issue with my new saves?

**Comment by FakelsHub** [comment]
I need your save in which there is a hang, for example, I do not have any freezes in random battles.
or describe the conditions of the battle in which the freezes occurs.

**Comment by NovaRain** [comment]
There's another report about game freezing in combat on Reddit, this time is in Vault 15:
https://www.reddit.com/r/classicfallout/comments/nuctlx/fo2_vault_15_game_freezes_when_in_combat/

**Comment by venom9891** [comment]
Okay I saved my game when I was experiencing some lag. Here's the link:

https://drive.google.com/drive/folders/10gu07_gcq6NhlAkLiJpD53m5WH_kzYDZ?usp=sharing

Although, the problem usually disappears when exiting and restarting the game so I'm not sure if you'll experience the same thing on your end.

**Comment by NovaRain** [comment]
The new 4.3.0.1 release should address the freezing in combat. Closing the issue for now.

**Comment by yooksi** [comment]
The freezing still happens in the newest version (4.3.0.2).

I am not sure if it is the same type of freeze as reported in this issue, but my issue happens during combat only after a couple of enemy turns and lasts until the enemies play their turns. It is important to note that this issue does not occur when playing in fullscreen, only in windowed fullscreen (mode 6). 

I would be quite happy to play in fullscreen, however FO1 runs really badly in fullscreen for me so that is not an option for me until I can figure out how to resolve issues I have in fullscreen (low framerate and screen tearing).

**Comment by NovaRain** [comment]
> my issue happens during combat only after a couple of enemy turns and lasts until the enemies play their turns.

Try setting `EXTRA_WIN_MSG_CHECKS=1` in f2_res.ini.

**Comment by yooksi** [comment]
> Try setting EXTRA_WIN_MSG_CHECKS=1 in f2_res.ini.

Thank you, that resolved my issue.
