### ISSUE TITLE
floaters problem

### ISSUE THREAD

**Issue by nirran** [phobos2077/sfall#388]
with this code doesnt always float all critters,on small sized maps it seems to work mostly,on large maps none at all or few critters float,think vanilla bug

specificaly the health floats,no idea why but containers floats mostly work

[GL_Containers.zip](https://github.com/phobos2077/sfall/files/6603583/GL_Containers.zip)

**Comment by NovaRain** [comment]
I remember there can be only 20 floats at the same time.

**Comment by nirran** [comment]
and how do i make text windows?lol

**Comment by nirran** [comment]
according to this post even scripting windows wont be possible,any chance of adding floats max to sfall or adding text to highlight functions? https://www.nma-fallout.com/threads/create_win.220850/

**Comment by FakelsHub** [comment]
how many floating messages do you need to create? 10 20 50?

**Comment by nirran** [comment]
i donno it depends on containers on map,50 would prolly be enough

**Comment by FakelsHub** [comment]
50 at the same time?

**Comment by NovaRain** [comment]
I have a feeling after increasing to 50 you will say it's not enough yet again.

**Comment by FakelsHub** [comment]
Okay, I've already figured out how we can make the display of new floating messages.
In the future, as far as possible, we will increase their number to 50.

**Comment by nirran** [comment]
ok thank you

**Comment by nirran** [comment]
> I have a feeling after increasing to 50 you will say it's not enough yet again.

hah maybe set ddraw.ini to a byte settings,making 225 max setting?
