### ISSUE TITLE
Auto Save feature

### ISSUE THREAD

**Issue by blackpaulillyria** [phobos2077/sfall#389]
Auto Save feature would help with people losing progress because they got carried away and they haven't saved but they died or the game crashed. It doesn't have to be present in the Game Options menu but it can be invoked from a script or setup globally to run on every map change in `ddraw.ini`

**Comment by NovaRain** [comment]
You can check the [gl_sfall-mods script](https://github.com/FakelsHub/sFall-Extended/blob/devUnofficial/artifacts/mods/gl_sfall-mods.ssl) by Mr.Stalin.

**Comment by FakelsHub** [comment]
The function does not work very conveniently, need a special modification for the save slots.
