### ISSUE TITLE
Game Freezes in Combat When Turn Ends

### ISSUE THREAD

**Issue by ACiDxCHRiST** [phobos2077/sfall#390]
[SLOT104.zip](https://github.com/phobos2077/sfall/files/6605251/SLOT104.zip)

sfall 4.3, Initiate fight with robot, end turn, the game hard locks

Does not happen with sfall v4.2.9

-Mods
RPU v20
fo2tweaks v12.5
Inventory Filter v2.0.0

**Comment by NovaRain** [comment]
Weird, if I load the save in original RP and w/o fo2tweaks (don't know what components you enabled), fighting the robot works fine.

**Comment by ACiDxCHRiST** [comment]
[fo2tweaks.zip](https://github.com/phobos2077/sfall/files/6605367/fo2tweaks.zip)
Here is my fo2tweaks ini, I will try the test build

**Comment by ACiDxCHRiST** [comment]
Weird. I tested the 4.3.0.1 build and it did not crash. I put 4.3 back and it didn't crash either. Then I realized that I had disabled debugging since I reported this. I re-enabled debugging and that caused 4.3 to start crashing again. 4.3.0.1 did NOT cause a crash.

**Comment by ACiDxCHRiST** [comment]
Disregard the last reply. Continuing to play with 4.3.0.1 even with debugging off, resulted in the same kind of hard lockup in combat. End turn, hard lockup.

It locks up right before Sulik is set to begin his turn, so it might have something to do with that.

**Comment by FakelsHub** [comment]
Attach your ddraw.ini just in case.
I'll look at your savegame later.

**Comment by ACiDxCHRiST** [comment]
> Attach your ddraw.ini just in case.
> I'll look at your savegame later.

ddraw.ini is in the SLOT104.zip from original post

**Comment by NovaRain** [comment]
The new 4.3.0.1 release should address the freezing in combat. Closing the issue for now.
