### ISSUE TITLE
Stuck in combat

### ISSUE THREAD

**Issue by venom9891** [phobos2077/sfall#391]
I'm in the Navarro base and can't exit combat mode even after I've killed every enemy in the base. 

Here is my save: https://drive.google.com/drive/folders/1_OuOpDZVMJGwB9sfw9KcK_v8XYLZL42q?usp=sharing

**Comment by venom9891** [comment]
This was on Sfall 4.3 but was the same issue on older versions too.

**Comment by Lexx2k** [comment]
Are you playing with the UPU or RPU? Because the UPU v19 fixes this issue.

**Comment by venom9891** [comment]
There were indeed 2 turrets left. I killed them and issue was solved! :)
