### ISSUE TITLE
Game freezes in combat, unable to exit game

### ISSUE THREAD

**Issue by wanderer0809** [phobos2077/sfall#392]
hi, im at the boxing ring in new reno, and the game freezes during when you start combat. everything works fine until then (introduction of boxing ring players etc), right until starting of combat then the game freezes and i am unable to even force quit fallout 2. however combat works fine in other areas like new reno's chop shop.

i am using rpu restoration project v20 with included sfall 4.3 

attached my save file here: https://drive.google.com/drive/folders/1_0VHtFifqj3ySfslXQIE-VcVt5hTdnAa?usp=sharing

thanks in advance!

**Comment by NovaRain** [comment]
Try disabling AIDrugUsePerfFix in ddraw.ini.

**Comment by NovaRain** [comment]
Oh, OK. It's good that disabling AIDrugUsePerfFix works, wasn't sure about it so I removed my comment.

**Comment by FakelsHub** [comment]
waiting savegame the fight in the third round.

**Comment by FakelsHub** [comment]
I do not confirm hangups in a fight with boxers.

**Comment by NovaRain** [comment]
I tried the updated save but didn't have any hang in combat with the Masticator.
If it freezes every time for you (i.e. can be produced reliably), try the [test build](https://github.com/phobos2077/sfall/suites/2936867436/artifacts/65975992) (just ddraw.dll itself) see if it helps.

**Comment by wanderer0809** [comment]
it must be something wrong with my laptop then :/ ok i will give that a try and close this issue. thanks a lot for your help!
