### ISSUE TITLE
Vault City is deserted and I cannot leave.

### ISSUE THREAD

**Issue by venom9891** [phobos2077/sfall#393]
I went to vault city to speak with Lynette about a quest and she and a bunch of other important characters weren't there. I thought that maybe it's because it was night time so I went to rest but I can't rest in that location so decided to leave the area to rest. I try to leave Vault city but I can't get exit through the entrance door that the guards are blocking. Interacting with the door does nothing.

Here is my save: https://drive.google.com/drive/folders/1HZ51ZzRO5-m2QjDhNNj7_JRbWrlgFR6l?usp=sharing

**Comment by venom9891** [comment]
I'm using the latest Sfall version btw. Game is vanilla with no other mods besides this one.

**Comment by venom9891** [comment]
Actually, I just realized I'm having trouble opening all kinds of doors.

**Comment by venom9891** [comment]
So going back to a previous version fixed it. Must be a bug from today's update.

**Comment by NovaRain** [comment]
Please re-download 4.3.0.1 release. Sorry about the trouble.
