### ISSUE TITLE
Unable to Open Some Containers

### ISSUE THREAD

**Issue by ACiDxCHRiST** [phobos2077/sfall#394]
[savegame.zip](https://github.com/phobos2077/sfall/files/6626923/savegame.zip)
Can't open the locker that the Player is standing right next to.

It works in sfall 4.2.9 and 4.3

Savegame, ddraw.ini, fo2tweaks.ini, debug.log, etc. are all in attached savegame.zip

-MODS
sfall v4.3.0.1
RPU v20
fo2tweaks v12.5
Inventory Filter v2.0.0

**Comment by NovaRain** [comment]
Please re-download 4.3.0.1 release. Sorry about the trouble.
