### ISSUE TITLE
open pipboy quest page causes freeze

### ISSUE THREAD

**Issue by nirran** [phobos2077/sfall#397]
sometimes shit happens 

freeze happens with latest sfall release,does not happen with 4.2.9

megamod latest slightly modified :

(master.dat is vanilla + latest release of megamod)
(data folder is my edits)
https://www.mediafire.com/file/ry60jb88rih90z7/Data.7z/file

and save to reproduce,load and click pipboy : 

https://www.mediafire.com/file/n5sxbo6157fqrl4/SLOT103.7z/file

edit : donno if it matters but modoc has 11 quests one of them is on second page

**Comment by nirran** [comment]
verified it happens with 4.3.0 and 4.3.0.1

**Comment by NovaRain** [comment]
Please check [the test build](https://github.com/phobos2077/sfall/suites/3041279428/artifacts/69055954), see if it helps.

**Comment by nirran** [comment]
yup,the dll fixed it,thnx guys
