### ISSUE TITLE
Old \n feature for line breaks not working anymore

### ISSUE THREAD

**Issue by Cerebro83** [phobos2077/sfall#401]
This is a late one, but old sfall versions had the following feature, documented in the changelog way back when:

26/06/15
+ Added an ability to use line break (\n) in pro_*.msg files (TEXT/ENGLISH/GAME folder).

This does not work anymore. Unfortunately, I don't know which version of sfall broke the feature, but I did a test with sfall 1.8 and it worked. It does not work anymore with newer sfall versions. As I'd like to mod some text files, I would very much appreciate it being brought back.

**Comment by NovaRain** [comment]
AFAIK it's the feature from Crafty's build (hence you have "1.8" version number but in year 2015), it's never been in the official build.

**Comment by Cerebro83** [comment]
Oh dang, I wasn't aware that this was a completely other version. I guess my chances for this feature to get implemented are less than stellar, then. Thanks for the quick reply, however.

**Comment by FakelsHub** [comment]
Забыли добавить поддержку символа переноса для описаний предметов в интерфейсе бартера.

**Comment by NovaRain** [comment]
> Забыли добавить поддержку символа переноса для описаний предметов в интерфейсе бартера.

"hyphen support"?

**Comment by Cerebro83** [comment]
Didn't notice this got implemented until yesterday. Just wanted to swing by and say thanks!  Much appreciated! (A fix for the barter screen would be nice, though ;))
