### ISSUE TITLE
Jet addiction glitches

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#405]
Strange jet addiction glitches keep coming up: https://github.com/BGforgeNet/Fallout2_Unofficial_Patch/issues/78, https://github.com/BGforgeNet/Fallout2_Restoration_Project/issues/118.
I don't really know how to debug this. Some savegame corruption? Fairly sure that it's not caused by scripts.

**Comment by FakelsHub** [comment]
In general, I found out the reasons for the appearance of the bug.
You can not go to the global map when there is an addiction to JET. :)

**The question is when the "Addiction to JET" perk should appear in the perks tab of the character.
In save №11, this perk is in the character's perk list.**

When starting a new game, this perk does not appear after the addiction penalties from JET.
Maybe he shouldn't appear?
I can't remember how it should work correctly.

**Comment by egornovivan** [comment]
> I can't remember how it should work correctly.

See how the other addictions work, or is there the same problem?

**Comment by NovaRain** [comment]
> When starting a new game, this perk does not appear after the addiction penalties from JET.
> Maybe he shouldn't appear?
> I can't remember how it should work correctly.

No, drug addictions should be shown in "Karma" tab under the reputation.
There are addiction "perks" but never used.

**Comment by FakelsHub** [comment]
> There are addiction "perks" but **never used**

Did you mean that never appeared in the list in the Perks tab?

**Comment by NovaRain** [comment]
> 
> 
> > There are addiction "perks" but **never used**
> 
> Did you mean that never appeared in the list in the Perks tab?

Yes, at least in my tests in UP/RP.

> 
> How did `PERK_add_jet` appear in this list... (in savegame)

I don't know, the engine code and RP scripts don't seem to add addiction "perks" to the player. Although there are checks on the perk when performing withdrawal (`item_d_take_drug` and `item_wd_process`).

**Comment by GelgoogJager** [comment]
> 
> 
> > > There are addiction "perks" but **never used**
> > 
> > 
> > Did you mean that never appeared in the list in the Perks tab?
> 
> Yes, at least in my tests in UP/RP.
> 
> > How did `PERK_add_jet` appear in this list... (in savegame)
> 
> I don't know, the engine code and RP scripts don't seem to add addiction "perks" to the player. Although there are checks on the perk when performing withdrawal (`item_d_take_drug` and `item_wd_process`).

So you think the bug is not engine related?
