### ISSUE TITLE
Key repeat rate gets out of control when using fast speedhack settings

### ISSUE THREAD

**Issue by Giussi** [phobos2077/sfall#406]
it can get quite annoying trying to toggle sneak (1), weapon slot (b), and others with hotkeys .
I did some digging and found these two variables.
0x51e23c | _GNW95_repeat_rate
0x51e240 | _GNW95_repeat_delay
There might be better ways trying to fix this issue.

**Comment by NovaRain** [comment]
You might try this [test build](https://github.com/phobos2077/sfall/suites/3688671978/artifacts/89893931), see if hotkeys don't repeat like crazy.

**Comment by Giussi** [comment]
This fix works perfectly but I noticed another case,
It seems that speedhack is being applied to inventory and other interfaces only in combat mode.
This causes mouse right click to behave similarly when trying to toggle cursor mode in inventory screen [when trying to use healing in combat for example].

**Comment by NovaRain** [comment]
Try [this one](https://github.com/phobos2077/sfall/suites/3696986375/artifacts/90182060).

**Comment by Giussi** [comment]
Beautiful job guys!
