### ISSUE TITLE
The APCost in Unarmed.ini doesn't seem to have effect

### ISSUE THREAD

**Issue by tnevolin** [phobos2077/sfall#413]
The AP cost seems to be fixed by attack type.
primary punch = 3
secondary punch = 4
primary kick = 4
secondary kick = 5

I tried different APCost values for secondary attacks but they don't seem to have effect. Above values do not change.

**Comment by NovaRain** [comment]
I just checked and the parameter works correctly.
If you have other gameplay mods (e.g. F2WR) installed, they might have a hook script that overrides the AP costs.

**Comment by tnevolin** [comment]
Found the problem: EcCo.

> MELEE & UNARMED:
- The cost of the unarmed special attacks has been lowered to 4 for punches and 5 for kicks (taken from Weapons Redone mod).

Not sure where is this configuration in EcCo, though. But never mind. Not sFall bug.
