### ISSUE TITLE
HOOK_TOHIT does not include weapon/ammo

### ISSUE THREAD

**Issue by tnevolin** [phobos2077/sfall#414]
HOOK_TOHIT does not include weapon among parameters. The weapon can carry important perks affecting accuracy and so does ammo. Can these parameters be included?

**Comment by NovaRain** [comment]
Just get the weapon pointer from the attacker's hand.

**Comment by tnevolin** [comment]
Which hand?

**Comment by FakelsHub** [comment]
https://phobos2077.github.io/sfall/sfall-funcx-macros/#critter_inven_obj2

for a non-player character, the active hand is always right. (_RIGHT_SLOT)

**Comment by tnevolin** [comment]
Awesome! Thank you.
