### ISSUE TITLE
write memory doesn't seem to work

### ISSUE THREAD

**Issue by tnevolin** [phobos2077/sfall#415]
I have set AllowUnsafeScripting=1 and running code below to test direct memory write. There is no error but value does not change either. Do I use it right?

```
		variable s = "abc";
		variable p = get_string_pointer(s);
		debug_msg(s);
		debug_msg("" + read_byte(p));
		write_byte(p, 48);
		debug_msg(s);
```

# Output

```
abc
97
abc
```

**Comment by FakelsHub** [comment]
In order to write outside the Fallout 2 address space, you need to set AllowUnsafeScripting=**2**
but in general it is not recommended to use very-low-level programming in the c++ style.

**Comment by tnevolin** [comment]
Thank you for pointing this out.
Yes. I don't like to access memory directly either but this seems to be the last resort. I am trying to modify messages loaded into memory from *.msg files by program at start time. Let me know if there is there is a programmatic and safe way to modify them.
Other option would be to add more information in description window at the time the item description is requested.

**Comment by NovaRain** [comment]
> Other option would be to add more information in description window at the time the item description is requested.

Have you checked [HOOK_DESCRIPTIONOBJ](https://github.com/phobos2077/sfall/blob/master/artifacts/scripting/hookscripts.md#hook_descriptionobj-hs_descriptionobjint)?

**Comment by tnevolin** [comment]
That may do. Thank you.
