### ISSUE TITLE
HOOK_TOHIT The raw hit chance before applying the cap is capped 

### ISSUE THREAD

**Issue by tnevolin** [phobos2077/sfall#416]
HOOK_TOHIT advertises this parameter like that:
> int     arg7 - The raw hit chance before applying the cap

However, it is actually already capped at 110.

**Comment by NovaRain** [comment]
No, it's not capped at 110.
![test1](https://user-images.githubusercontent.com/8564973/141883744-ef878363-7ed5-4e9c-9f81-9a00a933b38c.png)
![test2](https://user-images.githubusercontent.com/8564973/141883757-1f1061b6-7b40-44c6-85c4-5d4e5bed2594.png)
Test script:
```pas
procedure start begin
   if game_loaded then begin
      register_hook_proc(HOOK_TOHIT, hook_test);
   end
end

procedure hook_test begin
   variable
      toHit    := get_sfall_arg,
      attacker := get_sfall_arg,
      target   := get_sfall_arg,
      bodypart := get_sfall_arg,
      srcTile  := get_sfall_arg,
      atkType  := get_sfall_arg,
      ranged   := get_sfall_arg,
      rawToHit := get_sfall_arg;

   display_msg("TOHIT: " + toHit + ", Raw: " + rawToHit);
end
```

**Comment by tnevolin** [comment]
Hmm. Thank you for pointing this out. Maybe some other mod intercepts this and caps value.
