### ISSUE TITLE
HOOK_TOHIT Ranged flag seems to be always 1

### ISSUE THREAD

**Issue by tnevolin** [phobos2077/sfall#417]
```
		register_hook_proc(HOOK_TOHIT, handleToHit);
```

```
procedure handleToHit
begin

	ndebug("handleToHit");

	variable hitChanceCapped = get_sfall_arg;
	variable attacker = get_sfall_arg;
	variable target = get_sfall_arg;
	variable targettedBodypart = get_sfall_arg;
	variable sourceTile = get_sfall_arg;
	variable attackType = get_sfall_arg;
	variable ranged = get_sfall_arg;
	variable hitChanceRaw = get_sfall_arg;

	display_msg("ranged: " + ranged);
```

This just one example. I have tried different attack types: melee, thrown, unarmed.

![toHitRanged](https://user-images.githubusercontent.com/830161/142092567-24d52bcf-21d0-467d-acf3-5d5bfd1c2428.png)

**Comment by NovaRain** [comment]
Yes, that's how the engine does even for melee/unarmed attacks when it's the player. It's only zero for AI.

**Comment by FakelsHub** [comment]
"1 means the hit chance is calculated by taking into account the bonuses/penalties of the distance to the target."

Sometimes English descriptions are very difficult to understand the essence, even I did not understand what is written in this description. :)
(I do not know why, but when it is translated from Russian into English, it is very difficult to understand the essence of what is translated back)

1 - is set when the distance (to the target) is taken into account in the calculation to hit, this does not mean that the current distance to the target is equal to 1 or 2

**Comment by tnevolin** [comment]
So, I guess, the only way to understand whether range penalties apply is to determine which skill is used by attack. If it is unarmed/melee then there is no penalty, otherwise, there is.
