### ISSUE TITLE
How to add new line in object description?

### ISSUE THREAD

**Issue by tnevolin** [phobos2077/sfall#418]
Is there a way to add new line in HOOK_DESCRIPTIONOBJ text? Inventory window description clearly adds some new lines for extra information. Would it be possible to embed something into description to force new line (\n) ? If not, would it be possible to hook the code that outputs this extra information in inventory window starting with new lines and add more new lines of text to it? Thank you.
![newline](https://user-images.githubusercontent.com/830161/142699808-75ced75c-e36c-49aa-8158-d9057ed36eea.png)

I have tried to add \n, \r test to the description. None works.

**Comment by FakelsHub** [comment]
There are no telepaths here for your question.
1. Show the raw text.
2. Which version of HRP are you using?

**Comment by NovaRain** [comment]
Make sure your sfall is updated and use double backslashes.
`str := get_string_pointer("Hello\\nWorld!\\nTest message.");`
![itmdesc](https://user-images.githubusercontent.com/8564973/142706051-b2567824-38b6-4ceb-ae6a-6d0bc38b0356.png)

**Comment by tnevolin** [comment]
Awesome! Thank you.
