### ISSUE TITLE
Error With random force encounter

### ISSUE THREAD

**Issue by nirran** [phobos2077/sfall#421]
I Wrote a script to easily check random encounters,it forces them one by one,with sfall version 4.3.0.2 it does not error and loads them correctly,with versions 4.3.1 and 4.3.2 after a few maps it will load with only dude and party members and the esc menu doesnt load or work,hafta alt tab and kill prog(the error happens w/o script too if that matters),and map enter procedure doesnt fire,here is the script and sfall logg
[debug.log](https://github.com/phobos2077/sfall/files/7873507/debug.log)
[Testers.zip](https://github.com/phobos2077/sfall/files/7873518/Testers.zip)

**Comment by nirran** [comment]
also sometimes when a random encounter fires,it either skips it or crashes with thi
![Screenshot (58)](https://user-images.githubusercontent.com/16279441/149595597-d35bdd02-b625-4af9-9963-5fafd8e184b7.png)
s

**Comment by FakelsHub** [comment]
set FadeBackgroundMusic to off

**Comment by nirran** [comment]
thank you,that fixed the map load error,however i got one crash with pic above.rare tho and playable,thxn
