### ISSUE TITLE
The music stopped after loading savegames in-game

### ISSUE THREAD

**Issue by NovaRain** [phobos2077/sfall#422]
Original thread on NMA:
https://www.nma-fallout.com/threads/fallout-2-music-stop-when-loading-game-in-game.220936/

The game music doesn't play after loading a save in-game (loading the save from the main menu works), only after the map change the music starts playing. The issue is started from 4.3.1 due to `PlayingMusicPatch()` in MiscPatch.cpp, disabling it in the code makes the music play again after loading the save.

**Comment by FakelsHub** [comment]
I don't seem to have that problem. I would have noticed it right away when I was testing AI recently or fixing a bug with files. need more information.

**Comment by NovaRain** [comment]
> I don't seem to have that problem. I would have noticed it right away when I was testing AI recently or fixing a bug with files. need more information.

For me it's fairly easy to reproduce:
1. Start the game, load a save in the Den from the main menu.
2. The music "05raider.acm" plays.
3. Open the Load Game screen and load the same save again, now there's no music. I need to exit the map then return to make the music play.
4. If I exit to the main menu and reload the save, the music plays normally.

The music always plays after loading the save (in step 3) in 4.3.0.2 or earlier versions. Starting from 4.3.1 I cannot hear the music in step 3. I tried commenting out `PlayingMusicPatch()` and the music works again.
