### ISSUE TITLE
cannot display bypass for dude combatdmaage hook

### ISSUE THREAD

**Issue by nirran** [phobos2077/sfall#423]
works for critters other then dude,but this code with no the combat hook scripts,doesnt display bypassed dmg
[GL_Test_Bypass.zip](https://github.com/phobos2077/sfall/files/7895001/GL_Test_Bypass.zip)

or is my scripting wrong?

edit : how the heck u add code tags? the button puts ''

**Comment by NovaRain** [comment]
I'm not sure what you want from the code, the "always bypass" is for when the attacker is the player. Of course it doesn't apply when other critters attack the player.
Check GitHub Doc on [how to use markdown syntax](https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax).

**Comment by nirran** [comment]
Donno what u ment,when setting the flag to dude attacking critter to bypass,the engine does not display it,shows crit or reg damage,thats it

**Comment by NovaRain** [comment]
> Donno what u ment,when setting the flag to dude attacking critter to bypass,the engine does not display it,shows crit or reg damage,thats it

This is what I got in game with your script when I attack a brahmin, it clearly shows "armor bypassed" message:
![scr00000](https://user-images.githubusercontent.com/8564973/150089654-d22087b5-0daa-45b4-9aac-1bacbc0f415c.jpg)

**Comment by nirran** [comment]
odd,didnt for me

**Comment by NovaRain** [comment]
If I were you, I'd make sure there is no global script using the same hook to avoid any possible conflict, given that you have a tendency to cram your modded game with various scripts.

**Comment by nirran** [comment]
Yea Perks script causes it,sorry for false report
