### ISSUE TITLE
console has error in new HRP setting

### ISSUE THREAD

**Issue by nirran** [phobos2077/sfall#424]
when display_msg is sent and loading game,the console doesnt display it(intermitten) with mash HRP it does

**Comment by FakelsHub** [comment]
nothing is clear. write normally report.

**Comment by nirran** [comment]
display_msg is erroring in sfall hrp mode,i think it is adding several blank lines to the display because the saved console file looks normal

it isnt displaying console messages FakelsHub

**Comment by NovaRain** [comment]
You really should give more details about how you use `display_msg` and how it failed, preferably with code line and screenshots.
Here's one of my test script printing in the game:
```pas
// was used to check the mouse drop zone fix
display_msg("Check address val: " + read_int(0x47523D));
display_msg("Check address val: " + read_int(0x475231));
display_msg("Check address val: " + read_int(0x4752BE));
display_msg("Check address val: " + read_int(0x4752B2));
```
![scrnshot](https://user-images.githubusercontent.com/8564973/150447577-62fc70fe-7fdb-4751-82a8-e570de5c47a3.jpg)

**Comment by nirran** [comment]
correction,it is displaying but it is adding blank lines,such as :
![Screenshot (61)](https://user-images.githubusercontent.com/16279441/150448491-1bceed71-0f48-499f-ae52-68d4692c5d21.png)

and on load it doesnt show me the load message,but is in console.txt log

**Comment by NovaRain** [comment]
OK, it seems caused by enabling `ConsoleOutputPath`.

**Comment by FakelsHub** [comment]
it's still unclear what the conditions are.

@NovaRain do you have such a problem when examining in combat?

**Comment by nirran** [comment]
thnx dude,can run it off,also THANK YOU GUYS very much,frp sfall setting gets rid of the need for
'''
; Set EXTRA_WIN_MSG_CHECKS=1 to prevent the "NOT RESPONDING" error that may occur in windowed mode.
; Adds extra windows message checks to several loops during combat and fade effects.
; This setting is always enabled if ALT_MOUSE_INPUT=1.
EXTRA_WIN_MSG_CHECKS=1
'''

ty much

**Comment by NovaRain** [comment]
> it's still unclear what the conditions are.
> 
> @NovaRain do you have such a problem when examining in combat?

Yes, it seems nearly all "You see: blahblah" description lines for objects are blanked in the message window, only when I open the inventory and move the cursor through the list I can see items's "You see: ..." lines.

**Comment by nirran** [comment]
wanta appologize for very vague original report,i know better,was taught by the Navy

**Comment by FakelsHub** [comment]
> ConsoleOutputPath

Just overrides hacks.

**Comment by NovaRain** [comment]
> > ConsoleOutputPath
> 
> Just overrides hacks.

Ah, right. Console module is initialized after `Game` functions. The one in Text.cpp got overridden by Console module.

**Comment by FakelsHub** [comment]
yes, a message about overwriting popped up.

**Comment by nirran** [comment]
> thnx dude,can turn it off,also THANK YOU GUYS very much,frp sfall setting gets rid of the need for ''' ; Set EXTRA_WIN_MSG_CHECKS=1 to prevent the "NOT RESPONDING" error that may occur in windowed mode. ; Adds extra windows message checks to several loops during combat and fade effects. ; This setting is always enabled if ALT_MOUSE_INPUT=1. EXTRA_WIN_MSG_CHECKS=1 '''
> 
> ty much
> 
> edit : typo

donno how to describe,but with pre 2.3.3 vrs and running windowed,sometimes window would stop responding for a min or 2,and display a blue circle 'cursor',havent seen it yet with newest version,thank you =D

**Comment by nirran** [comment]
> thnx dude,can turn it off,also THANK YOU GUYS very much,frp sfall setting gets rid of the need for ''' ; Set EXTRA_WIN_MSG_CHECKS=1 to prevent the "NOT RESPONDING" error that may occur in windowed mode. ; Adds extra windows message checks to several loops during combat and fade effects. ; This setting is always enabled if ALT_MOUSE_INPUT=1. EXTRA_WIN_MSG_CHECKS=1 '''
> 
> ty much
> 
> edit : typo

ack spoke too soon,however the 
``EXTRA_WIN_MSG_CHECKS=1 
seems to work ty again
