### ISSUE TITLE
Dialog mod

### ISSUE THREAD

**Issue by dzmitry-rudnouski** [phobos2077/sfall#428]
Hi, 
I'd like to propose dialog mod. It shows that additional dialog option could be available if player increase his Intelligence, but it doesn't allow to use this option with current Intelligence.
![scr00000](https://user-images.githubusercontent.com/19704782/153502925-f260b270-8093-478f-a688-af44be176ea2.png)

Code is here: https://github.com/dzmitry-rudnouski/Fallout2_Unofficial_Patch/pull/1/files

There are 2 problems for now: I can't compile it for some ssl files, because they don't contain Node999. And I don't know how to create real mod from this code, i.e. separate set of files that could be added to F2 installation folder.

So I wonder if you're interested to include it into sfall.

**Comment by NovaRain** [comment]
Things like this should be done in scripting level, not in the engine code.
