### ISSUE TITLE
books.ini variables manipulation

### ISSUE THREAD

**Issue by nirran** [phobos2077/sfall#45]
Please add access to the different variables for books.ini (min/max skill points without perk,min/max skill points with perk,and max skill skill level able to be upgraded with books)

**Comment by phobos2077** [comment]
You can override handling of books with hook scripts. Try `hs_useobj` and` set_sfall_return(1)`.

**Comment by nirran** [comment]
thank you for the reply,i am aware of the hook script method,the problem is that if the player has over 999 hp it triggers the hp scroll of the numbers,glitched but appears,that is why I asked for the number scroll to be disabled,please concider adding acces to the variables


Nirran


________________________________

**Comment by phobos2077** [comment]
I'm afraid I don't understand how this HP glitch is related to skill books. Could you provide an example code and what's going wrong with it?

**Comment by nirran** [comment]
the only way to have the books deleted when used if not using sfall book method is to make the .pro a drug ,ive tried many ways,this is a sample of the code with that method


      LVar2 := get_sfall_arg;
      LVar3 := get_sfall_arg;
      LVar4 := get_sfall_arg;
      if ((LVar3 == dude_obj) and (LVar2 == dude_obj)) then begin
         if (obj_pid(LVar4) == 778) then begin
            if (has_skill(dude_obj, 0) < get_sfall_global_int(4592)) then begin
               LVar0 := random(get_sfall_global_int(6173), get_sfall_global_int(6174));
               LVar1 := random(get_sfall_global_int(6171), get_sfall_global_int(6172));
               gfade_out(10);
               if (has_trait(0, dude_obj, 81)) then begin
                  critter_mod_skill(dude_obj, 0, LVar0);
                  display_msg(message_str(1, 160) + LVar0 + message_str(1, 178));
               end
               else begin
                  critter_mod_skill(dude_obj, 0, LVar1);
                  display_msg(message_str(1, 160) + LVar1 + message_str(1, 178));
               end
               game_time_advance(60 * (60 * 10));
               gfade_in(10);
            end
            else begin
               display_msg(message_str(1, 203) + message_str(1, 205) + message_str(1, 204));
               gfade_out(10);
               game_time_advance(60 * (60 * 10));
               gfade_in(10);
            end
         end


Nirran



________________________________

**Comment by phobos2077** [comment]
> the only way to have the books deleted when used if not using sfall book method is to make the .pro a drug ,ive tried many ways,this is a sample of the code with that method

That's not true. I just tested and this worked:
```
// in start proc
register_hook_proc(HOOK_USEOBJ, useobj_handler);

procedure useobj_handler begin
   display_msg("gl_test useobj "+debug_array_str(get_sfall_args));
   set_sfall_return(1);
end
```

This will completely override vanilla handler for books and remove them properly after using. 
So I still don't understand what issue are you getting with this method exactly...
