### ISSUE TITLE
Really always run

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#46]
Right now, when "always run" option is enabled, and destination is within 3 hexes or so, the dude still walks to it. Is it possible to force run always?

**Comment by phobos2077** [comment]
I can't seem to reproduce. If always run is disabled, clicking twice on the same hex makes dude run. But opposite is not working.

**Comment by burner1024** [comment]
Yes, my bad. It triggers only when dude is told to "use" an object (open container, etc). Normally it's not much of an issue, but when path to the object is blocked, it results in slowly walking the long way.
