### ISSUE TITLE
Use numbers in dialogue option

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#47]
When there are many options in dialogue, it becomes somewhat hard to navigate using number keys. Especially with HRP and higher resolutions.

I think displaying reply numbers instead of dots would improve user experience in that scenario. Would something like this be possible?

**Comment by NovaRain** [comment]
Implemented NumbersInDialogue option will be available in the next release.

**Comment by burner1024** [comment]
Wow that was fast. Thank you! Looking forward to it.
