### ISSUE TITLE
Controlling NPCs - making it useful

### ISSUE THREAD

**Issue by Kaiketsu27** [phobos2077/sfall#49]
I love the idea behind controlling critters sfall gives (essentially Fallout Tactics in FO2 setting), but since NPCs acquire all your tags, perks and traits, it quickly turns them into copies of you, essentially way too powerful to make this option a valid way to play the game.

Could it be changed so that each time the NPCs (or critters you control in general) get a turn, they get their perks wiped out, their tags wiped out or changed to something unimportant (like gambling, sneak) and traits cleaned/changed to unimportant like sexappeal?

That would totally make it worth to re-play the game as a proper squad commander for extra flavor.

**Comment by phobos2077** [comment]
Thanks for you input. I was thinking about sorting this feature out and maybe replace it with a set of scripting functions along with the global script. This way it will be much better customizable. You will be able to change when control is switched to another character, etc... May be useful for switching to another character in real time mode (like adventure games with several controllable characters). I'm not sure how difficult it will be so need to do some research.

**Comment by Kaiketsu27** [comment]
I am very happy you consider doing this. I would be fully satisfied if it was "just" a current version, just without the perk/trait/tag transfer to NPCs, as I find it relatively stable and sufficient. It would be also probably much easier to "just" fix instead of expanding and/or developing further.

But... yay. I always wanted to play sort of fallout tactics in Fallout2 setting. So happy! Hope this goes well.

**Comment by phobos2077** [comment]
It's just I don't like complex features that are hard-coded into the sfall (being an extension of the engine). It's complicated to make them configurable and still someone might not like how it works. With scripts it's easy to modify any aspect of the feature/mod without need for C++ compiler and C++/asm knowledge. Not to mention that modifying scripts is a lot safer (crash prone sometimes, but still) than direct engine modifications.

**Comment by Kaiketsu27** [comment]
how's the progress? any difficulties? ;)

**Comment by phobos2077** [comment]
Mostly done (the fix, without scripting solution). There might be some leftover issues related to drug addictions, etc.

**Comment by tspoff** [comment]
Very interested in how this turns out! Seems like a tough codebase.

**Comment by phobos2077** [comment]
Party control needs more work, but all issues described in first message should be fixed now. Let's create additional issues if needed.
