### ISSUE TITLE
Externalize explosives

### ISSUE THREAD

**Issue by phobos2077** [phobos2077/sfall#5]
Move explosives to INI properly (inactive => active PIDs for each and min/max damage) 
(maybe flares along with them?)

Points of interest:
- queue_do_explosion: replace min/max dmg code
- obj_use_explosive_: replace cmp pids code, "active pid" code
- check messages 590, 589

**Comment by NovaRain** [comment]
With the new item_make_explosive from metarule2_explosions and get_ini_* functions, it's now possible to write a global script to load INI settings and set up explosives accordingly. Just not _that_ modder-friendly because one has to make the script first.

**Comment by FakelsHub** [comment]
You can create a generic template script for modder-friendly use.
