### ISSUE TITLE
Forced map update

### ISSUE THREAD

**Issue by phobos2077** [phobos2077/sfall#51]
Is there any way to force map_update (with calls to all scripts _map_update_p_proc_)? 
If there is no way, need to add opcode for it.

**Comment by phobos2077** [comment]
Added command sfall_func0("exec_map_update_scripts");

**Comment by FakelsHub** [comment]
> The map _ * _ p_proc procedures are now executed for all global scripts containing them

Make a note, that these procedures are performed only for the global script mode 0 (and 3)
