### ISSUE TITLE
Quick Save key doesn't work properly.

### ISSUE THREAD

**Issue by NovaRain** [phobos2077/sfall#57]
In vanilla FO2 or with sfall 3.7.4, pressing F6 first time in the game brings up a "Pick a Quick Save slot" window. But with sfall 3.8 pressing F6 only brings up a normal "Save Game" window, acting the same way as F4.

**Comment by NovaRain** [comment]
The bug is introduced in commit ce72ef5, line 107 in LoadGameHook.cpp.
Also it's worth noting that with SaveInCombatFix enabled, sfall changes pressing F6 in combat to open normal "Save Game" window instead of "Pick a Quick Save slot".

**Comment by phobos2077** [comment]
I don't see any different behavior between current version and 3.7.4. The bug you described only happens if SaveInCombat is enabled and it happens in 3.7.4 too.

**Comment by phobos2077** [comment]
Ok the bug was not directly related to commit you pointed out, it was old bug in ASM code. Fixed in develop branch.
