### ISSUE TITLE
Need new function steal_success. (rus)

### ISSUE THREAD

**Issue by FakelsHub** [phobos2077/sfall#59]
Нужна функция с помощью, которой можно было узнать, была ли предыдущая попытка кражи успешной или провальной, что-то типа Steal_Success
1 - успешна
0 - провал
-1 - не определено.  и сброс возвращаемого значения в -1 после использования этой функции.

**Comment by phobos2077** [comment]
Каков пример использования такой функции?

**Comment by FakelsHub** [comment]
да пример можно любой на фантазировать, к примеру в том-же HOOK_STEAL
procedure steal_hook_proc begin
...
       steal_obj_hook:=true;
       if theft_success then skill+=random(25,50); //бонус при успешной(повторной) краже
...
end
procedure removeinv_hook_proc begin
     if steal_obj_hook then begin
        theft_success:=true;    //кража была удачной
        steal_obj_hook:=false;
     end
end

сейчас как ты уже понял это можно проверить только через HOOK_REMOVEINVENOBJ совместно с HOOK_STEAL (или HOOK_USESKILL)
было бы удобно одной функцией.

**Comment by phobos2077** [comment]
Не совсем понятен смысл в данной функции. Кроме как в момент кражи эта функция будет бесполезна, а в HOOK_STEAL ты какбы сам задаешь правила кражи. Так что просто перепиши логику которая игра использует для проверки успеха сам и вызывай set_sfall_return(1 иди 0). 
Может заодно сделаешь формулу воровства более справедливой, а то народ постоянно жалуется что кража в игре сильно портит баланс :)

**Comment by FakelsHub** [comment]
>Кроме как в момент кражи эта функция будет бесполезна, а в HOOK_STEAL ты как бы сам задаешь правила кражи.

Да все правильно бесполезна в момент кражи, но основываясь на предыдущей попытке(успех/провал) можно уже при следующей попытке(к примеру если игрок продолжает тырить) в HOOK_STEAL анализировать нашу переменную. вот в чем соль.
Да это все решается и так скриптово без этой функции, через доп проверки.
И если так не хочется с этим возиться, можно и забить на нее.
Лучше вот более полезное реализуйте - Issues #66 :)

> Может заодно сделаешь формулу воровства более справедливой
Может...)

**Comment by phobos2077** [comment]
> Лучше вот более полезное реализуйте - Issues 

А я жду когда ты сам это реализуешь xD

**Comment by FakelsHub** [comment]
Думаю делать такую функцию не целеобразно. :-)  Closed.
