### ISSUE TITLE
Keypress hook not working after game_ui_disable

### ISSUE THREAD

**Issue by phobos2077** [phobos2077/sfall#60]
Need to find a way to catch key presses after game_ui_disable.

**Comment by FakelsHub** [comment]
Я не думаю что это является ошибкой, а наоборот защищает от появления таковых, сейчас объясню.
К примеру мы имеем один сценарий который должен блокировать управление игрока через game_ui_disable.
И второй сторонний скрип **от другого производителя**, который управляет какими-то действия игрока, в то время как такое управление не желательно для игры!
Несложно догадаться что произойдут нежелательные действия для игры, от того что игрок нажал какую-то клавишу, в то время как это запрещено.

В чем вообще надобность использования клавиатуры при выключенном интерфейсе?

**Comment by FakelsHub** [comment]
Close Issue. This is not an bug.
