### ISSUE TITLE
Making WorldMapEncounterFix/Rate independent from WorldMapFPSPatch

### ISSUE THREAD

**Issue by NovaRain** [phobos2077/sfall#62]
Their code doesn't interfere with WorldMapFPSPatch and still works with the setting enabled. Currently they can only be used with WorldMapFPSPatch=0, which makes world map travel speed lightning fast on modern specs, unless users know how to use the obsolete WorldMapFPS setting and adjust its value. No point in keeping them dependent on WorldMapFPSPatch IMO.

**Comment by phobos2077** [comment]
So can we close this now?

**Comment by NovaRain** [comment]
Yes.
