### ISSUE TITLE
Add item_weight script function

### ISSUE THREAD

**Issue by phobos2077** [phobos2077/sfall#63]
Consider externalizing item_weight and item_total_weight engine functions as scripting functions (using sfall_func1).

From Mr.Stalin:
`call_offset_r1(0x477B88, ItemPtr); /* Get Item Weight (for weapon include load ammo weight) */ `

**Comment by FakelsHub** [comment]
> Get Item Weight (for weapon include load ammo weight) */

Для итемов контенеров тоже считает вес его содержимого.

**Comment by phobos2077** [comment]
Just a thought.. Why do we need this scripting function if it's already possible to calculate item weight in script?

**Comment by FakelsHub** [comment]
> if it's already possible to calculate item weight in script?

I do not quite understand) 
I used it to calculate the weight of the weapon with loaded ammo.

**Comment by phobos2077** [comment]
Added.
