### ISSUE TITLE
User-defined script Hooks (RUS)

### ISSUE THREAD

**Issue by FakelsHub** [phobos2077/sfall#65]
Есть некое предложение сделать на основе хуков, скрипты которые бы перехватывали управление движка задаваемым пользователем, и в скрипте бы уже выполнялись нужные функции, а после возвращала бы нужные скриптеру аргументы обратно в движок по указанному адресу, как это делает сам sfall.
Возможно ли такое сделать на основе скриптов?.

**Comment by phobos2077** [comment]
Не совсем понятно. Можешь ли привести пример кода/псевдокода использования таких хуков?

**Comment by FakelsHub** [comment]
Да сам не знаю как это понятно написать.
Ну вот допустим надо в движковых функциях что-то изменить под свои нужды есть два варианта, это править в НЕХ, или писать доп. функционал в самом коде сфала. понятное дело что в нех много не изменишь, а сфалл надо компилировать каждый раз под новые версии.
Я вот и предлагаю реализовать что-то на подобии MakeCall/HookCall но чтобы наш код вставки выполнялся в среде самих скриптов.
Такое вообще возможно?

**Comment by phobos2077** [comment]
По сути ты предлагаешь функции в стиле call_offset, где нужно передать адрес вызова и указатель на скриптовую процедуру... Идея не плохая, но такая функция хороша лишь для отладки. В конечных модах все равно лучше полагаться на код самого sfall. 
Я сейчас в процессе переписывания кода таким образом чтобы дополнять функционал было проще. В будущем я вижу такой процесс:
1) Мододелу понадобился функционал которого нет. 
2) Мододел форкает репу, создает ветку и запиливает свою фичу. Компилирует локально для отладки (подойдет бесплатная версия Visual Studio).
3) Делаем Pull Request. За счет улучшенной структуры кода, процесс принятия изменения должен быть проще.
4) Автоматическая сборка текущей версии из Github для всех желающих. Правда я ни разу такое не настраивал, но если не ошибаюсь есть бесплатные сервисы которые позволяют такое настроить... Не уверен правда что там Visual Studio компилятор есть. 
Как запасной вариант можно после каждого мерджа Pull Request выкладывать сборку вручную...

**Comment by FakelsHub** [comment]
> По сути ты предлагаешь функции в стиле call_offset, где нужно передать адрес вызова и указатель на скриптовую процедуру... 

нет не аналог call_offset...
а - скрипт который бы перехватывал управление движка задаваемым пользователем, и в скрипте бы уже выполнялась часть кода движка, а после возвращалось управление в движок. типа код движка но только в скрипте, во такая загагулина)

> Ибо что если кто-то портирует sfall целиком под 1й Fallout? Или Sfall для Mapper-a, там все адреса другие. Соответственно любой мод построенный на предположении о то что все смещения движка высечены на камне - сломается.

Ну это ты уже в крайности полез. есть один движок US версии, остальные считаем не совместимыми)

**Comment by phobos2077** [comment]
> Ну это ты уже в крайности полез. есть один движок US версии, остальные считаем не совместимыми)

Ну это эгоистичный подход. Например китайский язык запилить невозможно в движок US версии, т.к. банально одного байта на символ недостаточно для представления иероглифов. Тут нужна специальная версия Sfall и все смещения будут другими - ваши "хакерские" моды работать не будут, а ведь это большой потенциальный рынок игроков :)

**Comment by FakelsHub** [comment]
> Тут нужна специальная версия Sfall 

У китайцев, что нет своих программистов, переписать сфалл под китай?)
Китайский рынок игроков))) - у них там своя песочница.
