### ISSUE TITLE
No radius damage in metarule2_explosions... bug?

### ISSUE THREAD

**Issue by FakelsHub** [phobos2077/sfall#67]
> set_attack_is_explosion_fire
> if you call this right before using a weapon with fire damage type, it will produce explosion effects (and radius damage) just like "explosion" type, but all targets will still recieve fire damage.
       
metarule2_explosions(4, 2, 0);
Почему то нет повреждений окружающим от самого взрыва (radius damage) ошибка?
или надо это как-то совместно с чем-то использовать?

**Comment by phobos2077** [comment]
Please provide more information for your case. I used all of those functions in my mod and they worked fine.

**Comment by FakelsHub** [comment]
да-да я тоже использовал твой функционал из мода) но как оказывается то сплеш дамага то нет.
вот переделанный скрипт для молотова)
```
procedure start begin
 if game_loaded then begin
    register_hook_proc(1, hit_hook);     //HOOK_AFTERHITROLL
    register_hook_proc(16, damage_hook); //HOOK_ITEMDAMAGE
    display_msg("molotov");
 end
end

procedure hit_hook begin
//Runs after fallout has decided if an attack will hit or miss
variable TypeHit, CritterAttack, CritterTarget;
variable hslot, item;
   TypeHit := get_sfall_arg;
   CritterAttack := get_sfall_arg;
   CritterTarget := get_sfall_arg;

   if (CritterTarget and CritterAttack) then begin
      if (obj_type(CritterTarget) == 1) and (TypeHit <= 1) then begin
          hslot:=active_hand;
          if hslot == 0 then hslot:=2;
          item:=obj_pid(critter_inven_obj(dude_obj, hslot));
          if item==159 and get_proto_data(item, 48)==2 then begin //PROTO_WP_DMG_TYPE
              display_msg("fire_miss");
              metarule2_explosions(1, 1, 0);
              metarule2_explosions(4, 2, 0);
          end
      end
   end
   
end

procedure damage_hook begin
//Runs when retriving the damage rating of the players used weapon. (Which may be their fists.)
 variable temp, weapon_obj_used;

     temp := get_sfall_arg;
     temp := get_sfall_arg;
     weapon_obj_used := get_sfall_arg;

     temp:=obj_pid(weapon_obj_used);
     if (temp == 159) and (get_proto_data(temp, 48) == 2) then begin //PROTO_WP_DMG_TYPE
        display_msg("fire_exp");
        set_weapon_knockback(weapon_obj_used, 0, 0);
        metarule2_explosions(1, 1, 0);
        metarule2_explosions(4, 2, 0);
     end
end
```

**Comment by phobos2077** [comment]
I remember shooting incendiary grenades at a bunch of wanamingos (they have high explosion resistance but low fire resistance) and they all got hit in a radius with fire damage type. Try playing around with set_attack_explosion_radius(). It should work for both grenades and rockets.

**Comment by FakelsHub** [comment]
> Try playing around with set_attack_explosion_radius()

this not working

**Comment by phobos2077** [comment]
Provide a simplest possible example mod for vanilla game showing off your issue.

**Comment by FakelsHub** [comment]
```
        metarule2_explosions(4, X, 0);
```
No Splash Damage. Check sfall code.

**Comment by phobos2077** [comment]
This is not helpful. I need a working mod and step-by-step instruction to reproduce the issue.

**Comment by FakelsHub** [comment]
> I need a working mod (global script) 

Ready code for script test I wrote above, copy it and compile. Set for PID 159 type of damage = fire. set_proto_data(159, 48, 2);
Test: throwing a Molotov cocktail into a crowd of opponents, you will see that surrounding opponents (including the player) will not take any damage from the explosion.

```
Готовый код для тестового скрипта я привел выше, скопируйте его и скомпилируйте. Установите для PID 159 тип наносимого повреждения огонь.
Кидая коктель молотова в толпу противников, вы увидите что окружающие противники(включая игрока) не будут получать никакого урона от взрыва... урон будет получать только тот в кого попало.
_Фобоc, если это ты пиши блин на русском. :)_
```

**Comment by phobos2077** [comment]
Please check this build (based on 3.8). https://yadi.sk/d/mXr_FxBn3ETdYy
Does it fixes the issue?

**Comment by FakelsHub** [comment]
> Does it fixes the issue?

Yes it fixed the problem. Thank you)

**Comment by FakelsHub** [comment]
```
	// explosion dmgtype
	for (i=0; i<4; i++) {
	SafeWrite8(explosion_dmg_check_adr[i], 6);
```
Еще здесь забыли сделать правку

**Comment by burner1024** [comment]
I think this is broken again. On 4.1.1, Molotovs don't explode anymore.

**Comment by NovaRain** [comment]
I just so happened to test my molotov script (ripped from EcCo) today. Other than finding out Sulik in RP missed NMSULAAO.FRM, I didn't notice anything unusual.

**Comment by FakelsHub** [comment]
Проверил скрипт молотова все в норме.
Проверьте ваш скрипт.

> I just so happened to test my molotov script (ripped from EcCo) today.

from EcCo is not a working implementation.

**Comment by NovaRain** [comment]
>from EcCo is not a working implementation.

well, my script works w/o problems for missed shots on my home PC. Not sure why it happens on my office PC. Maybe you could post yours?

**Comment by FakelsHub** [comment]
```
procedure start begin
   if game_loaded then begin
      register_hook_proc(HOOK_AFTERHITROLL, Hit_Hook);
      register_hook_proc(HOOK_ITEMDAMAGE, ItemDamage_Hook);
   end
end

procedure Hit_Hook begin
variable TypeHit, CritterAttack, CritterTarget;
variable hand_slot, item;
   TypeHit       := get_sfall_arg;
   CritterAttack := get_sfall_arg;
   CritterTarget := get_sfall_arg;

   DEBUGMSG("Molotov: Hit_Hook " + TypeHit)
   DEBUGMSG("Molotov: CritterTarget " + obj_name(CritterTarget))
   if (CritterTarget and CritterAttack) then begin
     if ((obj_type(CritterTarget) == OBJ_TYPE_CRITTER) and (TypeHit <= 1))
     or ((obj_type(CritterTarget) == OBJ_TYPE_SCENERY) and TypeHit) then begin  // miss hit
         if CritterAttack == dude_obj then begin
             get_active_hand(hand_slot); // in hand_slot = # slot
             item := critter_inven_obj(CritterAttack, hand_slot);
         end
         else item := critter_inven_obj(CritterAttack, INVEN_TYPE_RIGHT_HAND);

         if item > 0 and obj_pid(item) == PID_MOLOTOV_COCKTAIL then begin
             call Set_AttackFire;
         end
      end
   end
end

procedure ItemDamage_Hook begin
variable weapon_obj_used := get_sfall_arg;
         weapon_obj_used := get_sfall_arg;
         weapon_obj_used := get_sfall_arg;

   DEBUGMSG("Molotov: ItemDamage_Hook")
   if weapon_obj_used > 0 and (obj_pid(weapon_obj_used) == PID_MOLOTOV_COCKTAIL)
   and obj_item_subtype(weapon_obj_used) == item_type_weapon then begin
      call Set_AttackFire;
   end
end

procedure Set_AttackFire begin
   if (get_proto_data(PID_MOLOTOV_COCKTAIL, PROTO_WP_DMG_TYPE) == DMG_fire) then begin
      set_attack_explosion_pattern(1, 0);
      set_attack_explosion_radius(2);
      set_attack_is_explosion_fire;
      debug_msg("Molotov: Attack as explosion fire.");
   end
end
```

**Comment by NovaRain** [comment]
I suppose the script should be compiled with -s switch, and the molotov should have the dmg type set to fire in its proto? But it would make opening Vic's door in RP a bit harder, as now you can't blow up the door with a molotov.

**Comment by FakelsHub** [comment]
Yes.

> But it would make opening Vic's door in RP a bit harder, as now you can't blow up the door with a molotov.

Modify the script so that it would destroy the door.
HOOK_ITEMDAMAGE - This is probably not needed here and is superfluous.

**Comment by burner1024** [comment]
Вроде в основном работает, но такое слегка странноватое поведение, при промахах иногда не взрывается. А иногда вроде взрывается но без анимации. Не могу пока до конца разобраться.

**Comment by FakelsHub** [comment]
Количество анимаций в конфиге поставлено на мах? (Непомню как параметр называется)

**Comment by burner1024** [comment]
120 поставлено. Пробую на браминах в Модоке. То так, то сяк.

**Comment by burner1024** [comment]
Вот [видео](https://www.useloom.com/share/dbf432ba0acc4d47b4f9eb7640926eca). То же самое на 4.0.
У меня еще EcCo установлен, я посмотрел там он тоже делает в скрипте дамаг огнем, возможно какой-то конфликт опять.
И еще я прочитал где-то на форуме, что молотов захардкоден в движке на огонь, несмотря на то что в прото прописан взрыв. Так что, возможно, этот твик вообще бессмысленен.
Плюс я уже не помню как в оригинале, всегда взрывается или нет. По идее должен всегда.

**Comment by FakelsHub** [comment]
> И еще я прочитал где-то на форуме, что молотов захардкоден в движке на огонь, несмотря на то что в прото прописан взрыв. 

Фигню всякую не читай) все взрывы в движке захаркорены на повреждение взрыв.
На огонь он там захаркорено только анимация смерти.

**Comment by FakelsHub** [comment]
Посмотрел твое видео проблема в скрипте.

**Comment by burner1024** [comment]
Ну это вот скрипт который ты чуть выше запостил.

**Comment by FakelsHub** [comment]
Окно отладочных собщении включи и проверь и проверь в игре debug_msg("Molotov: Attack as explosion fire.")
И фобовский скрипт убери.

**Comment by burner1024** [comment]
Да я теперь и так вообще все скрипты/хуки удаляю при проверках.
Попозже еще попробую на чистой установке.
