### ISSUE TITLE
The bag bug for keeping items that are supposed to be moved from the inventory

### ISSUE THREAD

**Issue by NovaRain** [phobos2077/sfall#70]
From Per's ["The Nearly Ultimate Fallout 2 Guide"](http://user.tninet.se/~jyg699a/fallout2.html):

> The Bag is responsible for an inventory bug which sometimes lets you keep items that are really supposed to disappear from your inventory, depending on which script command is being used to remove them. Items are "protected" if they're **below the Bag in your inventory**, apparently because the engine can't handle the container item type properly.

**Comment by phobos2077** [comment]
Looks like the bug is in item_count_ function, it returns 0 when it shouldn't.

**Comment by phobos2077** [comment]
Fixed in my module-system branch. Was too lazy to switch to another branch, but this fix can be ported easily to 3.8 branch.
