### ISSUE TITLE
Bug in ExplosionsEmitLight.

### ISSUE THREAD

**Issue by FakelsHub** [phobos2077/sfall#78]
When is set ExplosionsEmitLight = 1 option, flash(PID_FLARE) it does not lighting up in the throw and on ground.

**Comment by NovaRain** [comment]
Weird, in my game flares still light up during attack and on the ground with ExplosionsEmitLight=1.

**Comment by NovaRain** [comment]
Weird, in my game the flare does light up during attack and on the ground with ExplosionsEmitLight=1.

**Comment by FakelsHub** [comment]
Are you sure?
In my game flare ceases to be a source of light, and when flying does not illuminate.

**Comment by phobos2077** [comment]
Did you modify flare's the proto? There should be enough light radius and intensity value. 
Does it light up in vanilla game?

**Comment by FakelsHub** [comment]
Checked even on the original proto files. Engine is US 1.02d not modified.

**Comment by phobos2077** [comment]
@FakelsHub, you didn't answer my question. I just checked and in my game the flare does light up regardless if ExplosionsEmitLight is enabled or disabled. 
Checked sfall 3.8.1 and current **develop**.

**Comment by FakelsHub** [comment]
Чтоб было всем понятно пишу на русском)
Как это не загорается в оригинале(без включенной опции)? когда кидаешь вспышку она начинает излучать свет.
вот скрины, и без разницы оригинал игра, или это мод.
http://www.imageup.ru/img189/2708019/scr00001.jpg  / ExplosionsEmitLight - off.
http://www.imageup.ru/img189/2708022/scr00004.jpg  / ExplosionsEmitLight - on
Просто лежит на земле без эффекта свечения.

**Comment by phobos2077** [comment]
Как я уже сказал, у меня не удается повторить. Подсвечивается с включенной и выключенной опцией.

**Comment by FakelsHub** [comment]
Да не в прохах дело все родное и двиг, я уже и все глобальные скрипты удалял, и прохи родные оставлял. 
И на чистом фоле без HPR на 640х480 проверил все равно не зажигает.
http://imageup.ru/s2708118

Да вот тут собака зарыта.
static void __declspec(naked) ranged_attack_lighting_fix() {
Найдите там ошибку) или сделайте исключение для FLARE.

**Comment by phobos2077** [comment]
@FakelsHub: Ошибки нет. Когда опция включена, она использует значение освещенности из прототипа. Я для своей игры правил прототип фонарика (Proto\Misc\00000024.pro). Не уверен что стоит хардкодить какие-то айдишнике, ведь проблема не в движке а в дефолтном прототипе.

**Comment by FakelsHub** [comment]
Но я вообще не трогал misc прототип, к тому же на чистом фоле такая же фигня.
Может быть у меня что-то включено лишнего в настройка ddraw.ini ?
надо попробовать с дефолтными настройками

**Comment by phobos2077** [comment]
Прочитай еще раз мой комментарий, как раз на дефолтных прошках и не светится, т.к. в них для флешки нули прописаны))
Но я кажется нашел что происходит и как можно пофиксить без хардкода. Фонарики подсвечиваются в момент когда берешь их в руки, а не при броске. Попробую добавить проверку.

**Comment by FakelsHub** [comment]
>Прочитай еще раз мой комментарий, как раз на дефолтных прошках и не светится, т.к. в них для флешки нули прописаны))
Блять))) так бы и сказали что надо misc прототип править под это дело)

**Comment by FakelsHub** [comment]
>Не уверен что стоит хардкодить какие-то айдишнике, ведь проблема не в движке а в дефолтном прототипе.

Прототип то и так уже захаркоден в движке, т.е. обрабатывает им по дефолту.

**Comment by phobos2077** [comment]
> Прототип то и так уже захаркоден в движке, т.е. обрабатывает им по дефолту.

У меня в планах было расхардкодить его, вместе с динамитами.

**Comment by FakelsHub** [comment]
А ясно)

**Comment by phobos2077** [comment]
Пофиксил. Если объект перед броском уже был засвечен то освещенность меняться не будет.. Тут могут быть тоже подводные камни, но по крайней мере это решает проблему и не ломает для остальных предметов.
