### ISSUE TITLE
Move Reload hotkey to a script

### ISSUE THREAD

**Issue by phobos2077** [phobos2077/sfall#84]
Need to implement Reload hotkey as a mod and remove it from sfall code.

**Comment by burner1024** [comment]
One more thing I'd like to add: Reload hotkey also works as "Use item", which is very convenient. For example, you can use Lockpicks with it. Not sure if that was the intention or a byproduct.
However, sometimes it stops working (but it still does reload). I can't pinpoint when that happens. No game reloads or map walking or switching items in hands change that. And then it suddenly starts to work again.

Please take that into account when moving the code into a mod.

**Comment by phobos2077** [comment]
@burner1024 , we will, thanks for pointing out.

**Comment by FakelsHub** [comment]
you are not going to move it, it may be closed.
