### ISSUE TITLE
New scripting functions for working with INI files

### ISSUE THREAD

**Issue by FakelsHub** [phobos2077/sfall#85]
I think that we need function that would allow us to change the value of the parameter in ini file from script. :)

**Comment by phobos2077** [comment]
Are you talking about ddraw.ini? This is currently not possible. Most sfall modules read their settings during init (before main menu is loaded), so there is no point changing those settings - they will do nothing.

Basically you will have to add ability to change values for every case when it makes sense. But general solution is not possible.

**Comment by FakelsHub** [comment]
No, not about ddraw.ini
About custom .ini in which you can store the settings of your mod, and not in sfall global variables.
- ну как бы такая альтернатива для хранения не игровых параметров. вот. :)

**Comment by phobos2077** [comment]
So do you want scripting functions for **setting** INI values? That should not be hard to do at all. Btw, I've added 2 scripting commands for reading names of all sections in INI and all key/value pairs in specific section. I plan to add alternative commands for reading individual values as well (the get_ini_string/setting have awful API). 

I was thinking about doing some config-heavy mods (extended weapon prototypes - settings in INI files and implemented via hook scripts), and how we can use INI not just for simple settings but for a lot more. We need to optimize how INI are loaded, now it uses GetPrivateProfileXXX functions from WinAPI - they are bad for several reasons:
- Outdated API from Win 95 era
- Always trying to read from windows registry
- Probably loads and parses files every time (not efficient when you want to read settings often)

They may be fine for *writing* though, as it's done less often. And writing INI without using Win API is slightly harder to do.

**Comment by FakelsHub** [comment]
> We need to optimize how INI are loaded, now it uses GetPrivateProfileXXX functions from WinAPI - they are bad for several reasons:
> They may be fine for writing though, as it's done less often. And writing INI without using Win API is slightly harder to do.

The engine has its own functions for reading and writing values ​​into config files get / set_config_value (string), which work on the principle .ini
