### ISSUE TITLE
Elevators are broken in develop

### ISSUE THREAD

**Issue by phobos2077** [phobos2077/sfall#88]
Need to check custom elevators, reported as not working.

**Comment by Lexx2k** [comment]
My elevators haven't changed in ages. This is the spatial script code:
`metarule(15, 26);`

This is in my elevators.ini:
`[26]
Image=1
ID1=205
Elevation1=0
Tile1=16516
ID2=206
Elevation2=0
Tile2=16516`

If I revert my ddraw.dll to an older version, the elevators work again.

**Comment by phobos2077** [comment]
I fixed the bug. Check out latest develop or new binary on nma thread.

**Comment by Lexx2k** [comment]
I've just tried it-- appears to be fixed. Thanks.
