### ISSUE TITLE
Add a hook to influence resting timer

### ISSUE THREAD

**Issue by Lexx2k** [phobos2077/sfall#89]
Being able to track the time a player is waiting via PipBoy resting function, and allowing to cancel the action could be useful.
Maybe it's possible to "fetch" the option chosen by the player and return the time value, then modify it and call another script / procedure once done?
=> If I click "rest 1 hour", I get the value of 60 minutes back, which I then modify to 30 minutes via script function. After the 30 mins, the pipboy will close + the next script function will start.

Example situation to use in:
Rest too long in a specific location will cancel the resting and spawn enemy critters around the player. Let's call this "in map encounters".

**Comment by NovaRain** [comment]
The new HOOK_RESTTIMER should be able to work for your in-map encounters. Although you can't overwrite the ticks of a planned resting, you can simply cancel the resting with return value of 1.

An example script that will close the pipboy after the player rest for more than one hour (about 70~75 mins usually):
```
procedure start;
#include ".\HEADERS\DEFINE.H"
#include ".\headers\sfall.h"
#include ".\headers\dik.h"

procedure start begin
   if game_loaded then begin
      register_hook(30);
   end else begin
      variable
         ticks := get_sfall_arg,
         event := get_sfall_arg,
         hours := get_sfall_arg,
         mins := get_sfall_arg,
         tmp;

      tmp := game_time;

      if ((ticks - tmp) > ONE_GAME_HOUR) then begin
         set_sfall_return(1);
         display_msg("Sorry, you have rested enough.");
         tap_key(DIK_ESCAPE);
      end
   end
end
```

**Comment by phobos2077** [comment]
@NovaRain @FakelsHub , guys you are awesome :+1:
