### ISSUE TITLE
Sfall 4.0 Bug: Combat mode - critters flee....

### ISSUE THREAD

**Issue by FakelsHub** [phobos2077/sfall#92]
Тестирую 4.0 и пока не разобрался в чем точно проблема, но заметил, что NPC(critters) начинают убегать с поля боя от игрока.
Такая дрянь на всех npc.
`Малый Радскорпион: FLEEING: Can't possibly Hit Target! Малый Радскорпион is using Scorpion packet with a 0еhance to taunt`
v4.0 dll от 20170405
В 3.8.3  все нормально с этим.

**Comment by FakelsHub** [comment]
Такая дрянь на всех.
`Малый Радскорпион: FLEEING: Can't possibly Hit Target!
Малый Радскорпион is using Scorpion packet with a 0еhance to taunt`

**Comment by phobos2077** [comment]
У тебя HOOK_TOHIT нигде не переопределяет шанс попадания?

**Comment by FakelsHub** [comment]
Убирал все глобалки.
Нормально когда ты его ранил или еще чего, а тут все убегают как только входят в бой :-)

**Comment by FakelsHub** [comment]
Проблема бегства в настройках AI packet - если в параметре `min_to_hit=0` выставлен в нуль то такие криттеры начинают сразу убегать. В оригинале (как и в версии 3.8) нули означают что такие криттеры никогда не будут убегать, с поля боя.

**Comment by phobos2077** [comment]
Будем посмотреть.

**Comment by phobos2077** [comment]
Проверил на маленьких Гекко - не повторяется. У них пакет с `min_to_hit=0` но никакого аномального поведения не замечено. Причина гдето в другом месте.
На неваде проверял?

**Comment by FakelsHub** [comment]
Убирал все глобалки/хуки. в 3.8.3 все же нормально с этим.
HOOK_TOHIT у меня вообще нигде не используется.

min_to_hit - это порог процента шанса попадания ниже которого NPC начинают убегать, при 0 никогда, при 100 всегда.
меняешь min_to_hit с 0 на 1 и убегать перестают.
притом что в AI.txt я ничего не трогал, он оригинальный.
сможешь отключить эти новые параметры в TOHIT ну чтоб он был как в 3.8, что-бы я смог проверить, в них дело или нет.

**Comment by phobos2077** [comment]
Я хз может ты както криво компилируешь?) 
Попробуй откатиться до коммита c83fe0690b59b9949ab151027db31166ec6a6121  (до изменения TOHIT). Если проблема останется значит дело не в хуке...

**Comment by FakelsHub** [comment]
> Я хз может ты както криво компилируешь?)

Я сфалл не компилирую, у меня не стоит 15 студия, я просто использую длл которую ты выложил на NMA. скомпиируй мне обновленный вариант может в той баг.

> но в таком случае все что больше 0 тоже должно вызывать бегство...

условие скорее такое.
if  (to_hit > min_to_hit)  then combat..
else flee...
при нуле бегства никогда не будет.

**Comment by NovaRain** [comment]
Did you notice that all your skill are 0% or not when the critter fleeing bug happens?
With current sfall 4.0, if you try to start a new game by creating a character or taking a premade one, you can notice that all skills are 0%. Probably all critters' skills are the same, so they will just flee since their hit chance is below 0%.

**Comment by FakelsHub** [comment]
NovaRain, you're right!

**Comment by phobos2077** [comment]
Проверяй: https://yadi.sk/d/3zohB7UK3GsW9Z
