### ISSUE TITLE
town_map function not recognized

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#95]
The following script compiles with world_map, but not with town_map. Accroding to the [doc](http://falloutmods.wikia.com/wiki/Fallout_1_and_Fallout_2_scripting_-_commands,_reference,_tutorials), the usage should be exactly the same.
```
procedure keypress_hook_handler begin
  variable town_key, temp;
  town_key := 20;
  if (not(combat_is_initialized)) then begin
    if (key_pressed(town_key)) then begin
//      world_map;
      town_map;
    end
  end
end

procedure start begin
  if game_loaded then begin
    register_hook_proc(HOOK_KEYPRESS, keypress_hook_handler);
  end
end
```
The error is
```
Compiling gl_g_map.ssl
[Error] <gl_g_map.ssl>:37:16: Assignment operator expected.
```

**Comment by NovaRain** [comment]
The function seems only available in Fallout 1. (op_town_map_)

**Comment by burner1024** [comment]
Strange, mapper docs seem to list it for F2.

**Comment by NovaRain** [comment]
Not surprising if there are errors in the official doc.
Also checking the extra.c in sslc source code, the town_map function is only available when FALLOUT_VERSION != 2.

**Comment by burner1024** [comment]
ok it's a pity, but I guess that's a no.

**Comment by phobos2077** [comment]
@burner1024:
I don't see op_town_map function in the engine, looks like they removed it not just from compiler. Are you sure there is no alternatives for doing the same?

You could probably make another issue for implementing this function for FO2. Not sure if I could do it quickly enough though. Given how transitions between game "states" are done in the engine, it might be more difficult than simple call of a function.

**Comment by burner1024** [comment]
I don't see any other function having anything to do with town map ui.

What I did is created a scripted hotkey to call the map to avoid running to the exit grid, sometimes through multiple areas. I wanted to have 2 separate keys, for convenience.
Anyway, worldmap call works fine (in F2, not sure about F1, global scripts don't seem to run with sfall1). And townmap is one click away from worldmap. So it's not perfect, but good enough for me.
