### ISSUE TITLE
Automaps saved in the PipBoy

### ISSUE THREAD

**Issue by Lexx2k** [phobos2077/sfall#96]
Is there any chance we could get better control (or control at all) over the automaps that are saved in the PipBoy? As far as I am aware, the game only recognizes the first 150 maps. For whatever reason, though, I don't have any automaps in my mod at all (maybe because I am counting 244 maps in total as of now? Didn't really investigated the issue, as I am way over the 150 maps limit in any case)

What would be great:
- being able to define custom town categories (like "Arroyo" for example)
- being able to define the automaps saved in each category ("Village", "Temple of Trials", etc) ... maybe based on map id? This way we could have more than just 3 automaps per category (3 map elevations) and keep everything grouped together.
- Bonus objective: Any chance to add custom info like shop locations on the automap display?

**Comment by phobos2077** [comment]
Would be great if you could do a proper research on this topic:

- check if automaps work for original maps in your mod (or just maps below 150 range)
- check what TXT files in data/data folder might customize automaps in any way

**Comment by Lexx2k** [comment]
They dont work, I've tried already yesterday. What makes matters more complicated as well is that i mostly replaced the contents of the city.txt file. What i probably would need to do is to revert my files to a very old revision where it still worked and then check what the difference is. I'll try this later today.

**Comment by Lexx2k** [comment]
All right, this is what I could figure out by now: 

1. Apparently the automaps (saved in the PipBoy) didn't ever worked in my mod. I reverted to a very old revision and they never showed up. No idea what the issue is, tbh, as the Restoration Project also uses over 150 maps. So this can't cause it.
2. Everything PipBoy/Automap related is in the Map.msg file. 
3. The "location category" is the short city name. 
4. The automap map names are lines 200+
5. Lines 100-150 don't seem to be related to the PipBoy at all. At least I couldn't make out their effect. Likely this is some old Fo1 stuff, considering the names (Hub, Glow, Boneyard,...)

**Comment by Lexx2k** [comment]
Here is something more:
Maps are tied to a city category via their entry point definition in the city.txt file. This is also visible when looking at the normal ingame map (TAB key): If you are in a local map that is not defined as an entry point to any city in city.txt, it will automatically take the name of city 0 (usually Arroyo). 
This, too, is a bit annoying, as I had to replace the "Arroyo" string with "" to prevent the name to show up. Sometimes it's not good to add a map via "entrance_..." to a city, as I don't always want the player to jump into the map via the Town/World interface.

**Comment by FakelsHub** [comment]
> If you are in a local map that is not defined as an entry point to any city in city.txt, it will automatically take the name of city 0 (usually Arroyo). ... Sometimes it's not good to add a map via "entrance_..." to a city, as I don't always want the player to jump into the map via the Town/World interface.

What you prevents making new hidden [AREA ###] (with start_state=off), for these maps? Are any nuances?

**Comment by Lexx2k** [comment]
Area bloat, for one. Also these locations would then appear on the worldmap too, so you'd have to go extra hoops to hide them again. But this issue in itself isn't really a problem-- getting it work correctly with the PipBoy/Automaps screen would be better.

Never had a crash in such "non-connected" locations. I tested it again right now just to be sure, and all is fine.

**Comment by FakelsHub** [comment]
> - check if automaps work for original maps in your mod (or just maps below 150 range)

Automaps are saved even if its map number is above 150.
Another thing is that it seems like there is a limited number of automaps that can saved in pipboy.

**Comment by FakelsHub** [comment]
There is a limit of 159 maps for each level.
Extending the range to save is impractical and difficult.

**Comment by FakelsHub** [comment]
> Bonus objective: Any chance to add custom info like shop locations on the automap display?

I can add a function to print text on the automap interface, if you still need it?

**Comment by Lexx2k** [comment]
Would be cool, but if we can't have automaps >160, it isn't of use for me, as pretty much all my new maps are up there. If I had known that before, I would have reused all vanilla map slots first - now it's too late to change. :/

**Comment by FakelsHub** [comment]
Usually with proper organization of scripts, there are no problems with transferring the map to another number.

**Comment by Lexx2k** [comment]
I would have to redo all the exit grids.

**Comment by FakelsHub** [comment]
> Would be cool, but if we can't have automaps >160, it isn't of use for me personally, as pretty much all my new maps are up there.

It is possible to make more than 160, but it takes time for this implementation, and since the efficiency of these automaps is low, this is left indefinitely.
And it implied the ability to make an inscription on the automap interface, which are called by the Tab key, and not in the pip-boy automaps.

**Comment by Lexx2k** [comment]
Old thread, but reverse question --- is it possible to *disable* the automap feature for maps / locations?

**Comment by FakelsHub** [comment]
>Added support for the new 'automap=yes/no' parameter to maps.txt. This parameter overrides the hardcoded values for displaying the map in the pipboy automaps for the first 160 maps

+ block button "map" on interface and the TAB key to call the automap.

**Comment by Lexx2k** [comment]
Works perfect. Thanks.

**Comment by FakelsHub** [comment]
_v4.1.7/3.8.17_
**Added support for the new 'automap=yes/no' parameter to maps.txt.
This parameter overrides the hardcoded values for displaying the map in the pipboy automaps for the first 160 maps**
