### ISSUE TITLE
Failing to re-compile ecco's scripts

### ISSUE THREAD

**Issue by burner1024** [phobos2077/sfall#98]
I can't recompile Vic's script from EcCo with int2ssl/compile.exe from modderspack 3.8.2/3.8.3. Not sure if that's EcCo bug or modderspack, but 3.4.7 doesn't have this problem.
What I'm doing is literally:
1. Extrach DCVIC.int from the mod
2. int2ssl DCVIC.int
3. compile -p DCVIC.ssl

The result is:
```
Startreck scripting language compiler (Fallout 2 sfall edition 3.8)

Preprocessing handled by mcpp 2.7.2
Copyright (c) 1998, 2002-2008 Kiyoshi Matsui <kmatsui@t3.rim.or.jp>
All rights reserved.

Compiling DCVIC.ssl
[Error] <DCVIC.ssl>:8:15: Redefinition of GVar0.

*** THERE WERE ERRORS (1 of them) ***
```
Persumably due to this in DCVIC.ssl
```
/*******************************************************
*      Some unreferenced imported varables found.      *
*      Because of it it is impossible to specify       *
*      the real names of global variables.             *
*******************************************************/

variable GVar0;
variable GVar0;variable GVar1;
variable GVar0;variable GVar1;variable GVar2;
variable GVar0;variable GVar1;variable GVar2;variable GVar3;
variable GVar0;variable GVar1;variable GVar2;variable GVar3;variable GVar4;
variable GVar0;variable GVar1;variable GVar2;variable GVar3;variable GVar4;variable GVar5;
variable GVar0;variable GVar1;variable GVar2;variable GVar3;variable GVar4;variable GVar5;variable GVar6;
variable GVar0;variable GVar1;variable GVar2;variable GVar3;variable GVar4;variable GVar5;variable GVar6;variable GVar7;

/* ?import? variable ProtoOfItemGiven; */
/* ?import? variable ValueOfRollCheck; */
...
```

**Comment by FakelsHub** [comment]
Декомпиляция это зло :-)

**Comment by burner1024** [comment]
@FakelsHub ну я же это все не руками делаю. Установка fo2tweaks просто застревает.

**Comment by phobos2077** [comment]
Установщик это все сам делает? Хардкорно)
Завтра посмотрю.

**Comment by FakelsHub** [comment]
Ну нифига себе прямо роботезированно у вас там все)
/* ?import? variable ProtoOfItemGiven; */
А вот эти переменные нафига int2ssl их пометил как импортные, это же обычные глобальные переменные из command.h

**Comment by burner1024** [comment]
Версия EcCo последняя, 0.6.2.

Установщик делает сам, да, ну там не так сложно, не в ассемблере копаться. Автоматизировано чтобы не переписывать под разные моды и версии.

**Comment by burner1024** [comment]
Are there int2ssl/compile.exe available for 4.0 pre-release? I'd try with that.

**Comment by NovaRain** [comment]
There will be a fixed int2ssl for 4.0. The sslc (compile.exe) is fine as it is now.

**Comment by NovaRain** [comment]
Did some tests today. The issue seems related to the changes between sslc 3.4 and 3.5.

I recompiled the DCVic.ssl in EcCo's source code with sslc 3.5 (or newer), and the new DCVic.int can be decompiled normally (no "unreferenced imported varables found" warning or bunch of repeating GVars) with both new/old int2ssl. But with sslc 3.4, the DCVic.int has the same decompiling issue with new int2ssl. Guess you have to use old int2ssl (modderspack 3.5 or older) for some scripts compiled with older sslc.

**Comment by burner1024** [comment]
So you're saying it's actually a fault in compiler?
The problem is that fo2tweaks installer does all that automatically. So I'd have to ship 2 versions of int2ssl, and choose whichever needed for decompilation based on whether EcCo is installed or not. And even that wouldn't fix the generic problem, only this specific one for dcvic.
It seems that it's easier to wait until EcCo is updated, then.

**Comment by FakelsHub** [comment]
Напиши консольку, которая бы сама убирала продублированные объявленные переменные, и перед компиляцией пусть парсит скрипты. Это луший выход  из положения.

**Comment by phobos2077** [comment]
Not sure if this issue should've been closed. The way I see it, if the script works, latest int2ssl should properly decompile it. So the decompiler is still flawed.

**Comment by phobos2077** [comment]
@burner1024, @NovaRain, try this version https://yadi.sk/d/_tbJXUMK3Nfqy9. Fixed a couple of bugs. VS2017 build :)

**Comment by NovaRain** [comment]
OK, I tested it with EcCo's DCVIC.int, the redundant GVarX are now gone. :D

**Comment by phobos2077** [comment]
Some more bugs were fixed in the int2ssl. Will be included in next modderspack.

**Comment by FakelsHub** [comment]
```
variable GVar0;
variable GVar1 := 1;
variable GVar2;
variable GVar3;
variable GVar4;
variable GVar5;
variable GVar6;
variable GVar7;
variable GVar8;
variable GVar9;
variable GVar10;
variable GVar11;
variable GVar12;
variable GVar13;
variable GVar14;
variable GVar15;
variable GVar16;
variable GVar17;
variable GVar18;
variable GVar19;
variable GVar20;
variable GVar21;
variable GVar22;

/* ?import? variable ProtoOfItemGiven; */
/* ?import? variable ValueOfRollCheck; */
/* ?import? variable Scenery_Creation; */
/* ?import? variable Scenery_Creation_Hex; */
/* ?import? variable Scenery_Creation_Count; */
/* ?import? variable Temp_Scenery_Creation_Hex; */
/* ?import? variable Scenery_Creation_Ptr; */
/* ?import? variable How_Many_Party_Members_Are_Injured; */
/* ?import? variable How_Many_Party_Members_Armed; */
/* ?import? variable PartyHealingItem; */
/* ?import? variable global_temp; */
/* ?import? variable dest_tile; */
/* ?import? variable step_tile; */
/* ?import? variable in_dialog; */
/* ?import? variable forced_node; */
/* ?import? variable restock_amt; */
/* ?import? variable restock_obj; */
/* ?import? variable restock_trash; */
/* ?import? variable removed_qty; */
/* ?import? variable toRemove_qty; */

/* ?import? variable Kevin; */

import variable Door_guard;

/* ?import? variable talking_float; */
/* ?import? variable dialog_loop; */
/* ?import? variable loop_numbers; */
```
What is the reason for replacing the actual names of variables to GVar# ??
