### ISSUE TITLE
Add Dead Critter Highlighting & DontTurnOffSneakIfYouRun

### ISSUE THREAD

**Issue by sanscriptum** [phobos2077/sfall#99]
[Crafty's sfall](https://github.com/Sduibek/sfall_1/) had an option called ``TurnHighlightContainers`` (Which is called ``HighlightContainers`` here), which could highlight both containers AND dead critters, but this sfall can highlight only containers. Is this intentional?
Also there was an option to keep the stealth enabled when running via option ``DontTurnOffSneakIfYouRun``, it was very useful since game sometimes likes to ignore shift input for some bizarre reason.
Could you add those?

**Comment by Lexx2k** [comment]
Actually, highlight corpses is in the latest Sfall version. See sfall-mods.ini and the line "Corpses=0"

**Comment by sanscriptum** [comment]
What's sfall-mods.ini? I couldn't find it. Creating it and adding that line does nothing.

**Comment by burner1024** [comment]
@sanscriptum I guess the main reason is that Crafty is a lazy ass bastard who doesn't want to participate in public development.
I second the request, about DontTurnOffSneak, though.

**Comment by NovaRain** [comment]
The name of DontTurnOffSneakIfYouRun is kinda misleading IMO, since what it actually does is to prevent you from running in all situations when you're sneaking and don't have Silent Running perk. But seeing its name would make me think of free Silent Running effect.

**Comment by sanscriptum** [comment]
@NovaRain I see. Ability to customize highlighted items and their highlight color should be great.
And yeah, just as you said, that option didn't directly replace Silent Running, it just forced PC to walk to keep the stealth on if running was always enabled.

**Comment by FakelsHub** [comment]
DontTurnOffSneakIfYouRun: write_byte(0x418135, 0xEB);

**Comment by NovaRain** [comment]
DontTurnOffSneakIfYouRun is implemented in both 3.8-maintenance and 4.0 develop branches.
